### ISSUE TITLE
Redis (Sentinel): The underlying connection is not renew if it's broken 

### ISSUE THREAD

**Issue by JorTurFer** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1003]
**What happened**: If you are running this health check in a Redis HA scenario using Sentinel (in Kubernetes), it could happen that the master node doesn't exist anymore because any cluster operation. Even the instance is recreated, the attached IP changes, so the connection is still broken. 

There is [an issue](https://github.com/StackExchange/StackExchange.Redis/issues/1584) in [StackExchange.Redis](https://github.com/StackExchange/StackExchange.Redis)[](https://github.com/StackExchange/StackExchange.Redis) explaining this problem.

This produces that after this situation, the healtcheck never comes back because it tries to hit an unexisting IP address.

**What you expected to happen**:
I'd expect that after new master node is elected, the health check work again

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy a Redis Sentinel solution (for example using redis-operator). 
2. Create an app using this check and run it.
3. Kill master node.
4. Hit the healthchek endpoint

**Anything else we need to know?**:
We have solved this problem removing the connection from the dictionary if the check fails, just for creating a fresh connection for the next time in that case. Upgrading the Redis package to latest version is another good improvement for Sentinel support.

I'm willing to open a PR with it if you think that this is useful

**Comment by sungam3r** [comment]
> Upgrading the Redis package to latest version is another good improvement for Sentinel support.

OK but as you said here https://github.com/StackExchange/StackExchange.Redis/issues/1584#issuecomment-1063801016 that does not work.

**Comment by JorTurFer** [comment]
> > Upgrading the Redis package to latest version is another good improvement for Sentinel support.
> 
> OK but as you said here [StackExchange/StackExchange.Redis#1584 (comment)](https://github.com/StackExchange/StackExchange.Redis/issues/1584#issuecomment-1063801016) that does not work.

Yes, that's true. It is their recommendation and that's why I suggested it, but our solution has been removing the connection from the dictionary if the check fails.
> We have solved this problem removing the connection from the dictionary if the check fails, just for creating a fresh connection for the next time in that case.

**Comment by JorTurFer** [comment]
Let me open the PR because it's 3 minutes change, and we could discuss over the code
