### ISSUE TITLE
Add tests into HealthChecks.AzureDigitalTwin.Tests project

### ISSUE THREAD

**Issue by sungam3r** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1017]
See #766

**Comment by carlosrecuero** [comment]
I will ask the author of the PR for creating the tests.

**Comment by carlosrecuero** [comment]
@rafaarcangel Rafa, do you feel like to create them?

**Comment by sungam3r** [comment]
I found some in UnitTest project.

**Comment by rafa-arcangel** [comment]
Of course, I did some tests under the general Test project.
![image](https://user-images.githubusercontent.com/13365264/158224191-395504d0-c15b-4eee-ae1d-127d27aff16e.png)

Do you want me to create/copy those tests to a specific project inside /tests?

**Comment by sungam3r** [comment]
@carlosrecuero What is the purpose of UnitTests project? I do not see it is triggered by any CI worflow. It seems to me that tests from this project must be transferred to the appropriate other test projects and UnitTests itself should be removed.

**Comment by carlosrecuero** [comment]
Yes, you are right @sungam3r . The UnitTests folder was the previous location before splitting the code . They should be moved into a Tests/HealthChecksAzureDigitalTwin.Tests folder, as well as run a dotnet test on CI/CD.

**Comment by rafa-arcangel** [comment]
Ok, I'll move to the right folder/project

**Comment by carlosrecuero** [comment]
@rafa-arcangel  ;)

**Comment by rafaarcangel** [comment]
Hi guys!
You can review on https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1122

**Comment by sungam3r** [comment]
Conflicts...

**Comment by rafaarcangel** [comment]
Fixed!
