### ISSUE TITLE
Why to tun tests for CD?

### ISSUE THREAD

**Issue by sungam3r** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1022]
What is the reason to run tests for CD workflows? Assuming that CI occurs only on the `master` branch, this means that all the tests have already been completed earlier during CI workflows. I understand that in the general case you can run tests whenever you want but for CD purposes it may be a problem if some test fails for unknown/transient reason. I propose delete `dotnet test` commands from all CD workflows. This implies also that services docker settings may be removed as well. Only CI workflows need to bother with these settings to run tests.  @carlosrecuero @unaizorrilla What do you think?

**Comment by carlosrecuero** [comment]
I see your point. My only concern is that, in the way that we currently deploy, a deployment can be generated several weeks later the CI run. Additionaly, both processes are executed independently. So, you can run a deployment (if you don't realize) even though the CI failed.

**Comment by sungam3r** [comment]
@carlosrecuero If you don't mind I would like to post PR removing all dotnet test and containers stuff from CD-workflows.

**Comment by carlosrecuero** [comment]
Ok, go ahead.
