### ISSUE TITLE
Support for using DelegatingHandlers for webhook endpoints

### ISSUE THREAD

**Issue by jabadmgm** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1023]
**What would you like to be added**:
A `.UseWebhookEndpointDelegatingHandler<MyDelegatingHandler>()` that can be used to register our own delegating handlers (as in #536).

**Why is this needed**:
Personally, I need to add a delegating handler for taking care of service authorization, but I think #536 explains the general need for it well.

**Comment by sungam3r** [comment]
PRs are welcome.
