### ISSUE TITLE
Missing health check with rabbitMq configured to use TLS.

### ISSUE THREAD

**Issue by hansehe** [Xabaril/AspNetCore.Diagnostics.HealthChecks#103]
The rabbitMq health check misses an option to set TLS (SSL) settings. 

Please see PR: https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/102

**Comment by unaizorrilla** [comment]
Hi @hansehe 

I see PR 102 but is not finsished to be merged righ now! Can you check my comments?
