### ISSUE TITLE
Folder Health Check

### ISSUE THREAD

**Issue by lukerogers** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1068]
**What would you like to be added**:
A new health check that makes sure a folder exists.

**Why is this needed**:
My specific use case is around volumes in Kubernetes. I want to make sure the volume exists as part of the health check so it is marked unhealthy if it is not accessible. This is to make sure it works upon startup, but also during normal execution. I am concerned that if the secret changes it will cause the volume to be inaccessible and will only recover after pod restart. If this check is in place as a liveness probe, it should restart it when it is inaccessible. I think this is often overlooked and a potential risk that can be mitigated with this health check. This isn't specific to K8s and can work with any application that uses a folder.

I created the code in a fork and it can be found at https://github.com/lukerogers/AspNetCore.Diagnostics.HealthChecks/commit/52f2e1c73adbec6cbf05c33fdffe5a7239968022. I'd love feedback on the idea, implementation, and if a PR would make sense.

**Comment by sungam3r** [comment]
PRs are welcome. Use `HealthChecks.System` project to add new health check.

**Comment by carlosrecuero** [comment]
Related changes have deployed on version 6.0.5
