### ISSUE TITLE
Oracle TNS_ADMIN might not be configured as an environment variable

### ISSUE THREAD

**Issue by camiteca** [Xabaril/AspNetCore.Diagnostics.HealthChecks#107]
In order to stablish a successfull connection we need to have configured an environment variable with the TNS_ADMIN pointing to the TNSNames file.

There's also another option: having a copy of the TNSNames file locally (in the same folder where the executing assembly is located at).

Would you consider adding an extension method that retrieves the file and places it on the executing assembly folder?

I'm thinking about something like this:

    public static class IServiceCollectionExtensions
    {
        public static IServiceCollection AddOracleTnsNames(this IServiceCollection serviceCollection, string tnsNamesDirectoryPath, string tnsNamesFile)
        {
            string tnsFilePath = Path.Combine(tnsNamesDirectoryPath, tnsNamesFile);

            if (Directory.Exists(tnsNamesDirectoryPath)
                &&
                File.Exists(tnsFilePath))
            {
                File.Copy(tnsFilePath, Path.Combine(AppDomain.CurrentDomain.BaseDirectory, tnsNamesFile), overwrite: true);
            }

            return serviceCollection;
        }
    }

This is needed when the environment should work when disconnected from the location of the TNSNames file (might be shared over a network folder and lose access).

**Comment by unaizorrilla** [comment]
Hi @karlmtc 

Can you send a PR with this changes to be reviewed!

**Comment by CarlosLanderas** [comment]
@karlmtc any update on this? Do you want to submit a PR or can we close the issue?
Thanks

**Comment by karlmtc** [comment]
@CarlosLanderas sorry for the late response but I'm overwhelmed at work right now. I first thought it would be a nice addition when connection to oracle, but thinking it through, I don't know if it's in the scope of this repo? I don't mind on making a pull request, but I'd rather consider your toughts on it first. Is there part of your repo where you handle "crosscutting"?
