### ISSUE TITLE
Place sqlite db in App_Data Instead of ContentRoot

### ISSUE THREAD

**Issue by marlon-tucker** [Xabaril/AspNetCore.Diagnostics.HealthChecks#110]
Hello,

Please can you either make the path creation for the sqlite db an extension point or change so it creates the db in the App_Data folder instead of the ContentRoot.

At the moment, it requires the IIS_User for the application pool to have write permissions for the content root, from memory this is considered bad, and that user should only have write permissions to App_Data (or wwwroot etc).

Either that or allow the use of Sql Server Compact which has the ability to use tokens such as `DataDirectory` in the connection string. 

I've tried using relative paths for the current connection string, but each time I get the following: `SqliteException: SQLite Error 14: 'unable to open database file'.` From reading EFCore SqLite github issues relative paths are supposed to work but that hasn't been my experience so far.

**Comment by unaizorrilla** [comment]
You can do it, please check 

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/samples/HealthChecks.UIAndApi/appsettings.json

You can configure the conection string and using environment variables on this, like %appdata%

**Comment by unaizorrilla** [comment]
Hi @marlon-tucker 

Can I close this issue?

**Comment by marlon-tucker** [comment]
@unaizorrilla Yes you can.

However, I would still like to extend the options to allow the customisation of the EF Core context. IdentityServer4 provides the ability and it just involves exposing the `DbContextOptionsBuilder`.

That way consuming code can do what it wants.

Would you be open to accepting a pull request which facilitates this?

**Comment by unaizorrilla** [comment]
Yeap, contributions are open!
