### ISSUE TITLE
In case of unhealthy, error is written in Windows event log

### ISSUE THREAD

**Issue by pknegi** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1103]
Please, fill the following sections to help us fix the issue

**What happened**: In case of unhealthy, error is written in Windows event log 

**What you expected to happen**: there should be some configuration to stop writing into windows event log

**How to reproduce it (as minimally and precisely as possible)**:

**Source code sample**:

**Anything else we need to know?**:

**Environment**:

- .NET Core version : 3.1.1
- Healthchecks version
- Operative system:
- Others:

**Comment by sungam3r** [comment]
Maybe you have configured logging subsystems in this way? Could you provide an example of logged event?

**Comment by pknegi** [comment]
following is the evetlog entry:

Category: Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService
EventId: 103
RequestId: 8000002e-0001-fa00-b63f-84710c7967bb
RequestPath: /idp/healthz
SpanId: |d85410c2-4cf6d423c25ac81d.
TraceId: d85410c2-4cf6d423c25ac81d
ParentId: 
HealthCheckName: Database Connection

Health check Database Connection completed after 0.5643ms with status Unhealthy and '(null)'

**Comment by sungam3r** [comment]
It's not an issue withing this repo. See category - `Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService`. This is MS code that writes log message to `Microsoft.Extensions.Logging.ILogger` instance. So it's up to you how this message will be handled further. Check your app settings.
