### ISSUE TITLE
Webhook - notify description as well

### ISSUE THREAD

**Issue by FurstLevy** [Xabaril/AspNetCore.Diagnostics.HealthChecks#111]
Hello everyone
The project works for its purpose and I am starting to use in my services.
Eventhough, at the webhook, I miss to be informed the content of the existent problem.
My sugestion is to creat another key at config, that works the same way as [[LIVENESS]] and [[FAILURE]],  that is, creating a key  [[DESCRIPTIONS]].
The notification method would recover the unhelthy services descriptions, with sting.join displaying a notification containing the  new information.

I did a Fork of the project and have already implemented on my side. It worked pretty well.
I would like to contribute by sharing the code I have developed.
How can I proceed to do so?

Thank you in advance

**Comment by CarlosLanderas** [comment]
Hello, you can submit a pull request so it can be reviewed and tested.

**Comment by FurstLevy** [comment]
#112
