### ISSUE TITLE
Azure Blob Health Check Does Not Work with Container Connection Strings

### ISSUE THREAD

**Issue by chambomusic** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1123]
### Steps to reproduce:

1. Create a Blob Container in an Azure Storage Account
2. Create a Shared Access Signature at the container level
    2.1. In Azure Storage Explorer right-click on the container
    2.2. Select "Get Shared Access Signature"
    2.3. Click "Create" button
    2.4. Copy the "URL" value
3. Connection String:
    3.1. BlobEndpoint=<URL value copied from the SAS generation

```
services.AddHealthChecks()
    .AddAzureBlobStorage(blobConnectionString
                        , blobContainerName
                        , "MyBlobHealthCheck");
```

Issue is with this line: https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/95061fcc45e73321d32da517117d6159e7b92aed/src/HealthChecks.AzureStorage/AzureBlobStorageHealthCheck.cs#L39

Suggest that this part of the code is moved to an `else` block after the container logic.  If a ContainerName is specified then the Health Check should only validate that the container is accessible.  It should not try and enumerate all containers in the storage account. 

Thoughts?  Guidance?  I'd be happy to submit a PR if the proposed solution is reasonable in your mind.

**Comment by sungam3r** [comment]
Relates to #806, https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/806#pullrequestreview-714818443

**Comment by chambomusic** [comment]
@sungam3r - I agree #806 introduced this issue.  Can you provide some guidance on what might be a suitable fix or rework of this function to allow for container access checks without having to have permissions to the entire account?

**Comment by sungam3r** [comment]
Nope. I don't use any Azure stuff.

**Comment by sungam3r** [comment]
I think it was covered by #1372.
