### ISSUE TITLE
Namespaces in k8s service discovery

### ISSUE THREAD

**Issue by rnarayana** [Xabaril/AspNetCore.Diagnostics.HealthChecks#113]
Can I specify namespaces in service discovery in kubernetes?

**Comment by CarlosLanderas** [comment]
No it doesn't. But let me add them asap :)

**Comment by ekjuanrejon** [comment]
any progess on this?

**Comment by OmnipotentOwl** [comment]
I see there is currently a PR #231  that would resolve this that has been open for over a month with no reviewers commenting on it. Hopefully, it will get some traction soon that will improve the Kubernetes experience.

**Comment by CarlosLanderas** [comment]
I'll review it tomorrow. We have been working in UI 2.0 and .net core 3.0

**Comment by OmnipotentOwl** [comment]
@CarlosLanderas Any update on PR #231 for when someone might look at it and provide feedback?

**Comment by CarlosLanderas** [comment]
Namespaces in k8s discovery services are now supported.
