### ISSUE TITLE
Support for Azure.Core.TokenCredential in the health-check HealthChecks.CosmosDb.TableServiceHealthCheck

### ISSUE THREAD

**Issue by nielsruys** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1134]
**What would you like to be added**:  Because we use Azure User Assigned Managed Identities, we would like to authenticate to the Azure Storage Account with those managed identities using the Azure Identity (https://docs.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme) and Microsoft.Extensions.Azure (https://docs.microsoft.com/en-us/dotnet/azure/sdk/dependency-injection) library.

Currently, the health-check tries to get a table ACL, this requires account owner permissions. (https://docs.microsoft.com/en-us/rest/api/storageservices/get-table-acl#authorization) Can an alternative implementation be provided that requires fewer permission?

**Why is this needed**: So, that we can reuse the health-check for services that are using Azure AD for authentication/authorization to an Azure Storage Account instead of a shared key.

Currently, the health-check tries to get a table ACL, this requires account owner permissions.

**Comment by sungam3r** [comment]
PR is welcome.

**Comment by levimatheri** [comment]
I'd be interested in tackling this one.
