### ISSUE TITLE
healthchecksdb no records

### ISSUE THREAD

**Issue by SergiuMir** [Xabaril/AspNetCore.Diagnostics.HealthChecks#115]
Hello,

My problem is that the healthchecksdb database doesn't contain any records. When I open the health link in Browser, it show me the json with results, but it doesn't write anything in database.

My code:
`services.AddHealthChecks()
                //.AddAzureTableStorage(Configuration["AzureTableStorage:ConnectionString"])
                .AddAzureServiceBusQueue(Configuration["NServiceBusParameters:ConnectionString"], "CAPIMSPurchaseAPI")
                .AddAzureServiceBusTopic(Configuration["NServiceBusParameters:ConnectionString"], "CAPIMSPurchaseAPI")
                .AddCheck<MailerHealthCheck>("mailer")
                .AddDocumentDb(c =>
                {
                    c.UriEndpoint = Configuration["CosmosDBParameters:Endpoint"];
                    c.PrimaryKey = Configuration["CosmosDBParameters:AccessKey"]
                    ;
                });`

and 
`app.UseHealthChecks("/healthz", new Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckOptions
            {
                Predicate = registration => true,
                ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse,
            }
            );`
The application is deployed in a Service Fabric Local Cluster

Thank you in advance for your assistance

**Comment by unaizorrilla** [comment]
Well, where is configured HealthChecksUI and wich configuration have?

**Comment by SergiuMir** [comment]
`services.AddHealthChecksUI();`

`app.UseHealthChecksUI();`

The json part related HealthCheksUI:
"HealthChecks-UI": {
    "HealthChecks": [
      {
        "Name": "HTTP-Api-Basic",
        "Uri": "http://localhost:4020/healthz"
      }
    ],
    "Webhooks": [
      {
        "Name": "",
        "Uri": "",
        "Payload": "",
        "RestoredPayload": ""
      }
    ],
    "EvaluationTimeOnSeconds": 10,
    "MinimumSecondsBetweenFailureNotifications": 60,
   }

To be honest, I don't understand the link between HealthCheckUI and records in healthchecksdb.
Shouldn't HealthChecks write there data even the HealthCheckUI is not used?

Thank you

**Comment by unaizorrilla** [comment]
Hi @SergiuMir 

HealthChecks don't create any database, with healthz you have a endpoint that response the health status of your services, no more!

HealthChecksUI is a UI for this json response status and save result entries on a db with other features. If you have AddHealthChecksUI and UseHealthChecksUI and your endpoint configuration is OK (ie, http://localhost:4020/healthz respond with a valid json format) a new db healthchecksdb is created on ContentRoot by default.

You have a lot of samples, docs and videos to understand this project, please checkout https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks#tutorials-demos-and-walkthroughs-on-aspnet-core-healthchecks to get more information.

**Comment by SergiuMir** [comment]
Hi, 
Initially I thought the same.
And I saw that HealthChecksUI page invoke the "healthcheck-api" link. This link was returning an empty array "[]".
That make me to think that it can be that HealthChecks is writing information in db and healthchecksui is reading it.

Anyway, did you observe any errors in my code/configuration?
And why healthchecks-api return an empty []

Thank you

**Comment by SergiuMir** [comment]
Hi,
I found the problem. :)
Service Fabric Application was ignoring the appsettings.json file.
As soon as I solved that issue, everything was fixed.
Sorry for disturbing you from your work and thank you for your patience!

Best regards,
Sergiu

**Comment by unaizorrilla** [comment]
No worries!
