### ISSUE TITLE
Lazily initialize UriHealthCheckOptions for Uri health check

### ISSUE THREAD

**Issue by jnovick** [Xabaril/AspNetCore.Diagnostics.HealthChecks#116]
Most of the health checks lazily use the values passed in to create a health check, but UriHealthCheckOptions adds the uri not inside the service provider lambda function. This can cause errors while running tests that call Startup.ConfigureServices but does not initialize some configuration values. This also causes issues with NSwag client generators that run based on the code when the configuration is not in place because it comes from environment variables.

**Comment by unaizorrilla** [comment]
Merged by #120, thanks @jnovick !
