### ISSUE TITLE
How to set HTTP TimeOut?

### ISSUE THREAD

**Issue by projectje** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1160]
I read https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/60

I have a healthcheck that calls a stored procedure that (in some cases) takes longer than 100 seconds. So that gives me The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

Could not figure out where to define this

**Comment by sungam3r** [comment]
`UriHealthCheckOptions.Timeout` or `UriOptions.Timeout` for each uri in `UrisOptions`.

**Comment by projectje** [comment]
ok but where to place this ? Every one of my components/dlls currently has a method to call that adds its healthcheck e.g.: 



     public static IServiceCollection AddCoreHealthChecks(this IServiceCollection services, string uri)
    {
        services
           .AddHealthChecks()
           .AddCheck<Core_LogCheck>(HealthCheckLogCheckLabel,
                HealthStatus.Unhealthy, tags: new[] { HealthCheckMainTag })
           ;

        services.AddHealthChecksUI(settings => settings.AddHealthCheckEndpoint(HealthCheckMainTag,
             uri + HealthPointEndPointUrl));
        
        return services;
    }

**Comment by sungam3r** [comment]
```cs
 public static IHealthChecksBuilder AddUrlGroup(
            this IHealthChecksBuilder builder,
            Action<UriHealthCheckOptions>? uriOptions,                       <--------------- HERE
            string? name = default,
            HealthStatus? failureStatus = default,
            IEnumerable<string>? tags = default,
            TimeSpan? timeout = default,
            Action<IServiceProvider, HttpClient>? configureClient = null,
            Func<IServiceProvider, HttpMessageHandler>? configureHttpMessageHandler = null)
        {
            var registrationName = name ?? NAME;
            ConfigureUrisClient(builder, configureClient, configureHttpMessageHandler, registrationName);

            return builder.Add(new HealthCheckRegistration(
                registrationName,
                sp =>
                {
                    var options = new UriHealthCheckOptions();
                    uriOptions?.Invoke(options);

                    return CreateHealthCheck(sp, registrationName, options);
                },
                failureStatus,
                tags,
                timeout));
        }
```

**Comment by projectje** [comment]
But isn't this for checking external urls ?

This is my own API's endpoints for the custom healthchecks.

**Comment by vasiokp** [comment]
@projectje Hi, you can try that:

```
services.AddHealthChecksUI(settings =>
{
    settings.ConfigureApiEndpointHttpclient((sp, client) =>
    {
        client.Timeout = TimeSpan.FromMinutes(5);
    });
    settings.AddHealthCheckEndpoint(HealthCheckMainTag, uri + HealthPointEndPointUrl);
});
```
