### ISSUE TITLE
Optimize S3 healthcheck

### ISSUE THREAD

**Issue by KennyEliasson** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1168]
**What would you like to be added**:
When using the S3 health check on a bucket with many items the health check request will always return 1000 items (as stated in AWS documentation).

It would be nice if you can could set the properties MaxKeys and/or Prefix on the request towards AWS S3.

**Why is this needed**:
Unnecessary big response data.

I am more than willing to implement this if we think this is a good fit.

**Comment by sungam3r** [comment]
PR is welcome.

**Comment by sungam3r** [comment]
fixed by #1711
