### ISSUE TITLE
AzureServiceBusQueue force detached connections are reused

### ISSUE THREAD

**Issue by tomdaniel-it** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1169]
**What happened**:
One health check of a Azure ServiceBus Queue failed because of the connection being 'force detached' (see exception below). All the following health checks used that same queue connection, causing all following health checks to fail until the application is restarted, forcing a new connection.

**What you expected to happen**:
When the connection to a queue fails, I'd expect that connection to not be saved to a dictionary to be used for future health checks, but instead to be removed to force the creation of a new connection for the next health check. 

**How to reproduce it (as minimally and precisely as possible)**:
- Register a health check for a queue
- Somehow simulate a force detach event of the connection to the queue
- Continue running health checks, which will use the closed connection and fail

**Source code sample**:
N/A

**Anything else we need to know?**:
1. Exception of the closed connection, as description of the unhealthy health check (queue names redacted):
```json
{
  "<QueueName>": {
    "data": {},
    "description": "The link 'G61:RR:221394063:637520800997630000:<sb-namespace>:Queue:<queue-name>$management:103196:sender' is force detached. Code: ServerError. Details: AmqpControlProtocolClient.Fault. TrackingId:091a31c0-c2ce-4181-88a0-0f8cf9890d98_B20, SystemTracker:<sb-namespace>:<queue-name>, Timestamp:2022-05-18T09:33:06 Reference:14ff0854-5256-4fd5-9f7c-7a6a3f2a90a0, TrackingId:2b2ffc32-976e-456a-9b8b-b849c173b3ea_G61, SystemTracker:NoSystemTracker, Timestamp:2022-05-18T09:33:06",
    "duration": "00:00:00.0105120",
    "exception": "The link 'G61:RR:221394063:637520800997630000:<sb-namespace>:Queue:<queue-name>$management:103196:sender' is force detached. Code: ServerError. Details: AmqpControlProtocolClient.Fault. TrackingId:091a31c0-c2ce-4181-88a0-0f8cf9890d98_B20, SystemTracker<sb-namespace>:Queue:<queue-name>, Timestamp:2022-05-18T09:33:06 Reference:14ff0854-5256-4fd5-9f7c-7a6a3f2a90a0, TrackingId:2b2ffc32-976e-456a-9b8b-b849c173b3ea_G61, SystemTracker:NoSystemTracker, Timestamp:2022-05-18T09:33:06",
    "status": "Unhealthy",
    "tags": []
  }
}
```

2. To make sure that the cause of the problem was as described as above, we created connections to the queue with the use of .AddTransient() dependency injection. This proved that the queue was healthy and reachable, and that the unhealthy health check results were because of an old closed connection being used.

**Environment**:

- .NET Core version: 3.1
- Healthchecks version: 3.1.1
- Operative system: Windows
- Others: /

Since the logic of reusing connections of queues has not been changed from HealthChecks version 3.1.1 to now, I believe this is still an issue on the current version of HealthChecks. However, I have not been able to test this issue on the current version, due to not knowing how to simulate a force detach event on a queue connection.

**Comment by sungam3r** [comment]
PR is welcome.

**Comment by sungam3r** [comment]
> However, I have not been able to test this issue on the current version.

Closing this one due to inactivity and absense of repro. Moreover, HC code was rewritten/updated so that issue could disappear some time ago.
