### ISSUE TITLE
RabbitMQ SSL default behavior changed

### ISSUE THREAD

**Issue by srocher** [Xabaril/AspNetCore.Diagnostics.HealthChecks#117]
With 2.2.1 for "AspNetCore.HealthChecks.Rabbitmq default behavior changed from using SSL to defaulting to false if you do not pass it in.  Existing code will fail under this scenario for those using SSL.  Can we please default to true or make this a major or minor change rather than a patch since it changes default behavior?

**Comment by unaizorrilla** [comment]
True, this is my fault! I try to fix it asap!

**Comment by srocher** [comment]
commit c4aa201e1c9fec6ee45e69c2a40cec155db7a3e1 appears to have added  
```
using (var connection = factory.CreateConnection()) (original)
                using (var connection = CreateConnectionWithSslOption(factory, _sslOption)) (changed)
```
Then the change from two days ago changed the name of the CreateConnection method.

**Comment by srocher** [comment]
I will review the code again for the original CreateConnection, as I might have missed something.  When we upgraded to this version all of our Rabbit healthchecks began failing, as soon as we reverted, everything worked again.

**Comment by unaizorrilla** [comment]
And works with latest version when set ssloption?
Can you debug why fail or send me a repro?

Un Functional Tests all is working again

**Comment by srocher** [comment]
We had to get our code out, so I have not had a chance to try the latest version again.  Give me a few days and I should be able to do some more checking.  Thank you for the prompt response.

**Comment by unaizorrilla** [comment]
Ok

**Comment by unaizorrilla** [comment]
> We had to get our code out, so I have not had a chance to try the latest version again.  Give me a few days and I should be able to do some more checking.  Thank you for the prompt response.

Any update?

**Comment by unaizorrilla** [comment]
I think issue is closed, please reopen is you have any update!
