### ISSUE TITLE
Disabled status in UIHealthReport

### ISSUE THREAD

**Issue by karmacarrot** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1172]
**What would you like to be added**:
I'd like to add a disabled status to the enum in UIHealthReport 
**Why is this needed**:
We have functionality in our health check json to return a disabled status for many downstream APIs. The disabled status we return doesn't match Healthy, Unhealthy, or Degraded so it throws an error when trying to map it. 

I can raise a PR if it'd be useful to others

**Comment by sungam3r** [comment]
`Microsoft.Extensions.Diagnostics.HealthChecks.HealthStatus` has only 3 enumeration members so it will problematic to add one more here without some tricky mapping. I'm fine to discuss possible design if you have one and as I always say - PR is welcome - but for now I would close this as `wontfix`.
