### ISSUE TITLE
Cosmos DB with Gremlin health check not working

### ISSUE THREAD

**Issue by kranthikumar-kvs-by** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1223]
We are connecting to Cosmos DB with Gremlin and when performing the health check it is not working.

```
ConnectionPoolSettings connectionPoolSettings = new ConnectionPoolSettings { MaxInProcessPerConnection = 10, PoolSize = 30, ReconnectionAttempts = MaxRetryCount, ReconnectionBaseDelay = TimeSpan.FromMilliseconds(RetryTimeout) };
var webSocketConfiguration = new Action<ClientWebSocketOptions>(options => { options.KeepAliveInterval = TimeSpan.FromSeconds(10); });

using var client = new GremlinClient(_gremlinServer, new GraphSON2Reader(), new GraphSON2Writer(), GremlinClient.GraphSON2MimeType, connectionPoolSettings, webSocketConfiguration);
using var conn = new DriverRemoteConnection(client);
var g = Traversal().WithRemote(conn);
await g.Inject(0).Promise(t => t.Next());
```

**Exception -**

Gremlin.Net.Driver.Exceptions.ResponseException: 'MalformedRequest: 

ActivityId : 35c5f5ea-be67-4d64-a61f-dca11fd79405
ExceptionType : GraphMalformedException
ExceptionMessage : 
	Gremlin Malformed Request: Unsupported request operation: 'bytecode'.
	GremlinRequestId : 5cc65471-3ddc-44b9-9520-2195e9811fea
	Context : global
	GraphInterOpStatusCode : MalformedRequest
	HResult : 0x80131500

**Gremlin.Net** version we are using is **3.4.10**

**Comment by sungam3r** [comment]
I can see neither `CosmosDbHealthCheck` nor `GremlinHealthCheck` in your issue.

**Comment by kranthikumar-kvs-by** [comment]
@sungam3r, I am not using the GremlinHealthCheck directly in my component but the code we have here -

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.Gremlin/GremlinHealthCheck.cs

Exception occurred in this line of code -
await g.Inject(0).Promise(t => t.Next());
