### ISSUE TITLE
Shouldn't Task.Delay be called with cancellationToken?

### ISSUE THREAD

**Issue by pekspro** [Xabaril/AspNetCore.Diagnostics.HealthChecks#124]
In `HealthCheckCollectorHostedService` there is this code in `ExecuteASync`:

     private async Task ExecuteASync(CancellationToken cancellationToken)
     {
            var scopeFactory = _serviceProvider.GetRequiredService<IServiceScopeFactory>();

            while (!cancellationToken.IsCancellationRequested)
            {
                ...
                await Task.Delay(_settings.EvaluationTimeOnSeconds * 1000);
            }
     }

Shouldn't the call to `Task.Delay` be like this?

            try
            {
                await Task.Delay(_settings.EvaluationTimeOnSeconds * 1000, cancellationToken);
            }
            catch(TaskCanceledException )
            {
            }

`KubernetesDiscoveryHostedService` also has this potential problem.

**Comment by unaizorrilla** [comment]
Hi @pekspro 

Thanks for fill the issue, the code you show can be improved, can you send a PR for this?

**Comment by unaizorrilla** [comment]
Fixed on 2.2.19, at this moment on appveyor, when finished a new package will be on NuGet
