### ISSUE TITLE
Have possibility to create custom IHealthCheckFailureNotifier

### ISSUE THREAD

**Issue by VKAlwaysWin** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1248]
**What would you like to be added**:
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1247

**Why is this needed**: it is good idea to have possibility to create custom IHealthCheckFailureNotifier. It is already passed using TryAddScoped - but it is impossible to add different implementation, because interface is closed.

**Comment by mhbuck** [comment]
This is would be a useful change 👍

**Comment by sungam3r** [comment]
fixed by #1247
