### ISSUE TITLE
Error in bundle.js

### ISSUE THREAD

**Issue by umeshjoshi62** [Xabaril/AspNetCore.Diagnostics.HealthChecks#125]
Hi
I am getting below error when deploying on EC2 in HealthCheckUI page(it works fine on my local machine IIS )

SCRIPT1002: Syntax error
File: healthchecks-bundle.js, Line: 1, Column: 2294

I am deploying on IIS in Windows 2008 R2 server , Processor is "Intel(r) Xeon(r) CPU E52686 V4".

Can some one help on this.

**Comment by unaizorrilla** [comment]
ping @CarlosLanderas

**Comment by CarlosLanderas** [comment]
@umeshjoshi62 what browser are you using?

**Comment by umeshjoshi62** [comment]
Ok.it was IE 11, I was testing in isolation and later on I aattached ec2 to web and tried it on chrome browser and it worked fine. Looks like some IE 12 has some issues with js. Thanks for your response.

**Comment by CarlosLanderas** [comment]
You are welcome :)
