### ISSUE TITLE
Use SetLogHandler for Kafka HealthCheck

### ISSUE THREAD

**Issue by ViniciusSouza** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1265]
During a recent project we were implementing OpenTelemetry for Kafka, the project is using the Kafka HealthCheck and we noticed a message at the console that was not following the payload. 

Later on, we discovered that setting a SetLogHandler reference at the producer builder fixed our problem getting the logs scrapped and queried.

**What would you like to be added**:

- Set the SetLogHandler to avoid log messages being produced without a standard path

**Why is this needed**:

Improve traceability, following a standard for the log message being produced

**Comment by sungam3r** [comment]
See #837 . You can take it as a base for the new PR.

**Comment by sungam3r** [comment]
Fixed in #1594
