### ISSUE TITLE
When using AspNetCore.HealthChecks.EventStore and EventStore.Client v5.0.1 VS2017 cannot resolve the last one assmbly to resolve classes from it

### ISSUE THREAD

**Issue by kos811** [Xabaril/AspNetCore.Diagnostics.HealthChecks#127]
Hi everybody!
When i using `AspNetCore.HealthChecks.EventStore 2.2.0` and `EventStore.ClientAPI.NetCore 4.1.0.23` - everything works fine, but if change  `EventStore.ClientAPI.NetCore 4.1.0.23` -> `EventStore.Client 5.0.1` 
i have next error (see on pic no.1).

When trying to select any assembly - nothing happens.

p.s.: while researched this problem, i've noticed than namespaces in both assemblies (`EventStore.ClientAPI.NetCore` and `EventStore.Client`) is the same, and in nupkg `EventStore.Client 5.0.1`  on assembly file there is not assembly version (pic no.2)

![image](https://user-images.githubusercontent.com/5595120/54339920-3eb23700-4647-11e9-90b8-ae6698307428.png)
![image](https://user-images.githubusercontent.com/5595120/54340103-a9fc0900-4647-11e9-8616-8bead44a5ab2.png)

**Comment by unaizorrilla** [comment]
Hi @kos811 
EventStore HealthCheck use[ EventStore.ClientAPI.NetCore](https://github.com/EventStore/ClientAPI.NetCore) 4.0.1.23. At this moment I thin EventStore.Client is the recomended (official) version, right?
We try to update package to use the new official library

**Comment by kos811** [comment]
> Hi @kos811
> EventStore HealthCheck use[ EventStore.ClientAPI.NetCore](https://github.com/EventStore/ClientAPI.NetCore) 4.0.1.23. At this moment I thin EventStore.Client is the recomended (official) version, right?
> We try to update package to use the new official library

i've tried to do this in my code and it works (copypasted healthcheck) :)
thank you for so fast responce 👍

**Comment by unaizorrilla** [comment]
A new build is in progress,  in a few minutes  will have a new event store healtcheck 2.2.1 version using EventStore.Client!!

**Comment by unaizorrilla** [comment]
A new version is on nuget 2.2.1 for EventStore using new official package.
