### ISSUE TITLE
Question: Should the UI Still Show Service Status When It Is Unreachable

### ISSUE THREAD

**Issue by roblangston** [Xabaril/AspNetCore.Diagnostics.HealthChecks#128]
Hi,

We are using packages AspNetCore.HealthChecks.UI v2.2.19 and AspNetCore.HealthChecks.UI.Client v2.2.2.  I have created a standalone AspNetCore 2.2 Service which just displays the UI to monitor our other services health endpoints.  If any of the services are stopped when you initially request the UI page, they do not show in the list of available services.  If a service stops and the UI refreshes, that service is not marked as Unhealthy at the top level but just shows the last health state of when it was available.  Is this behavior by design as it seems pretty odd.

Many Thanks,

**Comment by unaizorrilla** [comment]
Hi @roblangston

I discover this bit few days ago. We try to fix it ASAP

**Comment by unaizorrilla** [comment]
Hi @roblangston 

A new release build is on appveyor, when finish a new 2.2.20 ui package version will be on NuGet. Can you check if this release solve your issue and close the this?

**Comment by roblangston** [comment]
Sure thing, as soon as the new NuGet package is available, I will test to make sure the issue is resolved and close.

**Comment by roblangston** [comment]
Hi, just been through some testing with the new 2.2.20 package and the behavior seems to be worse for me.  I can now no longer get the services to appear regardless of its running state.  I have tried deleting the local SQLLite database (healthchecksdb) and clearing browser cache but unfortunately that hasn't made any difference.  If I downgrade the package back to 2.2.19, I can get the service to appear with the original behavior as detailed above.  Thanks for the fast replies.

**Comment by unaizorrilla** [comment]
Sure!

When the UI works for the first time it  needs some time to execute the colector. I only modify the flow when the request to Service throws AM exception. Can you re-check and wait a litem bit (refresh the page)

**Comment by roblangston** [comment]
I have upgraded the package again, waited for about 5 minutes, performed a few manual browser refreshes inc. Ctrl-F5 a few times but still do not see the service listed in the UI.  With the older 2.2.19 package, I get the service showing within about 30 seconds.  The testing is being done locally through VS 2017 with the site running in IIS Express.  Would I get different behavior if I publish out to IIS running on Windows Server 2016?

**Comment by unaizorrilla** [comment]
Is so weird!! Can you paste the xhr api  response here?

**Comment by unaizorrilla** [comment]
Can you check the sample UIAndApiCustomization and modify the settings to check your scenario?

**Comment by roblangston** [comment]
Ok, digging a bit further, there is some strange behavior.  I am using custom endpoint paths, /healthapi for the ApiPath and /healthui for the UIPath.  With 2.2.19 package, I get the following JSON returned from /healthapi `[{
		"id": 1,
		"status": "Healthy",
		"onStateFrom": "2019-03-15T14:56:44.2769559+00:00",
		"lastExecuted": "2019-03-15T14:56:54.6045009+00:00",
		"uri": "http://localhost/test/health/ui",
		"name": "TestService",
		"discoveryService": null,
		"entries": [{
				"id": 1,
				"name": "process Memory Health Check",
				"status": "Healthy",
				"description": "Process Memory Health",
				"duration": "00:00:00.0000086"
			}, {
				"id": 2,
				"name": "process Up Time Health Check",
				"status": "Healthy",
				"description": "Uptime Health",
				"duration": "00:00:00.0000023"
			}, {
				"id": 3,
				"name": "sql Connection Health Check for Database",
				"status": "Healthy",
				"description": "Sql Connection Health",
				"duration": "00:00:00.0010279"
			}
		],
		"history": []
	}
]`
With the 2.20 package, I do not receive any JSON at the same endpoint.  I tried removing the custom endpoint configuration so it defaults to /healthchecks-ui but this doesn't change the behavior.

**Comment by unaizorrilla** [comment]
With the same appsetings.json configuration? Are you test the sample UIandApiCustomization?

**Comment by roblangston** [comment]
Yes, the appsettings were the same between package versions.  I am just waiting for the UIandApiCustomization project to finish download the Npm packages and will report back.

**Comment by unaizorrilla** [comment]
I check you settings and the Url for your heathz is not valid is health/ui

**Comment by roblangston** [comment]
Yes, it responds with the following:-`{
	"status": "Healthy",
	"totalDuration": "00:00:00.0011758",
	"entries": {
		"process Memory Health Check": {
			"data": {
				"totalMemoryBytes": 16504288,
				"gen0GarbageCollects": 0,
				"gen1GarbageCollects": 0,
				"gen2GarbageCollects": 0
			},
			"description": "Process Memory Health",
			"duration": "00:00:00.0000082",
			"status": "Healthy"
		},
		"process Up Time Health Check": {
			"data": {
				"startedAtUtc": "2019-03-15T15:44:53.8439588Z",
				"uptime": "00:05:06.6226498",
				"uptimeMinutes": 5.1103774966666666
			},
			"description": "Uptime Health",
			"duration": "00:00:00.0000027",
			"status": "Healthy"
		},
		"sql Connection Health Check for Database": {
			"data": {},
			"description": "Sql Connection Health",
			"duration": "00:00:00.0009802",
			"status": "Healthy"
		}
	}
}
`

**Comment by unaizorrilla** [comment]
Well i think all is ok, can you test the sample? So weird!! Can you share the Project with me ( i need some hours i’m travelling)

**Comment by roblangston** [comment]
I have pulled down the sample code and modified the appsettings.json in the UIAndApiCustomization.csproj.  As I was having trouble getting the solution to build, I detached the sample project and re-pointed the project references to the corresponding NuGet packages.  I get the same behavior with the sample project as I do with my own.  I cant share this exact project as its company code but will re-create it at home this evening and share it on GitHub if that works for you.  I appreciate all the help.

**Comment by unaizorrilla** [comment]
Ok perfect, many thanks! When you send me a repro I try to check ASAP!

**Comment by unaizorrilla** [comment]
Hi @roblangston 

My fault :-( .. I don't upgrade UI Client version and break UI on runtime, so sorry. I update both package and a new build is on appveyor, when the build finish a new packages 2.2.21 for UI and 2.2.3 for UI.Client will be on Nuget.

**Comment by roblangston** [comment]
Ill give the new version a try when I get a second.  I did create a really simple example here on GitHub [https://github.com/roblangston/aspdotnetcorehealthchecks](url)

**Comment by unaizorrilla** [comment]
Hi @roblangston 

Please checkout 2.2.21 version this update also 2.2.3 UI.Client, i think all is working well now!

**Comment by roblangston** [comment]
Yes, will try as soon as it appears on NuGet

**Comment by unaizorrilla** [comment]
You can update your csproj directly, is on nuget right now!!

**Comment by roblangston** [comment]
It is looking better now, but still some odd behavior wit the UI (see attached picture).  If you start the main UI project first without the test services, it correctly shows them as unhealthy.  Then start each test service and the overall status correctly goes to healthy for each.  However, the error line is still visible from when the service was not running (see below).

<img width="995" alt="example" src="https://user-images.githubusercontent.com/13354992/54461816-9fd02c80-4765-11e9-8ab3-3fa982b91cec.png">

**Comment by unaizorrilla** [comment]
Hi @roblangston 

Yeap, I check this and we have issue here, I fix this and also issues with older entries are different from new entries.

A new build is on appveyor, when finish can you check 2.2.22 version?

Unai

**Comment by roblangston** [comment]
I have done some initial testing and all is looking good now.  If I hit any other issues, I will open a new issue on GitHub.  Many thanks for getting these resolved so quickly.
