### ISSUE TITLE
error in ui client javascript - filter is not a function in liveness page

### ISSUE THREAD

**Issue by tuath** [Xabaril/AspNetCore.Diagnostics.HealthChecks#129]
My health endpoint correctly returns a 200 or 503 with contents similar to:

{"status":"Degraded","totalDuration":"00:00:00.0058159","entries":{"temporaryTestHealthCheck":{"data":{},"description":"healhty desription","duration":"00:00:00.0000064","status":"Healthy"},"2":{"data":{},"description":"degraded","duration":"00:00:00.0000017","status":"Degraded"}}}

The UI shows the error : Could not retrieve health checks data
TypeError: A.filter is not a function
    at e.LivenessPage.<anonymous> (healthchecks-bundle.js:1)
    at Generator.next (<anonymous>)
    at s (healthchecks-bundle.js:1)

My config is simple : 
            app.UseHealthChecks("/health", new Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckOptions() {
                    Predicate = _ => true,
                    ResponseWriter = HealthChecks.UI.Client.UIResponseWriter.WriteHealthCheckUIResponse
            });
            app.UseHealthChecksUI(setup => { setup.ApiPath = "/health"; setup.UIPath = "/health-ui"; setup.ResourcesPath = "/health-ui-resources"; setup.WebhookPath = "/health-webhooks"; });

Any ideas - I am no javascript expert !

**Comment by CarlosLanderas** [comment]
Could you show your UI appsettings.json with configured healthcheck endpoints?

**Comment by unaizorrilla** [comment]
This is the typical error when your configuration is not well on the UI

**Comment by tuath** [comment]
Thanks so much ! my appSettings.json stuff was not declared correctly...
