### ISSUE TITLE
[Feature Request] CosmosDb Managed Identities

### ISSUE THREAD

**Issue by jonathanburrows** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1298]
**What would you like to be added**:
Allow the CosmosDbHealthCheck to accept a `TokenCredential` and endpoint uri. Introduce another extension method to allow registration.

**Why is this needed**:
Connection strings are generally considered unsafe, most infra now uses managed identities.

**Comment by sungam3r** [comment]
PR is welcome.

**Comment by levimatheri** [comment]
Would be interested on working on this
