### ISSUE TITLE
Cloudwatch publisher

### ISSUE THREAD

**Issue by sebandres** [Xabaril/AspNetCore.Diagnostics.HealthChecks#13]
Is there an interest of having a publisher for cloudwatch? 

Not really an Azure customer and have my grafana plugged into my cloudwatch as backend so both AppInsights and Prometheus aren't of much use to me at the moment. 

I was planning on adding one that would publish metrics and can PR that in if there is interest.

**Comment by unaizorrilla** [comment]
A pull request for this is welcome!

**Comment by CarlosLanderas** [comment]
@sebandres @unaizorrilla  should we publish metrics with two dimensions (assembly and machine name) like Application Insight has and add the same metrics? (**AspNetCoreHealthCheckStatus** and **AspNetCoreHealthCheckDuration**)

![metrics](https://i.ibb.co/0Gwwd13/metrics.png)

**Comment by CarlosLanderas** [comment]
@sebandres any update with this? Do you plan to do the PR?

**Comment by CarlosLanderas** [comment]
I know what you mean. I've been there :D.
Whatever you decide. I posted the question above to know it that was what you needed. It is actually the data posted in the other publishers.

**Comment by CarlosLanderas** [comment]
Closing issue by inactivity

**Comment by william-keller** [comment]
Re-open please

**Comment by william-keller** [comment]
> Is there an interest of having a publisher for cloudwatch?
> 
> Not really an Azure customer and have my grafana plugged into my cloudwatch as backend so both AppInsights and Prometheus aren't of much use to me at the moment.
> 
> I was planning on adding one that would publish metrics and can PR that in if there is interest.

Hello Guys!  @sebandres @unaizorrilla  @CarlosLanderas 

Just added the PR 

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1437

**Comment by sungam3r** [comment]
Tracked by #1435

**Comment by sungam3r** [comment]
@sebandres It's here https://www.nuget.org/packages/AspNetCore.HealthChecks.Publisher.CloudWatch/6.0.0
