### ISSUE TITLE
Different statuscode for degraded httpResponseMessage

### ISSUE THREAD

**Issue by ACaj580** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1300]
**What would you like to be added**:
A degraded httpResponseMessage should have a different httpStatusCode.

**Why is this needed**:
Right now im catching the responses with a handler to send notification-emails. If the service is unhealthy
HttpResponseMessage.IsSuccessStatusCode returns false, but true if its only degraded. I have to read every response and look for the status to catch the degraded responses.

**Comment by ACaj580** [comment]
I would say here:
return Task.FromResult(HealthCheckResult.Degraded(description, exception, data));
The returned HealthCheckResult has the same statuscode (200) as a healthy health check result, but i think it should be something else, so 
response.IsSuccessStatusCode will return false, when its a degraded health check result.

**Comment by sungam3r** [comment]
> I would say here:
return Task.FromResult(HealthCheckResult.Degraded(description, exception, data));

Sorry but I still do not understand. Where do you suggest to place this line of code?

**Comment by ACaj580** [comment]
Nevermind, found a solution for my problem.
