### ISSUE TITLE
HealthChecks UI not showing configured Webhook

### ISSUE THREAD

**Issue by snavarropino** [Xabaril/AspNetCore.Diagnostics.HealthChecks#131]
I have set up a webhooks to an Azure function using following configuration:

```json
 "HealthChecks-UI": {
    "HealthChecks": [
      {
        "Name": "Api",
        "Uri": "https://healthchecksapi.azurewebsites.net/healthCheck"
      },
      {
        "Name": "AnotherApi",
        "Uri": "https://healthchecksanotherapi.azurewebsites.net/healthCheck"
      }
    ],
    "Webhooks": [
      {
        "Name": "Send to azure function",
        "Uri": "https://savetoqueue.azurewebsites.net/api/HttpTrigger1?code=###",
        "Payload": "{\"HealthCheck\": \"[[LIVENESS]]\",\"Message\": \"[[FAILURE]]\"}",
        "RestoredPayload": "{\"HealthCheck\": \"[[LIVENESS]]\",\"Message\": \"Healthy\"}"
      }
    ]
  }
```
It is working fine, I can see invocations to my azure function, however the UI is not showing me this webhook

![imagen](https://user-images.githubusercontent.com/11868679/54682241-a74d5800-4b0e-11e9-8f2b-0621b52794b3.png)

**Comment by unaizorrilla** [comment]
This is a regression bug! Fixed on my latest commit and create a new tag. When appveyor finish you will be a new version on Nuget 2.2.23!

Thanks @snavarropino for fill this issue!

**Comment by snavarropino** [comment]
Working fine after updating the package.

Thanks for your prompt response guys!
