### ISSUE TITLE
Helm Deployment Errors - Microsoft.EntityFrameworkCore.DbUpdateException: Required properties '{'Uri'}' are missing for the instance of entity type 'HealthCheckConfiguration'

### ISSUE THREAD

**Issue by Alchemy86** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1314]
Please, fill the following sections to help us fix the issue

**What happened**: When deploying a working implementation based on eShopOnContainers via helm, the appliation will forever restart with the same error.

[12:02:19 INF] Configuring web host (WebStatus)...
--
Thu, Jun 30 2022 12:02:20 pm | [12:02:20 INF] Package versions (WebStatus)
Thu, Jun 30 2022 12:02:20 pm | [12:02:20 INF] Starting web host (WebStatus)...
Thu, Jun 30 2022 12:02:20 pm | [12:02:20 WRN] Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
Thu, Jun 30 2022 12:02:20 pm | [12:02:20 INF] Initializing UI Database
Thu, Jun 30 2022 12:02:21 pm | [12:02:21 INF] Saving healthchecks configuration to database
Thu, Jun 30 2022 12:02:22 pm | [12:02:22 ERR] An exception occurred in the database while saving changes for context type 'HealthChecks.UI.Core.Data.HealthChecksDb'.
Thu, Jun 30 2022 12:02:22 pm | Microsoft.EntityFrameworkCore.DbUpdateException: Required properties '{'Uri'}' are missing for the instance of entity type 'HealthCheckConfiguration'. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the entity key value.

**What you expected to happen**: Should startup succesfully

**How to reproduce it (as minimally and precisely as possible)**: A helm deployment of a basic healthcheck setup appears to be enough to trigger this.

**Source code sample**:
```
services.AddHealthChecks()
                .AddCheck("self", () => HealthCheckResult.Healthy());
                
                services.AddHealthChecksUI(setupSettings: settings =>
            {
                settings
                    .DisableDatabaseMigrations()
                    .SetEvaluationTimeInSeconds(10)
                    .SetMinimumSecondsBetweenFailureNotifications(100);
            }).AddInMemoryStorage();
            
           app.UseHealthChecksUI(config =>
            {
                config.ResourcesPath = string.IsNullOrEmpty(pathBase) ? "/ui/resources" : $"{pathBase}/ui/resources";
                config.UIPath = "/hc-ui";
            }); 
            
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapHealthChecks("/liveness", new HealthCheckOptions
                {
                    Predicate = r => r.Name.Contains("self")
                });
            });
```

**Anything else we need to know?**:

**Environment**: Kubernetes

- .NET Core version: 6
- Healthchecks version: 6.0.4
- Operative system: Linux
- Others:

**Comment by sungam3r** [comment]
`HealthCheckConfiguration.Uri` property is required one so I think you may missed to set it somewhere in your code/settings. Please free to reopen if this issue is still actual for you.
