### ISSUE TITLE
Not all nuget packages support netstandard2.0

### ISSUE THREAD

**Issue by michele-albanese-deltatre** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1315]
Some packages like :
AspNetCore.HealthChecks.Publisher.Datadog
AspNetCore.HealthChecks.UI.Client
AspNetCore.HealthChecks.UI
AspNetCore.HealthChecks.UI.InMemory.Storage

only supports net60, while others ( AspNetCore.HealthChecks.MongoDb, AspNetCore.HealthChecks.AzureStorage ) supports also netstandard20, would be nice to have netstandard20 back in...

**What would you like to be added**: 
consistent netstandard2.0 supports in the nuget packages

**Why is this needed**: multitargeting libraries that uses these healthchecks

**Comment by sungam3r** [comment]
PRs are welcome.

**Comment by sungam3r** [comment]
@michele-albanese-deltatre When preparing to v7 release many (but not all) projects were changed to use netstandard2.0 TFM. Check out the latest preview versions.
