### ISSUE TITLE
HealthChecks UI Not Preserving Order When Monitoring Multiple Services

### ISSUE THREAD

**Issue by roblangston** [Xabaril/AspNetCore.Diagnostics.HealthChecks#132]
When defining multiple services to monitor within the appsettings.json, I have seen scenarios where the displayed order of these services doesn't always reflect that in which they are defined. i.e. in the appsettings.json, I have the following:
`    "HealthChecks": [
      {
        "Name": "Service1",
        "Uri": "https://localhost:8050/health/ui"
      },
      {
        "Name": "Service2",
        "Uri": "https://localhost:8051/health/ui"
      },
      {
        "Name": "Service3",
        "Uri": "https://localhost:8052/health/ui"
      },`
In the UI, you can get any combination of displayed order i.e. Service3, Service1, Service2 or Service2, Service3, Service1.  I am guessing that the checks are currently being run async and rendered as the results come back in but it becomes difficult to track failures when the ordering changes.

**Comment by roblangston** [comment]
Hi, I have just upgraded the UI to 2.2.24 but the problem still seems the same.  I have not upgraded any of the services, they are still using UI.Client 2.2.3

**Comment by CarlosLanderas** [comment]
Hello @roblangston. It's weird. I've introduced another change where healthchecks configurations will be sorted before retrieving the health checks reports. As you can see I am getting all the endpoint configurations ordered the same way I have them configured in my appsettings.json
Let's see if version 25 works for you.

![image](https://user-images.githubusercontent.com/16475649/54764444-18b50580-4bf8-11e9-930d-95b1312936eb.png)

**Comment by roblangston** [comment]
Just upgraded to version 25 and there still seems to be a problem, see attached screenshot:-

![ServiceOrder](https://user-images.githubusercontent.com/13354992/54783762-224f6500-4c1a-11e9-999e-2febb2debf16.png)

**Comment by unaizorrilla** [comment]
Can you share with us your appsettings.json healthchecks section? (you can delete the healthz uri's )

**Comment by roblangston** [comment]
Sure, `"HealthChecks-UI": {
	"HealthChecks": [{
			"Name": "Service1",
			"Uri": ""
		}, {
			"Name": "Service2",
			"Uri": ""
		}, {
			"Name": "Service3",
			"Uri": ""
		}, {
			"Name": "Service4",
			"Uri": ""
		}, {
			"Name": "Service5",
			"Uri": ""
		}, {
			"Name": "Service6",
			"Uri": ""
		}, {
			"Name": "Service7",
			"Uri": ""
		}, {
			"Name": "Service8",
			"Uri": ""
		}, {
			"Name": "Service9",
			"Uri": ""
		}, {
			"Name": "Service10",
			"Uri": ""
		}, {
			"Name": "Service11",
			"Uri": ""
		}, {
			"Name": "Service12",
			"Uri": ""
		}, {
			"Name": "Service13",
			"Uri": ""
		}, {
			"Name": "Service14",
			"Uri": ""
		}, {
			"Name": "Service15",
			"Uri": ""
		}, {
			"Name": "Service16",
			"Uri": ""
		}, {
			"Name": "Service17",
			"Uri": ""
		}, {
			"Name": "Service18",
			"Uri": ""
		}, {
			"Name": "Service19",
			"Uri": ""
		}
	],
	"Webhooks": [{
			"Name": "",
			"Uri": "",
			"Payload": "",
			"RestoredPayload": ""
		}
	],
	"EvaluationTimeOnSeconds": 10,
	"MinimumSecondsBetweenFailureNotifications": 60
}
}
`
