### ISSUE TITLE
Is it possible to modify the frequency on health checks ? 

### ISSUE THREAD

**Issue by junsaw** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1321]
My StartUp code has this, is it possible to modify the frequency ? Any help will be much appreciated. 

services.AddHealthChecks()
.AddApplicationInsightsPublisher(Configuration["App:AppInsightsInstrumentationKey"])
.AddAzureBlobStorage(Configuration["Data:StorageAccountConnectionString"].ToString())
.AddAzureTable(Configuration["Data:StorageAccountConnectionString"].ToString());

**Comment by junsaw** [comment]
Do we have any update on this request ?

**Comment by rob-baldwin** [comment]
Hi @junsaw, the frequency of calls to your healthcheck endpoint can be determined by the [HealthChecksUI configuration](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks#ui-polling-interval) or whichever other tool you are using to check the health of your application, e.g. load balancer.

**Comment by sungam3r** [comment]
@rob-baldwin Thanks for response. Yes, HC design is poll-related (passive), not push (active).

**Comment by sungam3r** [comment]
For push design use `IHealthCheckPublisher` related classes.
