### ISSUE TITLE
AddAzureServiceBusTopic should have an option to create the topic if it doesn't already exist

### ISSUE THREAD

**Issue by Place1** [Xabaril/AspNetCore.Diagnostics.HealthChecks#134]
For my use-case I want to health check using a dedicated topic called "HealthCheck". For a particular environment this topic might not yet exist and it'd be helpful if the `AddAzureServiceBusTopic` health check had an option to create the topic automatically.

**Comment by CarlosLanderas** [comment]
Maybe we can add a flag in configuration. Something like CreateTopicIfNotExist or something like that.

**Comment by unaizorrilla** [comment]
IMHO create the topic is not our responsability!
