### ISSUE TITLE
Multiple Postgres DB support

### ISSUE THREAD

**Issue by vadrsa** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1346]
**What would you like to be added**: I would like to have the ability to add multiple Postgres database health checks

**Why is this needed**: In some scenarios the application may use multiple Postgres databases/schemas(different connection strings at the end of the day). In this scenarios this is very much needed.

I created a pull request with initial suggestion of how to implement it.
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1345

**Comment by sungam3r** [comment]
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1345#issuecomment-1363310703
