### ISSUE TITLE
Checks using background thread

### ISSUE THREAD

**Issue by mantasaudickas** [Xabaril/AspNetCore.Diagnostics.HealthChecks#135]
Hi,

did you considered a possibility to use background thread which does the heavy load and actual call to it just returns already known status?
As an example could be SQL server checks. Scenario I am looking for:
- healthcheck launches a thread where it does checking independently from requests (for example once in a second)
- request which calls check already gets a status from instance without actually connecting to database

Reason for that - we do not load sql with so many requests (at least it would be controlled), as health check requests might come much more often.

**Comment by unaizorrilla** [comment]
Not considered at this moment!

**Comment by mantasaudickas** [comment]
Would you consider a pull request with such implementation?

**Comment by unaizorrilla** [comment]
Hi @mantasaudickas 

First of all, thanks for fill the issue and colaborate with this project. IMHO this feature increment the complexibility with no (less) value. The number of healthcheck request depend on your configuration (liveness, readiness, ipublisherservice etc)  and (as your example) the cost of check (SELECT 1;) is priceless for the server.

**Comment by mantasaudickas** [comment]
Well.. if you think about one or two instances, than I can agree with you.
Now lets imagine 100 service instances running.. lets imagine that those instances might get status checks from consul each 10 seconds. Also there are other services (also can count more than 10), which depends on first set of instances and also might do status checks on their own.
So you will end up having almost 100 connections to the SQL server just for status and thousands of (SELECT 1;) calls.. which is not priceless anymore :)

I will do my own implementation in my project :)
Thanks for your thoughts.
