### ISSUE TITLE
Migrate from legacy "Microsoft.IdentityModel.Clients.ActiveDirectory" (ADAL) to "Microsoft.Identity.Client" (MSAL)

### ISSUE THREAD

**Issue by Kiechlus** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1363]
**What would you like to be added**:

We found out that KeyVault checks (and possibly others) still [use](https://www.nuget.org/packages/AspNetCore.HealthChecks.AzureKeyVault/) the deprecated [ADAL authentication library](Microsoft.IdentityModel.Clients.ActiveDirectory).

**Why is this needed**:

We are currently investigating SSL Heartbleed issues and detected that ADAL is using `System.Security.Cryptography.OpenSsl` version `4.3.0` from 2016. We are not sure if this is causing the issue, but it is still quite old. The new MSAL does not contain this package (tested on .Net 6).

**Comment by sungam3r** [comment]
PR is welcome.

**Comment by Kiechlus** [comment]
I don't even understand why this package is needed. I checked all files in the `HealthChecks.AzureKeyVault` namespace and don't find any reference to that package.

**Comment by WillemRB** [comment]
Both `Microsoft.Azure.Services.AppAuthentication` and `Microsoft.IdentityModel.Clients.ActiveDirectory` aren't needed in the project.

**Comment by sungam3r** [comment]
@Kiechlus I see no Microsoft.IdentityModel.Clients.ActiveDirectory references in `master`. Please try the latest preview packages.
