### ISSUE TITLE
Create option to publish only healthreports reporing a failure

### ISSUE THREAD

**Issue by Expecho** [Xabaril/AspNetCore.Diagnostics.HealthChecks#138]
Given the `AddApplicationInsightsPublisher()` method, I would love to have it support a flag indicating only reports indicating a failure are send to Application Insights. I am only interested in the amount of failures over time and since I am paying for the amount of data ingested I would like to filter out the normal state.

Other option would be to create an `ITelemetryProcessor` to filter out the items but I'd rather have built-in support.

I am more than willing to create a PR so we can take a closer look at how an implementation might look like.

**Comment by unaizorrilla** [comment]
You can filter on Application Insights using the status property if you are interested only on failures.

**Comment by Expecho** [comment]
I understand, but I do pay for that ingested data. So I would prefer to prevent it from entering Application Insights at all.

**Comment by unaizorrilla** [comment]
You can reduce the amount of data on AI using sampling!

**Comment by Expecho** [comment]
Also correct, but that might sample out unhealthy reports as well.

**Comment by Expecho** [comment]
So summarized, this are the current options:

- Sampling, but the drawback here is that unhealthy reports are excluded as well
- Telemetry Filter, best option for now but requires more work
- Filter in the query using the portal, but the drawback here is we still pay for the data we are not interested in and we send data over the wire we do not need/want

So I still see added value for being able to create a flag indicating only reports indicating a failure are send to Application Insights.

**Comment by unaizorrilla** [comment]
I'm not sure, let me check this with more people on the project and I try to respond you ASAP!

**Comment by lfraile** [comment]
After talking with @unaizorrilla we think waht you propose, @Expecho, makes sense.

Let me a couple of days to work in it.

**Comment by unaizorrilla** [comment]
or @Expecho you can contribute this?

**Comment by Expecho** [comment]
Sure, no problem. I will give it a go later this week!

**Comment by Expecho** [comment]
@lfraile @unaizorrilla I think we need to discuss the testing part of this proposed change. See the PR for details.

**Comment by lfraile** [comment]
Will take a look tomorrow

________________________________
De: Peter Bons <notifications@github.com>
Enviado: Thursday, April 4, 2019 9:13:13 PM
Para: Xabaril/AspNetCore.Diagnostics.HealthChecks
Cc: Luis Fraile Hernandez; Mention
Asunto: Re: [Xabaril/AspNetCore.Diagnostics.HealthChecks] Create option to publish only healthreports reporing a failure (#138)


@lfraile<https://github.com/lfraile> @unaizorrilla<https://github.com/unaizorrilla> I think we need to discuss the testing part of this proposed change. See the PR for details.

**Comment by unaizorrilla** [comment]
Closed by #143
