### ISSUE TITLE
Release newest code of AspNetCore.HealthChecks.AzureStorage

### ISSUE THREAD

**Issue by ChangeTheCode** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1382]
Please release the current code state to have the newest Azure.Storage.Blobs packages. 

[Bump Azure.Storage.Blobs from 12.12.0 to 12.13.0](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/commit/08638a8cab5f8fb68815bc4f1126e66cd47d2c93)

The newest version Azure.Storage.Blobs 12.13.0 has a vulnerably fix [info](https://security.snyk.io/package/pip/azure-storage-blob/12.8.1)

**Comment by sungam3r** [comment]
2.13 is compatible with 2.12. What if you just bump this dependency explicitly in your app ?

**Comment by ChangeTheCode** [comment]
I do not really like to add a transitive dependency in case it comes with an nuget package. I know i could fix it on this way. 
Tanks for your answer

**Comment by sungam3r** [comment]
@ChangeTheCode I published preview packages. Azure.Storage.Blobs now has version 12.14.1.
