### ISSUE TITLE
CosmosDbHealthCheck - consider registration overloads that accept a CosmosClient instance

### ISSUE THREAD

**Issue by danielmpetrov** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1384]
Hi. I appreciate the library and your effort. 👍

**What would you like to be added**:

I would like to see an overload for CosmosDb health checks that accepts a `CosmosClient` instance.

**Why is this needed**:

According to the official Cosmos SDK v3 documentation (see https://docs.microsoft.com/en-us/azure/cosmos-db/sql/performance-tips-dotnet-sdk-v3-sql#sdk-usage), the `CosmosClient` was designed to be singleton for optimal performance. However, the library does not expose a dependency injection overload that accepts a client, but instead internally creates and maintains a new client for each health check - https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.CosmosDb/CosmosDbHealthCheck.cs#L58.

This can cause a frustrating developer experience when reading cosmos diagnostic logs and seeing more client instances than expected.

**Comment by sungam3r** [comment]
> instead internally creates and maintains a new client for **each** health check

Not true. Clients are cached in static dictionary by connection.

**Comment by danielmpetrov** [comment]
You're right, it's a new client per connection. The main point still stands, that's an extra client per process, which is not ideal. Would you consider accepting a PR for this?

**Comment by sungam3r** [comment]
I don't understand yet how it can be client **not** per connection if `CosmosClient` constructor accepts `connectionString` argument 😕  .

**Comment by danielmpetrov** [comment]
It cannot be, but the server using the application already creates its own client. The health check creates its own client also, resulting in two clients in the same process for the same connection string.

**Comment by sungam3r** [comment]
Understood. 

> I would like to see an overload for CosmosDb health checks that accepts a CosmosClient instance.

Sure. PR is welcome.

**Comment by danielmpetrov** [comment]
Good news, #1405 has added the exact API that we needed. 🎉

Thank you @wsugarman for the contribution. 👍

**Comment by wsugarman** [comment]
@danielmpetrov Haha! Happy to (inadvertently) help!

**Comment by danielmpetrov** [comment]
It's a really good change, but registration methods that directly accept a client will still be beneficial in cases where we have apps that reach out to multiple cosmos accounts.

Code sample:

```csharp
var client1 = new CosmosClient(connection1);
var client2 = new CosmosClient(connection2);

// ...

services
    .AddHealthChecks()
    .AddCosmosDb(client1, name: "sample 1")
    .AddCosmosDb(client2, name: "sample 2");
```

In this case we don't directly register the clients in the container because they share a type, so the overloads from #1405 won't work. However, that PR sets this change to be a very simple one, since the health check now has the appropriate constructor overloads.

I could add the registration methods if this still makes sense to everyone.

**Comment by sungam3r** [comment]
PR is welcome.
