### ISSUE TITLE
IdSvrHealthCheck: missing string interpolation

### ISSUE THREAD

**Issue by espenrl** [Xabaril/AspNetCore.Diagnostics.HealthChecks#14]
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/7980f0dada403ac444b39347de4787af0c91b333/src/HealthChecks.IdSvr/IdSvrHealthCheck.cs#L28

Minor issue, but this string should be an interpolated string.

**Comment by unaizorrilla** [comment]
Thanks @espenrl for fill this issue, I try to solve asap
