### ISSUE TITLE
HealthCheck-UI Container (inside a K8s POD) is increasingly consuming CPU

### ISSUE THREAD

**Issue by NabilKem** [Xabaril/AspNetCore.Diagnostics.HealthChecks#142]
Hello,
I deployed the HealthCheck-UI in an K8s, and when I first check the CPU consumption of the POD , it has a small value, but after a couple of hours it start consuming 20% of CPU, and after couple of days it is showing a consumption of 50% of CPU !! 

Can you please help investigate this behavior as this escalate in CPU consumption will make K8s kill the POD.

Please advice, Thanks in advance!

**Here is the environment set  :** 

      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - HealthChecks-UI__HealthChecks__1__Name=Service1-Api
      - HealthChecks-UI__HealthChecks__1__Uri=http://Service1-api/hc
      - HealthChecks-UI__HealthChecks__2__Name=Service2-Api
      - HealthChecks-UI__HealthChecks__2__Uri=http://Service2-api/hc
      - HealthChecks-UI__HealthChecks__3__Name=Service3-Api
      - HealthChecks-UI__HealthChecks__3__Uri=http://Service3-api/hc
      - HealthChecks-UI__HealthChecks__4__Name=Service4-Api
      - HealthChecks-UI__HealthChecks__4__Uri=http://Service4-api/hc
      - HealthChecks-UI__HealthChecks__5__Name=Service5-Api
      - HealthChecks-UI__HealthChecks__5__Uri=http://Service5-api/hc
      - HealthChecks-UI__HealthChecks__6__Name=Service6-Api
      - HealthChecks-UI__HealthChecks__6__Uri=http://Service6-api/hc
      - HealthChecks-UI__HealthChecks__7__Name=Service7
      - HealthChecks-UI__HealthChecks__7__Uri=http://Service7/hc
      - HealthChecks-UI__HealthChecks__8__Name=Web
      - HealthChecks-UI__HealthChecks__8__Uri=http://web/hc
      - HealthChecks-UI__HealthChecks__9__Name=Service9
      - HealthChecks-UI__HealthChecks__9__Uri=http://Service9/hc
      - HealthChecks-UI__HealthChecks__10__Name=Service9
      - HealthChecks-UI__HealthChecks__10__Uri=http://Service9/hc
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY_SERVICESSTATUS}

**Comment by unaizorrilla** [comment]
Hi,

Witch version?

**Comment by NabilKem** [comment]
Hi,

Here all the Healthcheck packages I am using, Thanks!

    <PackageReference Include="AspNetCore.HealthChecks.UI" Version="2.2.8" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="2.2.2" />
    <PackageReference Include="AspNetCore.HealthChecks.Uris" Version="2.2.0" />
     <PackageReference Include="Microsoft.AspNetCore.Diagnostics.HealthChecks" Version="2.2.0" />

**Comment by unaizorrilla** [comment]
Please upgrade to UI 2.2.27 (we have memory leaks and other performance issues on old versions) and let met know!

**Comment by NabilKem** [comment]
OK, I redeployed with the latest package versions, I will check the CPU consumption later today! Thanks!

**Comment by NabilKem** [comment]
Ok, updating the packages resolved the issue.
Thanks
