### ISSUE TITLE
Include symbols (.pdb) in nuget package

### ISSUE THREAD

**Issue by afaganga** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1423]
**What would you like to be added**: I would like for the compilation symbols to be added to the .nupkg, specifically, to the HealthChecks.RabbitMQ package.

**Why is this needed**: This enables line-by-line debug and observing the exception to determine the root cause.

**Comment by sungam3r** [comment]
SourceLink support was added in #953 .

**Comment by sungam3r** [comment]
@afaganga Try the latest preview packages.
