### ISSUE TITLE
Add configuration to control whether to output logs

### ISSUE THREAD

**Issue by JavaScript-zt** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1426]
health checks  too many logs,
Add configuration to control whether to output logs plz

![image](https://user-images.githubusercontent.com/19992219/188349096-37a1a31b-f034-4193-8208-67e28a63681f.png)

**Comment by sungam3r** [comment]
You can configure logging verbosity for Microsoft.Extensions.Logging by specifying [configuration values](https://docs.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line#configure-logging).

**Comment by JavaScript-zt** [comment]
wtf

**Comment by sungam3r** [comment]
@JavaScript-zt Feel free to reopen if you have further questions.
