### ISSUE TITLE
Consider downgrading to .NET Standard 2.0

### ISSUE THREAD

**Issue by sjetha** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1427]
**What would you like to be added**:
The .NET Standard version of the library downgraded to .NET Standard 2.0.

**Why is this needed**:
We currently have two separate back-end applications where one is a legacy .NET Framework 4.8 implementation and one is a .NET 6 implementation. We would like to have health checks for both back-end applications but because this library supports .NET Standard 2.1, we are unable to use this library for our .NET Framework application. We would appreciate it if the library's .NET Standard support were downgraded to .NET Standard 2.0.
Presently, we are cloning the repo and making the required changes locally, but this can easily lead to drift against this repo.

**Comment by sungam3r** [comment]
What **library** exactly are you talking about? This repo contains ~40 projects.

**Comment by sjetha** [comment]
Hi. Here are the libraries from this project that we are currently using. From what I understand the only change is related to 

HealthChecks.ApplicationStatus
HealthChecks.Aws.S3
HealthChecks.Aws.SecretsManager
HealthChecks.Aws.Sns
HealthChecks.Aws.Sqs
HealthChecks.Aws.SystemsManager
HealthChecks.DynamoDb
HealthChecks.ElasticSearch
HealthChecks.Kafka
HealthChecks.Network
HealthChecks.SignalR
HealthChecks.SqlServer
HealthChecks.System
HealthChecks.Uris

**Comment by sungam3r** [comment]
Each project you provided is targeted as `<TargetFrameworks>$(NetFrameworkVersion);$(NetStandardVersion)</TargetFrameworks>` where `NetStandardVersion` equals `netstandard2.0`

**Comment by sjetha** [comment]
That's peculiar. I'll take another look at what we're doing and re-open the ticket if I find something new.
Thanks for taking the time to do this.

**Comment by RoLYroLLs** [comment]
@sjetha I was under the impression this couldn't be used with .Net Framework 4.8. I was actually about to write my own custom checks when I found this. I'm going to scour the internet for how to do this. Any help/guidance would be greatly appreciated.

**Comment by sungam3r** [comment]
> Any help/guidance would be greatly appreciated.

**All** packages listed above have TFM=netstandard2.0 . What guidance exactly do you expect?

**Comment by RoLYroLLs** [comment]
> What guidance exactly do you expect?

Thank you for your reply! Looking through the docs, it shows how to use them in .Net Core projects, ie: `services.AddHealthChecks(); ...` I'm unfamiliar with how to get started using them with .Net Framework 4.7.2.

**Comment by sungam3r** [comment]
I'd suggest you to look into `Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckMiddleware` and `Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService`. You may reuse all that code to a greater or lesser extent depending on how your application is designed.

**Comment by RoLYroLLs** [comment]
Thank you! I'll look into that.

**Comment by RoLYroLLs** [comment]
Thanks @sungam3r Apparently, I'm not knowledgeable enough to understand what I have to do for a .net Framework 4.7.2 Web Forms app. For now I'll just make something simple until I figure things out or find good resources. Thanks again!
