### ISSUE TITLE
Example to check smtp and memory health check 

### ISSUE THREAD

**Issue by RaminderRandhawa91** [Xabaril/AspNetCore.Diagnostics.HealthChecks#144]

**Comment by lurumad** [comment]
Hi @RaminderRandhawa91 

You have an example in FunctionalTests project:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/test/FunctionalTests/HealthCheck.Network/SmtpHealthCheckTests.cs

And also for the memory:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/test/FunctionalTests/HealthChecks.System/MemoryHealthCheckTests.cs

Please let me know if works for you.

Regards!

**Comment by RaminderRandhawa91** [comment]
Thank you so much. That helped a lot
