### ISSUE TITLE
How to add custom description for health check

### ISSUE THREAD

**Issue by RaminderRandhawa91** [Xabaril/AspNetCore.Diagnostics.HealthChecks#145]
I am able to see Name, Health, Description and Duration fields for my database. 
But the description field is empty.
Is there a way to add customized string for the description ?

Thanks in advance!

**Comment by unaizorrilla** [comment]
Hi @RaminderRandhawa91

Description field contain the error description when the healthcheck entry is not working. Probably Error | Error Description will be a good name for this field. We are working on next version of the UI, I try to address this!

**Comment by RaminderRandhawa91** [comment]
Thank you!
