### ISSUE TITLE
Realtime Database / Cloud Firestore

### ISSUE THREAD

**Issue by Odonno** [Xabaril/AspNetCore.Diagnostics.HealthChecks#146]
Create HealthChecks package for the Firebase platform starting with:

* Realtime Database
* Cloud Firestore

**Comment by unaizorrilla** [comment]
Hi @Odonno 
I don't use Firebase platform and don't know libraries etc.. Contributions are open on this repo if you can create new HealthChecks for this plattform.!

Unai

**Comment by unaizorrilla** [comment]
Merged!
