### ISSUE TITLE
Oracle health check timeout

### ISSUE THREAD

**Issue by epetrushevsky** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1467]
Please, fill the following sections to help us fix the issue

**What happened**:
OracleHealthCheck doesn't respect timeout setting.
As ODP.NET isn't async, passing CancellationToken doesn't affect underlying db operation.
You will get TaskCancelledException, that will make oracle dependency Unhealthy, only if you provide already cancelled CancellationToken.

**What you expected to happen**:
OracleHealthCheck doesn't take longer than timeout I specified.

**How to reproduce it (as minimally and precisely as possible)**:

**Source code sample**:

**Anything else we need to know?**:

**Environment**:

- .NET 6
- Healthchecks version: 6.0.3
- Operative system: windows (doesn't matter)
- Others:

**Comment by sungam3r** [comment]
> As ODP.NET isn't async, passing CancellationToken doesn't affect underlying db operation.

Could you provide a test that verifies this?

**Comment by sungam3r** [comment]
Closed due to lack of feedback. Also you may try the latest preview package.
