### ISSUE TITLE
HealthCheck timeouts in correlation with HealthCheckUI

### ISSUE THREAD

**Issue by michaeloxygen** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1470]
Some of this issue was also mention here [#1160](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/1160)
But I have done some further testing to simplify the case.

Sometimes our HealthCheckUI overview fails to show that a HealthCheck has failed because it took longer than 100 seconds to complete. We have some heavy db operations that verify the integrety of a product tree. It's ok that it takes more than 100 seconds to complete, but if it does HealthCheckUI just shows that "The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing."
There is no HttpClient involved in my HealthCheck so I can only assume that HealthCheckUI uses an HttpClient to check the configured endpoints to see if they are alive.
When calling the endpoint directly I get that the healthcheck is successfull.

To reproduce this issue I have created the following:

- One HealthCheck implemented as such, notice the 2 minute timeout on this HealthCheck

`services.AddHealthChecks()
                .AddCheck<TimeoutHealthCheck>("TimeoutCheck", failureStatus: HealthStatus.Unhealthy, timeout: new TimeSpan(0, 2, 0), tags: new[] { "TimeoutTest" });`

- Mapped the HealthCheck to a route and filtered it to show on "TimeoutTest" on the app.UseEndpoints(endpoints =>
`endpoints.MapHealthChecks("/healthcheck/timeouttest", new HealthCheckOptions
                {
                    Predicate = reg => reg.Tags.Contains("TimeoutTest"),
                    ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
                });`

- Setup the MapHealthChecksUI
`endpoints.MapHealthChecksUI(setup =>
                {
                    setup.AddCustomStylesheet("dotnet.css");
                });`

- Added the HealthChecksUI config in appsettings.json
`"HealthChecksUI": {
    "HealthChecks": [
      {
        "Name": "TimeoutTest",
        "Uri": "/healthcheck/timeouttest"
      }
    ]`
- Implemented the HealthCheck which does nothing except run i a while loop until 105 seconds have elapsed to simulate work
`Stopwatch sw = Stopwatch.StartNew();
            while(sw.ElapsedMilliseconds < 105000)
            {
                //do stuff
            }
            sw.Stop();
            return HealthCheckResult.Healthy($"Timeout not hit Stopwatch ran for {sw.ElapsedMilliseconds} ms");`

With this the url /healthchecks-ui#/healthchecks returns an Unhealthy state for my HealthCheck endpoint "TimeoutTest" (not the HealthCheck it self)
![2022-09-30_13-04-54](https://user-images.githubusercontent.com/8157442/193256594-c6010da8-36a2-4e61-aa26-b0ff0dfb2dde.png)

But the endpoint for the actual healthcheck completes successfully
![2022-09-30_13-05-49](https://user-images.githubusercontent.com/8157442/193256805-ceb5248e-18cc-412a-ba17-f17762152f14.png)

There doesn't seem to be anywhere I can configure the HttpClient timeout for the HealthCheckUI built in HttpClient, but if it's there please do share :) If it's not there can I circumvent this behaviour or have it added in some way?

Thanks in advance!

**Comment by CrustyApplesniffer** [comment]
I think you can set up the client timeout this way (if you want a 5 minutes timeout):
```
services.AddHealthChecksUI(setupSettings: setup => {
    setup.ConfigureApiEndpointHttpclient((sp, client) => {client.Timeout = TimeSpan.FromSeconds(300); });
};
```

**Comment by sungam3r** [comment]
Thanks @CrustyApplesniffer . Indeed, `HealthCheckReportCollector` pulls HttpClient with `health-checks` name from DI container (via `IHttpClientFactory.CreateClient` API).

`ConfigureApiEndpointHttpclient` configures http client with the same name.
