### ISSUE TITLE
Requesting Permission to make EventStore gRPC HealthCheck Package

### ISSUE THREAD

**Issue by NielsPilgaard** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1486]
Hi! 👋 

**What would you like to be added**:
I would like to create a HealthCheck package for the gRPC client for EventStore.

**Why is this needed**:
EventStore has deprecated their TCP client and moved to a gRPC implementation. 
It would be nice to have a healthcheck package for it, to verify whether a connection can be made or not.

**Comment by sungam3r** [comment]
PR is welcome.

**Comment by NielsPilgaard** [comment]
Great 👍
