### ISSUE TITLE
SQL Server Health Check with Managed Identity (Azure Access Token)

### ISSUE THREAD

**Issue by johnayoub** [Xabaril/AspNetCore.Diagnostics.HealthChecks#150]
The current API doesn't allow connecting to Azure SQL Server using managed identity and an access token!

Any plans to add this feature or any suggested workaround in the meantime?

**Comment by unaizorrilla** [comment]
Hi, 

Interesting!! Let me check this. Of course contributions are open!! 👍

**Comment by inkel** [comment]
I've similar issues with this and ended up creating a custom SQL Server health check: we use a custom connection manager, so this health check uses that, but while working on that I thought about how this feature could be added to `AspNetCore.HealthChecks.SqlServer`.

There's a tutorial named [_Secure Azure SQL Database connection from App Service using a managed identity_](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-connect-msi) that does the following once the connection is created:

```csharp
var conn = (System.Data.SqlClient.SqlConnection)Database.GetDbConnection();
conn.AccessToken = (new Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider()).GetAccessTokenAsync("https://database.windows.net/").Result;
```

In this case `conn` could be replaced with `conn = SqlConnection(_connectionString)` in [`src/HealthChecks.SqlServer/SqlServerHealthCheck.cs`](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/83047f04bdb1bdc8b641208dd5c36e7a0599d372/src/HealthChecks.SqlServer/SqlServerHealthCheck.cs), however that way of getting the access token is only for Azure managed SQL Databases. At my company we get the access token in a different way:

```csharp
var credential = new ClientCredential(clientId, clientSecret);
var authenticationContext = new AuthenticationContext(databaseAuthority);
var authenticationResult = await authenticationContext.AcquireTokenAsync(target, credential);
var accessToken = authenticationResult.AccessToken;
```

Given that there might be many different ways to specify the value of [`SqlConnection.AccessToken`](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.accesstoken), I think that the easiest way to implement this is to change the `SqlServerHealthCheck` constructor to either accept an optional `string accessToken = null` value, or an overloaded that accepts an `SqlConnection` instead.

I think the simplest is definitely adding an additional parameter, however, adding a constructor that accepts `SqlConnection` can be useful when combined with dependency injection.

Either way, I'll gladly send a PR for this if you like and we agree on how to implement it.

**Comment by Nisden** [comment]
@inkel What about adding an ```Action<SqlConnection> beforeOpen```? That would allow users to set the AccessToken, and would be more future proof.

**Comment by inkel** [comment]
@Nisden that sounds great! Would you like me to submit a PR for this?

**Comment by Nisden** [comment]
@inkel If you got the time for it, it would be awesome. Otherwise I could look into it.

**Comment by inkel** [comment]
@Nisden hey, sorry for the delay in replying. 

Yeah, I think I can manage to make the time this or next week. Would that work?

**Comment by JoeSainsburys** [comment]
I could really do with this functionality as well. I will raise a PR today if that is alright? I think I will go for the beforeOpen Action approach since that seems more flexible.

**Comment by inkel** [comment]
@JoeSainsburys thank you! I really hope they approve it soon and is available in the next release.
