### ISSUE TITLE
Feat - Control health checks from appsettings.json

### ISSUE THREAD

**Issue by ruant** [Xabaril/AspNetCore.Diagnostics.HealthChecks#151]
Would be really nice to be able to control the healthchecks from the appsettings.
Is there a package for this?

**Comment by unaizorrilla** [comment]
Can you explain with more detail the scenario?

**Comment by ruant** [comment]
So let's say you have an application that has many features.  
Where the customers can activate different features of the application.

Let's say Customer A is using Feature 1 and 2.
Customer B is using Feature 1 and 3.

The application is deployed to the customers own server.
So then I want to be able to have the healthchecks "mirror" the features that's been activated.

Now, the healthchecks are hardcoded in the Startup file, would be really nice if this hardcoded stuff could be read from appsettings.json

(Sorry for the late reply)

**Comment by CarlosLanderas** [comment]
@ruant, we have tens of Health Checks and surely more to come, and there is no simple way to be able to configure health checks by using appsettings.json as health checks have different registrations mechanisms. They can be registered using code factories, using different overloads, etc.

I suggest you create your own registration mechanisms based on Features and configuration.

Thanks
