### ISSUE TITLE
Healthcheck summary prometheus / grafana dashboard

### ISSUE THREAD

**Issue by gmoreno90** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1516]
Hi team. 
Anybody is working with exporting healthchecks to prometheus and have a dashboard to show that information using grafana?
Many thanks in advance

**Comment by sungam3r** [comment]
Probably not.

**Comment by sungam3r** [comment]
@gmoreno90 I'm not sure but StackOverflow may be better place to ask. Closing, sorry.
