### ISSUE TITLE
Ability to register TCP EventStore HealthChecks with IEventStoreConnection

### ISSUE THREAD

**Issue by NielsPilgaard** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1523]
**What would you like to be added**:
An additional registration method for the EventStore HealthCheck package, that accepts a ConnectionSettings object instead of a connection string. 

**Why is this needed**:
Making an EventStore connection string for anything but plain localhost is cumbersome, and error prone, for me at least 😄 
Using the EventStore provided ConnectionSettingsBuilder would simplify the registration quite a bit.

I'll gladly make the changes required of course.

**Comment by sungam3r** [comment]
👍

**Comment by NielsPilgaard** [comment]
After playing around with this, I found out accepting `IEventStoreConnection` was more fitting, as it would support clustered/non-clustered scenarios better. I hope that's fine :)

**Comment by NielsPilgaard** [comment]
I'm abandoning my efforts to implement this.
