### ISSUE TITLE
Registration methods for EventStore TCP+gRPC passing in the ServiceProvider

### ISSUE THREAD

**Issue by NielsPilgaard** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1531]
**What would you like to be added**:
I would like access to the `ServiceProvider` when adding eventstore healthchecks, so I can access configurations through it.

**Why is this needed**:
This will allow creation of connection string to change depending on configuration.

I'll gladly submit a PR for this. I plan to copy the logic utilized in the `HealthChecks.SqlServer` package.

**Comment by sungam3r** [comment]
ok
