### ISSUE TITLE
Error with running .Net 7

### ISSUE THREAD

**Issue by mehdihadeli** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1534]
Hi,
Today I migrated my app to .Net 7, but health check doesn't work correctly, and I get some error.
I think you should upgrade some of your packages.

**Comment by sungam3r** [comment]
Rel: #1533

**Comment by marioleed** [comment]
For reference, what errors do you get?

I'm not having any problems yet. "Works on my machine" 😅

**Comment by sboulema** [comment]
I got errors about the ui client reporter, related to trimming.

Removing the trimmode=link from my build pipeline fixed it.

Net7 changed trim defaults, so errors were to be expected there anyway.

**Comment by mehdihadeli** [comment]
I checked it again and it works :D
