### ISSUE TITLE
Add Managed Identity support for EventHub in Azure Service Bus

### ISSUE THREAD

**Issue by marioleed** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1537]
**What would you like to be added**:
TokenCredential (MSI) support for EventHub in the same manner Service Bus (same package) is set up today.

**Why is this needed**:
To be able to use MSI (with all the benefits it entails) instead of a connection string.

**Comment by marioleed** [comment]
I could help out and contribute with a PR.

**Comment by unaizorrilla** [comment]
> I could help out and contribute with a PR.

👌
