### ISSUE TITLE
Is there a way to change HealthChecks.UI.Configuration.SetEvaluationTimeInSeconds dynamically at runtime?

### ISSUE THREAD

**Issue by MeiPorulSeeker** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1541]
I am using this HealthChecks nuget package to develop a customized Health check app. One usecase requires the polling frequency to be different across 2 time slots. Eg: from 11pm - 5 am it has to be polling every 10 seconds and from 5 am - 11pm it needs to poll every minute. 

Is there any way to change the polling interval "SetEvaluationTimeInSeconds" dynamically when clock hits 11pm?

**Comment by sungam3r** [comment]
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollectorHostedService.cs#L94

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollectorHostedService.cs#L31


Just try to obtain `IOptions<Settings>` from DI container, change `EvaluationTimeInSeconds` and that's all. `HealthCheckCollectorHostedService` should use the same instance of settings so it will take your new value for `Task.Delay`.

**Comment by sungam3r** [comment]
@MeiPorulSeeker Did it work for you?

**Comment by MeiPorulSeeker** [comment]
Yes this worked @sungam3r . I nearly gave up on getting a solution but then found ur answer yday and the hint worked for me to extend it for my requirement. 
Thanks!
However I have one question.. If there are more than one endpoint to monitor, can we set a unique evalualtion time for each endpoint? I think NO is the answer because this setting is on App level and we can have only one timer. 
Let me know if my understanding is correct.

**Comment by sungam3r** [comment]
Right. One `HealthCheckCollectorHostedService`, one `Settings`. Strictly speaking this is DI-container level configuration (not app level, not some static stuff) so you _may_ try to host more than one container (ServiceCollection) in your app but it would be a very-very weird solution that is not worth spent efforts.
