### ISSUE TITLE
Update Nuget version for AspNetCore.HealthChecks.SendGrid

### ISSUE THREAD

**Issue by unger** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1543]
It seems like the latest published version of AspNetCore.HealthChecks.SendGrid is 6.0.2 which depends on SendGrid 9.24.4 although it looks like the master branch for AspNetCore.HealthChecks.SendGrid project is updated to use SendGrid 9.28.1.

Is it possible to release a new version of this Nuget package?

**Comment by sungam3r** [comment]
Of course this is possible but you may reference v9.28.1 directly in consuming project to bump dependency version.

**Comment by unger** [comment]
Yes I am aware of this, problem is kind of minor but I keep getting a warning of this when running Snyk dependency scanning :)

**Comment by sungam3r** [comment]
I think all packages could be published at once when https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/1533 will be complited.

**Comment by sungam3r** [comment]
@unger Please try this https://www.nuget.org/packages/AspNetCore.HealthChecks.SendGrid/7.0.0-rc2.3
