### ISSUE TITLE
NATS check still failing after NATS Server is restarted (AspNetCore.HealthChecks.Nats)

### ISSUE THREAD

**Issue by nosalan** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1544]
**What happened**:
1. Configure NATS check with NATS Url for readiness:
```
builder.AddNats(options =>
{
    options.Url = "nats://infra-nats:4222";
}, name: "nats", tags: new[]
{
    "ready"
});
```
2. Everyting is working, NATS (deployed in K8s too) is up, healthcheck is working.
3. NATS is down for like 2 minutes due to restart or Kubernetes moving it.
4. Service that has the health check detects it 
5. Service fails readiness probe 
6. NATS is back on-line
7. Service health check still fails despite NATS being accessible again. Readiness probe interval is 15 seconds but we waited like hours and the check never starts working again.
8. Only the service restart helps.

**What you expected to happen**:
NATS healthcheck detects that NATS is back online.

**Environment**:

- .NET Core version: 
```
.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
- Healthchecks version:` <PackageReference Update="AspNetCore.HealthChecks.Nats" Version="6.0.3" />`
- Operative system: `alpine 3.16.3` in Docker

**Comment by sungam3r** [comment]
@nosalan I have never used NATS. Check out #1546 . I was guided by general considerations based on public APIs.

**Comment by nosalan** [comment]
@sungam3r Thanks for looking into this. I don't have experience in using C# to interact with NATS other than ops perspective that includes healthchecks configuration. But I have given a general review. If you have published some pre-release version I can try it out.

**Comment by sungam3r** [comment]
@nosalan https://www.nuget.org/packages/AspNetCore.HealthChecks.Nats/6.0.4--rc2.2
