### ISSUE TITLE
Expose possibility to add custom discovery services

### ISSUE THREAD

**Issue by skwasiborski** [Xabaril/AspNetCore.Diagnostics.HealthChecks#155]
I would like to be able to write my own discovery service similar to the KubernetesDiscoveryHostedService (but for service fabric in my case).

As far as I understand the code base currently only way to change the configuration in runtime i.e. after initial startup is to write directly to the underlying db (this is what KubernetesDiscoveryHostedService does). Unfortunately all the dbContext related classes are internal so it is not possible to write any custom code changing the contents of the db.

It would be great if ability to reload the config or add new HealthCheckConfigurations would be provided.

**Comment by unaizorrilla** [comment]
Hi @skwasiborski 

I try to add this extensibility into next UI vesion, thanks for fill this issue. At this moment as you mentioned, the DbContext we use don't have any extensibility point.

**Comment by CarlosLanderas** [comment]
@skwasiborski we are going to add this and more requested features like customizing namespaces for k8s. We will try that registering custom discovery services is easy and straight forward. 
Thanks :)

**Comment by skwasiborski** [comment]
Great to hear you are working of this. @CarlosLanderas if you would consider accepting pull request for this let me know if I can help.

**Comment by phnx47** [comment]
@CarlosLanderas Any news? I want use consul discovery services. But, I see that many classes are internal.

**Comment by CarlosLanderas** [comment]
Hello. The latest preview UI version has several storage providers. The Context is now public and can be retrieved using Service Provider. All the details about this new version are in the README. Please take a look and tell me if this works four you

**Comment by CarlosLanderas** [comment]
We've also extended discovery service to support namespaces and included further features like labels and annotations and created the k8s operator that automatically deploys the UI and discoves services for you

**Comment by phnx47** [comment]
I want create my own discovery like k8s, but with Consul. I didn't find information about this in README. 

How I can extend this library without fork and change internal classes?

I use latest preview version.
