### ISSUE TITLE
MissingMethodException after migrating to .net7 and EF Core 7

### ISSUE THREAD

**Issue by vladop** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1555]
I get error System.MissingMethodException : Method not found: 'System.Collections.Generic.IList`1<Microsoft.EntityFrameworkCore.Metadata.Conventions.IModelFinalizingConvention> Microsoft.EntityFrameworkCore.Metadata.Conventions.ConventionSet.get_ModelFinalizingConventions()'.

I am using package 

after migrating to .net7 and EF Core 7

.NET Core version : .net7.0
Healthchecks version (latest at point of this writing: 6.0.5
Operative system: Windows 10
Others: s

**Comment by sungam3r** [comment]
What EF packages do you use?

**Comment by vladop** [comment]
Microsoft.EntityFrameworkCore.Design
Microsoft.EntityFrameworkCore
Microsoft.EntityFrameworkCore.Relational
Microsoft.EntityFrameworkCore.Sqlite
Microsoft.EntityFrameworkCore.SqlServer 
all of version 7.0.0

**Comment by sungam3r** [comment]
I'm pretty sure that all EF related packages here should be recompiled to use v7. Rel: #1533

**Comment by RickGanKL** [comment]
I also get an issue when I try to use the storage by SQLite.

`  services.AddHealthChecksUI()
                .AddSqliteStorage($"Data Source=sqlite.db");`

System.MissingMethodException: 'Method not found: 'Microsoft.EntityFrameworkCore.Migrations.Operations.Builders.OperationBuilder`1<Microsoft.EntityFrameworkCore.Migrations.Operations.CreateIndexOperation> Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder.CreateIndex(System.String, System.String, System.String, System.String, Boolean, System.String)'.'

**Comment by vladop** [comment]
@RickGanKL do you get error if you disable migrations with  options.DisableDatabaseMigrations();. I suppose you do but different error message will be shown

**Comment by LuigiMaestrelli** [comment]
I have a similar problem, but I'm using InMemoryStorage for now.

`Method not found: 'System.Collections.Generic.IList`1<Microsoft.EntityFrameworkCore.Metadata.Conventions.IModelFinalizingConvention> Microsoft.EntityFrameworkCore.Metadata.Conventions.ConventionSet.get_ModelFinalizingConventions()'.`

Libs:
NET 7
HeathCheck 6.0.5
EFCore 7.0.0

**Comment by FernandoSimoesPernabel** [comment]
> I have a similar problem, but I'm using InMemoryStorage for now.
> 
> `Method not found: 'System.Collections.Generic.IList`1<Microsoft.EntityFrameworkCore.Metadata.Conventions.IModelFinalizingConvention> Microsoft.EntityFrameworkCore.Metadata.Conventions.ConventionSet.get_ModelFinalizingConventions()'.`
> 
> Libs: NET 7 HeathCheck 6.0.5 EFCore 7.0.0

I have the same issue using InMemoryStorage

**Comment by alexandruhuruniuc** [comment]
> > I have a similar problem, but I'm using InMemoryStorage for now.
> > `Method not found: 'System.Collections.Generic.IList`1<Microsoft.EntityFrameworkCore.Metadata.Conventions.IModelFinalizingConvention> Microsoft.EntityFrameworkCore.Metadata.Conventions.ConventionSet.get_ModelFinalizingConventions()'.`
> > Libs: NET 7 HeathCheck 6.0.5 EFCore 7.0.0
> 
> I have the same issue using InMemoryStorage

I had the same issue using InMemoryStorage. I fixed it by adding `Microsoft.EntityFrameworkCore.InMemory` package to my project.

**Comment by sungam3r** [comment]
May be fixed by #1574 .

**Comment by dloperab** [comment]
> > > I have a similar problem, but I'm using InMemoryStorage for now.
> > > `Method not found: 'System.Collections.Generic.IList`1<Microsoft.EntityFrameworkCore.Metadata.Conventions.IModelFinalizingConvention> Microsoft.EntityFrameworkCore.Metadata.Conventions.ConventionSet.get_ModelFinalizingConventions()'.`
> > > Libs: NET 7 HeathCheck 6.0.5 EFCore 7.0.0
> > 
> > 
> > I have the same issue using InMemoryStorage
> 
> I had the same issue using InMemoryStorage. I fixed it by adding `Microsoft.EntityFrameworkCore.InMemory` package to my project.

Thank you so much @alexandruhuruniuc . It worked perfectly!

**Comment by sungam3r** [comment]
All 7.0.0-preview packages have been published. Please try https://www.nuget.org/packages/AspNetCore.HealthChecks.UI/7.0.0-rc2.6 .

**Comment by FernandoSimoesPernabel** [comment]
> All 7.0.0-preview packages have been published. Please try https://www.nuget.org/packages/AspNetCore.HealthChecks.UI/7.0.0-rc2.6 .

@sungam3r I removed Microsoft.EntityFrameworkCore.InMemory from my project and update to rc2.6 and worked correctly, thank you very much!

**Comment by sungam3r** [comment]
Thanks for feedback. I close this issue as resolved.
