### ISSUE TITLE
JsonSerializerOptions customization

### ISSUE THREAD

**Issue by k0st1x** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1557]
**What would you like to be added**:
Text data which comes with non-eng letters will be escaped.
But in such way, it is not readable by human.
We need a way to customize the used JsonSerializerOptions on healthcheck writing.

**Why is this needed**:
"你好" will become "\u4F60\u597D"
but we need exactly "你好" word.

**Comment by sungam3r** [comment]
PR is welcome.

**Comment by sungam3r** [comment]
@k0st1x PR from @cieciurm  in fact does not provide ability to **customize** response, but it eventually does what you want. To customize response use custom ResponseWriter and set it here
```cs
app.UseHealthChecks("/health", new HealthCheckOptions
{
    ResponseWriter = MyMethods.WriteHealthCheckUIResponseWithSuperCustomizations, // <---HERE
});
``` 

See `HealthChecks.UI.Client.UIResponseWriter` for examples.
