### ISSUE TITLE
Make RavenDB Healthcheck Timeout configurable

### ISSUE THREAD

**Issue by itisslizz** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1558]
**What would you like to be added**:
It would be great if we could have the timeout that is used for the RavenDB healthcheck configurable, right now it is hardcoded at 15 seconds.

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/4bd0e1dca241ccebb43993d21162cc02b4de7913/src/HealthChecks.RavenDB/RavenDBHealthCheck.cs#L136

**Why is this needed**:
It would be good to be able to control this timeout based on the general health check settings one wants to use.

**Comment by sungam3r** [comment]
PR is welcome.
