### ISSUE TITLE
Failed to load resource: the server responded with a status of 503 ()

### ISSUE THREAD

**Issue by RaminderRandhawa91** [Xabaril/AspNetCore.Diagnostics.HealthChecks#156]
When I try to serialize the /healthz api 
If the status is Healthy then it gives the Healthy status.
If the status is Degraded then it gives the Degraded status.
But if the status is Unhealthy then I get "Failed to load resource: the server responded with a status of 503 ()"  and none of the other health checks are shown either.
This is happening when I am using SMTP health check with wrong credentials.

Is there any solution to show Unhealthy health checks as well directly by serializing the /healthz api ?

**Comment by RaminderRandhawa91** [comment]
I found the issue. I had to specify the  "failureStatus: HealthStatus.Degraded" when I add service.

**Comment by unaizorrilla** [comment]
Hi Raminder,

Yeap, all AddXX honor the FailureStatus ! 

I can close this issue?
