### ISSUE TITLE
[Redis] Improve reliability of the health check on service startup

### ISSUE THREAD

**Issue by ar3cka** [Xabaril/AspNetCore.Diagnostics.HealthChecks#157]
We have observed a minor issue with the health check. The issue happens when a first connection takes more time than checking period. In this case, the check reports the error with the description "New Redis connection can not be added into the dictionary." which indicates that it was another thread that managed to establish the connection successfully. 

The following changes improve the reliability of the health check:
- reuse the already created connection for PING request
- dispose  the new unnecessary connection  

```csharp
if (!_connections.TryGetValue(_redisConnectionString, out connection))
{
    connection = ConnectionMultiplexer.Connect(_redisConnectionString);

    if (!_connections.TryAdd(_redisConnectionString, connection))
    {
        // Dispose new connection which we just created, because we don't need it.
        connection.Dispose();        

        // Re-use existing connection for PING           
        connection = _connections[_redisConnectionString];
    }
}
```

**Comment by unaizorrilla** [comment]
Hi @ar3cka 

Can you send a PR with these changes?
