### ISSUE TITLE
AspNetcore.HealthChecks.Publisher.Seq is not exists

### ISSUE THREAD

**Issue by cilerler** [Xabaril/AspNetCore.Diagnostics.HealthChecks#158]
In [here](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/commit/40a2eed48717a3642430ca618cce853488a22826#diff-04c6e90faac2675aa89e2176d2eec7d8) it states that there is a package called **AspNetcore.HealthChecks.Publisher.Seq** exists. Where I couldn't find it, please advise.

**Comment by unaizorrilla** [comment]
Hi @cilerler 

I'm sorry! We merge a PR for Seq Publisher but the Build.ps1 can't contain the package publication entry and this package is not automatically pushed to nuget.

I fixed it and when the latest release build finished a new package will be on NuGet.

Thanks for fill this issue!

**Comment by unaizorrilla** [comment]
https://www.nuget.org/packages/AspNetCore.HealthChecks.Publisher.Seq/2.2.1
