### ISSUE TITLE
The process cannot access the file healthchecksdb

### ISSUE THREAD

**Issue by nilfdev** [Xabaril/AspNetCore.Diagnostics.HealthChecks#161]
Hi. 

After deploying web application with integrated health-check UI to Azure we've faced with error: 
Error can be fixed by restarting the app itself. 
Error occurs periodically after deploying new version of the application. 

```
An error occurred while starting the application.
AggregateException: One or more errors occurred. (The process cannot access the file 'D:\home\site\wwwroot\healthchecksdb' because it is being used by another process.)
System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)

IOException: The process cannot access the file 'D:\home\site\wwwroot\healthchecksdb' because it is being used by another process.
System.IO.FileSystem.DeleteFile(string fullPath)

AggregateException: One or more errors occurred. (The process cannot access the file 'D:\home\site\wwwroot\healthchecksdb' because it is being used by another process.)
System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddHealthChecksUI(IServiceCollection services, string databaseName)
Finturi.Api.Extensions.HealthCheckExtensions.AppendHealthChecks(IServiceCollection services) in HealthCheckExtensions.cs
Finturi.Api.Startup.ConfigureServices(IServiceCollection services) in Startup.cs
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Show raw exception details
IOException: The process cannot access the file 'D:\home\site\wwwroot\healthchecksdb' because it is being used by another process.
System.IO.FileSystem.DeleteFile(string fullPath)
System.IO.File.Delete(string path)
Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Delete()
Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.DeleteAsync(CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureDeletedAsync(CancellationToken cancellationToken)
Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.CreateDatabase(IServiceProvider serviceProvider)


.NET Core 4.6.27521.02 X86 v4.0.0.0    |   Microsoft.AspNetCore.Hosting version 2.2.0-rtm-35687    |    Microsoft Windows 10.0.14393  

```

**Comment by unaizorrilla** [comment]
Hi @nilfdev 

By default, UI delete existing SQLite database file before start again the process. Ensure the file is not opened in other process and you have permissions to delete this file.

You can configure the path for this SQLite to ensure w3p has permissions to delete this file.

**Comment by unaizorrilla** [comment]
Hi again @nilfdev 
Do you stop the app service before deploy a new version?

**Comment by nilfdev** [comment]
we do it with azure devops by deploying the application to the new slot. 

![image](https://user-images.githubusercontent.com/15476934/56493343-0a0b8800-64ef-11e9-8ed3-02e30a8e506d.png)

and then we swap slots to make it publicly available:

![image](https://user-images.githubusercontent.com/15476934/56493370-21e30c00-64ef-11e9-967c-5243d8f1d650.png)

During setup it should remove all the files and then start the application again. 

More information: 

In the postman scenario we have script to call the healthcheck endpoint if the app is up and running
and it passes successfully. 
but after swapping slots - I see the error: The process cannot access the file healthchecksdb

**Comment by unaizorrilla** [comment]
You can stop de slot before deploy and swap! Try it, if the problem persist let me some time to do repro the scenario!

**Comment by yagoluiz** [comment]
Hi @unaizorrilla,

I'm having the same problem mentioned by @nilfdev. Here are my current scenarios:

- Stop Web App (Windows OS) before publish
- Removing personalized health checks

I found that this error only occurs with custom health checks. It does not occur, for example, in the health checks of SQL Server and Service Bus that I have tested.

**Comment by unaizorrilla** [comment]
Hi @yagoluiz 

I try to create a repro ASAP, but probably I need some days. Is curious that the error only occurs with custom healchecks.

**Comment by nilfdev** [comment]
I use only standard built-in validation of SQL Server, Azure storages, Queues connection. 
I've fixed the problem by: 
Stopping slot
Installing app into slot
Starting slot. 

It is workaround that we really don't want to use, because we already faced with issue that we stopped the slot and never started it again. 
Feels like temporary workaround that we're not going to use.

**Comment by unaizorrilla** [comment]
Hi @nilfdev 

When you work on .NET Core, Stop and Start is the recommended way and I do always this pattern, please read relevant issues on this for .NET Core:

https://github.com/aspnet/AspNetCore/issues/694 
https://github.com/aspnet/AspNetCore/issues/3719 

My question is  "we already faced with issue that we stopped the slot and never started it again" -> this is related with UI or is unrelated with this project?

**Comment by nilfdev** [comment]
Hi @unaizorrilla 

It is not related to UI. 
it is related only to our project.

**Comment by udlose** [comment]
> Hi @nilfdev
> 
> By default, UI delete existing SQLite database file before start again the process. Ensure the file is not opened in other process and you have permissions to delete this file.

@unaizorrilla 
How do I stop the database from being deleted?  Is there an option to do this?

**Comment by yagoluiz** [comment]
Guys and @unaizorrilla,

My solution for this problem, was to add option _"HealthCheckDatabaseConnectionString"_ in JSON **HealthChecks-UI**:

``
 "HealthCheckDatabaseConnectionString": "Data Source=%APPDATA%\\healthchecksdb"
``

**Comment by udlose** [comment]
@yagoluiz  thanks for your response!  I wasn't aware of that option.

Unfortunately, my app is in the Cloud so I can't rely on file storage.  I need a distributed solution. I guess I could fork this repo and add one but I was hoping one already existed...

**Comment by Odonno** [comment]
@udlose I have the same problem. I host my solution in an Azure App Service but I don't know how to fix this error...

**Comment by Odonno** [comment]
I had an idea just now. But, why can't we put a global try/catch in the code. The thing is the main pain point is that this library crash the entire web app. If the healthchecks system is not working, it's ok as long as the app itself is still working, or am I wrong?

**Comment by CarlosLanderas** [comment]
Sadly, Azure App service with Linux is not compatible with SQLite. That's why we are going to create new configuration providers. 

Please, participate in the following issue for design:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/455

**Comment by Odonno** [comment]
I believe that my app is running under a Windows Server.

**Comment by CarlosLanderas** [comment]
Storage providers feature has been implemented in UI version 3.1.1-preview1. 
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/455#issuecomment-613093369
Maybe it's interesting trying with InMemory or another database provider

**Comment by udlose** [comment]
> Storage providers feature has been implemented in UI version 3.1.1-preview1.
> [#455 (comment)](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/455#issuecomment-613093369)
> Maybe it's interesting trying with InMemory or another database provider

@CarlosLanderas  I'll give it a try with MySql sometime this week. Thanks!

**Comment by CarlosLanderas** [comment]
@udlose , sadly mysql provider is not yet compatible with version 3.1. As soon as they release a new version we will implement a new UI provider.

**Comment by udlose** [comment]
> @udlose , sadly mysql provider is not yet compatible with version 3.1.  

version 3.1 of what?  .NET Core?  

> As soon as they release a new version

Who are 'they'?

**Comment by CarlosLanderas** [comment]
Yes, netcore app 3.1 and they, are mysql team:

https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework-core.html
