### ISSUE TITLE
Add codecoverage badge

### ISSUE THREAD

**Issue by sungam3r** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1618]
https://docs.codecov.com/docs/status-badges

I would like to add code coverage badge into readme.

@carlosrecuero @unaizorrilla I can't get it work - I don't see repo, perhaps I have not required permissions.

**Comment by ThumNet** [comment]
You can add the following to the markdown file for the status badge

```md
[![codecov.io](https://codecov.io/github/Xabaril/AspNetCore.Diagnostics.HealthChecks/coverage.svg?branch=master)](https://codecov.io/github/Xabaril/AspNetCore.Diagnostics.HealthChecks?branch=master)
```

Resulting in this: [![codecov.io](https://codecov.io/github/Xabaril/AspNetCore.Diagnostics.HealthChecks/coverage.svg?branch=master)](https://codecov.io/github/Xabaril/AspNetCore.Diagnostics.HealthChecks?branch=master)

**Comment by sungam3r** [comment]
👍 961f1ec
