### ISSUE TITLE
Memory leak in ApplicationStatusHealthCheck

### ISSUE THREAD

**Issue by tsvetelintsonev** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1628]
Please, fill the following sections to help us fix the issue

**What happened**:
Heap Generation 2 size increasing constantly and objects not being collected by the GC

**What you expected to happen**:
Heap Generation 2 does not increase constantly

**How to reproduce it (as minimally and precisely as possible)**:
- Create a new web api project with dotnet new
- Add AspNetCore.HealthChecks.ApplicationStatus NuGet package
- Observe memory usage with a memory profiler

**Source code sample**:
https://github.com/tsvetelintsonev/application-status-health-check-memory-leak

**Anything else we need to know?**:
Following are links to default implementation of the built-in health check service and the HealthCheckRegistration API used to register the app health status health check. It seems like a new instance of ApplicationStatusHealthCheck is created for each health check, hence the resources it uses are never collected by the GC.

[HealthCheckRegistration](https://github.com/dotnet/aspnetcore/blob/main/src/HealthChecks/Abstractions/src/HealthCheckRegistration.cs#L121)
[DefaultHealthCheckService](https://github.com/dotnet/aspnetcore/blob/main/src/HealthChecks/HealthChecks/src/DefaultHealthCheckService.cs#L81)

**Environment**:

- .NET Core - 6 & 7
- Healthchecks version - 6.0.0 & 7.0.0-rc2.2
- Operative system: macOS Monterey v12.2.1
- Others:

Running the API with no health status checks
<img width="1552" alt="Screenshot 2023-01-11 at 15 17 29" src="https://user-images.githubusercontent.com/14884588/211829552-561f0c3e-eb36-4f16-8168-8ef673408077.png">

After 200.000 requests to /health endpoint
<img width="1567" alt="Screenshot 2023-01-11 at 15 22 49" src="https://user-images.githubusercontent.com/14884588/211830606-454f3584-dd51-4b6e-8650-554071a54c4f.png">

After ~450.000 request to /health endpoint
<img width="1562" alt="Screenshot 2023-01-11 at 15 34 55" src="https://user-images.githubusercontent.com/14884588/211833725-09281cd8-17fc-48b6-9e91-e495861f8161.png">

**Comment by tsvetelintsonev** [comment]
As far as I understand it we need a cached/singleton-ish instance of the health check. In such case we a simple fix might be to just cache and return the same instance from the factory:

```csharp 
public static IHealthChecksBuilder AddApplicationStatus(
        this IHealthChecksBuilder builder,
        string? name = default,
        HealthStatus? failureStatus = default,
        IEnumerable<string>? tags = default,
        TimeSpan? timeout = default)
    {
       ApplicationStatusHealthCheck? applicationStatusHealthCheck = null;

        return builder.Add(new HealthCheckRegistration(
            name ?? NAME,
            sp => applicationStatusHealthCheck ??= new ApplicationStatusHealthCheck(sp.GetRequiredService<IHostApplicationLifetime>()),
            failureStatus,
            tags,
            timeout));
    }
```

**Comment by sungam3r** [comment]
Ooops, somehow I missed that thought we discussed memory leak with @OlegOLK https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1365#discussion_r934735717 and https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1365#discussion_r940675920

**Comment by sungam3r** [comment]
@tsvetelintsonev I published fresh preview packages. Try https://www.nuget.org/packages/AspNetCore.HealthChecks.ApplicationStatus/7.0.0-rc2.3

**Comment by tsvetelintsonev** [comment]
Awesome, thank you for the quick fix and great work! I will give it a try tomorrow :)

**Comment by mcallaghan-geotab** [comment]
Is this issue present in the `6.0.0` version of the package?

**Comment by sungam3r** [comment]
Seems so. I would not back-patch it because of significant changes in the codebase. At least try v7 first.

**Comment by mcallaghan-geotab** [comment]
@sungam3r  - yes but if running a .net6 application we thought it a bit suspect to try to run this package's `7.0.0.*` version as there are 7.0 dependencies.

It _seems_ to be working, except we had an explicit version conflict with `Microsoft.Bcl.AsyncInterfaces` (other dependencies of the system depend on `6.0.0` of that package but `AspNetCore.Diagnostics.HealthChecks` depends on `7.0.0`.

**Comment by mcallaghan-geotab** [comment]
The diff specifically for back patching seems small enough to manage (https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1638/files) ?

Unless that code area itself has deviated since `6.0.0` ...

**Comment by sungam3r** [comment]
Microsoft.Bcl.AsyncInterfaces dependency is a known PITA. I suggest to open a new issue if you have problems with it.
