### ISSUE TITLE
EasyNetQ connection string format problem

### ISSUE THREAD

**Issue by brunobritodev** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1633]
**What happened**:
A popular component to use RabbitMQ with .NET is [EasyNetQ](https://github.com/EasyNetQ/EasyNetQ).

The problem is that EasyNetQ use it own RabbitMQ connection string. So when we add AspNetCore.HealthChecks.RabbitMQ to monitor Rabbit it uses RabbitMQ offical component under the hood. Then we came into a problem with the connstring format.

EasyNetQ use this connstring format: `host=myServer;virtualHost=myVirtualHost;username=mike;password=topsecret`
RabbitMQ official component use this on: `amqp://user:pass@hostName:port/vhost`

In this case there are a few options:
* 2 Connection strings in the same project
* Convert EasyNetQ connection string to RabbitMQ `IConnection`. 

The first option is simpler. but it definetely isn't a good practice. It could lead developer to make a mistakes and is really annoying to keep 2 connstring.

The second options is the best, but it's not a easy task.

**What you expected to happen**:
I know it's not a problem that concerns to you guys, but o docs showing how to accomplish it would be great. 

If you agree, I provide the steps and make a pr.

**workaround**
```csharp
public static class EasyNetQRabbitHealthCheck
{
    public static IHealthChecksBuilder AddEasyNetQRabbitHealthCheck(this IHealthChecksBuilder healthChecksBuilder, string connectionString)
    {
        var easyNetQConnstringParser = new ConnectionStringParser();
        var connectionConfiguration = easyNetQConnstringParser.Parse(connectionString);
        var connRabbit = CreateConnectionFactory(connectionConfiguration);
        var rabbitHealthCheck = new RabbitMQHealthCheck(connRabbit);
        healthChecksBuilder.Services.AddSingleton(sp => rabbitHealthCheck);

        return healthChecksBuilder.Add(new HealthCheckRegistration(
            "RabbitMQ",
            sp => sp.GetRequiredService<RabbitMQHealthCheck>(),
            default,
            tags: new[] { "infra" },
            default));
    }

    private static IConnectionFactory CreateConnectionFactory(ConnectionConfiguration configuration)
    {
        var connectionFactory = new ConnectionFactory
        {
            AutomaticRecoveryEnabled = true,
            TopologyRecoveryEnabled = false,
            VirtualHost = configuration.VirtualHost,
            UserName = configuration.UserName,
            Password = configuration.Password,
            Port = configuration.Port,
            RequestedHeartbeat = configuration.RequestedHeartbeat,
            ClientProperties = configuration.ClientProperties,
            AuthMechanisms = configuration.AuthMechanisms,
            ClientProvidedName = configuration.Name,
            NetworkRecoveryInterval = configuration.ConnectIntervalAttempt,
            ContinuationTimeout = configuration.Timeout,
            DispatchConsumersAsync = true,
            ConsumerDispatchConcurrency = configuration.PrefetchCount,
        };

        if (configuration.Hosts.Count > 0)
            connectionFactory.HostName = configuration.Hosts[0].Host;

        return connectionFactory;
    }
}
```

**Comment by sungam3r** [comment]
I understand this issue since I faced it some time ago in my projects. I would not bring ENQ here. I would convert ENQ string into RabbitMQ string when configuring healthcheck. You may use that overload https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.Rabbitmq/DependencyInjection/RabbitMQHealthCheckBuilderExtensions.cs#L233 to obtain source connection string from `serviceProvider` and then convert in into ENQ format - either via `string.Format` or via newing `EasyNetQ.ConnectionConfiguration`.

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
