### ISSUE TITLE
HealthChecksUI keeps logging even if I'm not in the UI

### ISSUE THREAD

**Issue by PedroFerreira4470** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1640]
Hey,
Is there any way to only trigger the HealthChecks if I enter the UI? I'm getting logs every 6 seconds.

This is what triggers the logs.

`  
services.AddHealthChecksUI(setup =>
        {
            setup.SetEvaluationTimeInSeconds(6);
            setup.SetMinimumSecondsBetweenFailureNotifications(60);
            setup.MaximumHistoryEntriesPerEndpoint(15);
            setup.AddHealthCheckEndpoint("Health Checks", ResolveHealthCheckEndpoint(configuration));
            setup.UseApiEndpointHttpMessageHandler(sp => new HttpClientHandler
            {
                ClientCertificateOptions = ClientCertificateOption.Manual,
                ServerCertificateCustomValidationCallback = (httpRequestMessage, cert, cetChain, policyErrors) => true
            });
        })
            .AddInMemoryStorage();
`

Note: I don't want to suppress the logs
Thank you.

**Comment by rob-baldwin** [comment]
Hi @PedroFerreira4470, the health checks are polled by design, but you can alter the poll frequency by changing `setup.SetEvaluationTimeInSeconds(6)` to another value.  However, viewing the UI has no effect on the polling, the healthcheck endpoints are polled independently of requests to the UI.
