### ISSUE TITLE
Redis healthchecks don't respect the timeout configure by healthcheck registration

### ISSUE THREAD

**Issue by bdurrani** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1658]
Please, fill the following sections to help us fix the issue

**What happened**:
We've configured the StackExchange Redis library to basically do infinite retries in case of connection errors. 
This means that `ConnectionMultiplexer.ConnectAsync()` will not return til the connection is established. 
This also means that the healthcheck endpoint request never completes till the connection is established. The healthcheck request will not complete in this case till the redis connection is established.

One way of managing this is to use the timeout parameter when setting up the healthcheck registration. Unfortunately the way the redis healthcheck is currently written, it ignores the cancellationtoken passed in.

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/eeb24329d33fb0332ca22ac916516348bd646205/src/HealthChecks.Redis/RedisHealthCheck.cs#L27

`ConnectAsync()` does not take a `cancellationToken` so it would require a bit of extra work checking for the timeout in the library. 

It shouldn't be too complicated to use something like the following to timeout the healthcheck. 

```csharp
var redisConnectionTask = ConnectionMultiplexer.ConnectAsync();
 var timeoutTask = Task.Delay(Timeout.Infinite, cancellationToken);
        var firstTask = await Task.WhenAny(redisConnectionTask, timeoutTask) ;
        if (firstTask == timeoutTask)
        {
            throw new Exception("healthcheck timed out");
        }
```

**What you expected to happen**:

The healthcheck should fail if the redis connection is not established without the timeout set up as part of the healthcheck registration

**How to reproduce it (as minimally and precisely as possible)**:
Use a connection string like the following for talking to redis
```csharp
  var connectionString =
            "localhost:6379,ssl=False,abortConnect=False,connectRetry=2147483647";
```
I was using redis running in docker. But in this scenario, make sure there is not redis docker container running so there is nothing for the application to connect to

Hit the healthcheck endpoint. Notice the request never completes. 

Try setting a timeout value for the healthcheck as well. It will have no effect. 

**Source code sample**:

**Anything else we need to know?**:

**Environment**:

- .NET 6
- Healthchecks version: AspNetCore.HealthChecks.Redis 6.0.4
- Operative system: mac os
- Others:

**Comment by sungam3r** [comment]
I suggest to add additional extension methods taking `Action\<ConfigurationOptions>`. Then you can configure `ConfigurationOptions.ConnectTimeout`:
```
/// <summary>
        /// Specifies the time in milliseconds that should be allowed for connection (defaults to 5 seconds unless SyncTimeout is higher).
        /// </summary>
        public int ConnectTimeout
        {
            get => connectTimeout ?? ((int?)Defaults.ConnectTimeout?.TotalMilliseconds) ?? Math.Max(5000, SyncTimeout);
            set => connectTimeout = value;
        }
```

**Comment by sungam3r** [comment]
PR is welcome.

**Comment by bdurrani** [comment]
Hi there

Please take a look at this one. 
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1661

Thanks

**Comment by bdurrani** [comment]
> I suggest to add additional extension methods taking `Action<ConfigurationOptions>`. Then you can configure `ConfigurationOptions.ConnectTimeout`:
> 
> ```
> /// <summary>
>         /// Specifies the time in milliseconds that should be allowed for connection (defaults to 5 seconds unless SyncTimeout is higher).
>         /// </summary>
>         public int ConnectTimeout
>         {
>             get => connectTimeout ?? ((int?)Defaults.ConnectTimeout?.TotalMilliseconds) ?? Math.Max(5000, SyncTimeout);
>             set => connectTimeout = value;
>         }
> ```

My understanding is that with max retries set to a high value, if the connection times out, the `ConnectionMultiplexer` will just retry again and again

Unfortunately none of the redis methods accept a cancellation token. There is a [PR](https://github.com/StackExchange/StackExchange.Redis/issues/1039) open for it.
