### ISSUE TITLE
Datadog Publisher :: Where to look in Datadog?

### ISSUE THREAD

**Issue by eokorieFA** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1668]
Hi, hope someone can shed a bit of light.  On a project we are working on, we are looking to push the health check results to Datadog.  We have implemented the correct code and imported the package.  However, we are unsure of where in Datadog we are supposed to be seeing the health check results.

Are we missing something?  It is worth noting that our code has been deployed to AKS cluster and there is a datadog agent already running on the cluster itself.

In the Program.cs file we have added the following:

`
builder.Services
        .AddHealthChecks()
        .AddProcessAllocatedMemoryHealthCheck(512)
        .AddCheck<SampleHealthCheck>("Sample-HealthCheck", HealthStatus.Unhealthy, new string[] { "sample"})
        .AddDatadogPublisher($"{configuration["Settings:HealthCheckServiceName"]}");
`

So any help  in knowing where to look  in Datadog for the health checks would be appreciated.

Thanks

**Comment by HuntJason** [comment]
I believe its under "Metrics" but, let me know if confirm as I am not 100%.

**Comment by sungam3r** [comment]
@eokorieFA I hope you managed to solve this issue. Closing since there is nothing to do here.
