### ISSUE TITLE
Add RavenDB 3.5.X support

### ISSUE THREAD

**Issue by jasonycw** [Xabaril/AspNetCore.Diagnostics.HealthChecks#167]
Currently, HealthChecks.RavenDB 2.2.2 uses RavenDB.Client 4.1.3

But for some legacy reason, our RavenDB is stucked at 3.5.8 max and the ping method in 4.1.3 cannot work properly
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/706fb5b7c1991272ab73aa00a3e868c03589d93f/src/HealthChecks.RavenDB/RavenDBHealthCheck.cs#L28-L64

If HealthChecks.RavenDB 2.2.2 is used to ping RavenDB 3.5.8 with
``` C#
.AddRavenDB(
   opt =>
   {
     opt.Urls = new[] { configuration.GetConnectionString("RavenDb") };
     opt.Database = "DbName";
   },
   name: "My RavenDB")
```
the following will be logged
> Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Error: Health check My RavenDB completed after 1778.9839000000002ms with status Unhealthy and '(null)'

--------------------

Here is our current ping method using RavenDB.Client 3.5.8 
``` C#
public static async Task<bool> IsRavenConnected(string ravenUrl, string database)
{
    try
    {
        return await Task.Factory.StartNew(() =>
           {
               using (var ravenStore = new DocumentStore
               {
                   Url = ravenUrl,
                   DefaultDatabase = database
               })
               {
                   ravenStore.Initialize(true);
                   return ravenStore.AsyncDatabaseCommands.GlobalAdmin.GetBuildNumberAsync().Wait(TimeSpan.FromSeconds(3));
               }
           }).WaitWithTimeout(TimeSpan.FromSeconds(10));
    }
    catch
    {
        return false;
    }
}
```

**Comment by unaizorrilla** [comment]
Hi,

Let me check, I need some days. If you discover something let me know!

Unai

**Comment by sungam3r** [comment]
@jasonycw Now `master` references RavenDB.Client v5.2.3 . If you need to use older versions for legacy reasons then just copy source code - only 3 small files - and change needed parts.
