### ISSUE TITLE
GetHealthReport - exception on Azure.

### ISSUE THREAD

**Issue by mskuratowski** [Xabaril/AspNetCore.Diagnostics.HealthChecks#168]
Hi, I'm getting and an error when I try to see HealtChecksUI.

> GetHealthReport threw an exception when trying to get report from https://myazureurl.net/swagger configured with name Billennium FeedMe API.
> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
>    at Newtonsoft.Json.JsonTextReader.ParseValue()
>    at Newtonsoft.Json.JsonTextReader.Read()
>    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
>    at System.Net.Http.HttpResponseMessageExtensions.As[TContent](HttpResponseMessage response)
>    at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReport(HealthCheckConfiguration configuration)

Everything works fine locally, but on Azure with different HealthChecks Uri doesn't work anymore.

Here are my appsettings.json settings for HealthCheck-UI

>   "HealthChecks-UI": {
>     "HealthChecks": [
>       {
>         "Name": "Billennium FeedMe API",
>         "Uri": "https://my-azure-url.azurewebsites.net"
>       }
>     ],
>     "Webhooks": [],
>     "EvaluationTimeOnSeconds": 10,
>     "MinimumSecondsBetweenFailureNotifications": 60
>   }

When I change Uri for a local instance(I mean localhost), it locally works.

Do you have any ideas what could be wrong?

**Comment by unaizorrilla** [comment]
Hi,

https://my-azure-url.azurewebsites.net is a health**z** uri? 

Unai

**Comment by CarlosLanderas** [comment]
@mskuratowski is this issue fixed for you? Could you give us additional details?

Where you using the docker image and deploying it to Azure Web App for Containers or just deploying your own application?

Where you using appsettings.json file or environment variables?

**Comment by wingchunninja** [comment]
Hi,

we are experiencing the same issue. 

We have a .NET Core project that is being built with a docker image and it is published as App service in Azure. 

As application settings are used the ones from azure in the following way HealthChecksUI__HealthChecks__0__Uri (used as environment variables). 

We have three projects published the same way. In the healthchecks-ui overview
the other two show status healthy where this one unhealthy. Even though calling /check on this project returns a healthy state, the ui shows unhealthy with the same error:

Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

Any experience with this?

**Comment by CarljohanDanling** [comment]
Having same problem as OP. Working like a charm local, but in Azure, running as an web app, it throws: "GetHealthReport threw an exception when trying to get report from ...".

• Exception type: "Newtonsoft.Json.JsonReaderException".
• Failed method: "Newtonsoft.Json.JsonTextReader.ParseValue".

**Comment by eobeda** [comment]
The issue of "Unexpected character encountered while parsing value: <. Path '', line 0, position 0." occurs in two flavors:

1) All the time, as in issue #15247.
2) Occasionally/intermittently.

The cause is due to the System.Net.Http.HttpResponseMessageExtensions.As function expects only JSON content. It does not check the content-type of the response before passing it to Newtonsoft.

So, when you misconfigure the url to something that does not respond with a JSON payload ( #1 above)  or when the server (usually when configured to query multiple sites) returns an HTML status page instead of the JSON payload ( #2 above), an exception is throw by the HealthCheck UI.

It would be nice if HealthCheck UI checked the content-type and marked the url as "unhealthly" or "unavailable" when non-JSON payloads are received, but not throw an exception.

**Comment by paulvanbladel** [comment]
I'm getting the same problem even when not being on azure. Just in visual studio in debug mode.
Is there a potential workaround?

**Comment by simonskr** [comment]
Same here. Just hit a roadblock with this.

**JSON:**
`  "HealthChecksUI": {`
`    "HealthChecks": [`
`      {`
`        "Name": "Scribe API Check",`
`        "Uri": "http://localhost:5000/health"`
`      }`
`    ]`
`  },`

**Docker Compose:**
`version: '3.4'`

`services:`
`  statuschecks:`
`    image: statuschecks`
`    build:`
`      context: .`
`      dockerfile: WebApps\Health\StatusChecks\Dockerfile`
`    depends_on:`
`      - scribe.api`

**Docker Compose Override:**
`version: '3.4'`

`services:`

`  statuschecks:`
`    environment:`
`      - ASPNETCORE_ENVIRONMENT=Development`
`      - ASPNETCORE_URLS=https://+:443;http://+:80`
`      - HealthChecksUI__HealthChecks__0__Name=Scribe API Check`
`      - HealthChecksUI__HealthChecks__0__Url=http://scribe.api/health`
`    ports:`
`      - "5000:80"`
`      - "5001:443"`
`    volumes:`
`      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro`
`      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro`

I've logged the configuration values in Program and Startup and they are using the provided environment variables (i.e. `http://scribe.api/health`) however, GetHealthReport fails with this message:

`GetHealthReport threw an exception when trying to get report from **http://localhost:5000/health** configured with name Scribe API Check.`

So the configuration is being read with AddEnvironmentVariables(), but for some reason HealthChecks isn't using it? Am I missing something?

**Comment by unaizorrilla** [comment]
This exception is related with bad UI configuration or when the heatlhz endpoints are no respond valid json (response writer is UI.Client).

We try to sanitize de error to help about what is bad configured.

**Comment by udlose** [comment]
I am also getting this error intermittently when hosting the dashboard on Linux in an AWS environment.  All of my HealthChecks are configured via appsettings.json.  My WebHook notification is configured programmatically because of the need to customize the `ShoudlNotifyFunc`.

Is there any update?

**Comment by udlose** [comment]
So I was able to determine the cause of my specific issue:

Since I'm running in ECS FARGATE, there is a default HealthCheck that AWS uses to test the availablility of the app container to decide whether or not it should spin up a new instance.  The default value for the url of the AWS HealthCheck is the root of the application.  Since we have our AspNetCore.Diagnostics.HealthChecks dashboard app running by itself, and the AspNetCore.Diagnostics.HealthChecks SPA doesn't serve anything at the root folder (a 404 is returned), the AWS HealthCheck thought the app was down and kept trying to restart. It was during these restart periods when the 503 was served.

Hope this helps someone else in the future :)

**Comment by CarlosLanderas** [comment]
@udlose , you might want to take a look to ui version 3.1.1-preview1 that introduces new storage providers (sqlserver, sqlite, inmemory and postgres). SQlite is not compatible with Azure App Service for linux and not sure if it would work nice with AWS as well.

**Comment by udlose** [comment]
> @udlose , you might want to take a look to ui version 3.1.1-preview1 that introduces new storage providers (sqlserver, sqlite, inmemory and postgres). SQlite is not compatible with Azure App Service for linux and not sure if it would work nice with AWS as well.

I looked at it today. However, my app requires support for MySql which doesn't appear to exist yet.

**Comment by CarlosLanderas** [comment]
It will, when they add support for netcore 3
