### ISSUE TITLE
Incorrect spelling / grammer issues in HangfireHealthCheck

### ISSUE THREAD

**Issue by KevinSchumm-Limeade** [Xabaril/AspNetCore.Diagnostics.HealthChecks#169]
The error message for exceeding MaximumJobsFailed has some issues.

Currently reads: "Hangfire have #{failedJobsCount} failed jobs and the maximun available is {_hangfireOptions.MaximumJobsFailed}."

Should probably read: "Hangfire **has** #{failedJobsCount} failed jobs and the **maximum** available is {_hangfireOptions.MaximumJobsFailed}."

**Comment by unaizorrilla** [comment]
I see the PR, let me a couple of days to merge!

Thanks for contribute!

**Comment by unaizorrilla** [comment]
Fixed by #170 

thanks!
