### ISSUE TITLE
Add control over Health Check response

### ISSUE THREAD

**Issue by akm151** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1693]
**A feature to ignore Exception or Description from the response when .AddAzureServiceBusQueue(connectionstring, queuename, name) is being added to ServiceCollection for HealthChecks.**

**With the response of type HealthCheckResult , I do not want to expose in detail exception and description of Unhealthy Queues. So a feature allowing control on the response will help to control what to expose and what not to.**:

**Comment by sungam3r** [comment]
PR is welcome.

**Comment by akm151** [comment]
any kind of access needed for pushing changes ?
Getting below error while push
![image](https://user-images.githubusercontent.com/16291902/220911987-61963fa7-ace5-4963-a151-74b05d32c442.png)

**Comment by sungam3r** [comment]
Fork repo, make changes there, then post PR from your fork into this repo. You (as well as almost every user in GitHub) cannot push into origin repo directly.

**Comment by sungam3r** [comment]
As I understand from discussion in #1719 this is not needed.
