### ISSUE TITLE
Prometheus - Wrong Encoding used by the browser

### ISSUE THREAD

**Issue by k0st1x** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1694]
**What happened**:
View the promethous report in the browser.
there are text like "# HELP response_time Ð¡ÑƒÐ¼Ð¼Ð°Ñ€Ð½Ð¾Ðµ Ð²Ñ€ÐµÐ¼Ñ Ð²Ñ‹Ð¿Ð¾Ð»Ð½ÐµÐ½Ð¸Ñ Ð·Ð°Ð¿Ñ€Ð¾ÑÐ¾Ð²" for own metrics.
And the response headers has no info about charset.

**What you expected to happen**:
the '# HELP requests_total Количество вызовов сервиса' string in the response.
And the response header thould be 'Content-Type: text/plain; version=0.0.4; charset=utf-8'

**How to reproduce it (as minimally and precisely as possible)**:
create metrics, inc it and get the prometheus report

**Source code sample**:
```cs
Metrics.CreateCounter("requests_total", "Количество вызовов сервиса", "method_name")
```

I may prepare the MR to update
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.Prometheus.Metrics/LivenessPrometheusMetrics.cs#L8
```cs
CONTENT_TYPE = PrometheusConstants.TextContentTypeWithVersionAndEncoding;
```
instead of
```cs
CONTENT_TYPE = "text/plain; version=0.0.4"
```

**Comment by sungam3r** [comment]
PR is welcome
