### ISSUE TITLE
S3 healthcheck can become expensive if there are a lot of objects in the bucket

### ISSUE THREAD

**Issue by bdurrani** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1705]
Please, fill the following sections to help us fix the issue

**What happened**:

When using the S3 healthcheck, I noticed the `/healthcheck` request became slow over time. To the point where it was taking more than 3 seconds to complete.

The issue turned out to be related to the number of objects in the S3 bucket being healthchecked. The check is currently using the default configuration for `ListObjects` which will attempt to list up to 1k objects. So the more objects are in the bucket, the more time `ListObjects` will take.

**What you expected to happen**:

Healthcheck should be faster, and ideally not depend much on the number of objects in the bucket

**How to reproduce it (as minimally and precisely as possible)**:

Use the healthcheck with an empty bucket and note the initial healthcheck request time

Upload a 1000+ files to the bucket. Note that the request time increases

**Source code sample**:

**Anything else we need to know?**:
The fix would be to use the `ListObjectsRequest` overload of `ListObjectsAsync()` with `MaxKey` set to 1

I did a little benchmark to see the difference between the two implementations

```csharp
[SimpleJob(launchCount: 2, warmupCount: 5, iterationCount: 10)]
public class MyBenchmarkDemo
{
    private IAmazonS3 _client;

    private static readonly ListObjectsRequest ListRequest = new()
    {
        BucketName = "buckety-bucket-test",
        MaxKeys = 1
    };

    [GlobalSetup]
    public void GlobalSetup()
    {
        _client = new AmazonS3Client();
    }

    [Benchmark]
    public async Task DefaultListObject()
    {
        await _client.ListObjectsAsync("buckety-bucket-test", CancellationToken.None);
    }
    
    [Benchmark]
    public async Task ListObjectWithMaxKey()
    {
        await _client.ListObjectsAsync(ListRequest, CancellationToken.None);
    }
}
````

Here are the results from benchmark.net

```shell
// * Summary *

BenchmarkDotNet=v0.13.5, OS=macOS Ventura 13.2.1 (22D68) [Darwin 22.3.0]
Apple M1 Pro, 1 CPU, 10 logical and 10 physical cores
.NET SDK=7.0.200
  [Host]     : .NET 7.0.3 (7.0.323.6910), Arm64 RyuJIT AdvSIMD
  Job-LFJMZA : .NET 7.0.3 (7.0.323.6910), Arm64 RyuJIT AdvSIMD

IterationCount=10  LaunchCount=2  WarmupCount=5

|               Method |    Mean |    Error |   StdDev |
|--------------------- |--------:|---------:|---------:|
|    DefaultListObject | 5.466 s | 1.5997 s | 1.7117 s |
| ListObjectWithMaxKey | 1.925 s | 0.2682 s | 0.2981 s |

// * Hints *
Outliers
  MyBenchmarkDemo.DefaultListObject: IterationCount=10, LaunchCount=2, WarmupCount=5    -> Something went wrong with outliers: Size(WorkloadActual) = 20, Size(WorkloadActual/Outliers) = 1, Size(Result) = 18), OutlierMode = RemoveUpper
  MyBenchmarkDemo.ListObjectWithMaxKey: IterationCount=10, LaunchCount=2, WarmupCount=5 -> Something went wrong with outliers: Size(WorkloadActual) = 20, Size(WorkloadActual/Outliers) = 0, Size(Result) = 19), OutlierMode = RemoveUpper

// * Legends *
  Mean   : Arithmetic mean of all measurements
  Error  : Half of 99.9% confidence interval
  StdDev : Standard deviation of all measurements
  1 s    : 1 Second (1 sec)

// ***** BenchmarkRunner: End *****
Run time: 00:04:32 (272.19 sec), executed benchmarks: 2

Global total time: 00:04:35 (275.38 sec), executed benchmarks: 2
```

Note the mean time for the max key version is significantly lower. And the fix should be trivial. 

**Environment**:

- .NET Core version: 6
- Healthchecks version: latest
- Operative system:
- Others:

**Comment by sungam3r** [comment]
PR is welcome.

**Comment by bdurrani** [comment]
See PR #1711
