### ISSUE TITLE
DataDog Publishing

### ISSUE THREAD

**Issue by HuntJason** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1706]
Hello,
    I would like to use the DataDog exporter. Is there any information on how to integrate the healthchecks within the DataDog product? I am not sure whether the WebHooks or Prometheus, or ??? integration is used to consume the results of the DataDog publisher.

**Comment by rob-baldwin** [comment]
Hi @HuntJason, there's a specific publisher for DataDog.

```
install-package AspNetcore.HealthChecks.Publisher.Datadog
```

Add publisher[s] into the IHealthCheckBuilder:
```
services
    .AddHealthChecks()
    .AddDatadogPublisher(serviceCheckName: "serviceCheckName", datadogAgentName: "127.0.0.1");
```

**Comment by sungam3r** [comment]
Thanks @rob-baldwin .
