### ISSUE TITLE
Health check for multiple hosts should not return on the first failing host

### ISSUE THREAD

**Issue by michaelmairegger** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1710]
My suggestion is that health check should not return on the first failing host, but try all other hosts registered with AddHost and return a message with all failing hosts. FolderHeathCheck returns a error description for each missing folders

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.System/FolderHealthCheck.cs#LL26C9-L26C9

Most of the other HealthCheck e.g.

- Ping https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.Network/PingHealthCheck.cs#LL28C28-L28C28
- TCP https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.Network/TcpHealthCheck.cs#L32
- SSL https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.Network/SslHealthCheck.cs#L42

return the erro on the first failing host. Therefore if multiple hosts fail than only one is reported. It would be nice if all healthchecks that have the AddHost method to add multiple hosts support the error message construction like FolderHeathCheck does.

For now the workaround is to use multple time AddPingHealthCheck, AddTcpHealthCheck, ...

**Comment by sungam3r** [comment]
PR is welcome.

**Comment by michaelmairegger** [comment]
Of course. I can create a PR if this is desired. Before I start i just wanted to know if this modification is desired.
