### ISSUE TITLE
DocumentDb HealthCheck new-ing up DocumentClient per call

### ISSUE THREAD

**Issue by ymitis** [Xabaril/AspNetCore.Diagnostics.HealthChecks#172]
The [DocumentDbHealthCheck](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.DocumentDb/DocumentDbHealthCheck.cs) creates a new instance of DocumentClient for each call to CheckHealthAsync.

[Official Documentation](https://azure.microsoft.com/en-us/blog/performance-tips-for-azure-documentdb-part-1-2/) suggests using a Single instance of the DocumentClient per lifetime of the application.

`

            try
            { 
                using (var documentDbClient = new DocumentClient(
                    new Uri(_documentDbOptions.UriEndpoint),
                    _documentDbOptions.PrimaryKey))
                {
                    await documentDbClient.OpenAsync(cancellationToken);
                    return HealthCheckResult.Healthy();
                }
            }
            catch (Exception ex)
            {
                return new HealthCheckResult(context.Registration.FailureStatus, exception: ex);
            }
`

**Comment by unaizorrilla** [comment]
We fix this issue on other healtchecks, I try to fix it ASAP.

**Comment by unaizorrilla** [comment]
Fixed on 2.2.1 package, this will be available when appveyor finish the release build!
