### ISSUE TITLE
Last .AddNpgSql connection string is used for all .AddNpgSql health checks

### ISSUE THREAD

**Issue by NyleAlliss** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1727]
Currently when adding multiple NpgSql Health checks in version 6.0.2 the connection string of the last added check is used when calling the previously added health checks. But in version 6.0.1 it works as I intend it to. Health check configuration setup:
```
builder.Services.AddHealthChecks()
    .AddNpgSql(
        builder.Configuration.GetConnectionString("first-connection-str"),
        name: "FirstCheck",
        tags: new[] {Checks.READINESS}
    )
    .AddNpgSql(
        builder.Configuration.GetConnectionString("second-connection-str"),
        name: "SecondCheck",
        tags: new[] {Checks.READINESS});
```
When testing responses in AspNetCore.Diagnostics.HealthChecks 6.0.2 I've noticed that the health status of the lase health checkis returned for both responses. I.e. if I make `second-connection-str` invalid and keep `first-connection-str` as a valid connection string, both health checks will return `Unhealthy` status. Likewise if I change `first-connection-str` and not `second-connection-str` then both responses will be `Healthy`.

Whilst debugging NpgSqlHealthCheck.cs in 6.0.2 I can see that the same connection string is retrieved in the CheckHealthAsync  method each time it is ran on line 23:
`using (var connection = new NpgsqlConnection(_connectionString))`
I haven't been able to determine the cause of the problem any further. We are using an internal HealthCheck package but even with this removed the problem persists in 6.0.2, and the package works with 6.0.1

**Comment by sungam3r** [comment]
Fixed in #1592. Try 7.0.0 preview packages https://www.nuget.org/packages/AspNetCore.HealthChecks.NpgSql
