### ISSUE TITLE
Register connection string from factory

### ISSUE THREAD

**Issue by JoshKeegan** [Xabaril/AspNetCore.Diagnostics.HealthChecks#173]
Hi,
I've just started to use this library and it's working great :)  

I'm using it for SQL Server, and we keep our connection details in an object that gets wired up via dependency injection. This means at the point we come to register the health check, the `IServiceProvider` hasn't been built, so we can't get at it. This means I can't use your `pservices.AddSqlServer(...` method (which requires the connection string) and instead must use `services.Add(new HealthCheckRegistration(...` from Microsoft.Extensions.Diagnostics.HealthChecks because it can accept a factory to build the health check (allowing us to access an `IServiceProvider`).

Would there be any interest in a new `services.AddSqlServer(...` method that supports a factory for the connection string?
The same thing could be done for the other health checks if there's interest?

### Existing usage
```cs
services.AddHealthChecks()
	.Add(new HealthCheckRegistration("db", provider =>
	{
		DatabaseSettings dbSettings = provider.GetService<DatabaseSettings>();
		return new SqlServerHealthCheck(dbSettings.ConnectionString, "SELECT 1;");
	}, null, new string[] { "readiness" }));
```

### Proposed usage
If there was a factory for building the connection string from the `IServiceProvider`, this could become:
```cs
services.AddHealthChecks()
	.AddSqlServer(provider => provider.GetService<DatabaseSettings>().ConnectionString,
		name: "db", tags: new string[] {"readiness"});
```

**Comment by unaizorrilla** [comment]
Hi @JoshKeegan 

Sound interesting !  Can you send a PR? and we can start discussing implementation details!

**Comment by JoshKeegan** [comment]
@unaizorrilla Will do :)

**Comment by JoshKeegan** [comment]
@unaizorrilla Any thoughts on the PR?

**Comment by CarlosLanderas** [comment]
Merged.
