### ISSUE TITLE
Support the options reload for ability to update app onthefly - Use "IOptionsMonitor<XXHealthCheckOptions>" instead of "XXHealthCheckOptions"

### ISSUE THREAD

**Issue by k0st1x** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1752]
**What would you like to be added**:
simply use "IOptionsMonitor<XXHealthCheckOptions>" instead of "XXHealthCheckOptions" will be great.

**Why is this needed**:
XXHealthChecks uses XXHealthCheckOptions, so there is no ability to update config/settings without app restart.

**Comment by sungam3r** [comment]
I doubt the need for such a step. If you like you can make a PR, where this approach is demonstrated.

**Comment by k0st1x** [comment]
Here the article https://thecodeblogger.com/2021/04/22/ioptionsmonitor-demo-reload-configurations-in-net-applications/
Simply call Configure<>() method on app-start,
then use IOptionsMonitor<XXHealthCheckOptions> in the service ctor, so options will be updated on every config reload.

(But I cannot analyze, can be such update have a breaking-change behavior)

Currently on working projects I cannot use the 'AspNetCore.Diagnostics.HealthChecks'-packages only for reason - configs should be reloaded without app restart.

@sungam3r , I got that you "doubt the need", so I will close current issue.

**Comment by sungam3r** [comment]
I know general theory around options patterns and I've read provided article. If you have a real need for this feature, then a **complete** PR will be much better than links to articles and scattered instructions on what to write where. And yes, it most probable will be breaking for existing consumers. Also you should think about introduced changes in overall design.
