### ISSUE TITLE
HealthChecks UI Take Entries From Database

### ISSUE THREAD

**Issue by imranbaloch** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1769]
I am using https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks and registering in ConfigureServices,

            services.AddHealthChecksUI(setupSettings: setup =>
            {

                setup.AddHealthCheckEndpoint("Test", "https://myDoman/healthz");
                setup.AddHealthCheckEndpoint("Test DB", "https://myDoman/healthz-db");
            }).AddInMemoryStorage();

It is working. But if I do,

    public void Configure(IApplicationBuilder app, IDbService dbService, HealthChecksDb healthChecksDb)
    {
            // Get NameFromDB using dbService service
            // Get UrlFromDB using dbService service
             ..........................................
             ..........................................
                healthChecksDb.Configurations.Add(new HealthCheckConfiguration
                {
                    Name = NameFromDB,
                    Uri = UrlFromDB,
                });
                healthChecksDb.SaveChanges(); 
    }

It will show in the UI with error,

`Unexpected character encountered while parsing value: <. Path '', line 0, position 0.`

How can I add entries from DB?

https://stackoverflow.com/questions/75854363/healthchecks-ui-take-entries-from-database

**Comment by rob-baldwin** [comment]
Given that this question has been answered in stackoverflow, this issue should be closed.
