### ISSUE TITLE
Reuse existing connection for Redis in healthcheck

### ISSUE THREAD

**Issue by Sonic198** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1773]
**What would you like to be added**: 
Since Redis recommendation is to use one connection through whole application there should be a way to pass connection (IConnectionMultiplexer) to Redis health check.

https://docs.redis.com/latest/rs/references/client_references/client_csharp/#aspnet-core

**Comment by sungam3r** [comment]
PR is welcome.

**Comment by Sonic198** [comment]
> PR is welcome.

I have a code but I'm not able to push it to repo. Should I create a fork and add code there so you can review it or what's your preference?

**Comment by Sonic198** [comment]
Would it be possible to merge this PR?

**Comment by sungam3r** [comment]
Will be published in v7.
