### ISSUE TITLE
Install Codecov app? 

### ISSUE THREAD

**Issue by sungam3r** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1778]
See notification
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1776#issuecomment-1491055952

Thoughts?

**Comment by rob-baldwin** [comment]
It certainly makes sense to install the app, I can't see any downside.

**Comment by sungam3r** [comment]
I read the documentation and I got the impression that everything will work further for a long time without interference on our part.

**Comment by sungam3r** [comment]
I would like to close this as I don't see some action is needed here, at least for now.
