### ISSUE TITLE
Please consider signing your assemblies

### ISSUE THREAD

**Issue by TimHess** [Xabaril/AspNetCore.Diagnostics.HealthChecks#179]
Hello,

Could you please consider signing your assemblies so that they can be used in a wider range of projects where strong-name information is required?

Further reading: https://www.pedrolamas.com/2018/09/11/start-strong-naming-your-assemblies/

**Comment by Elouel** [comment]
Hello, any development on this question?

**Comment by sungam3r** [comment]
Check this https://github.com/dsplaisted/strongnamer , it may help.
