### ISSUE TITLE
Move from Newtonsoft.Json to System.Text.Json

### ISSUE THREAD

**Issue by preardon** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1798]
Remove Newtonsoft as a dependency and user the newer faster System.Text

Benefits would be Performance and less dependant packages./

I would be happy to do the work

**Comment by sungam3r** [comment]
PR is welcome. See #1712 for run UI tests on CI. These tests use serialization.

**Comment by sungam3r** [comment]
UI CI was fixed.

**Comment by preardon** [comment]
Excellent, initially I might love the tests with Newtonsoft to help ensure no regression

**Comment by sungam3r** [comment]
@preardon This will be published in v7.
