### ISSUE TITLE
AspNetCore.HealthChecks.Kafka getting "Method not found" -> Confluent.Kafka version is to old, please update it to version 1.x

### ISSUE THREAD

**Issue by senzacionale** [Xabaril/AspNetCore.Diagnostics.HealthChecks#180]
I am trying to use "AspNetCore.HealthChecks.Kafka" to monitor if kafka is up and running. Kafka is working without any problem but I am always getting trhis error

> "kafka":{"data":{},"description":"Method not found: 'Confluent.Kafka.Error Confluent.Kafka.Message`2.get_Error()'.","duration":"00:00:00.0011929","exception":"Method not found: 'Confluent.Kafka.Error Confluent.Kafka.Message`2.get_Error()'.","status":"Unhealthy"}

Code:

```
var config = new Dictionary<string, object>()
                    {
                        { "bootstrap.servers", "127.0.0.1:9092" }
                    };

                    services.AddHealthChecks()
                        .AddKafka(config, name: "kafka");
```

and It looks like "CheckHealthAsync" is never triggered

> 
> [08:03:51 ERR] Health check kafka threw an unhandled exception after 48.0857ms
> System.MissingMethodException: Method not found: 'Confluent.Kafka.Error Confluent.Kafka.Message`2.get_Error()'.
>    at HealthChecks.Kafka.KafkaHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken)
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
>    at HealthChecks.Kafka.KafkaHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken)
>    at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.CheckHealthAsync(Func`2 predicate, CancellationToken cancellationToken)
> 

Your Confluent.Kafka version is to old, please update it to version 1.x and then method will be trigered.

**Comment by senzacionale** [comment]
I think zour Confluent.Kafka version is to old, please update it to version 1.x

**Comment by unaizorrilla** [comment]
Let me check today, I try to review dependency versions and check functional tests for Kafka!

**Comment by unaizorrilla** [comment]
Hi @senzacionale 

I upgraded package for Kafka with new dependency on Confluent 1.X and using new API's in this version. Now, a ProducerConfig class is used to configure the healthcheck producer, please checkout functional tests https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/test/FunctionalTests/HealthChecks.Kafka/KafkaHealthChecksTests.cs 


A new package 2.2.2 for Kafka will be available on Nuget when release build on appveyor finish. Please, close this issue if issue is resolved with this new package.

**Comment by senzacionale** [comment]
Tested and working. Thank you.
