### ISSUE TITLE
How to healthCheck  third party need authentication Api 

### ISSUE THREAD

**Issue by AsyncTaskSola** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1803]
Hello ,I have a question for health Checks. When I need to health Check   third party ApI ，but this API need to authentication .It need token ,how can I do ? I use addurlGroup this function can't see  use token to call api . When I use addOpenIdConnect to save Tokens first time, next to use addurlGroup but aways say me Discover endpoint #0 is not responding with code in 200...299 range. How can I do ? Is it have sample ?

**Comment by Sonic198** [comment]
You can customize httpclient to pass any header you want
```csharp
services.AddHealthChecks()              
      .AddUrlGroup(
          new Uri("https://some-API.com/api/some-endpoint"),
          name: "some-API",
          timeout: TimeSpan.FromSeconds(5),
          configureClient: (sp, client) =>
          {
              //client.DefaultRequestHeaders.Authorization
              client.DefaultRequestHeaders.Add("X-API-KEY", "some-API-key");
          },
          tags: new[]
          {
              "some-tag"             
          })
```

**Comment by AsyncTaskSola** [comment]
thanks, I got it
