### ISSUE TITLE
HealthChecks.Publisher.Seq - Add dictionary of additional static properties to SeqPublisherOptions

### ISSUE THREAD

**Issue by Valem** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1811]
**What would you like to be added**:
I would like to request an enhancement for the HealthChecks.Publisher.Seq project. My proposal is to add a dictionary with additional properties as options, allowing users to push static properties to Seq along with the health check results.

**Why is this needed**:
This feature would enable users to add contextual information to the health check logs in Seq, which could be helpful for filtering and analyzing health check data across multiple applications or environments.

Example usage:
``` csharp
services.AddHealthChecks()
    .AddSeqPublisher(options =>
    {
        options.Endpoint = Configuration["Seq:Endpoint"];
        options.ApiKey = Configuration["Seq:ApiKey"];
        options.AdditionalProperties = new Dictionary<string, object>
        {
            { "Application", "MyApplication" },
            { "Environment", "Production" }
        };
    });
```

If you want I can provide the PR for this?

**Comment by sungam3r** [comment]
I would expose `RawEvents` class and add `Action<RawEvents> Configure { get; set } = _ => { }` into `SeqOptions`.

**Comment by Valem** [comment]
I suppose your intention is, that the Configure() is applied on the "default" configuration of RawEwents right before the PublishMetricsAsync, but after setting RawEevents up?

Sounds like an idea. It would give much more control but the developer could also completely mess it up. 

Please advise me on the preferred approach: "defensive" with AdditionalProperties or "offensive." I'm open to both, but lean towards the defensive option.

**Comment by sungam3r** [comment]
> I suppose your intention is, that the Configure() is applied on the "default" configuration of RawEwents right before the PublishMetricsAsync, but after setting RawEevents up?

Yes.

> developer could also completely mess it up

As always and everywhere. I would not worry about that.

**Comment by Valem** [comment]
Ok, thanks! You will receive the PR soon with the more offensive approach.
