### ISSUE TITLE
UI does not automatically refresh to show new status

### ISSUE THREAD

**Issue by hades200082** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1829]
**What happened**: My monitored service became unhealthy, but the UI did not update to reflect that state until I refreshed or unfocused/refocused the page.

**What you expected to happen**: The UI should update in near real-time as statuses change.

**How to reproduce it (as minimally and precisely as possible)**:

1. Setup the most minimal health check app you can with the UI, monitoring anything
2. Load the UI in the browser.
3. Disable/turn off the thing being monitored _without un-focusing the browser window that is showing the UI_

**Anything else we need to know?**:

I suspect that this issue would not affect most users, but there are a couple of use cases that it will affect.

In the one I hit, we are trying to use the UI on a micro PC attached to a large TV screen in our office. If the UI doesn't auto-refresh itself then this use-case will not work.

**Environment**:

- .NET Core version 7.0
- Healthchecks version 6.0.7
- Operative system: Windows and Linux show the same issue

**Comment by iSatishYadav** [comment]
I tried the found working, check this sample repo:

https://github.com/iSatishYadav/SkyHealth

**Comment by hades200082** [comment]
Ok, I figured out the issue.

I was using `app.UseHealthChecks()` and `app.UseHealthChecksUI()`.

Your example uses `app.MapHealthChecks()` and `app.MapHealthChecksUI()`.

Swapping mine over to Map instead of Use seems to have solved this issue, and the issue of the polling interval not being displayed, etc.
