### ISSUE TITLE
System.Drawing.Common Vulnerability in HealthChecks.SqlServer

### ISSUE THREAD

**Issue by wapplegate** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1838]
Hey there, looks like System.Drawing.Common is a vulnerable package being transitively referenced by Microsoft.Data.SqlClient (3.0.1). I saw your message about additional maintainers so I thought I'd try to fix it, but it seems like the latest version has already been fixed which is great. What is the process for releasing a new version for HealthChecks.SqlServer? I can assist with any work that may be necessary.

**Comment by sungam3r** [comment]
See https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/1593#issuecomment-1617522623

I close this one, let's discuss in #1593.
