### ISSUE TITLE
Add credentials to health API calls

### ISSUE THREAD

**Issue by aiscrim** [Xabaril/AspNetCore.Diagnostics.HealthChecks#185]
For projects that need to disallow anonymous access, the health checks UI doesn't work: any check fails with the description "Unexpected character encountered while parsing value: <. Path '', line 0, position 0."
This is due to the underlying health API returning a 401 Unathorized code because the credentials were not supplied to the API call.

One way of solving this would be to configure the HttpClient factory to create an HttpClient with the UseDefaultCredentials parameter set to true. For example, in the AddHealthChecksUI extension, you could add this call:

```
services.AddHttpClient(Keys.HEALTH_CHECK_HTTP_CLIENT_NAME).ConfigurePrimaryHttpMessageHandler(() => {
                return new HttpClientHandler()
                {
                    UseDefaultCredentials = true
                };
            });
```

**Comment by CarlosLanderas** [comment]
Thanks for your feedback @aiscrim, I'm gonna take a look into it.

**Comment by CarlosLanderas** [comment]
@aiscrim a PR has been submitted, it gives the ability to configure a custom Http handler to UI settings

**Comment by aiscrim** [comment]
@CarlosLanderas excellent news, thanks a lot!

**Comment by CarlosLanderas** [comment]
UI Version 2.2.32 has been published and includes this fearture.
