### ISSUE TITLE
ApplicationInsightsPublisher: TelemetryClient from DI

### ISSUE THREAD

**Issue by espenrl** [Xabaril/AspNetCore.Diagnostics.HealthChecks#186]
Hi,

The ApplicationInsightsPublisher instantiates its own TelemetryClient. According to Microsoft documentation the best practice is to get it using the one in the DI container. And then it could me made a readonly field instead of static field with a lock.

https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Custom-Configuration

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/2d867c907c2e3bf6b1b2aae26d43a9141bf6fb37/src/HealthChecks.Publisher.ApplicationInsights/ApplicationInsightsPublisher.cs#L22-L23

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/2d867c907c2e3bf6b1b2aae26d43a9141bf6fb37/src/HealthChecks.Publisher.ApplicationInsights/ApplicationInsightsPublisher.cs#L85-L105

**Comment by unaizorrilla** [comment]
Can you send a PR with this change?

**Comment by CarlosLanderas** [comment]
Hello @espenrl, I was preparing a PR for this but after talking with @unaizorrilla this behaviour is on purpose.

Users might want to use default telemetry client for application monitoring and a different client for health checks monitoring. If you don't provide a telemetry key the health check will use the active telemetry configuration.
