### ISSUE TITLE
Intermittent System.ObjectDisposedException

### ISSUE THREAD

**Issue by teresaritorto** [Xabaril/AspNetCore.Diagnostics.HealthChecks#187]
We are running HealthCheck UI in ECS Fargate and am seeing the following error intermittently:

```
HealthCheck collector HostedService throw a error: Cannot access a disposed object.
Object name: 'Microsoft.Extensions.Caching.Memory.MemoryCache'.
```

Stacktrace:
`System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.Extensions.Caching.Memory.MemoryCache'.
  Module "Microsoft.Extensions.Caching.Memory.MemoryCache", in CheckDisposed
  Module "Microsoft.Extensions.Caching.Memory.MemoryCache", in TryGetValue
  Module "Microsoft.Extensions.Caching.Memory.CacheExtensions", in TryGetValue
  Module "Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache", in GetOrAddQueryCore
  Module "Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache", in GetOrAddAsyncQuery
  Module "Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler", in CompileAsyncQuery
  Module "Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler", in ExecuteAsync
  Module "Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider", in ExecuteAsync
  Module "Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions", in ExecuteAsync
  Module "Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions", in SingleOrDefaultAsync
  Module "HealthChecks.UI.Core.Notifications.WebHookFailureNotifier", in IsNotifiedOnWindowTime
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "HealthChecks.UI.Core.Notifications.WebHookFailureNotifier", in Notify
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "HealthChecks.UI.Core.Notifications.WebHookFailureNotifier", in NotifyDown
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "HealthChecks.UI.Core.HostedService.HealthCheckReportCollector", in Collect
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "HealthChecks.UI.Core.HostedService.HealthCheckCollectorHostedService", in ExecuteAsync`

Environment Details:

**Operating System:** Linux
**.Net runtime:** .NET Core 2.2.4
**Version:** AspNetCore.HealthChecks.UI v2.2.27 (latest Nuget Package)
**HealthCheck:** ElasticsearchHealthCheck

Sample appsetting:
`  "HealthChecks-UI": {
    "HealthChecks": [
      {
        "Name": "Search",
        "Uri": "https://localhost:44666/search/health-all"
      }
    ],
    "MinimumSecondsBetweenFailureNotifications": 60,
    "EvaluationTimeOnSeconds": 120
  }`

Startup:
```
app.UseHealthChecks("/health", new HealthCheckOptions()
{
  Predicate = registration => registration.Name == "self"
});
app.UseHealthChecks("/search/health-all", new HealthCheckOptions
{
  Predicate = registration => registration.Tags.Contains("search"),
  ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
});

app.UseHealthChecksUI(config => config.ApiPath = "/search/healthchecks-api");
```

**Comment by unaizorrilla** [comment]
Umm first notice!

Let me check on next days!
