### ISSUE TITLE
EventStore Healthcheck  do not closes connections

### ISSUE THREAD

**Issue by kos811** [Xabaril/AspNetCore.Diagnostics.HealthChecks#189]
When calling healthcheck, each time connection is not closed.
![eventstore-healthcheck-issue](https://user-images.githubusercontent.com/5595120/58242173-00c44400-7d57-11e9-9971-3f032a97fcf3.gif)

#190

**Comment by unaizorrilla** [comment]
Let me check!, PR are welcome also :-)

**Comment by kos811** [comment]
> Let me check!, PR are welcome also :-)

I've made and tested hotfix.
PR in progress :)

**Comment by unaizorrilla** [comment]
thanks!
