### ISSUE TITLE
Publish a recent Nuget Package ?

### ISSUE THREAD

**Issue by pleandre** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1927]
Hello, would it be possible to publish a recent NuGet package for:
- AspNetCore.HealthChecks.UI
- AspNetCore.HealthChecks.UI.InMemory.Storage
- AspNetCore.HealthChecks.UI.Client

The last version published is from over 6 months ago. I am interested in some recent changes, e.g. SetNotifyUnHealthyOneTimeUntilChange

Thanks a lot for your help :)

**Comment by rob-baldwin** [comment]
Hi @pleandre, please see this issue for details about an updated nuget package:  https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/1593

**Comment by sungam3r** [comment]
I hope to publish v7 release after fixing some PRs.
