### ISSUE TITLE
Health Check UI on root /

### ISSUE THREAD

**Issue by mmacagno** [Xabaril/AspNetCore.Diagnostics.HealthChecks#193]
Is there a way to configure the path for HealthCheckUI to respond to the root of the website?
(e.g. https://mywebsite.test.com/)
The setup configuration:

`.UseHealthChecksUI(setup => { setup.UIPath = "/"; setup.ApiPath = "/api"; })` 

will fail due to EnsureValidApiOptions validation.

![image](https://user-images.githubusercontent.com/2315384/58454361-17f68f00-80d3-11e9-85ea-79c7e33c12c2.png)

Is there a way?

thanks
mac

**Comment by mmacagno** [comment]
Any comment on this?

**Comment by CarlosLanderas** [comment]
@mmacagno the error that you are receiving is not from EnsureValidApiOptions, is an error thrown by Microsoft.AspNetCore.Http.Abstractions. You can't map a middleware in /. 

A workaround you could do is using:

app.UseDefaultFiles()
.UseStaticFiles()

and server an index.html file doing the redirection in a header script.

**Comment by mmacagno** [comment]
Thanks Carlos!

**Comment by CarlosLanderas** [comment]
You are welcome :)
