### ISSUE TITLE
Add tags array to UIHealthReportEntry class

### ISSUE THREAD

**Issue by msschl** [Xabaril/AspNetCore.Diagnostics.HealthChecks#194]
In dotnet core 3.0 the HealthReportEntry contains a IEnumerable of tags.
It would be nice to add these tags as an array to the json result in the [UIHealthReport](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.UI.Client/UIHealthReport.cs)

**Comment by unaizorrilla** [comment]
Sounds good! I need to create branch for 3.0 and migrate all healtchecks and ui

**Comment by msschl** [comment]
I have created a pull request for this issue. You probably have to rebase the banche. 😄

**Comment by gorillazliuzhe** [comment]
UI界面显示乱码

**Comment by kerray** [comment]
please is this still blocked or can Tags be added?

**Comment by msschl** [comment]
Nope, this should be ready to be implemented.

**Comment by unaizorrilla** [comment]
Hi @kerray 


this is ready to be implemented, a PR is welcome on this topic!

**Comment by kerray** [comment]
that's good news, I made some minor changes that have allowed UI to not fail hard when Tags are present (backend only), I can get a PR ready but getting it done right will need more work

**Comment by CarlosLanderas** [comment]
I can take this issue if you want. I would like to add the tags in the UI in a beautiful way. :)

**Comment by CarlosLanderas** [comment]
Im working in this issue:

![image](https://user-images.githubusercontent.com/16475649/93238436-b94e9c00-f781-11ea-9c06-d45291bfcd65.png)
