### ISSUE TITLE
HealthChecks don't work behind an API Gateway in 2.2.28

### ISSUE THREAD

**Issue by connorearl** [Xabaril/AspNetCore.Diagnostics.HealthChecks#196]
After upgrading to 2.2.28, Healthchecks-UI gets 404 errors looking for /healthchecks-api. It instead looks for it at the root (example.com/healthchecks-api) rather than relative to what the api gateway was routing it to (example.com/module/healthchecks-api)

I am using .NET Core 2.2 on Docker for Linux, with Ocelot 13.5.0

**Comment by CarlosLanderas** [comment]
This might be a regression caused when #129 was fixed. Let me take a look at it to see how can we do so both things can work together

**Comment by connorearl** [comment]
Thanks! 2.2.27 is still working fine

**Comment by CarlosLanderas** [comment]
Could you paste your current UI setup so I can try both scenarios?

Thanks!

**Comment by connorearl** [comment]
It seems the removal of AsRelativeResource() may have caused it in src/HealthChecks.UI/Core/Extensions/UIResourceExtensions.cs

Commit 2d867c9

**Comment by connorearl** [comment]
Yes, just give me one moment

**Comment by CarlosLanderas** [comment]
Yes this is one of the affecting changes, I
 want to test the gateway + nested paths scenario to make both of them work

**Comment by connorearl** [comment]
Here's some selections of code, I had to omit some as I have have a handful of different services now. each are docker containers in the same network.

### API Gateway - Ocelot.json
`"ReRoutes": [
    {
      "DownstreamPathTemplate": "/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "watchdog",
          "Port": 80
        }
      ],
      "UpstreamPathTemplate": "/status/{everything}",
      "UpstreamHttpMethod": []
    }
    //----More services ommitted 
  ]`

### Watchdog - appsettings.json
`{
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "AllowedHosts": "*",
  "HealthChecks-UI": {
      {
        "Name": "Some Docker Container",
        "Uri": "http://container/hc"
      }
    ],
    "EvaluationTimeOnSeconds": 30,
    "MinimumSecondsBetweenFailureNotifications": 60
  }
}`

### Watchdog - Startup.cs
`public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddHealthChecksUI();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHealthChecksUI(
                options => {
                    options.UIPath = "/ui";
                });
        }
    }`

**Comment by lafriks** [comment]
In latest version they also does not work for applications hosted in IIS in virtual directory, works just fine in 2.2.27

**Comment by unaizorrilla** [comment]
Hi @CarlosLanderas 

Can you check again this issue?

**Comment by carlowahlstedt** [comment]
I just ran across this today as well. Rolling back to .27 fixed the issue of the check not showing. My webhook still isn't showing but it is sending to Microsoft Teams though. Not sure what's going on there.

**Comment by carlowahlstedt** [comment]
Also, I think #209 is a dup of this.

**Comment by unaizorrilla** [comment]
Ley me check the issue with 2.2.28 and why is not working on IOS

**Comment by CarlosLanderas** [comment]
@carlowahlstedt, as there are several scenario to cover, (reverse proxies, nested server paths, etc), we are going to add the possibility to configure relative/absolute paths to math all cases.


 .UseHealthChecksUI(setup =>
            {
                setup.ApiPath = "/superapi";
                setup.UseRelativeApiPath = true; //true by default
                setup.ResourcesPath = "/resources";
                setup.UseRelativeResourcesPath = true; //true by default
               setup.WebhookPath = "/webhooks";
                setup.UseRelativeWebhookPath = true; //true by default
            });

**Comment by CarlosLanderas** [comment]
59ca8c39c920afa6e9183f2306c32506ea5ebfd1

**Comment by CarlosLanderas** [comment]
Closing the issue based on feedback, reopen if needed

**Comment by Mordag** [comment]
@CarlosLanderas  I am facing a few problems with setting a custom url. I have used the example but the actual UI is not loaded. The page is just blank.
