### ISSUE TITLE
V 8.0 Release

### ISSUE THREAD

**Issue by sungam3r** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1967]
Issue to track suggestions for features in the next major v8.0 release. Feel free to suggest anything new of peek some existing issues. For non-breaking changes please post suggestions to #1968.

**Comment by stanimirsellercloud** [comment]
Is there a plan to release v8.0 soon?

The current library depends on EfCore 7.0 which causes problems when one upgrades their own project to use EfCore 8.0 (a runtime error appears due to a change in EfCore internals).

**Comment by lkurzyniec** [comment]
Would that version/release cover the latest dotnet 8 release?

**Comment by lkurzyniec** [comment]
@sungam3r any ETA for thet release?

**Comment by adamsitnik** [comment]
Fixed with #2044, #2097 and #2104
