### ISSUE TITLE
V 7.1 Release

### ISSUE THREAD

**Issue by sungam3r** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1968]
Issue to track suggestions for features in the next v7.1 release. Feel free to suggest anything new of peek some existing issues. For breaking changes please post suggestions to #1967.

**Comment by johan-jernstrom** [comment]
I use v7 of this library in my project but missed support for **Azure Speech Services** and **Azure Translator Services** so I ended up writing them myself. 
- I would be happy to **contribute** by submitting a version of them for this library if anyone is interested?

ps. new to this comunity so wanted to ask before I just started submitting anything.  I have looked around in the current issues and pull requests and did not find anything going on already in regards to this - but please point me out if I missed anything!

**Comment by sungam3r** [comment]
@johan-jernstrom PR is welcome. I was away from that project for 4 months. Honestly, we already have code for v8 in `master` after NET8 release in November. Feel free to provide PRs.

**Comment by sungam3r** [comment]
Closed as we already shifted to net8 (v8 release).
