### ISSUE TITLE
After update package 7.0.0 Im geting error

### ISSUE THREAD

**Issue by phivanloi** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1971]
Affter update package to version 7.0.0
![image](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/12540136/7afba97b-e120-401e-b7d8-271bcfc9ed62)

Im geting error. can't show health dashboard.
![image](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/12540136/6f3a905a-325c-4031-8b66-ee3b239f8a62)

**Comment by nzdev** [comment]
Same

**Comment by cieciurm** [comment]
Hi,

I think the error is because front-end expects returned properties to begin with lowercase (f.e. status, color, etc.).

Currently, HealthCheck UI back-end returns values beginning with capital letters:

```json
[
    {
        "Id": 1,
        "Status": "Healthy",
        "OnStateFrom": "2023-07-31T07:28:42.1401329Z",
        "LastExecuted": "2023-07-31T07:28:42.1401329Z",
        "Uri": "http://dev-carts-eur.ebiz.dgs.com/api/status",
        "Name": "Cart API",
        "DiscoveryService": null,
        // ...
     }
]
```

**Comment by sungam3r** [comment]
Yep, thanks.

**Comment by sungam3r** [comment]
AFK now, I'll publish v7.0.1 in 2-3 hours.

**Comment by phivanloi** [comment]
Thanks you

**Comment by sungam3r** [comment]
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/releases/tag/release-ui-7.0.1

Was too busy. CD should push new package in a few minutes.
