### ISSUE TITLE
AddUrlGroup - Ignore Certificate Validation Flag

### ISSUE THREAD

**Issue by rcollina** [Xabaril/AspNetCore.Diagnostics.HealthChecks#198]
Hello,
Could use a way to ignore certificate errors. We've added healthchecks to a third party product that exposes self-signed certificates in dev and test environments.
These healthchecks fail due to certificate validation.

Thank you!

**Comment by unaizorrilla** [comment]
Um, can you explain more this scenario?

**Comment by rcollina** [comment]
Sorry for the duplicate issue.

As I mentioned, we’re integrating with a third party product. Among other healthchecks, we also check that the aforementioned third party product is available by using Uri healthchecks.

This product has an HTTP API of its own. It has been provided to us preconfigured with self-signed certificates that seemingly prevent the Uri healthcheck from working (Status is unhealthy). I am afraid I don’t have the specific error at hand, IIRC it should be along the lines of “unable to establish an SSL connection” but I might be mistaken.

In our own code we solve this by configuring HTTP Clients to ignore certificate errors in dev and staging environments.

Been wondering if the Uri healthcheck could support this same mechanism via a flag.

Hope that clears things up.
Thanks

**Comment by unaizorrilla** [comment]
Hi @rcollina 

Thanks for the explanation!!! I try to work on this ASAP, probably today!

**Comment by rcollina** [comment]
Thank you, much appreciated 😃

**Comment by unaizorrilla** [comment]
Hi @rcollina 

I review this issue and you can do this without modify existing healthchecks. Basically, URL healthcheck use a IHttpClientFactory that can be configured to disable certificate validation. 

This is a sample code to configure the httpclient for URL healtchecks

```
            services.AddHttpClient("uri-group") //default healthcheck registration name for uri ( you can change it on AddUrlGroup )
                .ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler()
                {
                    ClientCertificateOptions = ClientCertificateOption.Manual,
                    ServerCertificateCustomValidationCallback = (httpRequestMessage, cert, cetChain, policyErrors) =>
                    {
                        return true;
                    }
                });
```
You can test it with sample https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/samples/HealthChecks.UIAndApi/Startup.cs 

Please close the issue if this solved,

Thanks
Unai

**Comment by rcollina** [comment]
Hi Unai,
That’s brilliant. I’m afraid I won’t be able to test this soonish (away for a few days) but feel free to close the issue in the meantime if you prefer.

Thank you again for your help,
Rob

**Comment by xico002** [comment]
> Hi @rcollina
> 
> I review this issue and you can do this without modify existing healthchecks. Basically, URL healthcheck use a IHttpClientFactory that can be configured to disable certificate validation.
> 
> This is a sample code to configure the httpclient for URL healtchecks
> 
> ```
>             services.AddHttpClient("uri-group") //default healthcheck registration name for uri ( you can change it on AddUrlGroup )
>                 .ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler()
>                 {
>                     ClientCertificateOptions = ClientCertificateOption.Manual,
>                     ServerCertificateCustomValidationCallback = (httpRequestMessage, cert, cetChain, policyErrors) =>
>                     {
>                         return true;
>                     }
>                 });
> ```
> 
> You can test it with sample https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/samples/HealthChecks.UIAndApi/Startup.cs
> 
> Please close the issue if this solved,
> 
> Thanks
> Unai

This did not work for me. Did it work for you @rcollina ?

**Comment by rcollina** [comment]
@xico002 it's been some
time now but I seem to remember it worked at the time.
