### ISSUE TITLE
After up lib with RabbitMQ from 6.0.2 to 7.0.0 start get exception.

### ISSUE THREAD

**Issue by Janry** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1994]
Get exception 

`System.ArgumentException: 'A connection, connnection factory, or connection string must be set! (Parameter 'options')'`

Up lib from 6.0.2 to 7.0.0.

Registration health check
```
services.AddHealthChecks()
            .AddRabbitMQ(x => new ConnectionFactory
            {
                Uri = new Uri(Configuration.GetRabbitMqOptions().ConnectionString),
                AutomaticRecoveryEnabled = true
            })
```
The same registration works well with 6.0.2 version and with all previous too.

**Environment**:

- .NET Core 7.0
- Microsoft.Extensions.Diagnostics.HealthChecks 7.0.10
- Windows 11

**Comment by sungam3r** [comment]
This is overload with `Action<RabbitMQHealthCheckOptions>? setup` argument. Please change your code to
```c#
services.AddHealthChecks()
             .AddRabbitMQ(x => x.ConnectionFactory = new ConnectionFactory
            {
                Uri = new Uri(Configuration.GetRabbitMqOptions().ConnectionString),
                AutomaticRecoveryEnabled = true
            })
```
