### ISSUE TITLE
ASP.Net Core 2.2 - InProcess Hosting Issue

### ISSUE THREAD

**Issue by twurm** [Xabaril/AspNetCore.Diagnostics.HealthChecks#20]
Just so you are aware, using the Client.UI with [InProcess ](https://blogs.msdn.microsoft.com/webdev/2018/09/12/asp-net-core-2-2-0-preview2-now-available/)hosting will throw an error that it cannot read the SQLite database.  The issue seems to be caused by the following note found [here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2): 

> Directory.GetCurrentDirectory() returns the worker directory of the process started by IIS rather than the application directory (for example, C:\Windows\System32\inetsrv for w3wp.exe).

There is a more detailed discussion of the issue and possible work arounds [here](https://github.com/aspnet/AspNetCore/issues/4206).

**Comment by unaizorrilla** [comment]
Hi @twurm 

I try to check this, fixing the issue with database path is simple, addind HostsDefaults.ContentKey but I need to check also the behavior with embebded resources in the UI.

Thanks for fill this

**Comment by unaizorrilla** [comment]
Hi @twurm 

Opened a bug on asp.net core https://github.com/aspnet/AspNetCore/issues/4505 related with embedded resources and OnStarting response

**Comment by unaizorrilla** [comment]
Hi @twurm 

I push a new commit 809f8333dfca20e32769b9633ad95d357303c749 with fix for in-process model hosting. This take some time to build, execute tests and create nuget packages.

Check for new 2.2.4 package version of AspNetCore.HealthChecks.UI and please, if all is working close this issue,

Thanks again for fill this!!!

**Comment by unaizorrilla** [comment]
Published https://www.nuget.org/packages/AspNetCore.HealthChecks.UI/2.2.4 can you check it out @twurm ?

**Comment by twurm** [comment]
@unaizorrilla I’ll try and check it out this weekend.

**Comment by twurm** [comment]
@unaizorrilla a quick check seems like everything is working correctly.  I'll do some more testing on Monday but for now it looks like its fixed.
