### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by sungam3r** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2006]
Now all versions are written into build/version.props file. When making changes in some project you have to remember to bump corresponding version in that file. It's not convinient. Moreover, it's more unconvinient for PRs from dependabot like this one https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/2001. At the end when preparing for release maintainer needs to manually check all versions. This process shoul be simplified in some way.

**Comment by michaelmairegger** [comment]
We should move to centrac [package management](https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management). Then we can manage all the versions in one file. I can provide a PR if desired

**Comment by luizbon** [comment]
I see two mixed pieces of information here in this issue.
One is as a maintainer controlling the package versions and how this can be simplified.
Another one is the project dependencies and using bots to keep them updated.

A SemVer approach could help with the first one. Maybe introducing [MinVer](https://github.com/adamralph/minver), which controls versions based on Git Tags (closely related to GitHub releases), helps.

For the second one, the logical approach is introducing CPM (Central Package Management), native to NuGet.

Does that sound right, @sungam3r?
