### ISSUE TITLE
Method of setting ApiPath for the UI

### ISSUE THREAD

**Issue by ruant** [Xabaril/AspNetCore.Diagnostics.HealthChecks#201]
So I'm hosting my application in a subfolder on a domain.  
`https://example.com/myapplication`

So the UI thinks the `healthchecks-api` is at `https://example.com/healthchecks-api`

Setting this doesn't work,
```
app.UseHealthChecksUI(options =>
{
  options.ApiPath = "/myapplication/healthchecks-api";
});
```
since now the ui-api will be hosted at `/myapplication/myapplication/healthchecks-api`  
But the UI thinks it's hosted at `https://example.com/myapplication/healthchecks-api`

Is there a way to set the UI-API path for the frontend UI SPA only?

**Comment by auserx** [comment]
same issue here

**Comment by ruant** [comment]
I think this is the same as #196
Reverting back to the previous version it works fine.

Closing this one.

**Comment by CarlosLanderas** [comment]
@auserx @ruant , this was a regression from version 2.2.27 to version 2.2.28 where api path was not being served as a relative path to the frontend anymore. In version 2.2.30 you have new options to configure all paths as relative 

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/196#issuecomment-505764777
