### ISSUE TITLE
rabbitmq docker-swarm stack not working

### ISSUE THREAD

**Issue by josephderonde** [Xabaril/AspNetCore.Diagnostics.HealthChecks#203]
Hi Chaps,

Hoping you can help, I currently have RabbitMQ running in a different stack and in a clustered environment (i don't think that matters) but the connection to it is StackName_rabbitmq. When running locally and its in the same stack the healthchecks can pick up rabbitmq just fine and the readout goes all green. But when they are deployed to separate stacks and connected over docker network. they then fail.

any help would be greatly appreciated.

**Comment by josephderonde** [comment]
Error message in the UI is None of the specified endpoints were reachable

**Comment by CarlosLanderas** [comment]
@josephderonde it is difficult to be able to help with this information. It seems to be a network related issue. Could you provide configuration samples?

**Comment by josephderonde** [comment]
I have no idea why i have left this open for so long, i have the healthcheck for this working now

                .AddRabbitMQ(
                    $"amqp://{configuration["EventBusConnection"]}/",
                    failureStatus: HealthStatus.Degraded,
                    name: "basket_rabbitmq-check",
                    tags: new string[] { "rabbitmq", "basket_rabbitmq" })

connection to the seperate stack is StackName_rabbitmq and works fine, i do not even remember the issue i was having with it, i will close
