### ISSUE TITLE
Webhooks UI exposes secrets like slack URI

### ISSUE THREAD

**Issue by tzkhan** [Xabaril/AspNetCore.Diagnostics.HealthChecks#204]
The webhooks section in the UI exposes secrets. Is there any way to not display them?

![image](https://user-images.githubusercontent.com/11405775/59276583-7df82000-8c56-11e9-903b-dbc814ecd79f.png)

**Comment by CarlosLanderas** [comment]
@tzkhan as all webhooks formats differ depending on the platform, we have not a mechanism to extract the secrets from the uris. Maybe we can hold a dictionary to recognize de format of the most famour platforms as slack, teams, etc. But this will have to wait for next version.

Thanks

**Comment by tzkhan** [comment]
@CarlosLanderas another option would be to add a boolean property (like `RedactUri`) to `WebHookNotification` and in the `UIWebHooksApiMiddleware`, blot out the `Uri` value if the flag is enabled.

**Comment by CarlosLanderas** [comment]
Yeah, we could just leave http://hooks.slack.com/

**Comment by Zetanova** [comment]
Any news? 

I cant find a new property in WebHookNotification
