### ISSUE TITLE
Database is locked (when deployed to Azure App Service on Linux)

### ISSUE THREAD

**Issue by littlenetcoder** [Xabaril/AspNetCore.Diagnostics.HealthChecks#206]
Hi guys,
I tried the health checks locally on my dev machine with IIS express & Docker and everything worked great.
I deployed to Azure App services where everything is working fine but when i deployed same to Azure App Service on Linux i am getting error 
This is what I find on the app log:
![Capture](https://user-images.githubusercontent.com/26800311/59676571-7bad3d00-91e5-11e9-8f4f-4f075cc2f03b.PNG)
Thanks!

**Comment by unaizorrilla** [comment]
Hi

I need to check this, we use this without any issue, but let me check!

**Comment by rob-baldwin** [comment]
Hey @littlenetcoder,

I've come across this problem as well, as a workaround I changed the database name on each startup which avoids the locking issue.  It's a bit of an ugly solution, but does the trick:

```
var uniqueId = Guid.NewGuid().ToString("N").Substring(0, 8);
var databaseName = $"healthchecksdb_{uniqueId}";
services.AddHealthChecksUI(databaseName);

**Comment by littlenetcoder** [comment]
Hey @rob-baldwin,
I tried but did not work for me.

**Comment by ahryshchanka** [comment]
I got the same problem, any ideas how to fix it?

**Comment by CarlosLanderas** [comment]
Sqlite is not compatible with AppService in Linux, but affortunately last ui version (3.1.1-preview1) has support for storage providers and different databases can be configured now:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/455#issuecomment-613093369
