### ISSUE TITLE
'@' char in the password

### ISSUE THREAD

**Issue by RaynaldM** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2062]
if there is a '@' in the password, [AddRabbitMQ](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/2824b09121fb66763e971eb3bea5c93a8164f7ce/src/HealthChecks.Rabbitmq/DependencyInjection/RabbitMQHealthCheckBuilderExtensions.cs#L28C40-L28C51) launch an System.UriFormatException

**Comment by sungam3r** [comment]
I'm sure that it's not an issue in HC repo itself. Please ask question in corresponding RabbitMQ repo about escaping special characters in connection string.
