### ISSUE TITLE
Sign your assemblies with a strong name

### ISSUE THREAD

**Issue by rdvanbuuren-gasunie** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2076]
**What would you like to be added**:
Please sign your assemblies with a strong name. 
See https://learn.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name for more info.

**Why is this needed**:
So our strongly named assemblies can also use your nuget packages. Currently this is not possible and will throw a build error.

**Comment by adamsitnik** [comment]
This was done with #2044, will be part of the upcoming 8.0 release.
