### ISSUE TITLE
Add overload for SFTP with IServiceProvider

### ISSUE THREAD

**Issue by fcl-9** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2079]
**What would you like to be added**: I would like to allow the SftpConfiguration to be returned from a factory (similar to what happens witht he SQL HealthCheck), this would allow us to take advantage of the Service Provider.

**Why is this needed**: In my situation my Private Key Comes Encoded in Base64 from our KeyVaults and I have an utility class that is injected in the container, this utility class is reused in various part of the code where I use SFTP. Instead of continously instanciating this class I can just leave that to the container that manages the dependencies.

This is an example of the usage of what I am proposing above: 
```
services.AddHealthChecks().AddSftpHealthChecks(sp => {

	var config = sp.GetRequiredService<IConfiguration>();
	var utility = sp.GetRequiredService<IUtility>();

	var base64EncodedPrivateKey = config.GetValue<string>("SftpPrivateKey");
	var privateKeyDecoded = utility.ConvertBase64ToString(base64EncodedPrivateKey)
	using var privateKeyStream = utility.CreateStreamFromString(privateKeyDecoded);

	var keyFile = new PrivateKeyFile(privateKeyStream, ...)

	return new SftpConfigurationBuilder(...).AddPrivateKeyAuth(keyFile);

});
```

**Comment by fcl-9** [comment]
I am happy to raise the PR if want to proceed with this!

**Comment by sungam3r** [comment]
PR is welcome.

**Comment by fcl-9** [comment]
I will pick this up. I have very limited access to my machine until 30 December 2023 but shall be able to open the PR after this date.
