### ISSUE TITLE
HealthChecksUI does not properly resolves healthchecks-ui api url.

### ISSUE THREAD

**Issue by RonnyAnc** [Xabaril/AspNetCore.Diagnostics.HealthChecks#209]
We have our API deployed on premise in our own IIS and with a concrete name (for the website) and port in the IIS. 

The problem is that as the index.ts is mountint the api url using `window.location.origin` in the client page is trying to get data from a wrong url which does not exist.

### Example: 
My API is on: http://mymachine:81/MyApp/
My HealthChecksUI is on: http://mymachine:81/MyApp/status
But this last is looking for healthchecks-api without the website name. I mean: http://mymachine:81/healthchecks-api. It should be http://mymachine:81/MyApp/healthchecks-api instead, which is the endpoint which really exists and is well exposing health checks data. 

This is because `window.location.origin` takes only http://mymachine:81/.

### Possible solution
Maybe you could use the complete url and replacing the url from last slash to the end. If I didn't understand bad, I think the ui and that api will be only in the same place? aren't they?

**Comment by CarlosLanderas** [comment]
@RonnyAnc as there are multiple scenarios to server requests (nested application paths, reverse proxies, etc). So I am going to add two options to the UI Setup so all can coexist.

```
 .UseHealthChecksUI(setup =>
            {
                setup.ApiPath = "/superapi";
                **setup.UseRelativeApiPath = true;** //true by default
                setup.ResourcesPath = "/resources";
                **setup.UseRelativeResourcesPath = true;** //true by default
            })
```

If we use setup.UseRelativeApiPath it will use **healthchecks-api** instead of **/healthchecks-api** and it should work.

**Comment by CarlosLanderas** [comment]
59ca8c39c920afa6e9183f2306c32506ea5ebfd1

**Comment by RonnyAnc** [comment]
Thank you so much @CarlosLanderas! Much better option! It's more declarative. 

You solved our problem so fast! Thank you for that too 👍

**Comment by CarlosLanderas** [comment]
@RonnyAnc the last version also changed the React Router from <BrowserRouter> to <HashRouter>, because trying to reproduce your bug I tried with double nesting /app1/app2 and relative paths were not working with BrowserRouter as api calls were materializing to /app1/app2/healthchecks-api, so thanks for reporting so I could spot another possible bug.

**Comment by CarlosLanderas** [comment]
@RonnyAnc 

With latest version version everything worked for you using parameterless

`.UseHealthChecksUI();
`

as you are using the default api endpoint right? (/healthchecks-api )

**Comment by RonnyAnc** [comment]
@CarlosLanderas Hi!

I have just tested it and it works perfect now! 💯 

We are not using parameterless because we are configuring the endpoint for the cliente, but yes, we are using the default api endpoint.

Thank you so much!

**Comment by rapXidy** [comment]
![image](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/46676018/1c0d32bf-2cf8-4d29-8235-134b0960fe54)


Please what could be the cause this issue on iis?

**Comment by Acczad** [comment]
We also had the exact same problem on IIS while the code was working locally.
We changed the settings as below.

**we disabled UseRelativeApiPath.** 

config.MapHealthChecksUI(options => 
                {
                    //options.UIPath = "healthchecks-ui";
                    options.UseRelativeApiPath = false;
                    //options.ApiPath = "healthchecks-api";  
                });

And in the appsettings.json file. We change the URI in absolute form and then the problem was solved.
