### ISSUE TITLE
Individual Path

### ISSUE THREAD

**Issue by GustavoFonsecaDeAlmeida** [Xabaril/AspNetCore.Diagnostics.HealthChecks#21]
I was studying to perform the migration of the old beatpulse to this new implementation. 
I missed the individual path verification.

This is in paper for implementation or it will not be possible to be done in this new version.

**Comment by CarlosLanderas** [comment]
@GustavoFonsecaDeAlmeida Healthchecks offers a different approach to Beatpulse, you can filter by **tags** or **name** using the UseHealthChecks predicate.

If you want to group you healthchecks by **tags**

Register your healthchecks and add the target tags:

```csharp
      services.AddHealthChecks()
                .AddSqlServer(connectionString: Configuration["Data:ConnectionStrings:Sample"],
                     tags: new[] {"database"})
                .AddMySql("cnnString",
                     tags: new [] { "database"})
                .AddIdentityServer(new Uri("http://localhost:6060"),
                     tags: new[] {"identity"});
```

Map your tags to an url using the predicate:

```csharp
            app.UseHealthChecks("/health", new HealthCheckOptions()
            {
                Predicate = _ => true
            });

            app.UseHealthChecks("/database-health", new HealthCheckOptions()
            {
                Predicate = r => r.Tags.Contains("database")
            });
            
            app.UseHealthChecks("/identity-health", new HealthCheckOptions()
            {
                Predicate = r => r.Tags.Contains("identity")
            });

```


If you want to bind individual healthchecks to urls, you should use **name** registration:


```csharp
  services.AddHealthChecks()
                .AddSqlServer(connectionString: Configuration["Data:ConnectionStrings:Sample"],
                    name: "sqlserver1")
                .AddSqlServer(connectionString: Configuration["Data:ConnectionStrings:Sample2"],
                    name: "sqlserver2");
```

```csharp
            app.UseHealthChecks("/sql/1", new HealthCheckOptions()
            {
                Predicate = r => r.Name.Equals("sqlserver1")
            });
            
            app.UseHealthChecks("/sql/2", new HealthCheckOptions()
            {
                Predicate = r => r.Name.Equals("sqlserver2")
            });

```

**Comment by GustavoFonsecaDeAlmeida** [comment]
Thankss.. I will do this.

Other question.. About auth ( like a "api-key" at beatpulse ) would  have any approach available?

**Comment by unaizorrilla** [comment]
Nope, at this moment api-key or similar is not supported on HealthChecks.

You can fill an issue on github.com/asp/diagnostics

**Comment by CarlosLanderas** [comment]
I filled the issue as I am also interested in this feature:

https://github.com/aspnet/AspNetCore/issues/4544

Closing this issue.

Thanks
