### ISSUE TITLE
Question: Does the RestoredPayload work for Microsoft Teams?

### ISSUE THREAD

**Issue by carlowahlstedt** [Xabaril/AspNetCore.Diagnostics.HealthChecks#210]
I've never seen it send an alert stating that it's been restored. I'm using the wiki template example.

**Comment by CarlosLanderas** [comment]
@carlowahlstedt yes it does, you can check it working in this video where I configure it and we see it restoring live.

https://youtu.be/kzRKGCmGbqo?t=1941
