### ISSUE TITLE
Revert changes for net5 tfm 

### ISSUE THREAD

**Issue by sungam3r** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2103]
> for some projects I've removed net5.0 tfm as it's [not supported anymore](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)

![изображение](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/21261007/2c95ad1f-a4f2-4d50-a48f-d03f21ac9305)

It should be reverted. It make no sence to require higher TFM in case no specific APIs are used from that TFM. Yes, net5 not supported anymore but this is story about runtime/end-applications but not about libraries. With such change as at picture above you make impossible for net5 apps to use this health check though healthcheck itself works perfectly targeted for net5.

_Originally posted by @sungam3r in https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/2044#issuecomment-1837560421_

**Comment by sungam3r** [comment]
ping @adamsitnik

**Comment by adamsitnik** [comment]
> With such change as at picture above you make impossible for net5 apps to use this health check though healthcheck itself works perfectly targeted for net5.

But it's still targeting netstandard2.0, so .NET 5, .NET Core 3.1 and even 2.1 apps can still use it.

**Comment by sungam3r** [comment]
It's a question of another dimention. Look https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.Uris/UriHealthCheck.cs#L41

**Comment by adamsitnik** [comment]
> Look 

Thanks for pointing that out! 👍 

> One should not bump tfm requirements just because.

If we follow the .NET release schedule and use the same major version numbers, when should we drop non-supported TFMs?

**Comment by sungam3r** [comment]
No

**Comment by sungam3r** [comment]
"Not supported" is not applicable from api-set point of view.
