### ISSUE TITLE
EventHub checks missing from AspNetCore.HealthChecks.AzureServiceBus

### ISSUE THREAD

**Issue by aelghoneimy** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2128]
Please, fill the following sections to help us fix the issue

**What happened**: Missing `AddAzureEventHub` health check extension after updating to v8

**How to reproduce it (as minimally and precisely as possible)**: Update `AspNetCore.HealthChecks.AzureServiceBus` to v8

**Source code sample**:
```csharp
healthChecksBuilder.AddAzureEventHub("CONNECTION_STRING", "ENTITY_NAME");
```

**Comment by unaizorrilla** [comment]
We have a new package for this, right @adamsitnik ??

**Comment by aelghoneimy** [comment]
In the readme, it's mentioning v8 and EventHub in the AzureServiceBus package

![image](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/4632474/d8b9ac4b-7b00-4b95-a2a3-79f4d4eca425)

**Comment by marioleed** [comment]
Use [AspNetCore.HealthChecks.Azure.Messaging.EventHubs](https://www.nuget.org/packages/AspNetCore.HealthChecks.Azure.Messaging.EventHubs)

Also [read more about the breaking changes](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/tree/master/src/HealthChecks.Azure.Messaging.EventHubs#breaking-changes).

**Comment by adamsitnik** [comment]
@marioleed is right, the new package for Azure Event Hub is https://www.nuget.org/packages/AspNetCore.HealthChecks.Azure.Messaging.EventHubs

I've updated the docs in https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/2131

**Comment by mikocot** [comment]
To be fair I can expect more people running into this (just like me), cause there doesn't seem to be any hint about this change, or any information at all about the release of v 8.0. Also, quick google search and docs search doesn't easily get you to 

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/tree/master/src/HealthChecks.Azure.Messaging.EventHubs#breaking-changes if what you've been using so far is the ServiceBus package. Probably it's different for the new users.
