### ISSUE TITLE
Support configuration sourced from Azure App Configuration Service for the HealthChecks UI

### ISSUE THREAD

**Issue by faniereynders** [Xabaril/AspNetCore.Diagnostics.HealthChecks#213]
In my scenario, I'm running the HealthChecks UI straight from a Docker image in Azure, and the only way to provide endpoint configs is via environmental variables, which is not always friendly for many endpoints.

It would be great if the HealthChecks UI could support adding endpoint configurations from Azure App Configuration Service out of the box in the Docker Image so one can just run the image and manage the configuration from an external source.

**Comment by CarlosLanderas** [comment]
@faniereynders the feature is live.
Health Checks UI Docker image (/2.2.32 / latest) already implements AAC.

You can read this README for more information and samples:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/doc/ui-docker.md
