### ISSUE TITLE
[NET 8.0] AspNetCore.HealthChecks.AzureStorage is not up to date causing System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by VincentCentris** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2142]
**What happened**: On a .NET 8 project we are facing the same error as mentionned here  https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/2084 

**What you expected to happen**:

All packages for `AspNetCore.HealthChecks` are on 8.0.0 version on nuget, but it seems 
`AspNetCore.HealthChecks.AzureStorage` has not been updated or package was not pushed to nuget. We would need it. 

https://www.nuget.org/packages/AspNetCore.HealthChecks.AzureStorage

**How to reproduce it (as minimally and precisely as possible)**:

Just make usage of `AspNetCore.HealthChecks.AzureStorage 7.0.0` inside a .NET 8 projet 

**Environment**:

- .NET Core version : 8.0.0
- Healthchecks version : 7.0.0 (no 8.0.0 available)

**Workaround** : Install explicit reference of  https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces (8.0.0)

**Comment by asiffermann** [comment]
I was facing the same issue until I realized that Azure Storage health checks has been split into several different new NuGet packages :

- [AspNetCore.HealthChecks.Azure.Storage.Blobs](https://www.nuget.org/packages/AspNetCore.HealthChecks.Azure.Storage.Blobs)
- [AspNetCore.HealthChecks.Azure.Storage.Queues](https://www.nuget.org/packages/AspNetCore.HealthChecks.Azure.Storage.Queues)
- [AspNetCore.HealthChecks.Azure.Storage.Files.Shares](https://www.nuget.org/packages/AspNetCore.HealthChecks.Azure.Storage.Files.Shares)

Make sure to use one of these in your .NET 8 projects. I'm not sure if there is still health check for Azure Table Storage tho, I couldn't find it on nuget.org or in the sources in this repo...

**Comment by codymullins** [comment]
Is there a way to mark the old package as deprecated?

**Comment by sungam3r** [comment]
Yes. Nuget.org has such a feature. Package owner can unlist/deprecate package. I'm not an owner. Ping @unaizorrilla , @carlosrecuero .

**Comment by dmitry-pavlov** [comment]
Nice catch @asiffermann 👍 I had this issue after upgrading from 7 to 8, and replacing [AspNetCore.HealthChecks.AzureStorage](https://www.nuget.org/packages/AspNetCore.HealthChecks.AzureStorage) 7 with [AspNetCore.HealthChecks.Azure.Storage.Blobs](https://www.nuget.org/packages/AspNetCore.HealthChecks.Azure.Storage.Blobs) 8 did the trick. 

Also I had to adjust the way how BlobServiceClient and corresponding health check are DI-ed: 

```
services.AddSingleton(sp => new BlobServiceClient("<put-here-your-connection-string>"));
services.AddHealthChecks().AddAzureBlobStorage(tags: new[] { "azureblob", "blob", "storage", "files" });
```

**Comment by unaizorrilla** [comment]
Hi @sungam3r 

Done!

Just deprecated on NuGet and set a custom message with valid packages
