### ISSUE TITLE
Could not load file or assembly Microsoft.Bcl.AsyncInterfaces .NET 8

### ISSUE THREAD

**Issue by nschoenberg** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2163]
**What happened**:

Recently upgraded my web app to .NET 8, queue healthchecks where working fine before upgrading. Other healthchecks like postgre sql database are still working fine. Im getting the following error in Azure:

`Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
`

**What you expected to happen**:

No exception, healthcheck runs as expected

**How to reproduce it (as minimally and precisely as possible)**:

Add a healthcheck to a service bus

**Source code sample**:

```
var connectionString = "sb endpoint here";
.AddAzureServiceBusQueueMessageCountThreshold(connectionString , "YourQueueNameHere",
                                                              "Message Count", conf =>
                                                              {
                                                                  conf.ActiveMessages = new AzureServiceBusQueueMessagesCountThreshold
                                                                  {
                                                                      DegradedThreshold = 20000,
                                                                      UnhealthyThreshold = 100000
                                                                  };
                                                              });
```

**Anything else we need to know?**:

**Environment**:

- .NET Core version: .NET 8
- Healthchecks version 

<PackageReference Include="AspNetCore.HealthChecks.AzureServiceBus" Version="8.0.0" />
<PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="8.0.0" />
<PackageReference Include="AspNetCore.HealthChecks.Redis" Version="8.0.0" />
<PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="8.0.0" />

- Operative system: Windows x64
- Others:

**Comment by ben-002** [comment]
Is there a workaround for this? we encountered the same problem

**Comment by throwaway34059** [comment]
We are seeing the same thing for AspNetCore.HealthChecks.Azure.Storage.Blobs.

"StorageConnectionString":{"data":{},"description":"Could not load file or assembly \u0027Microsoft.Bcl.AsyncInterfaces, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51\u0027. The system cannot find the file specified."
