### ISSUE TITLE
Icons missing from health checks UI

### ISSUE THREAD

**Issue by jjmyrup** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2169]
**What happened**:
After pulling master icons have been replaced with text when running sample projects e.g. HealthChecks.UIAndApiCustomization
![image](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/20145185/e69f230e-825e-4387-8b0c-e84f5d37eab0)

**What you expected to happen**:
I expected icons not text for e.g. health status and expand.

**How to reproduce it (as minimally and precisely as possible)**:
In visual studio
- Set HealthChecks.UIAndApiCustomization as start up project 
- Run the project

**Source code sample**:
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/tree/release-all-8.0.0/samples/HealthChecks.UIAndApiCustomization

**Anything else we need to know?**:
I have used git bisect to identify that the problem was introduced with this commit cb4b3215b67c98e9be06f8546fd06ab315fceefb

**Environment**:

- .NET version: NET8.0
- Healthchecks version: 8.0.0
- Operative system: Windows 10
- Visual Studio: 2022

**Comment by rob-baldwin** [comment]
Duplicate of https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/2130

**Comment by Jamie-Clayton** [comment]
fixed in https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/2217

**Comment by Alirexaa** [comment]
Close as completed via #2217
