### ISSUE TITLE
Could not load type 'SqlGuidCaster' from assembly Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by aj-scram** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2182]
Recently upgrade project from .net7 to .net8 and immediately ran into this old https://github.com/dotnet/SqlClient/issues/1930

Seems that the root cause is any older version of Microsoft.Data.SqlClient (<5.2.0) than the newest release not playing well with reflection calls loading types/assemblies.

Could we get AspNetCore.HealthChecks.SqlServer to update to use the new version?

**Comment by unaizorrilla** [comment]
I just create a PR for this #2183, waiting for review!
