### ISSUE TITLE
Add Milvus client health check

### ISSUE THREAD

**Issue by timheuer** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2214]
**What would you like to be added**:
Add health check for the Milvus client:
https://github.com/milvus-io/milvus-sdk-csharp/blob/main/Milvus.Client/HealthState.cs

**Comment by smnsht** [comment]
@Alirexaa 
Hi,

If you haven't started yet, maybe you can let me take this one?
I am ready to submit PR.

**Comment by Alirexaa** [comment]
> @Alirexaa 
> Hi,
> 
> If you haven't started yet, maybe you can let me take this one?
> I am ready to submit PR.

Hi, thanks. No problem. Please Send PR.
