### ISSUE TITLE
material.css has invalid woff2 file

### ISSUE THREAD

**Issue by JimPShaw** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2219]
.Net core 8, chrome browser.

The material icons do not display properly (not loaded properly) due to an error in browser decoding the woff2 file for the material icons.

**Comment by dtwilliams10** [comment]
Pretty sure this is a duplicate of #2130

**Comment by JimPShaw** [comment]
Thanks, workaround is good.

**Comment by camiteca** [comment]
The problem with the workaround is that it's only useful if you can reach the internet on your host.

**Comment by Jamie-Clayton** [comment]
Fixed in https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/2217

**Comment by Alirexaa** [comment]
close this as completed via #2217
