### ISSUE TITLE
Health check debug logs

### ISSUE THREAD

**Issue by satishviswanathan** [Xabaril/AspNetCore.Diagnostics.HealthChecks#224]
I have my health check set up for my asp net core app and working fine but it seems to be generating lot of debug logs. Is there a way I can disable them?

**Comment by CarlosLanderas** [comment]
Use a higher logger level like Warning or Error. You can also set individual log levels for the different Microsoft Categories and HealthChecks namespace. Just check Microsoft Logging documentation.

**Comment by Tieantono** [comment]
Sorry for replying a closed issue, but @CarlosLanderas, do you know the right namespace for this package? I've set the minimum level of these following namespaces to `Warning` in Serilog settings:
* `Microsoft.AspNetCore.Diagnostics.HealthChecks`
* `Microsoft.Extensions.Diagnostics.HealthChecks`
* `AspNetCore.HealthChecks.UI`

But it is still generating the log output.

**Comment by CarlosLanderas** [comment]
Hi! It is HealthChecks

**Comment by Tieantono** [comment]
> Hi! It is HealthChecks

Thank you for the reply @CarlosLanderas , but it still generating the log output each 10 seconds) like this:
<details>
  <summary>Generated log output</summary>

![image](https://user-images.githubusercontent.com/14927392/79681866-fdc42300-8247-11ea-91bc-2f722a3e2cee.png)
</details>

This is my Serilog Settings in my appsettings.json:
```
"Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft.EntityFrameworkCore": "Information",
        "Microsoft.AspNetCore.Diagnostics.HealthChecks": "Warning",
        "Microsoft.Extensions.Diagnostics.HealthChecks": "Warning",
        "AspNetCore.HealthChecks.UI": "Warning",
        "HealthChecks": "Warning"
      }
    },
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "theme": "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console",
          "outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} <s:{SourceContext}>{NewLine}{Exception}"
        }
      },
    ]
  }
```
Of course, when I set `Microsoft.EntityFrameworkCore` value to `Warning` it won't generate the healthcheck query logs, but I do need the generated logs from EF Core package for profiling.

**Comment by CarlosLanderas** [comment]
That's Microsoft Entity Framework printing all the queries. Increase EF Core loglevel to warning

**Comment by Tieantono** [comment]
> That's Microsoft Entity Framework printing all the queries. Increase EF Core loglevel to warning. You are not seeing any Healthchecks logging there. Just database access

I see, so it all back to EF Core again. I just thought I can still log on `Information` level on EF Core and disable HC logs. Thank you.

**Comment by Alirezanet** [comment]
Hi,
Is there anyway to just disable EF core logging related to HC? I need my efcore logs but I want to disable everything related to HC.

**Comment by projectje** [comment]
this came out on google as first hit, so just use serilog filtering if using serilog, example:

`"Filter": [
      {
        "Name": "ByExcluding",
        "Args": {
          "expression": "RequestPath like '/health%' and RequestPath not like '/health_sys_version'"
        }
      }
    ],`

**Comment by billylarru** [comment]
After several tests the following worked for me:

`Log.Logger = new LoggerConfiguration()
                .Filter.ByExcluding("RequestPath like '/health%' and RequestPath not like '/health_sys_version'")
                .Filter.ByExcluding("RequestPath like '/ui%'")
                .Filter.ByExcluding("RequestPath like '/_framework%'")
                .Filter.ByExcluding("Scope[?] = 'HealthReportCollector is collecting health checks results.'")
                .CreateLogger();`
