### ISSUE TITLE
Error while copying content to a stream

### ISSUE THREAD

**Issue by EdwinThomas11** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2241]
Hello,

I hope you're doing well.

I'm working on implementing a health check in my application. Here are the changes I've made.

**Here is the code in the startup.cs**

services.AddHealthChecks()
.AddSqlServer("MyConnectionString");

services
.AddHealthChecksUI(s =>
{
s.AddHealthCheckEndpoint("endpoint1", "https://localhost:5001/health");
})
.AddInMemoryStorage();

app.UseEndpoints(endpoints =>
{
endpoints.MapControllers();
endpoints.MapHealthChecksUI();
endpoints.MapHealthChecks("https://localhost:5001/health", new HealthCheckOptions()
{
Predicate = _ => true,
ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
});
});

**Here is the package references:**
![image](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/144798244/23986f8a-ad2d-4c35-a896-494af3f21379)

**Here is the json health check:**
![image](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/144798244/39a19432-f571-4844-825d-7257a1adb482)

**Here is the health check UI:**
![image](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/144798244/5b44da33-b12e-4e80-aad7-5200f6a9fa27)

I'm not sure why I'm encountering this error ("Unexpected character encountered while parsing value: <. Path '', line 0, position 0.") in the health check UI.

I would appreciate any help you can provide.

Regards,
Edwin Thomas

**Comment by EdwinThomas11** [comment]
@adamsitnik, @Jamie-Clayton Appreciate your help here.

**Comment by dbarwikowski** [comment]
Could you show screenshot from dev tools, network tab? I'm interested in contents of /healthchecks-api request

**Comment by EdwinThomas11** [comment]
@dbarwikowski Please find the screenshot for your response
<img width="926" alt="image" src="https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/144798244/3430f67d-90aa-41f5-87dd-b080f5e0f736">

**Comment by dbarwikowski** [comment]
Thanks! Unfortunately it's not helpful :(
One more think that might be a problem is http**s**. Is your API setup to use it?

**Comment by EdwinThomas11** [comment]
@dbarwikowski The issue was due to the authorization for https://localhost:5001/health. After whitelisting this URL, it worked as expected.

**Comment by EdwinThomas11** [comment]
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/2255 -> Another ticket for reference.
CC : @dbarwikowski

**Comment by dbarwikowski** [comment]
I've seen the other issue of yours. Is this still a problem?
