### ISSUE TITLE
V 8.1

### ISSUE THREAD

**Issue by Alirexaa** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2243]
Issue to track suggestions for features in the next minor v8.1 release. Feel free to suggest anything new or peek at some existing issues.

**Comment by Jamie-Clayton** [comment]
The WebPack icon fix in #2217 would be a good fix to several UI complaints.

**Comment by Jamie-Clayton** [comment]
I'm personally interested in #2153, but I don't know if the PR that's been presented meets your code coverage expectations.

**Comment by Jamie-Clayton** [comment]
There are some very minor readme file typos in #2197 that could be included.

**Comment by Alirexaa** [comment]
Can you open new issues for these? 
> * Sample projects include a range of ports that have changed behavior from dotnet [v7](https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/7.0/https-binding-kestrel).
> * Sample projects and readme examples should be configured for[ SSL,](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-8.0#configure-https) and [AllowedHosts](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/host-filtering?view=aspnetcore-8.0) to ensure software engineers follow security by default.

**Comment by 0-gravity** [comment]
Add support for ExecutionStrategy wherever it possible. It can be useful to handle password rotations

**Comment by vienleidl** [comment]
Still waiting for the fix of UI icon in v8.1

**Comment by Alirexaa** [comment]
@unaizorrilla,
Please check merged PRs on this [list](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/milestone/5?closed=1) and release a new version for related packages.

**Comment by unaizorrilla** [comment]
> @unaizorrilla, Please check merged PRs on this [list](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/milestone/5?closed=1) and release a new version for related packages.

I will take a look for this tomorrow !

**Comment by Alirexaa** [comment]
@benjaminoerskov @vienleidl @Jamie-Clayton
AspNetCore.HealthChecks.UI Package published on nuget with version 8.0.2

@unaizorrilla thank you very much!

**Comment by benjaminoerskov** [comment]
Thank you @Alirexaa! 🎉
