### ISSUE TITLE
Allow to customize Failure message for webhooks

### ISSUE THREAD

**Issue by michalkisielewski** [Xabaril/AspNetCore.Diagnostics.HealthChecks#225]
It would be nice to have a possibility to customize [[FAILURE]] message in webhooks.
Currently it is defined like below.(https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/706fb5b7c1991272ab73aa00a3e868c03589d93f/src/HealthChecks.UI/Core/Notifications/WebHookFailureNotifier.cs)
```csharp
private string GetFailedMessageFromContent(UIHealthReport healthReport)
{
    var failedChecks = healthReport.Entries.Values
        .Count(c => c.Status != UIHealthStatus.Healthy);

    return $"There are at least {failedChecks} HealthChecks failing.";
}
```

**Comment by cjbush** [comment]
I'd be interested in having this feature as well. @michalkisielewski what were you thinking of in terms of how it could be customized?

**Comment by CarlosLanderas** [comment]
Hello, we are talking about this here:
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/415

Give your opinion about how do you think we should implement this. Thanks
