### ISSUE TITLE
AWS S3 Documentation

### ISSUE THREAD

**Issue by whoiskevinrich** [Xabaril/AspNetCore.Diagnostics.HealthChecks#227]
Would it be possible to add a functional test to the S3 healthcheck to demonstrate usage?

**Comment by CarlosLanderas** [comment]
@whoiskevinrich we do not have a functional test for AWS S3 as it is a cloud service. The usage is passing the arguments needed to create a client:

Options receive a access-key, a secret key, the bucket name and a AmazonS3Config object.

You have a sample here:

https://docs.min.io/docs/how-to-use-aws-sdk-for-net-with-minio-server.html

```csharp
  var config = new AmazonS3Config
        {
            RegionEndpoint = RegionEndpoint.USEast1, // MUST set this before setting ServiceURL and it should match the `MINIO_REGION` enviroment variable.
            ServiceURL = "http://localhost:9000", // replace http://localhost:9000 with URL of your MinIO server
            ForcePathStyle = true // MUST be true to work correctly with MinIO server
        };
        var amazonS3Client = new AmazonS3Client(accessKey, secretKey, config); 
```
