### ISSUE TITLE
Zero Second UI Refresh

### ISSUE THREAD

**Issue by carlowahlstedt** [Xabaril/AspNetCore.Diagnostics.HealthChecks#229]
Had someone mention to me that if they change the refresh value to 0 that it accepted it and started making a bunch of requests. I would suggest that it change to validate a minimum of 1 second.

![image](https://user-images.githubusercontent.com/2687687/61382408-bce34c00-a87a-11e9-893a-8654a2029764.png)

**Comment by CarlosLanderas** [comment]
Every zero seconds materializes in zero seconds setInterval, that means continuous checking

**Comment by carlowahlstedt** [comment]
Makes sense if that's the expected behavior.
