### ISSUE TITLE
wording/syntax issue with impact into UIResponsewriter

### ISSUE THREAD

**Issue by WernerMairl** [Xabaril/AspNetCore.Diagnostics.HealthChecks#23]
the  class MaximumValueHealthCheck<T> has the wfollowing property 
```

        private readonly T maximunValue;`
```

the wording should be fixed here and in some other place
maximunValue => maximumValue 

impact using UIResponseWriter and MemoryHealthCheck:

"virtualmemory":{"data":{},"description":"Maximu**n**=2147483648, Current=.....

regards 
Werner

**Comment by CarlosLanderas** [comment]
Thanks for reporting @WernerMairl. The Systeem healthcheck had some "maximun" word typos. They have been all fixed here:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/commit/314c963d9f137faa946415d7f50b9b38cb5f14e8

Package version 2.0.1 is being published.
