### ISSUE TITLE
Warning about securiy vulnerabilities

### ISSUE THREAD

**Issue by pekspro** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2317]
If I create a new ASP.NET project and add a reference to `AspNetCore.HealthChecks.UI`, I'll now get these warnings in Visual Studio 17.12:

```text
Package 'Microsoft.Extensions.Caching.Memory' 8.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-qj66-m88j-hmgj
Package 'System.Text.Json' 8.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-8g4q-xg66-9fp4
```

I can workaround this by adding never versions of these packages, but would be nice if these where referenced by default.

**Comment by Alirexaa** [comment]
Close as complete by #2327
