### ISSUE TITLE
Upgrade RabbitMQ.Client to v7

### ISSUE THREAD

**Issue by lechu445** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2319]
**What would you like to be added**:
To upgrade HealthChecks.RabbitMQ from v6 to v7.

**Why is this needed**:
Because v7 has lots of API changes in compare to v6, HealthChecks.RabbitMQ blocks users from upgrade the RabbitMQ client in their apps.

**More info**
- Release notes: https://github.com/rabbitmq/rabbitmq-dotnet-client/releases/tag/v7.0.0
- Migration guide: https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/main/v7-MIGRATION.md
- Discussion topic about migration: https://github.com/rabbitmq/rabbitmq-dotnet-client/discussions/1720

**Comment by czinegeroland** [comment]
It is mandatory to work with MassTransit 8.3.2. It is already using v7. https://masstransit.io/support/upgrade#version-832

**Comment by eerhardt** [comment]
[Add support for RabbitMQ.Client version 7. (Xabaril/AspNetCore.Diagnostics.HealthChecks#2323)](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/2323) adds support for version 7.

The strategy we are taking is to support both version 6 (with the existing package) and add a new package to support version 7. At 
a later date (probably on the next major release) we can swap the dependencies. See the PR for more detail on the plan.
