### ISSUE TITLE
HealthChecks.EventStore.EventStoreHealthCheck expects URI and not connection string

### ISSUE THREAD

**Issue by MuadDib** [Xabaril/AspNetCore.Diagnostics.HealthChecks#232]
EventStore module says it expects connection string as first parameter. While it actually expects URI to EventStore.
Test passes:
> "tcp://localhost:1113"

Test fails:
> "ConnectTo=tcp://admin:changeit@localhost:1113; HeartBeatTimeout=500"

In code you can see that it's used as URI and not connection string (HealthChecks.EventStore.EventStoreHealthCheck:27).

Have made separate (local) branch and created new extension that uses connection string. If you would like I can make a pull request for it.

Best,
Igor

**Comment by MuadDib** [comment]
Anyone?

**Comment by unaizorrilla** [comment]
Hi @MuadDib 

A PR is welcome!

**Comment by MuadDib** [comment]
#242

**Comment by sungam3r** [comment]
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/242#issuecomment-1306183172
