### ISSUE TITLE
HealthChecks.DocumentDb

### ISSUE THREAD

**Issue by adamsitnik** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2325]
HealthChecks.DocumentDb relies on deprecated Microsoft.Azure.DocumentDB.Core

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/0b1b657dac590cab673787cb3c8bd282388c4574/src/HealthChecks.DocumentDb/HealthChecks.DocumentDb.csproj#L12

From https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.Core:

> Please note, this package is obsolete as of 3/31/2023 and is no longer maintained or monitored. Microsoft encourages you to upgrade to the replacement package, Microsoft.Azure.Cosmos, to continue receiving updates.

We already provide a package that uses the recommended package:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/tree/master/src/HealthChecks.CosmosDb

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/0b1b657dac590cab673787cb3c8bd282388c4574/src/HealthChecks.CosmosDb/HealthChecks.CosmosDb.csproj#L11

I believe that we should also deprecate [HealthChecks.DocumentDb](https://www.nuget.org/packages/AspNetCore.HealthChecks.DocumentDb/) and remove the source code from the repo.

@eerhardt @unaizorrilla thoughts?

**Comment by eerhardt** [comment]
Sounds good to me.
