### ISSUE TITLE
The type 'MySqlConnectionStringBuilder' exists in both 'MySql.Data, Version=8.0.16.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d' and 'MySqlConnector, Version=0.40.4.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92'

### ISSUE THREAD

**Issue by khteh** [Xabaril/AspNetCore.Diagnostics.HealthChecks#234]
Bump into this build error when MySql assembly is included.
```
The type 'MySqlConnectionStringBuilder' exists in both 'MySql.Data, Version=8.0.16.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d' and 'MySqlConnector, Version=0.40.4.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92'
```

**Comment by AmirSasson** [comment]
Experiencing the same. did you find a solution? @khteh ?

**Comment by unaizorrilla** [comment]
Well,

I'm not a expert guy with MySql (this is a contribution healthcheck), is Mysql.Data the recommended data access library?

Can you add global:[namespace] to spcify valid type in your code?

**Comment by khteh** [comment]
`MySqlConnectionStringBuilder` was and old code from my legacy application. I remove that and use connection string defined in <foo>.json

**Comment by bgrainger** [comment]
> is there any reason not to use the MySql.Data assembly?

It doesn't support async operations properly (https://bugs.mysql.com/bug.php?id=70111) but the code uses `Async`: https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/1b8597151d19d4eaba0780cd4f4aa5920088ec45/src/HealthChecks.MySql/MySqlHealthCheck.cs#L23-L25

It was changed here: https://github.com/Xabaril/BeatPulse/issues/47

You should avoid using the `MySql.Data` NuGet package and just use the `MySqlConnector` NuGet package: https://www.nuget.org/packages/MySqlConnector/

**Comment by udlose** [comment]
@bgrainger 
> It doesn't support async operations properly (https://bugs.mysql.com/bug.php?id=70111) but the code uses `Async`:

The bug you reference was from 2013 in version 6.7.4.0. The latest version of MySql.Data is 8.0.19 and updated as recently as 1/13/2020

> You should avoid using the `MySql.Data` NuGet package and just use the `MySqlConnector` NuGet package: https://www.nuget.org/packages/MySqlConnector/

`MySqlConnector` is a 3rd party nuget package that is not distributed from Oracle.  I think using the  Nuget package that is actually issued by the vendor makes much more sense as it is officially supported.

**Comment by bgrainger** [comment]
> The bug you reference was from 2013 in version 6.7.4.0.

Correct, and it still hasn't been fixed 6½ years later. (The bug's status is "Verified" and it's trivial to write an example program that demonstrates the problem.)

> I think using the Nuget package that is actually issued by the vendor makes much more sense as it is officially supported.

I strongly disagree:

* Performance. A health check that's run frequently should have low overhead. MySqlConnector is superior in this regard: https://github.com/mysql-net/MySqlConnector#performance
* Reliability: Besides the async bug, there are numerous open bugs in MySql.Data that are fixed in MySqlConnector: https://mysqlconnector.net/tutorials/migrating-from-connector-net/#fixed-bugs
* License: MySql.Data [is GPL](https://downloads.mysql.com/docs/licenses/connector-net-8.0-gpl-en.pdf) and [according to GNU](https://www.gnu.org/licenses/gpl-faq.html#GPLStaticVsDynamic), dynamically linking with it would make this a combined work that also needs to be GPL. MySqlConnector is MIT.

**Comment by udlose** [comment]
@bgrainger  I stand corrected. I naively assumed that after 6.5 yrs, the MySql devs from Oracle would've come into the year 2000 and correctly implement async I/O in their nuget package.  How disappointing.

I am a consultant for a large Fortune 50 company who is very selective about the authors of a nuget package they decide to select.  Hence, my _general_ preference to opt for a nuget from a well-known author/Enterprise over another by a lesser-known author (no offense intended :) ).  Obviously, in this case, Oracle has failed to come to task.

**Comment by bgrainger** [comment]
Unfortunately, Connector/NET seems to have been on life-support for many years, with very little attention paid to the classic (i.e., not "X Protocol") part of the library; there are signs that this might be changing in the last couple of [8.0.x point releases](https://dev.mysql.com/doc/relnotes/connector-net/en/news-8-0.html), but still many bugs go without an update for years. (That was one of the driving factors behind creating an alternative.)

> Hence, my general preference to opt for a nuget from a well-known author/Enterprise

Completely understandable. (I would do the same.)

> lesser-known author (no offense intended :) )

None taken. 😀
