### ISSUE TITLE
Elasticsearch healthcheck failing due to type load error

### ISSUE THREAD

**Issue by raphaabreu** [Xabaril/AspNetCore.Diagnostics.HealthChecks#235]
Hello,

I am trying to use the Elasticsearch healthcheck plugin on a new asp.net core project and I am facing this issue:

`fail: Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService[104]
      Health check elasticsearch threw an unhandled exception after 14.888ms
System.TypeLoadException: Could not load type 'Nest.IPingResponse' from assembly 'Nest, Version=7.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d'.
   at HealthChecks.Elasticsearch.ElasticsearchHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken)
   at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.CheckHealthAsync(Func`2 predicate, CancellationToken cancellationToken)
`

My project has another dependency that is using the version 7.0.1 of the Nest project. I attempted to downgrade the other project to 7.0.0 to no avail.

Is there a work around?

Thanks!

**Comment by lurumad** [comment]
Hi @raphaabreu 

Thank you so much for your feeadback! I've created a PR in order to fix this problem. We think is related with some breaking change between NEST 6.1.0 (Current version in Elasticsearch health check).

I've updated lo 7.1.0.

Regards!

**Comment by unaizorrilla** [comment]
Hi @raphaabreu @lurumad 

PR is approved and release build is running now on appveyor, when finish a new package 2.2.3 will be on NuGet for ElasticSearch with 7.1.0 dependency.

@raphaabreu  can you close this issue if all is working now?

**Comment by unaizorrilla** [comment]
I close this because we don't have any response!

**Comment by raphaabreu** [comment]
@unaizorrilla / @lurumad  I am truly sorry for not providing a feedback earlier. The fix solved the issue I was facing and I am very grateful for the prompt response. I am looking forward to contributing to this project! Thank you!

**Comment by SonyLuz** [comment]
Hello, I am facing this problem, using version 7.4.1 of the Nest project. I tried to downgrade the other project to 7.0.0 without success.

Is there a work around?
