### ISSUE TITLE
Enable Health Check Release Gate to execute as a task

### ISSUE THREAD

**Issue by carlowahlstedt** [Xabaril/AspNetCore.Diagnostics.HealthChecks#237]
I setup a health check release gate to execute as a post deployment gate and it started failing. I eventually realized that the url I was trying to hit isn't public and therefore because the gate doesn't run on my on-prem agent that it's not going to succeed. I'd like to suggest enabling the task to be able to run as a task inside of a pipeline. If you agree this is a good idea, I'm willing to look at what we need to do. I've got some experience building tasks.

**Comment by CarlosLanderas** [comment]
Ping @lfraile

**Comment by lfraile** [comment]
Sorry I didn't read this before. 

Seems reasonable. All the code is in the repo so if you want to take a look go ahead. Let me know if you need help. We can do a remote coding session if needed.

**Comment by sungam3r** [comment]
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/291#issuecomment-1050354157
