### ISSUE TITLE
Port 80 or 30000 or 5000?

### ISSUE THREAD

**Issue by khteh** [Xabaril/AspNetCore.Diagnostics.HealthChecks#238]
You use port 80 in your pod spec but 30000 or 5000 in your `curl` command. This is confusing. Which is which?

**Comment by CarlosLanderas** [comment]
You do not offer much information but I guess you are talking about kubernetes.

Port 5000 is just the port we use during the tutorial to test our application. When we launch it with dotnet or vs. 

Then,  when working with k8s,  port 80 is the internal pod port and 30000 is the external pod node port.

**Comment by khteh** [comment]
Yes, I am referring to k8s. Which port does kestrel listen on in this case? I assume 80? Thanks.
