### ISSUE TITLE
Add Datadog publisher

### ISSUE THREAD

**Issue by rpopovych** [Xabaril/AspNetCore.Diagnostics.HealthChecks#239]
Datadog is a popular metrics and event aggregator that is often used to help operate and maintain your infrastructure. One of its features is service checks, which is very similar to health checks. I would like to add a publisher that pushes the health check results into Datadog as custom service checks.

Datadog Service Checks: https://docs.datadoghq.com/monitors/guide/visualize-your-service-check-in-the-datadog-ui/#pagetitle

**Comment by rpopovych** [comment]
I will make a PR shortly with the implementation.

**Comment by unaizorrilla** [comment]
Thanks @rpopovych 

The PR is on review, please, try to address the feedback!

Thanks for contribute!

**Comment by renatogbp** [comment]
Hi,

I have being trying to use the DataDog publisher, but it isn't publishing any metrics to datadog. 
This is my Setup:
```
var hcBuilder = services.AddHealthChecks();
hcBuilder.AddDatadogPublisher("serviceName.healthchecks");
```
Can someone add tests to make sure this is working, please?

I have been using DataDog for other metrics and that's how I configure:
```
public static void Configure(string serverName = null, int? port = null, string prefix = null)
{
	var dogstatsdConfig = new StatsdConfig();

	if (!string.IsNullOrWhiteSpace(serverName))
	{
		dogstatsdConfig.StatsdServerName = serverName;
	}

	if (port.HasValue)
	{
		dogstatsdConfig.StatsdPort = port.Value;
	}

	if (!string.IsNullOrWhiteSpace(prefix))
	{
		dogstatsdConfig.Prefix = prefix;
	}

	DogStatsd.Configure(dogstatsdConfig);
}
```

**Comment by rpopovych** [comment]
Sorry, I missed this message. The extension method configures it's own Datadog service internally, and currently exposes a parameter to configure the Datadog agent name.

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/5dde843c51c7a4b6778c444adae6a95527f58068/src/HealthChecks.Publisher.Datadog/DependencyInjection/DatadogHealthCheckBuilderExtensions.cs#L18

Using the `IDogStatsd` interface allows us to test more easily. I left a question on the PR about the correct place for the publisher tests, but did not get a response: https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/240#discussion_r306427500

In your example, you're configuring the static singleton Datadog instance, which this publisher does not use. If you pass in the server name into the DI extension method, and your agent is in the default port, you should see it work. If you need to customize the port or prefix, I will gladly expose an override that takes in a `StatsdConfig`.

**Comment by renatogbp** [comment]
Thank you @rpopovych, it works now!
Can I give a suggestion? Would be possible to add a try catch around DogStatsd.Configure ?
Sometimes I need to deploy to a test server where I don't have datadog running. With the current code, it keeps throwing exceptions because cannot resolve the container name

**Comment by IlSocio** [comment]
> Sorry, I missed this message. The extension method configures it's own Datadog service internally, and currently exposes a parameter to configure the Datadog agent name.
> 
> https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/5dde843c51c7a4b6778c444adae6a95527f58068/src/HealthChecks.Publisher.Datadog/DependencyInjection/DatadogHealthCheckBuilderExtensions.cs#L18
> 
> Using the `IDogStatsd` interface allows us to test more easily. I left a question on the PR about the correct place for the publisher tests, but did not get a response: [#240 (comment)](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/240#discussion_r306427500)
> 
> In your example, you're configuring the static singleton Datadog instance, which this publisher does not use. If you pass in the server name into the DI extension method, and your agent is in the default port, you should see it work. If you need to customize the port or prefix, I will gladly expose an override that takes in a `StatsdConfig`.

hi @rpopovych,
I just tried to use this package, but I need to customize other parameters of the StatsdConfig, could you expose that override that you were mentioning?

thanks!!!
