### ISSUE TITLE
HealthChecks.Uris ExpectContent PR

### ISSUE THREAD

**Issue by benmccallum** [Xabaril/AspNetCore.Diagnostics.HealthChecks#245]
Hi, thx for all this different health checks. Great library.

We've got a microservices kinda architecture, and we're currently looking at weaving in health checks, but one thing that's complicated is you've really got a web of interconnected services. The only really easy way to track health in a particular service is to just focus on its immediate dependencies' health and not worry about transitive dependencies. 

So for dependency tree like Service A >> Service B >> Service C:
* Service A should only care about health of its internals and Service B. 
* Service B should only care about health of its internals and Service C.
* Service A shouldn't worry about Service C unless it becomes a direct dependency; but Service B if unhealthy because of Service C will "bubble up" to A.

An immediate dependency in our case (if it's another microservice) is always going to have a /health check url configured, so I figured if that service is taking care of its dependencies and reporting their aggregate at /health, then the consumer can do a health check to that.

To facilitate this, we need to have the Uris Health Check support checking not just the status code (as [according to docs 200 is also returned for Degraded status](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-3.0#customize-the-http-status-code)) but also look for an expected response value so we could check for [the string value of HealthReport.Status](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-3.0#customize-output).

Would be happy to accept a PR for that? Could support a check for a straight raw string value and another that maybe accepts a `Func` to receive a more complex check.

**Comment by benmccallum** [comment]
I've got something whipped up so lemme know and I'll do a PR for it.

**Comment by sungam3r** [comment]
resolved in #1199
