### ISSUE TITLE
AzureServiceBusTopicHealthCheck + Partitioning

### ISSUE THREAD

**Issue by mattmelton** [Xabaril/AspNetCore.Diagnostics.HealthChecks#248]
Adding a message with the following will fail if the Topic is partitioned:

```
var scheduledMessageId = await topicClient.ScheduleMessageAsync(
    new Message(Encoding.UTF8.GetBytes(TEST_MESSAGE)),
    new DateTimeOffset(DateTime.UtcNow).AddHours(2));
```

The documentation [prescribes several methods of resolving a partition key](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-partitioning#using-a-partition-key) depending on the configuration.

I would suggest a configuration callback func/delegate. For example:

```
services.AddHealthChecks()
	.AddAzureServiceBusTopic("Endpoint=sb://unaidemo.servicebus.windows.net/;SharedAccessKeyName=policy;SharedAccessKey=AQhdhXwnkzDO4Os0abQV7f/kB6esTfz2eFERMYKMsKk=", "to1", partitionKey: () => Guid.NewGuid().ToString());
```

**Comment by mattmelton** [comment]
FWIW we can't use the Azure Service Bus checks in our production env (which is partitioned) until a partition key or message id is set

**Comment by Kiechlus** [comment]
Having the same problem, when I use partitioned queues with duplicate detection enabled: 
`"exception":"Batching brokered messages with distinct SessionId, PartitionKey, or MessageId  is not supported for an entity with partitioning and duplicate detection enabled.LogicalPartitionId:250::PartitionKey:::SessionId:::MessageId:aa371440ad2f4f9f86a2877f5b1f4fe4::ViaPartitionKey::: Reference:955d3fa5-e52a-4c1c-8dc5-a0e86bfc55e4, TrackingId:e31865af-72d6-4c4d-8e19-415b1bb433bf_B7`

**Comment by unaizorrilla** [comment]
Hi guys!

I’m on vacation but in a few days I try to check this issue

**Comment by unaizorrilla** [comment]
Hi @mattmelton  @Kiechlus 

A new version is on release build, When finished 2.2.5 will be on NuGet for Azure Service Bus, with this version you can set a Action<Message> when register the healtcheck in order to configure any property ( MessageId, PartitionKey etc )

Thanks to @mattmelton to contribute this!
