### ISSUE TITLE
[Question] Should Service Bus Healthchecks use a singleton QueueClient?

### ISSUE THREAD

**Issue by dantheman999301** [Xabaril/AspNetCore.Diagnostics.HealthChecks#25]
My (somewhat limited!) understanding is that for a Service Bus `QueueClient` for a particular queue should be a Singleton across an application.

https://github.com/Azure/azure-service-bus-dotnet/issues/130

Now this issue is quite old now and I know there was some larger changes for ServiceBus in 3.X.X but I think this still applies as "best practice".

Currently the Healthchecks create a new client per check for ServiceBus. Should the interface instead be passed a QueueClient to use continously or create one for it's own uses instead?

**Comment by unaizorrilla** [comment]
thanks @dantheman999301

True, I fix the same "issue" on redis health check, Labeled as "Help wanted if you want to fix it", if not I try to fix it ASAP

**Comment by unaizorrilla** [comment]
Well, two options can be a good idea, you need to support taht  users can registered multiple times a healthcheck for different queue client.

**Comment by dantheman999301** [comment]
Another quick question, is there any reason that `Microsoft.Azure.ServiceBus` is still on version is on 2.0.0? Would it be a problem if upgraded it?

**Comment by unaizorrilla** [comment]
Closed by #39
