### ISSUE TITLE
AddUrlGroup - show urls in data

### ISSUE THREAD

**Issue by inech** [Xabaril/AspNetCore.Diagnostics.HealthChecks#250]
Hi! We're migrating a project from deprecated Microsoft health checks ([Microsoft.Extensions.HealthChecks](https://github.com/dotnet-architecture/HealthChecks)) to new Microsoft.Extensions.Diagnostics.HealthChecks and we've decided to use your cool project :)

The deprecated `.AddUrlCheck(...)` contained `data` with url and status code of the response:
```csharp
public static async ValueTask<IHealthCheckResult> DefaultUrlCheck(HttpResponseMessage response)
        {
            var status = response.IsSuccessStatusCode ? CheckStatus.Healthy : CheckStatus.Unhealthy;
            var data = new Dictionary<string, object>
            {
                { "url", response.RequestMessage.RequestUri.ToString() },
                { "status", (int)response.StatusCode },
                { "reason", response.ReasonPhrase },
                { "body", await response.Content?.ReadAsStringAsync() }
            };
            return HealthCheckResult.FromStatus(status, $"status code {response.StatusCode} ({(int)response.StatusCode})", data);
        }
```
([link](https://github.com/dotnet-architecture/HealthChecks/blob/dev/src/Microsoft.Extensions.HealthChecks/Internal/UrlChecker.cs#L55))
which was useful to quickly figure out why health check fails.

Now with `.AddUrlGroup(...)` the `data` dictionary is empty and there is no easy way to see against which urls the check was performed and what was the status code.

What do you think about including "urls" and "status codes" to the "data"? If you like it, I can submit a PR.

**Comment by unaizorrilla** [comment]
PR is welcome
