### ISSUE TITLE
Azureservicebus checks is going crazy ... 

### ISSUE THREAD

**Issue by hugoterelle** [Xabaril/AspNetCore.Diagnostics.HealthChecks#253]
We have an issue in our production environment thanks to Healthchecks servicebus.  
How can we cancel all these messages?

![image](https://user-images.githubusercontent.com/2490657/62899255-adf79880-bd57-11e9-9605-66733a6f047f.png)

**Comment by unaizorrilla** [comment]
O try to review this healthcheck tomorrow and share with you more info!

**Comment by inicolay** [comment]
we are seeing this issue as well

**Comment by unaizorrilla** [comment]
I try to check this asap! Is so curios because the healtcheck is scheduling and cancel the message. I need check if some is broken or is a ‘permission ‘ issue in the client side.

Can you see any error on log message from helathcheck Code?

**Comment by unaizorrilla** [comment]
> 
> 
> We have an issue in our production environment thanks to Healthchecks servicebus.
> How can we cancel all these messages?
> 
> ![image](https://user-images.githubusercontent.com/2490657/62899255-adf79880-bd57-11e9-9605-66733a6f047f.png)

Is queue or topic health check?

**Comment by unaizorrilla** [comment]
Hi @hugoterelle @inicolay 

I debug AzureServiecBusTopicHealthCheck and is working fine on my side! I try to change the policy to use only send permission and also is working fine.

Can you create a repro that I can validate with my own topic service?

```
var scheduledMessageId = await topicClient.ScheduleMessageAsync(
                    new Message(Encoding.UTF8.GetBytes(TEST_MESSAGE)),
                    new DateTimeOffset(DateTime.UtcNow).AddHours(2));

await topicClient.CancelScheduledMessageAsync(scheduledMessageId);
```

This healtcheck create a scheduler message and cancel it, if you see many scheduled message this is because cancelation is not working? Are you see any exception/error message in your log?

**Comment by mattmelton** [comment]
@hugoterelle - try Service Bus Explorer: https://github.com/paolosalvatori/ServiceBusExplorer

I think there are a couple of issues with the code:

- RetryPolicy.NoRetry won't retry cancellation calls
- Cancelling ought to be a 'best-efforts' approach, i.e. a try-catch-finally with attemps in both the try and finally blocks
- CheckHealthAsync should throttle - currently the Azure code catches and swallows. Ideally the catch will apply backoff pressure or a hard stop after X failures in N seconds. I'd look into exponential backoff strategies with Transient Fault Handling/Polly etc.

**Comment by hugoterelle** [comment]
@mattmelton I tried Servicebus explorer and I also wrote some code to cancel the scheduled messages.  But without the "sequence number", I cannot cancel any message (this is a long value, I cannot try all possible values)

@unaizorrilla It is a queue.

Here is the code we use: 

```
       if (_env.IsProduction())
            {
                IHealthChecksBuilder healthCheck = services.AddHealthChecks();

                healthCheck.AddCheck("Database", new SqlConnectionHealthCheck(Configuration["DatabaseConnection"]))
                  .AddAzureServiceBusQueue(Configuration["ServicebusApi:Connection"], QueueNamingHelper.GetQueueName(Configuration["ServicebusApi:Queue"]))
                  .AddAzureBlobStorage(Configuration["DocumentStorage:Connection"])
                  .AddElasticsearch(Configuration["Elasticsearch:Nodes"]);
                services.AddHealthChecksUI();
            }
```

And here is the error we found in our logs before finding the problem in the queue:

**Health check "azurequeue" completed after 20015.7412ms with status Unhealthy and 'null'**

**Comment by unaizorrilla** [comment]
I try queues and topics yesterday and works fine! Is a regular queue? Partioned?duplication detection?

**Comment by hugoterelle** [comment]
Yes, this queue is partitionned.

![image](https://user-images.githubusercontent.com/2490657/62927748-78829780-bdb7-11e9-9b38-20a33e654f9d.png)

**Comment by unaizorrilla** [comment]
Can you try latest version? (Published yesterday) 2.2.5

**Comment by hugoterelle** [comment]
The problem is not in development.  It happened in our production environment while (maybe) servicebus was having a connection issue.  

We cannot test on demand as we need to publish a new version in production.  Before publishing a new version, it has to be tested, validated, etc.

Moreover, the problem only happened once (we use your library since 2 months).

Our concern right now is to cleanup more than 3600 messages that were created by your library :)

**Comment by unaizorrilla** [comment]
Well,
1. Is so curious your queue is partitioned and healthcheck is working because this feature only work with 2.2.5 after a @mattmelton PR that I merge yesterday.
2. By default scheduled messages is with a 2 hours time, after this 2 hours this messages are moved from scheduled to active messages and you can delete it using 360 tool, sdk etc. You can filter this message inspecting the body with content  "HealthCheckTest"

thanks
Unai

**Comment by hugoterelle** [comment]
@unaizorrilla These messages are present since 2-3 days as "scheduled" and we are not able to delete them using sdk, tools, etc.

**Comment by unaizorrilla** [comment]
No sense! The scheduling is for 2 hours by default! I check the code this morning and after this time message are moved to active Status

**Comment by hugoterelle** [comment]
And why @inicolay is facing the same issue?

**Comment by unaizorrilla** [comment]
Hi @hugoterelle 

Sorry, I try to help!! I try to do the same scenario but in my side is work fine. I schedule message a without cancel and after the specified time messages are active!

If i can do something more, please let me know!

**Comment by unaizorrilla** [comment]
I close the issue because we don't have more feedback or actions! Feel free to Re-Open
