### ISSUE TITLE
Typo in configuration example for "EvaluationTimeOnSeconds"

### ISSUE THREAD

**Issue by Flouss** [Xabaril/AspNetCore.Diagnostics.HealthChecks#254]
Current:
`{
  ...
    "EvaluationTimeOnSeconds": 10,
    ...
 }`
Should be:
`{
  ...
    "EvaluationTimeInSeconds": 10,
    ...
 }`

**Comment by CarlosLanderas** [comment]
Hello @Flouss , this issue has already been opened in the past. We will change it when shipping the next major version for .net core 3.0 because this breaking change affects all appsettings.json running health checks nowadays.

Thanks for reporting!.
