### ISSUE TITLE
Batching brokered messages is not supported for an entity with partitioning and duplicate detection

### ISSUE THREAD

**Issue by Kiechlus** [Xabaril/AspNetCore.Diagnostics.HealthChecks#255]
We always used queues with partitioning enabled. When we additionally turned on duplication detection, health tests fail with the following error: 

`{"status":"Unhealthy","description":null,"exception":"Batching brokered messages with distinct SessionId, PartitionKey, or MessageId  is not supported for an entity with partitioning and duplicate detection enabled.LogicalPartitionId:206::PartitionKey:::SessionId:::MessageId:7301261e16c847a19193ae6d227d5d58::ViaPartitionKey::: Reference:a6c69e87-7599-44bf-a832-5246e9d45b64, TrackingId:375ad65f-1979-4c3d-8ccb-bc9125b50e48_B14, SystemTracker:d15-rhs-servicebus:queue:patientscan-assignments~95, Timestamp:2019-08-16T12:07:37"}`

I thought this would be fixed 
 in https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/248.

But after switching to 2.2.5, the issue is still there.

**Comment by unaizorrilla** [comment]
Hi @Kiechlus 

With 2.2.5 registration method you have a configuringMessage action to setup your sessionid, partitionKey and other properties.

**Comment by Kiechlus** [comment]
Ok thanks, it worked by adding a partition key: `configuringMessage => configuringMessage.PartitionKey = "123"`

**Comment by Kiechlus** [comment]
@unaizorrilla This feature was removed ini `v3.2.2`. Latest working was `v3.1.1`. Is this breaking change intended? If yes, does the problem described above not exist anymore in > `3.2.2`?

**Comment by unaizorrilla** [comment]
Hi @Kiechlus 

Yeap, on 3.2.2 we don't need to send scheduled messages o check the availability of Topic / Queue, we use ManagementClient instead of. For this reason we don't need anymore availability to manage partitioning, session etc.
