### ISSUE TITLE
Can UseHttpMessageHandler accept a Func < IServiceProvider, HttpMessageHandler>?

### ISSUE THREAD

**Issue by saber-wang** [Xabaril/AspNetCore.Diagnostics.HealthChecks#256]
The "Cannot access a disposed object. Object name:'Sockets HttpHandler'" error will occur when passing an instance.The problem is caused because a single HttpClientHandler instance is used for all requests. It's the HttpClientFactory's job to manage, pool and recycle handlers.
https://stackoverflow.com/questions/54256792/net-core-httpclientfactory-dispose-httpclienthandler

**Comment by CarlosLanderas** [comment]
You are absolutely right. It is being used in with a named client but this should be a factory.

**Comment by saber-wang** [comment]
@CarlosLanderas Are there plans to support NetCore 3.0??

**Comment by CarlosLanderas** [comment]
@saber-wang , yes of course :)

**Comment by CarlosLanderas** [comment]
UI Version 2.2.33 is being published. You have a usage sample here:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/test/FunctionalTests/HealthChecks.UI/Configuration/UIConfigurationTests.cs#L171-L190

**Comment by saber-wang** [comment]
@CarlosLanderas  Good:)

**Comment by CarlosLanderas** [comment]
@saber-wang  is working for you?

**Comment by saber-wang** [comment]
@CarlosLanderas I work in NetCode 3.0 and currently do not support it, so I use my own compiled version. I see that the source code is consistent with my modification, and it's working very well at present.
