### ISSUE TITLE
HealthCecks-UI Webhook section

### ISSUE THREAD

**Issue by Zetanova** [Xabaril/AspNetCore.Diagnostics.HealthChecks#259]
The UI section "Webhooks" has low value and is leeking secrets from the Url or Payload.
Most of the destination require some kind of ApiKey in the Url or in the Payload

It would be better just to display the name, lastUsage, lastResultStatus and lastResultMessage(error message). 
Then it would have some diagnostic purpose.

**Comment by CarlosLanderas** [comment]
Related to #204 

I think we are going to show just the webhook name, that should identify the service, or maybe we can just strip out the querystring and keep the url host

**Comment by CarlosLanderas** [comment]
Version 3.0.3 won't display the whole webhook uri anymore, it will display the host instead.
