### ISSUE TITLE
Docker Container - EvaluationTimeOnSeconds

### ISSUE THREAD

**Issue by twurm** [Xabaril/AspNetCore.Diagnostics.HealthChecks#260]
There doesn't appear to be a way to override the EvaluationTimeOnSeconds when using docker images.  We tried setting: -e 'HealthChecksUI:EvaluationTimeOnSeconds=60' but the requests still seem to occur every 10 seconds.  

Docker Image: xabarilcoding/healthchecksui:latest

**Comment by sevansoft** [comment]
Try EvaluationTimeInSeconds, I think there is a discrepancy between some of the samples/the documentation and the implementation

**Comment by CarlosLanderas** [comment]
Yes. The property has a typo. We are gonna fix it in 3.0 because it is a breaking change.

As @sevansoft points is InSeconds:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.UI/Configuration/Settings.cs

**Comment by CarlosLanderas** [comment]
Related #254
