### ISSUE TITLE
How to Control AddApplicationInsightsPublisher interval?

### ISSUE THREAD

**Issue by sevansoft** [Xabaril/AspNetCore.Diagnostics.HealthChecks#262]
When using 
`services.AddHealthChecks().AddApplicationInsightsPublisher();` 

I am seeing customEvents items entered into the associated Application Insights Logs every 30 seconds. What settings are involved in this internal and can they be overridden?

**Comment by unaizorrilla** [comment]
Hi @sevansoft 

You can configure your TelemetryChannel on AI

https://docs.microsoft.com/en-us/azure/azure-monitor/app/telemetry-channels
https://docs.microsoft.com/es-es/azure/azure-monitor/app/telemetry-channels#configuration-in-code-for-aspnet-core-applications
