### ISSUE TITLE
K8S Error discovering service <servicename>. It might not be visible

### ISSUE THREAD

**Issue by cilerler** [Xabaril/AspNetCore.Diagnostics.HealthChecks#267]
_Possible duplicate of https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/113_

When I try to use Kubernetes discovery, it identifies the services which have `HealthChecks: "true"` in the label but throws the error below.

```
[41m[30mfail[39m[22m[49m: HealthChecks.UI.Core.Discovery.K8S.KubernetesDiscoveryHostedService[0]
      Error discovering service <servicename1>. It might not be visible
[41m[30mfail[39m[22m[49m: HealthChecks.UI.Core.Discovery.K8S.KubernetesDiscoveryHostedService[0]
      Error discovering service <servicename2>. It might not be visible
```

**Comment by unaizorrilla** [comment]
Hi @CarlosLanderas 

Can you check this?

**Comment by solacens** [comment]
Same problem here. Is it related to the fact that only HTTPS port is opened for the service to be discovered?

**Comment by cilerler** [comment]
@CarlosLanderas I appreciate if you may spare your time on this 🤗

**Comment by CarlosLanderas** [comment]
Please, check the latest version of the docs regarding the Kubernetes service discovery. New options have been added and the support for ipv4/ipv4 and customizable scheme has been added.

A new Kubernetes Operator has been created as well, I will upload the documentartion soon :)
