### ISSUE TITLE
Health Check driven from non-JSON response

### ISSUE THREAD

**Issue by NxSoftware** [Xabaril/AspNetCore.Diagnostics.HealthChecks#268]
Is it possible to configure the Health Check UI to look for a 200 OK response rather than attempting to parse the JSON response?

For example we have several services configured with Health Checks and returning the expected JSON response. We also have another service that is written by an external team and doesn't expose a health check API, however it does have a simple idempotent GET endpoint that could be used to indicate whether / not the service can be accessed.

Example configuration could be something like:

```
{
  "HealthChecksUI": {
    "HealthChecks": [
      {
        "Name": "HTTP-Api-Basic-1",
        "Uri": "http://localhost:6457/healthz"
      },
      {
        "Name": "HTTP-Api-Basic-2",
        "Uri": "http://localhost:7890/healthz"
      },
      {
        "Name": "HTTP-Api-Basic-3",
        "Uri": "http://localhost:8901/some-get-endpoint",
        "IgnoreBody": true
      }, 
    ],
    ...
}
```

**Comment by NxSoftware** [comment]
I guess, at least for now, I could add a custom [Uri HealthCheck](https://www.nuget.org/packages/AspNetCore.HealthChecks.Uris/) to the service running the Health Checks UI then configure the UI to point to itself.

**Comment by CarlosLanderas** [comment]
Hello @NxSoftware, yes the UI is designed to use the UI.Client so the best idea is using a Uri HealthCheck to have a successful status.

There are no plans to supports raw status codes in the UI
