### ISSUE TITLE
KubernetesHttpClientExtensions stop collecting if an endpoint returns an empty response

### ISSUE THREAD

**Issue by Zoon-bori** [Xabaril/AspNetCore.Diagnostics.HealthChecks#269]
Hi Team,

When I add two "uri" in the appsettings.json file as below, it returns below null reference error notification.
    "uri": [
      {
        "name": "Site A",
        "value": "https://www.SiteA.com/"
      },
      {
        "name": "Site B",
        "value": "https://www.SiteB.com/"
      }

-Error Notification------------------------------------------------------------------------------------
The HealthCheck (Any site) is failing with the error message: There are at least 1 HealthChecks failing. Response is null or message can't be deserialized as HealthChecks.UI.Client.UIHealthReport.
----------------------------------------------------------------------------------------------------

I checked the source code, and In the KubernetesHttpClientExtensions class, the GetServices method uses the As extension method to deserialize an UIHealthReport.

This will use the NewtonSoft JsonConvert.DeserializeObject that return a null object if content is empty. Which leads to an unhandled NullReferenceException that stop the Collect loop.

I also found similar error Issue report here and it was fixed/corrected.
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/1394659f49a2bf5105c9152d24b10cfa5f6f8c06/src/HealthChecks.UI/Core/Extensions/HttpResponseMessageExtensions.cs

Please check this and correct it if this is the same case of previous resolved issue.

Thanks for your support in advance.

**Comment by Zoon-bori** [comment]
wrong path.

**Comment by Zoon-bori** [comment]
Hi @unaizorrilla
Please help check this if this is the same issue here.
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/92

Thanks for your support in advance.

**Comment by unaizorrilla** [comment]
Hi @CarlosLanderas 

Can you check this?

**Comment by CarlosLanderas** [comment]
This has been fixed with the latest UI version. Now returned services are checked.
