### ISSUE TITLE
Allow scraping Prometheus metrics instead of pushing

### ISSUE THREAD

**Issue by jnovick** [Xabaril/AspNetCore.Diagnostics.HealthChecks#271]
If applications already have Prometheus metrics, it would be nice to be able to just add health check metrics in instead of pushing them. Where I work, we run our application in Kubernetes and federate our Prometheus servers between environments. We scrape automatically in Kubernetes. We don't like to use the push pattern, we prefer Prometheus scrape at a regular interval. This is also the recommended patter from Prometheus: https://prometheus.io/docs/introduction/faq/#why-do-you-pull-rather-than-push

**Comment by Daniel15** [comment]
I'd also like to see this. I don't imagine it'd be much work to have an API endpoint that exposes the data in Prometheus' format. Maybe I'll submit a PR adding it if I get some free time.

**Comment by Daniel15** [comment]
Actually, looking at the code, this is already possible today! It's just undocumented.

Add something like this to `Configure`:
```
endpoints.MapHealthChecks("/health/prom", new HealthCheckOptions
{
	ResponseWriter = (context, report) => PrometheusResponseWriter.WritePrometheusResultText(context, report)
});
```

Then you can add `https://example.com/health/prom` as a target in Prometheus.

**Comment by CarlosLanderas** [comment]
Thanks for the tip @Daniel15  :)
