### ISSUE TITLE
HealthChecks.EventStore under Linux: connection leak

### ISSUE THREAD

**Issue by Zetanova** [Xabaril/AspNetCore.Diagnostics.HealthChecks#273]
HealthChecks.EventStore lets the connection open or does not properly dispose it. 
There is a know issue with sockets under linux, 
where undisposed sockets don't get finalized by the GC and stack up over time. 

HttpClient's and other components fill then fail with "address already in use"

**Comment by unaizorrilla** [comment]
Follow this build https://ci.appveyor.com/project/Xabaril/aspnetcore-diagnostics-healthchecks/builds/27602790 to see when the package will be created, new version for EventStore is 2.2.3
