### ISSUE TITLE
Parameters Ipaddress and item.host are not showing in UI

### ISSUE THREAD

**Issue by Henkpuik** [Xabaril/AspNetCore.Diagnostics.HealthChecks#275]
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/9b6559fb12e4cc2378e0d075cf6a0ff57cf9e91e/src/HealthChecks.Network/DnsResolveHealthCheck.cs#L30

return new HealthCheckResult(context.Registration.FailureStatus, description: "Ip Address {ipAddress} was not resolved from host {item.Host}");

I think this is the solution for it.

return new HealthCheckResult(context.Registration.FailureStatus, description: **$**"Ip Address {ipAddress} was not resolved from host {item.Host}");

In front of the string must stand $ sign. Then the parameters work.

Kind regards 

Henk

**Comment by CarlosLanderas** [comment]
Totally right. It's missing the string interpolation. We fix it ASAP 

Thanks for reporting

**Comment by CarlosLanderas** [comment]
@Henkpuik thanks for reporting. Version 2.2.3 is being built and will have this fixed
