### ISSUE TITLE
AddHealthCheckEndpoint  Question

### ISSUE THREAD

**Issue by eobeda** [Xabaril/AspNetCore.Diagnostics.HealthChecks#279]
Feature: HealthChecks-UI

When using the AddHealthCheckEndpoint setting, I'd like to use a relative path or find a way to extract the IIS in-process address and port that the site in running under.
```
 services.AddHealthChecksUI("healthchecksdb", setupSettings =>
 {
     setupSettings.AddHealthCheckEndpoint("Name", "url relative path");
 }
```
I found the options for "UseRelativeApiPath" during config, but setting it to true doesn't seem to control the AddHealthCheckEndpoint  parsing
```
  config.MapHealthChecksUI(setup =>
                    {          
                        setup.UseRelativeApiPath=true;
```

Any suggestions ?
Thanks
Ed
ps: Using VS 2019 16.3 with Asp.Net Core 3.0 and custom branding of the HealthChecks-UI web page. AspNetCore.HealthChecks.UI  is version 3.0

**Comment by unaizorrilla** [comment]
Hi @eobeda 

thanks for ask the question, @CarlosLanderas can you take a look here!

**Comment by CarlosLanderas** [comment]
@eobeda , I know you can get the listening urls using 
```csharp
app.ServerFeatures.Get<IServerAddressesFeature>().Addresses;
```
You can get several addresses (http, https) and maybe use the first to get a relative url 
but this does not work with IIS, is a feature that only reports the listening addresses when using Kestrel.

We would need to have this feature working along with kestrel and IIS

Maybe @rynowak  can give us some more information about this, I don't know if this is possible from code when using IIS

**Comment by CarlosLanderas** [comment]
@rynowak @glennc any Idea about how this can be achieves when using IIS?

**Comment by rynowak** [comment]
@tratcher @jkotalik - any ideas?

**Comment by Tratcher** [comment]
IServerAddresses was added to IIS in-proc in 3.0. That said, using a relative path is a much better idea. What do the expected urls look like for these various components? Generating a url per-request is much easier because you can use the request's scheme, host, port, PathBase, etc..

**Comment by CarlosLanderas** [comment]
@rynowak @Tratcher thank you very much for your help :)

**Comment by CarlosLanderas** [comment]
@Tratcher is this working with IIS Express?. I'm doing a test and I get 0 ServerAddresses configuring IIS Express InProcess

![image](https://user-images.githubusercontent.com/16475649/68924441-215add00-0781-11ea-9e81-a8689f194dd1.png)

**Comment by MikeChristensen** [comment]
I came up with another solution for this problem, which I've added on https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/410
