### ISSUE TITLE
Run every healthcheck in its own scope

### ISSUE THREAD

**Issue by ThomasBergholdWieser** [Xabaril/AspNetCore.Diagnostics.HealthChecks#280]
Right now adding multiple different checks using the same DbContext type will result in some of them being failed, because the DbContext might already be disposed.

Default Lifetime of DbContext is scoped, it would be a shame to have to change that to transient for HealthChecks to work properly in this scenarop.

Please change or add options to configure this behavior.

**Comment by unaizorrilla** [comment]
Hi @ThomasBergholdWieser 

Can you send us a repro?

**Comment by ThomasBergholdWieser** [comment]
Sure. Here you go. You need to run dotnet ef database update on this first to be able to run obv.

https://github.com/ThomasBergholdWieser/healthchecksrepro

Just execute the /health endpoint a few times, it should happen pretty often. Change the Lifetime to Transient to make it work.

**Comment by unaizorrilla** [comment]
Hi @ThomasBergholdWieser 

Your healthcheck,  AddDbContext is out-of-box healthcheck from ASP.NET Core Diagnostics package. You will open the issue on http://github.com/aspnet/aspnetcore 
Probaly @rynowak can help you!! 

I close this, reopen if you consider is necessary!
