### ISSUE TITLE
AspNetCore.HealthChecks.UI does not read appsettings according to ASPNETCORE_ENVIRONMENT

### ISSUE THREAD

**Issue by rupeshtech** [Xabaril/AspNetCore.Diagnostics.HealthChecks#283]
# Issue Description

I am using AspNetCore.HealthChecks.UI nuget package to show in UI,  healthchecks of different services. 
It reads the endpoints from appsettings.json .

I have different appsettings (appsettings.json, appsettings.Test.json, appsettings.Production.json)
And setting ASPNETCORE_ENVIRONMENT accoridng to environment.

In Test Appsettings, endpoints are of Test
In production appsettings endpoints are of Prod.

But in **All environments it shows endpoints only from appsettings.json** .

#Configuration
Project is an MVC application with ..NETCore 3.0

`<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <WebProject_DirectoryAccessLevelKey>0</WebProject_DirectoryAccessLevelKey>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.UI" Version="3.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.AzureAD.UI" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.9.5" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.0.0" />
  </ItemGroup>
</Project>`

# Other things
To be sure that **correct Env is set**, I am printing Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") on my view page
and I am seeing **right values in my view for each environment** . but on health-ui I am seeing endpoints set in appsettings.json

**Comment by CarlosLanderas** [comment]
Hello. We relay on IConfiguration so we will use the configuration providers you have configured. Have you configured AddJsonFile by yourself? By default it should use target environments

**Comment by rupeshtech** [comment]
@CarlosLanderas  I dont know it is bug or not but if appsettings.Production.Json has less endpoints than appsettings.Json then it shows additional endpoints from appsettings.Json....Which was my case.
my appsettings.json has 6 endpoints where as appsettings.Production.Json when I removed extra 3 endpoints from appsettings.json then it show ONLY FROM appsettings.Production.json

**Comment by fglaeser** [comment]
When You have both appsettings, the values in they appsettings.json are overwrite by those in the appsetting.env.json, but this is not a complete replacement of all the values.

**Comment by rupeshtech** [comment]
@fglaeser sorry for late response.

Indeed it works as it supports IConfiguration
