### ISSUE TITLE
Using both a publisher and health checks UI

### ISSUE THREAD

**Issue by ThomasArdal** [Xabaril/AspNetCore.Diagnostics.HealthChecks#284]
Is it possible to configure both a publisher and health checks UI. The reason I'm asking is that I tried and my publisher isn't invoked when settings up Health Checks UI. Maybe I'm doing something wrong, but code looks pretty much like this:

```csharp
services.AddHealthChecksUI();
services
    .AddHealthChecks()
    .AddElmahIoPublisher();
```

The publisher is never called. If I remove the `AddHealthChecksUI` call, the publisher is invoked just fine.

**Comment by CarlosLanderas** [comment]
@ThomasArdal let me test it and I'll come back to you

**Comment by ThomasArdal** [comment]
@CarlosLanderas Any news on this one? :)

**Comment by CarlosLanderas** [comment]
@ThomasArdal  I see ElmahIoPublisher is a code of yours, Is difficult to find out what's going on without taking a look to the internal wiring of that method

**Comment by ThomasArdal** [comment]
@CarlosLanderas `ElmahIoPublisher` is written by me, yes 👍 I can definitely debug this, but the reason I was asking was to find out if both a publisher and UI can be configured. That definitely looks possible from your code, why this must be somewhere inside my code. I'll try to debug what is going on.

As for the implementation, it is here: https://github.com/elmahio/Elmah.Io.AspNetCore/tree/master/src/Elmah.Io.AspNetCore.HealthChecks

The publisher implements the interface:

```csharp
public class ElmahIoPublisher : IHealthCheckPublisher
```

and registered through DI like this:

```csharp
builder.Services.AddSingleton<IHealthCheckPublisher, ElmahIoPublisher>();
```

**Comment by ThomasArdal** [comment]
Weird. This works:

```csharp
services
    .AddHealthChecks()
    .AddElmahIoPublisher(options =>
    {
        options.ApiKey = "API_KEY";
        options.LogId = new Guid("LOG_ID");
    })
    .AddDiskStorageHealthCheck(o => o.AddDrive("c:\\"));

services.AddHealthChecksUI("healthchecksdb", settings =>
    settings.AddHealthCheckEndpoint("mychecks", "https://localhost:44346/health"));
```

If I invoke `AddHealthChecksUI` before setting up the publisher, the publisher is never invoked.
