### ISSUE TITLE
Response is null or message can't be deserialized as HealthChecks.UI.Client.UIHealthReport.

### ISSUE THREAD

**Issue by ranouf** [Xabaril/AspNetCore.Diagnostics.HealthChecks#285]
Hi,

i m using .net core 2.2, I configured my startup with :

            services.AddHealthChecks()
                .AddCheck<MYHealthCheck>("MY");
                .AddCheck<YOUHealthCheck>("YOU");
            services.AddHealthChecksUI();

AND

            // HealthCheck
            app.UseHealthChecks("/healthchecks", new HealthCheckOptions()
            {
                Predicate = _ => true,
                ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
            });
            app.UseHealthChecksUI();

app.Settings:

     "HealthChecksUI": {
		"HealthChecks": [
			{
				"Name": "Http and UI on single project with customizations-1",
				"Uri": "https://localhost:44360/hc-ui"
			}
		],
		"Webhooks": [],
		"EvaluationTimeinSeconds": 10,
		"MinimumSecondsBetweenFailureNotifications": 60
		//"HealthCheckDatabaseConnectionString": "Data Source=%APPDATA%\\healthchecksdb" 
               //-> Optional, default on WebContentRoot
	},

WHen I navigate to healthchecks, I get:

`{"status":"Healthy","totalDuration":"00:00:01.5964157","entries":{"MY":{"data":{},"duration":"00:00:00.6697264","status":"Healthy"},"YOU":{"data":{},"duration":"00:00:00.9261904","status":"Healthy"}}}`

When I navigate to /healthchecks-ui i get:
![image](https://user-images.githubusercontent.com/1764519/65936745-a1083480-e3eb-11e9-8cd4-9de39814544c.png)

Where did I misconfigured something?

**Comment by CarlosLanderas** [comment]
I've answered you in #87

**Comment by ranouf** [comment]
@CarlosLanderas  gave me the solution.

The issue came from the appSettings, here are the correct settings:

 ```
"HealthChecksUI": {
	"HealthChecks": [
		{
			"Name": "Http and UI on single project with customizations-1",
			"Uri": "https://localhost:44360/hc-ui"
		}
	],
	"Webhooks": [],
	"EvaluationTimeinSeconds": 10,
	"MinimumSecondsBetweenFailureNotifications": 60
	//"HealthCheckDatabaseConnectionString": "Data Source=%APPDATA%\\healthchecksdb" 
           //-> Optional, default on WebContentRoot
},
```
