### ISSUE TITLE
[Elasticsearch] Add degraded health status

### ISSUE THREAD

**Issue by inkel** [Xabaril/AspNetCore.Diagnostics.HealthChecks#287]
I was looking at the code of the Elasticsearch health check and found that it's using a simple ping to test whether Elasticsearch is up or not, which is not bad, but I was thinking that it would be nice to have it actually using the [cluster health](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html) API in Elasticsearch and report healthy for green, unhealthy for red, and degraded for yellow.

The reason why I think degraded is right for the yellow state, and not green as it currently is, is because this could mean that some writes might take time to replicate (or even get lost if something happens to the cluster before replication is done).

Another option could be to add an extra parameter to `ElasticsearchOptions` to indicate you want to use degraded for yellow, or otherwise use the regular check that currently exists.

Would you be interested in something like this? If so, I've already some local custom health that does something like this.

**Comment by unaizorrilla** [comment]
A PR is welcome for this!!

**Comment by inkel** [comment]
PR #290 adds this feature!

**Comment by sungam3r** [comment]
fixed by #1577
