### ISSUE TITLE
HealthChecks Uri is not overwritten in Azure

### ISSUE THREAD

**Issue by ranouf** [Xabaril/AspNetCore.Diagnostics.HealthChecks#288]
Hi,

I publish my webapp on Azure.

I set this configuration settings _HealthChecksUI:HealthChecks:Uri_ to _https://mywebsite.net/healthchecks_

but in the log I continue to see:

> 2019-10-01 19:39:26.236 +00:00 [Error] HealthChecks.UI.Core.HostedService.HealthCheckReportCollector: GetHealthReport threw an exception when trying to get report from https://localhost:44360/healthchecks configured with name HealthCheck.
> System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissions ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissionsat System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)--- End of inner exception stack trace ---at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReport(HealthCheckConfiguration configuration)
> fail: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]GetHealthReport threw an exception when trying to get report from https://localhost:44360/healthchecks configured with name HealthCheck.
> System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissions ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissionsat System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)--- End of inner exception stack trace ---at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReport(HealthCheckConfiguration configuration)

How to configure HeathCheckUI correctly?

Thanks

**Comment by ranouf** [comment]
I overwritten by code the configuration like:

            ```
services.AddHealthChecksUI(setupSettings: settings => {
                settings.AddHealthCheckEndpoint(
                    Configuration["HealthCheck:Name"],
                    Configuration["HealthCheck:Uri"]
                );
                settings.SetHealthCheckDatabaseConnectionString(Configuration["HealthCheck:HealthCheckDatabaseConnectionString"]);
                settings.SetEvaluationTimeInSeconds(int.Parse(Configuration["HealthCheck:EvaluationTimeinSeconds"]));
                settings.SetMinimumSecondsBetweenFailureNotifications(int.Parse(Configuration["HealthCheck:MinimumSecondsBetweenFailureNotifications"]));
            });
```

**Comment by CarlosLanderas** [comment]
Do you have any other configuration in your appsettings.json?

**Comment by CarlosLanderas** [comment]
@ranouf , HealthChecks are an array, you should configure them with indexes:

HealthChecksUI:HealthChecks:0:Name=httpBasic'
HealthChecksUI:HealthChecks:0:Uri='uri'
HealthChecksUI:HealthChecks:1:Name=httpBasic2'
HealthChecksUI:HealthChecks:1:Uri='uri2'

and so on
