### ISSUE TITLE
Immutable Deployments - Option for in memory (or other alternative) healthcheckdb for UI?

### ISSUE THREAD

**Issue by cscheib** [Xabaril/AspNetCore.Diagnostics.HealthChecks#29]
Have you considered options other than persisting a sqlite file to disk for the healthcheckdb?

We've been moving toward an immutable runtime environment model (Azure App Service using "Run From Package"), which means writing that file to disk is going to fail.

It looks like I can forgo instantiating the UI, and just query /healthchecks-api for check results, which may suffice for our needs.  But, a UI is always nice.

**Comment by CarlosLanderas** [comment]
@unaizorrilla what do you think about this. It's obvious that the UI is not prepared for this kind of scenario. Could we implement additional providers?

**Comment by unaizorrilla** [comment]
Well, this is not a priority on this moment!

**Comment by unaizorrilla** [comment]
Hi @cscheib 

I need to create a new feature for supporting specifying the database path, probably I try to add support for sqlite on memory also on this new feature.

**Comment by HalidCisse** [comment]
I had same issue before when my app fail to start because it cant write to the disk, how about an efcore dbcontext implementation ?

**Comment by unaizorrilla** [comment]
Hi @HalidCisse 

With new versions you can specify the db path for Sqlite. Check UIAndApi sample and the new appsettings.json parameter configuration.

Next version of the ui probably include a memory database support!

**Comment by SychevIgor** [comment]
Totally agree with @cscheib , we need at least in memory provider or better - they way to configure persistence. 
As a work-around- we can replace the call AddHealthChecksUI from an library
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.UI/ServiceCollectionExtensions.cs
without own code, where could by copy-pasted an original call, but without SQLLite

```
 services.AddDbContext<HealthChecksDb>(db =>
            {
                var connectionString = healthCheckSettings.HealthCheckDatabaseConnectionString;
                if (string.IsNullOrWhiteSpace(connectionString))
                {
                    var contentRoot = configuration[HostDefaults.ContentRootKey];
                    var path = Path.Combine(contentRoot, databaseName);
                    connectionString = $"Data Source={path}";
                }
                else
                {
                    connectionString = Environment.ExpandEnvironmentVariables(connectionString);
                }
                db.UseSqlite(connectionString);
            });
```

**Comment by unaizorrilla** [comment]
Hi @SychevIgor 

We try to add this feature on next ui version, thanks for your feedback.

Unai

**Comment by Odonno** [comment]
What about using `Microsoft.EntityFrameworkCore.InMemory` and using an enum as an option to specify what storage we want to use?

```csharp
enum HealthCheckStorageOption
{
  InMemory,
  Sqlite,
  SqlServer
}
```

**Comment by jalfaCM** [comment]
Hello, is this feature still on track to be added?

**Comment by unaizorrilla** [comment]
We are working on next version and this is the behavior bu default.

**Comment by jalfaCM** [comment]
I appreciate the work that you're doing. Would it be too much for me to ask on when we could expect said feature?

**Comment by unaizorrilla** [comment]
Hi @jalfaCM 

I try to release before summer!

**Comment by andreycherkashin** [comment]
@unaizorrilla any updates? Still in plan or suspended?

**Comment by alfreql** [comment]
Hi, if I dont want the health history, Can I disable the use of the db? How can I do it?

**Comment by CarlosLanderas** [comment]
Storage providers feature has been implemented in UI version 3.1.1-preview1. 
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/455#issuecomment-613093369

**Comment by alfreql** [comment]
Hi, Is there a way to not use database at all, or disable it? I don't interesting in historical data.

**Comment by CarlosLanderas** [comment]
Sure, you have the InMemoryProvider :)
