### ISSUE TITLE
Repeated LINQ "could not be translated and will be evaluated locally" warnings are logged when a health check fails

### ISSUE THREAD

**Issue by mikevanoo** [Xabaril/AspNetCore.Diagnostics.HealthChecks#293]
Could be similar to #94 .

When a health check fails, the following warnings are logged:

[11:23:29 ERR] Health check BlobStoreWrite (SqlServer) completed after 99.2562ms with status Unhealthy and 'null'
[11:23:30 WRN] The LINQ expression 'where [lf].HealthCheckName.Equals(__livenessName_0, InvariantCultureIgnoreCase)' could not be translated and will be evaluated locally.
[11:23:30 WRN] The LINQ expression 'Take(__p_1)' could not be translated and will be evaluated locally.
[11:23:30 WRN] The LINQ expression 'SingleOrDefault()' could not be translated and will be evaluated locally.

**Comment by CarlosLanderas** [comment]
Hello @mikevanoo
What UI version are you using?

**Comment by mikevanoo** [comment]
Apologies, @CarlosLanderas , I should have said. I'm using 2.2.34:

`<PackageReference Include="AspNetCore.HealthChecks.UI" Version="2.2.34" />`

**Comment by Daniel15** [comment]
This is likely due to changes in Entity Framework Core 3.0. Prior versions would implicitly/silently do client-side evaluation in cases where the query is not translatable to SQL, whereas in EF Core 3.0 it warns you about it. See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/#restricted-client-evaluation

**Comment by unaizorrilla** [comment]
Hi @Daniel15 , version 2.2.34 does not use EF Core 3, it still use 2.X, and client evaluation (log or throw) is also a configurable option.

@mikevanoo , we fix on 3.X, are you planned to migrate to 3? I try to solve this warnings on 2.X but I need some time to do that!

**Comment by mikevanoo** [comment]
@unaizorrilla We are in the process of upgrading our solutions to .NET Core 3.1 as it's the LTS release so we'll be upgrading your packages as well. So no pressure from me on this one.

**Comment by mikevanoo** [comment]
@unaizorrilla Just upgraded to v3.0.9 and I don't see this issue so from my point of view I'm happy.
