### ISSUE TITLE
DLL file from the AspNetCore.HealthChecks.SqlServer NuGet package (v3.0.0) has no date modified

### ISSUE THREAD

**Issue by mike-cochrane** [Xabaril/AspNetCore.Diagnostics.HealthChecks#298]
The DLL in the package has no Date modified.

![image](https://user-images.githubusercontent.com/1772681/66361400-22a72600-e9db-11e9-8658-d7f6ac1af06d.png)

This causes an issue when using NuGet pack for an application using the package.

[pack] The DateTimeOffset specified cannot be converted into a Zip file timestamp.

More details here

https://github.com/NuGet/Home/issues/7001

If I do a simple touch on the file then I can use NuGet pack as normal.

**Comment by CarlosLanderas** [comment]
It looks like a bug yes. I think we need to republish de nuget.

**Comment by inech** [comment]
Same problem for me with a _HealthChecks.Uris.dll_

**Comment by CarlosLanderas** [comment]
Are you still having troubles with this issue?

**Comment by mike-cochrane** [comment]
Thanks, this is now working as expected.

![image](https://user-images.githubusercontent.com/1772681/79279489-44411700-7f02-11ea-946b-775f1a17d24b.png)
