### ISSUE TITLE
HealthChecks.RabbitMQ 2.2 preview 3

### ISSUE THREAD

**Issue by SbiCA** [Xabaril/AspNetCore.Diagnostics.HealthChecks#3]
Hi could you publish this package also for `2.2.0-preview3-35497` at the moment its only available for `2.2.0-rmt-35613` ?

Cheers

**Comment by unaizorrilla** [comment]
Hi @SbiCA 
Rabbit me preview3-35497 is not on myget due a build issue fixed before rtm-35497. Why do you need this preview version package? Between preview3 and RTM HealthStatus is modified with a breaking change, probably is better update to new version!

Thanks 
Unai

**Comment by SbiCA** [comment]
Your totally right that's fine I was just confused because the .net core sdk is only available for preview-3 not rtm yet. 

Cheers
