### ISSUE TITLE
Persistant storage (HealthChecks.UI)

### ISSUE THREAD

**Issue by herkusas** [Xabaril/AspNetCore.Diagnostics.HealthChecks#303]
I do want to reuse SQLite database after every deployment so I could see all history...

If there is any way to do that without changing source code? I've missed something?

Since now every time I run solution DB wipes out... (e.x ... on state from: a few seconds ago...)

**Comment by unaizorrilla** [comment]
Hi @herkusas 

Nope :-( at this moment, UI delete an create a new database (with latest migrations) every time you start the UI.

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/9bc53be4d169e1af485df213747e4cba523b3f6e/src/HealthChecks.UI/ServiceCollectionExtensions.cs#L95

**Comment by CarlosLanderas** [comment]
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/455#issuecomment-613093369
