### ISSUE TITLE
Re-use rabbit connection for RabbitMq Health check

### ISSUE THREAD

**Issue by jnovick** [Xabaril/AspNetCore.Diagnostics.HealthChecks#304]
As per [official docs](https://www.rabbitmq.com/connections.html) and its suggestions on [high connectivity churn](https://www.rabbitmq.com/networking.html#dealing-with-high-connection-churn), connections are meant to be long lived. Ideally, I believe this should be configured as a singleton, but I understand there may be use cases where this could be configured differently. Currently the code does a [new connection per health check request](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/706fb5b7c1991272ab73aa00a3e868c03589d93f/src/HealthChecks.RabbitMQ/RabbitMQHealthCheck.cs#L28). I believe this should use an existing connection if there is already a connection registered via DI or create one to be used for all health check requests instead of creating a new one each time.

Edit: This is mainly an issue when running in an environment like Kubernetes that regularly hits the health check endpoint. In Kubernetes, the default is 10s as per [k8s official docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes). My readiness probe hits an endpoint that uses this health check and that is why it is creating such an issue for me.

**Comment by unaizorrilla** [comment]
Hi @jnovick 

We do some changes in other healtchecks related with the same issue, we are happy to accept a PR about his if you have some time, if not, I can do this but need some time!

**Comment by jnovick** [comment]
Okay, I'll submit a PR shortly. I am planning on adding several options to allow users to solve the problem in the best way that fits their project. I don't want to lock people into fitting their project architecture to fit the same way I have mine by designing the health check to solve my problem. Let me know what you think once I push up a PR.

**Comment by jnovick** [comment]
I have submitted a PR (https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/307). Let me know what you think. I prioritized not changing existing behavior and instead making it easy to follow a better pattern, but I am not sure if I created too many config options.

**Comment by rwkarg** [comment]
The Func based extension methods introduced in #307 don't actually result in connection reuse. A new RabbitMQHealthCheck instance is created from the factory each time the HealthCheck infrastructure evaluates.

PR #352 fixes this for the connection string based extension method, but the `Func<IServiceProvider, >` based extension methods will always result in the provided factory being called each time a health check is evaluated and the implementation of those extension methods always creates a new RabbitMQHealthCheck instance.
DefaultHealthCheckService will always call the Factory method every time that RunCheckAsync is called internally (each evaluation).

It's not clear how to address the `Func<IServiceProvider,>` extension methods.

Adding extension methods that take an IConnection or IConnectionFactory instance directly would allow the IConnection and IConnectionFactory (and ultimately the RabbitMQHealthCheck) to be only created once in Startup and then reuse would actually take place.

**Comment by CarlosLanderas** [comment]
Closing, both PR's were merged :)
