### ISSUE TITLE
HealthChecks.UI allow html/js customization

### ISSUE THREAD

**Issue by adamoisescu** [Xabaril/AspNetCore.Diagnostics.HealthChecks#306]
Hello,

We are using HealthChecks.UI package to display our services health and we'd like to add an icon for each service that would redirect to the corresponding Azure Application Insights. We tried to add it as a link or as html in the name/description we provide externally but (as expected) it was parsed as plain text :)

Since only CSS customization is possible from outside, is there any option to do this?
Are there any plans for future JS customization or some flexibility at UI level?

Thanks a lot for your work!

**Comment by unaizorrilla** [comment]
A think this is not supported right now, but we accept PR to improve customization features :-), probably @CarlosLanderas  can help on any question about this!

**Comment by CarlosLanderas** [comment]
Hello @unaizorrilla @adamoisescu 
Allowing consumers to bind their own javascript files to the UI is easy to implement.

What I am concerned about are the possible bugs that will be reported here because of this custom scripts

**Comment by adamoisescu** [comment]
Definitely a valid concern @CarlosLanderas 
What about allowing to pass a hyperlink and an icon per each app (optionally) and adding it besides the name of the app in the Health Checks table?
I could try to do it :)

**Comment by CarlosLanderas** [comment]
@adamoisescu, we will have your this customization option in consideration for next UI version.
Thanks :)

**Comment by adamoisescu** [comment]
Sounds great, thank you!
Do you already know more or less when the new UI version will be released?
