### ISSUE TITLE
Healthchecks-api always returns []

### ISSUE THREAD

**Issue by maikebing** [Xabaril/AspNetCore.Diagnostics.HealthChecks#31]
.Net Core 2.2 

 http://localhost:5000/healthchecks-api

**ConfigureServices**

`services.AddHealthChecks().AddSqlServer(_ConnectionString,name:"database").AddMQTTChatHealthChecks();`
    `        services.AddHealthChecksUI();
`

```
        private static void AddMQTTChatHealthChecks(this IHealthChecksBuilder builder)
        {
            builder.AddPrivateMemoryHealthCheck(1024 * 1024 * 1024,"privatememory")
             .AddDiskStorageHealthCheck(setup =>
             {
                 DriveInfo.GetDrives().ToList().ForEach(di =>
                 {
                     setup.AddDrive(di.Name, 1024);
                 });
             });
        }
```

  **Configure(IApplicationBuilder app, IHostingEnvironment env,------)**
`          app.UseHealthChecksUI();`

**Comment by maikebing** [comment]
It's been used before, deleted,
 do you want to look at my code? Https://github.com/IoTSharp/MQTT.Chat

**Comment by maikebing** [comment]
@CarlosLanderas   If you have time！ Thanks!

**Comment by CarlosLanderas** [comment]
The Response with you used and removed was one of your own. The UI works with the Responses to test that is in the package AspNetCore.HealthChecks.UI.Client. Take a look at the documentation  at README.md

**Comment by maikebing** [comment]
Thank! I got it.

**Comment by maikebing** [comment]
I think since the app is used  UseHealthChecksUI (), why not use UIResponseWriter.WriteHealthCheckUIResponse  by default ？

**Comment by CarlosLanderas** [comment]
Because the UI is in a separate project. The apps registering Health checks are who register the way to return that information to its callers. The writer is registered in the Microsoft Package (UseHealthChecks) not in UseHealthChecksUI

**Comment by maikebing** [comment]
Thanks again, I get it.

**Comment by CarlosLanderas** [comment]
You are welcome :)
