### ISSUE TITLE
Sftp Connection Refused

### ISSUE THREAD

**Issue by renatogbp** [Xabaril/AspNetCore.Diagnostics.HealthChecks#310]
On file [SftpHealthCheck](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.Network/SftpHealthCheck.cs), line 26, the port is not being set, even though there's a port property in options. What am I missing here? 
I try to make a sample Sftp connection without port and it didn't work. When I add the port it works.
```
using Renci.SshNet;
using System;
public static class SendFileToServer
{
    private static string host = "127.0.0.1";
    private static string username = "username";
    private static string password = "123456";

    public static int Send(string fileName)
    {    
        //var connectionInfo = new ConnectionInfo(host, 2222, username, new PasswordAuthenticationMethod(username, password));
        var connectionInfo = new ConnectionInfo(host, username, new PasswordAuthenticationMethod(username, password));
        // Upload File
	Console.WriteLine("trying to connect");
        using (var sftp = new SftpClient(connectionInfo)){
            
            sftp.Connect();
	    Console.WriteLine("connection stabilish");
            sftp.ChangeDirectory("/MyFolder");
	    Console.WriteLine("changed directory");
            using (var uplfileStream = System.IO.File.OpenRead(fileName)){
                sftp.UploadFile(uplfileStream, fileName, true);
            }
            sftp.Disconnect();
	    Console.WriteLine("disconnected");
        }
        return 0;
    }
}
```

**Comment by CarlosLanderas** [comment]
@renatogbp , let me take a look a it but it looks like you are absolutely right

**Comment by CarlosLanderas** [comment]
@renatogbp , version 3.0.1 is being published and it is now taking the configured port in consideration. Thanks for reporting the issue and let us know if everything works ok.

**Comment by renatogbp** [comment]
Just an updated. I've test the new library and the Sftp HealthCheck is not returning a response. The curl request on my docker compose stays open and creates many open requests which are causing memory leak on my container.

**Comment by CarlosLanderas** [comment]
Could you provide the code sample with your docker compose so I can test this? 

Thanks

**Comment by renatogbp** [comment]
I tried to reproduce on a local sftp server with a sample code but I wasn't able to
