### ISSUE TITLE
Persistance of health checks history after restart

### ISSUE THREAD

**Issue by adamoisescu** [Xabaril/AspNetCore.Diagnostics.HealthChecks#311]
Hello again.

We are using an Azure Web App for Containers to host our watchdog app for HealthChecks. We noticed that at every restart of the watchdog app our Health checks history would reset. We mounted an Azure Blob into our container to store the healthchecksdb there and not live within the webapp but the history is still not persisted.

This is most probably because Database.EnsureDeletedAsync() is called in AddHealthChecksUI and it seems to delete the db at every startup.
Is there a reason for this? Or another way to persist the health checks history?

Thanks a lot for your effort.

**Comment by CarlosLanderas** [comment]
Hello @adamoisescu. UI Version 3.1.1-preview1 already supports custom storage providers, so you can now configure different databases and not deletion is performed anymore:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/455#issuecomment-613093369
