### ISSUE TITLE
GC Info

### ISSUE THREAD

**Issue by Henkolicious** [Xabaril/AspNetCore.Diagnostics.HealthChecks#313]
Present GC Info example wanted, SO explanation here:
https://stackoverflow.com/questions/58620559/healthchecksui-memory-gcinfo-net-core-3

**Comment by CarlosLanderas** [comment]
@Henkolicious , data dictionary is new in 3.0 version and are still not supported. Let me talk with @unaizorrilla and we might add it.

**Comment by CarlosLanderas** [comment]
@Henkolicious I've seen we support data dictionary in the backend but we do not use it in the frontend as you can use HealthCheckResult description.

What exactly are you trying to do?

**Comment by Henkolicious** [comment]
@CarlosLanderas maybe I'm just doing it the wrong way, but I was simply just trying to collect GC metrics and present them in the UI. Which I managed to do, however my implementation does not feel like I did it the right way, this specific section in the SO thread:

<pre>
            .AddCheck("Memory", () =>                
                new GCInfoHealthCheck()            // This section right here
                    .CheckHealthAsync(             // seems to be a very
                        new HealthCheckContext()   // poor implementation due
                    ).GetAwaiter().GetResult(),    // to constant Heap allocation.
                tags: new[] { "memory" }
            );
</pre>

**Comment by CarlosLanderas** [comment]
Garbage collector health checks has been created in System Package.

**Comment by Henkolicious** [comment]
Seems like I've been a potato and probably misspelled the tag, because it worked like a charm. My bad!
