### ISSUE TITLE
Add Remaining Memory Health Check

### ISSUE THREAD

**Issue by RehanSaeed** [Xabaril/AspNetCore.Diagnostics.HealthChecks#314]
The memory check requires you to specify a maximum memory limit. Unfortunately, there doesn't seem to be a way in .NET Core to get the maximum memory allowed (this is especially useful in a Docker container).

It would be amazing if instead of specifying a maximum memory limit, we could do the opposite and specify a remaining memory limit e.g. If we have less than 200MB left, fail the health check. I believe the disk health check allows you to do it this way which I think is much more intuitive.

**Comment by unaizorrilla** [comment]
Hi @RehanSaeed 

The health check for memory is checking if the current process (not the entire system, container) is using more memory than a specified threshold! 

```
return builder.Add(new HealthCheckRegistration(
                name ?? MEMORY_NAME,
                sp => new MaximumValueHealthCheck<long>(maximumMemoryBytes, () => Process.GetCurrentProcess().PrivateMemorySize64),
                failureStatus,
                tags,
                timeout));
```

If you need a new healthcheck to check remaining memory on system ( container, machine ), pr is welcome!

**Comment by CarlosLanderas** [comment]
You can also use the ProcessAllocatedMemoryHealthCheck inside the System package.  It is using GC.GetTotalMemory and you can configure the maximum memory your current .NET Core can use.

**Comment by RehanSaeed** [comment]
@CarlosLanderas This is not quite the same. I'd like to specify the remaining memory available instead of a threshold. To do this, we'd need to know the total memory available on the system which I don't think can be done in .NET Core right now.

If I'm using Docker/Kubernetes it's common to specify a total memory limit for the app. If I get close to that, I want to set the health check to degraded.

**Comment by akiragothick** [comment]
Una consulta amigos, este metodo no lo entiendo muy bien: AddProcessAllocatedMemoryHealthCheck, es para saber cuanto espacio va ocupar almacenar el historico de health espacio en disco o ram? y si se sobrepasa se auto limpia o se hace manual?
