### ISSUE TITLE
UI: health check history feedback

### ISSUE THREAD

**Issue by espenrl** [Xabaril/AspNetCore.Diagnostics.HealthChecks#315]
I love the following piece of UI - it tells what has happened in  a useful way:

![image](https://user-images.githubusercontent.com/4621581/67860316-d18fdb00-fb1d-11e9-9a01-1a613559fe3a.png)

# Presents itself as per health check - which is false

The data is per endpoint, but the buttons to trigger the UI is per health check. In reality all the buttons trigger the same presentation.

![image](https://user-images.githubusercontent.com/4621581/67860394-0308a680-fb1e-11e9-8975-ef7e4ac264b0.png)

![image](https://user-images.githubusercontent.com/4621581/67860871-50d1de80-fb1f-11e9-8ac4-06f18b456ef7.png)

## Possible solution 1)
Filter the history to represent the corresponding health check.

## Possible solution 2)
Move the button to the level of endpoint. In that case it would be nice if "Unhealthy" was annotated with the name of the health check which went unhealthy.

**Comment by unaizorrilla** [comment]
Hi @CarlosLanderas 

I checked out this issue and probably we have a bug here!, can you take a look on this asap?

**Comment by CarlosLanderas** [comment]
Sorry for the delay. I'm gonna take a look

**Comment by CarlosLanderas** [comment]
@espenrl, I am fixing this problem and also adding error descriptions to the timeline:

![image](https://user-images.githubusercontent.com/16475649/68751725-5f7dc280-0602-11ea-92b4-32b8da7380b4.png)

**Comment by espenrl** [comment]
Looks good! Thanks @CarlosLanderas

**Comment by CarlosLanderas** [comment]
Glad to help @espenrl.
Thanks!
