### ISSUE TITLE
Caching mechanism

### ISSUE THREAD

**Issue by Odonno** [Xabaril/AspNetCore.Diagnostics.HealthChecks#316]
Hi,

I know you use Sqlite to store data (configurations, executions, failures).

I am curious and I want to know how (and if) this library handle caching of results. My question is that if 100 users display the healthchecks UI, how many times does it trigger the health execution? According to the delay between each execution of course.

When I checked the healthchecks UI web app and the healthz endpoint, I did not see anything about a potential `lastExecutionTime` property so if anyone know how it works, I would be happy to know.

Thank you. ;)

**Comment by Odonno** [comment]
Hi @unaizorrilla 

Thanks for your quick and crystal clear answer. It really helps. So, just one more: how do we know the settings we set in json file works? I cannot see the difference whether it is 10 or 300 seconds.

**Comment by Odonno** [comment]
Ok. I know that the client interval and the backend interval can be different. It makes sense because they do not start at the same time and the client wants the latest refreshed information.

I know how to set it in the appsettings but there is no way to know it works like expected. I mean, is there to add a log to be sure? Like a new package `HealthChecks.Log` with a `AppendLog` method?

Anyway, you gave me more than enough information about the "caching mechanism". Thank you.

**Comment by unaizorrilla** [comment]
If you configure your logs at debug level you will see

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/973c842564e3c82f953f3a6cc49ffb43db8f41c7/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollectorHostedService.cs#L52

at your specified interval

**Comment by Odonno** [comment]
Well, thanks for the tip. And guess what, I set the variable to `300` (5 minutes) and it sill checks every 10 seconds :(

**Comment by unaizorrilla** [comment]
Ohhhhh sorry!!

**Comment by Odonno** [comment]
Why? It's not your fault, it's ours :)

**Comment by unaizorrilla** [comment]
Empathy! 👍
