### ISSUE TITLE
Allow configuring Elastic Timeout

### ISSUE THREAD

**Issue by cypressious** [Xabaril/AspNetCore.Diagnostics.HealthChecks#317]
The Elastic client allows configuring request timeouts via `ConnectionSettings.RequestTimeout`, however this is not exposed in `AspNetCore.HealthChecks.Elasticsearch`.

Consider adding a way to configure the timeout.

**Comment by unaizorrilla** [comment]
PR welcome ! :-)

**Comment by inkel** [comment]
I'm happy to send a PR for this, however, I've got a couple of questions:

Both current extensions `IHealthChecksBuilder.AddElasticsearch` accept an optional, last parameter `TimeSpan? timeout = default`. Now, according to the documentation, this parameter is _An optional System.TimeSpan representing the timeout of the check._

My question would be: should we use that value too and pass it to `ElasticsearchOptions` or should we add a new one `TimeSpan? requestTimeout = default`?
