### ISSUE TITLE
Add Azure IoT Hub Health Check

### ISSUE THREAD

**Issue by ahryshchanka** [Xabaril/AspNetCore.Diagnostics.HealthChecks#318]
The health check will verify ability to read from Azure IoT Hub ?

The main idea is create registry client and try to read 0 rows based on connection string?
use [Microsoft.Azure.Devices](https://www.nuget.org/packages/Microsoft.Azure.Devices/1.27.0-preview-003)

**Comment by ahryshchanka** [comment]
PR #319

**Comment by unaizorrilla** [comment]
PR is cancelled
