### ISSUE TITLE
SMTP health check: problem with unencrypted connection / blank password

### ISSUE THREAD

**Issue by espenrl** [Xabaril/AspNetCore.Diagnostics.HealthChecks#32]
We have environments with unencrypted SMTP connections and blank password. Yeah, it's bad, but it's the way it is.

When using a non TLS/SSL connection, thus having `SmtpConnectionType.AUTO`, this method raises an exception.

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/0abdd5d0a05d37e26f5885e4b48b5f3639b27fb0/src/HealthChecks.Network/Core/SmtpConnection.cs#L34-L51

My temporary dirty fix that actually works:

``` CSharp
ConnectionType = (SmtpConnectionType)int.MaxValue;
```

With that one "fixed" my next problem is the blank password which raises an exception:
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/0abdd5d0a05d37e26f5885e4b48b5f3639b27fb0/src/HealthChecks.Network/SmtpHealthCheckOptions.cs#L9-L15

Hope support for unencrypted connections and blank password can be added. Thanks!

**Comment by CarlosLanderas** [comment]
Hello @espenrl, let me check it and I come back to you ;)

**Comment by CarlosLanderas** [comment]
@espenrl, I have been addind support for plain smtp and removed the need to set a password.
The commit is in here. It has bee added the `SmtpConnectionType.Plain` and I added a functional test against test.smtp.org server that uses raw connection and it is working. Do you think this could fit your scenario?.

[https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/commit/2cdb3b834901c636b8f9d3159253b42bfd859da8](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/commit/2cdb3b834901c636b8f9d3159253b42bfd859da8)

**Comment by CarlosLanderas** [comment]
@espenrl, that commit above is using raw smtp **with** password account as not postfix docker image supports now the passwordless scenario to my knowIedge. So the best approach it that you test this in your current scenario.

**Comment by espenrl** [comment]
Thanks Carlos. I've seen through the code and that should do it. I will test when the package is made available on NuGet.org.

**Comment by CarlosLanderas** [comment]
@espenrl a prerelease beta version containing this changes have been deployed to Nuget.
https://www.nuget.org/packages/AspNetCore.HealthChecks.Network/2.2.1-beta1

Please come back with feedback for your use case.

**Comment by CarlosLanderas** [comment]
@espenrl did you try the package? I would like to know if your scenario is fixed.

**Comment by espenrl** [comment]
Christmas holidays. I tested now and it works like a charm. Thanks!

**Comment by CarlosLanderas** [comment]
Great news! Thank you

**Comment by CarlosLanderas** [comment]
@espenrl stable 2.2.1 version for Network package is being published.
