### ISSUE TITLE
Health Check UI should be Mobile-responsive

### ISSUE THREAD

**Issue by iSatishYadav** [Xabaril/AspNetCore.Diagnostics.HealthChecks#320]
Health Check UI is a great ready-made page with minimal configuration required for setting up.
It would be a great help if the page can be made mobile-responsive by default.

**Comment by dviry** [comment]
re-opening this since at least in the latest version (6.1.11) the table is still not responsive (not even an horiz scrollbar). 
Can you pls have another look at this? 

Thanks in advance
