### ISSUE TITLE
AppInsightsPublisher doesn't push Healthy results

### ISSUE THREAD

**Issue by gdodd1977** [Xabaril/AspNetCore.Diagnostics.HealthChecks#325]
I'm using the AppInsightsPublisher and the only time I see anything pushed to AppInsights is if an unhealthy result is returned. Is that by design?

**Comment by unaizorrilla** [comment]
Hi,

No, publisher send also events when health check result success 

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/83047f04bdb1bdc8b641208dd5c36e7a0599d372/src/HealthChecks.Publisher.ApplicationInsights/ApplicationInsightsPublisher.cs#L90

You can set also detailed information for send events for each check inside.


If you can’t see this events please let me know the  version you use and I try to investigate more on this.

**Comment by gdodd1977** [comment]
Yeah. I'm definitely not getting anything published for healthy events. I'm on version 2.2.1.

**Comment by unaizorrilla** [comment]
Let me check, I try to create a simple repro and reply here

**Comment by unaizorrilla** [comment]
Hi @gdodd1977 

I check your version and publisher is working as expected. In the image bellow you can see a custom event with status Healthy. 

![image](https://user-images.githubusercontent.com/1630008/68576164-ddf52b80-046d-11ea-81c7-c3e6ef7a18c2.png)

Can this solve your question? Can I close the issue?

**Comment by gdodd1977** [comment]
Hi. Yes. I see that as well. The issue I was having was that the healthy checks weren't showing up in the Live stream metrics. Only unhealthy results were. And then I was looking in traces in the logs, not customEvents. Thanks for the info.

**Comment by inkel** [comment]
I think that is dependant on Azure App Insights and not this library. I'm also using this version and healthy results. Try with a query like the following:

```
customEvents
| where name startswith "AspNetCoreHealthCheck" 
| extend status = toint(customMeasurements.AspNetCoreHealthCheckStatus) 
| summarize count() by status
```
