### ISSUE TITLE
HealthCheckUI not displaying the status of the dependencies like CosmosDB

### ISSUE THREAD

**Issue by santoshpatro** [Xabaril/AspNetCore.Diagnostics.HealthChecks#326]
I have asp.net core 2.2 project for building APIs. The APIs are dependent on few other services like Azure CosmosDB, Azure ServiceBus, Azure Storage services. I have the following code to implement the HealthCheck:

**Startup.cs**

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
	services.AddCustomHealthChecks(Configuration);
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
	app.UseHealthChecks("/healthcheck", new HealthCheckOptions{Predicate = _ => true, ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse});
	app.UseHealthChecksUI();
}

public static IServiceCollection AddCustomHealthChecks(this IServiceCollection services, IConfiguration configuration)
{
	var cosmosDBServiceEndPoint = configuration.GetValue<string>("CosmosDBEndpoint");
	var cosmosDBAuthKeyOrResourceToken = configuration.GetValue<string>("CosmosDBAccessKey");
	var cosmosDBConnectionString = $"AccountEndpoint={cosmosDBServiceEndPoint};AccountKey={cosmosDBAuthKeyOrResourceToken};";
	var hcBuilder = services.AddHealthChecks();
	hcBuilder.AddCheck("self", () => HealthCheckResult.Healthy()).AddCosmosDb(connectionString: cosmosDBConnectionString, name: "CosmosDB-check", failureStatus: HealthStatus.Degraded, tags: new string[]{"cosmosdb"});
	services.AddHealthChecksUI(setupSettings: setup =>
	{
		setup.AddHealthCheckEndpoint("Basic healthcheck", "http://localhost:63812/healthcheck");
	}

	);
	return services;
}
```
On validating the following Url:

http://localhost:63812/healthcheck

**Results:**
```
{
  "status": "Healthy",
  "totalDuration": "00:00:00.0277870",
  "entries": {
    "self": {
      "data": {},
      "duration": "00:00:00.0000026",
      "status": "Healthy"
    },
    "cosmosDB-check": {
      "data": {},
      "duration": "00:00:00.0276920",
      "status": "Healthy"
    }
  }
}

```

But on checking the HealthCheckUI I am not seeing CosmosDB as the dependency on the dashboard:
http://localhost:63812/healthchecks-ui#/healthchecks

![HealthCheckUI_Results](https://user-images.githubusercontent.com/3316116/68580260-0005a280-049c-11ea-85ef-6642774b16f1.jpg)

Can anyone help me to know how to fix this issue?

**Comment by unaizorrilla** [comment]
hi @santoshpatro 

If your project is asp.net core app 2 please use UI 2.2.X and not 3.0.X versions.

Latest 2.2 version is 

https://www.nuget.org/packages/AspNetCore.HealthChecks.UI/2.2.35

**Comment by unaizorrilla** [comment]
The sample apply to healthchecks versions

**Comment by santoshpatro** [comment]
Hi @unaizorrilla ,

I applied the following nuget packages but still it is not working for me. I still see the same response.

![HealthCheckComponents](https://user-images.githubusercontent.com/3316116/68585483-65f82700-04a8-11ea-9193-67846ff6d147.jpg)

**Comment by unaizorrilla** [comment]
Can you share the project or a repro with me?

**Comment by santoshpatro** [comment]
Have some issues while sharing the project. But I followed all the steps that you mentioned above.

**Comment by unaizorrilla** [comment]
Try to create a repro (simple) or use sample  "UI and API" and I can check your configuration.

**Comment by luccasmf** [comment]
I'm having the same issue.

My endpoint with the health returns the json, but when I  try to load the UI, they are not shown, I'm using .Net Core 3.1

![image](https://user-images.githubusercontent.com/5990448/83219025-a61daf00-a145-11ea-804f-38527d51e62e.png)
