### ISSUE TITLE
Add Azure IoT Hub Health Check

### ISSUE THREAD

**Issue by ahryshchanka** [Xabaril/AspNetCore.Diagnostics.HealthChecks#335]
The health check will verify ability to communicate with Azure IoT Hub ?

The main idea is create clients and try to read 0 rows based on connection string/write-delete and etc.
use Microsoft.Azure.Devices nuget package

**Comment by ahryshchanka** [comment]
PR #334

**Comment by unaizorrilla** [comment]
Hi @ahryshchanka 

Thanks for fill the issue, i try to review the PR a soon as posible!
