### ISSUE TITLE
Add Authentication for Webhooks

### ISSUE THREAD

**Issue by tBStar** [Xabaril/AspNetCore.Diagnostics.HealthChecks#336]
Hi,
I am looking to send notifications to Webex but the API endpoint requires a token bearer to be passed along. Is there a way to add a token overload to the SendRequest method in the WebHookFailureNotifier class?

Thanks

**Comment by CarlosLanderas** [comment]
Hello @tBStar. I'm gonna implement two action setups in the UI settings to configure the HttpClient using this signature:

Action<IServiceProvider, HttpClient>

With this you will be able to configure any http client related stuff (including auth header) per request.

**Comment by CarlosLanderas** [comment]
Version 3.0.7 is buing deployed to nuget with this feature available. 
Read PR #370  or README for more information
