### ISSUE TITLE
IApplicationBuilder doesn't support app.UseRouting() how to use in version Asp.Net Core 2.2 

### ISSUE THREAD

**Issue by sonisudarshan0** [Xabaril/AspNetCore.Diagnostics.HealthChecks#337]
I'm trying to configure :-

           public void Configure(IApplicationBuilder app, IHostingEnvironment env)
            {
            app.UseRouter(config =>
            {
                   config.MapHealthChecksUI();
            });
            }

and getting this error :

             
![image](https://user-images.githubusercontent.com/50704950/68948086-23528980-07dd-11ea-971e-24f38ae214ab.png)

so, my concern is how we can use `app.UseRouting()` in ASP.Net Core 2.2 version or any other way to implement health check

**Comment by CarlosLanderas** [comment]
UseRouting is for 3.0. For 2.2 you have to use:

app.UseHealthChecksUI();
