### ISSUE TITLE
Add support custom storage provider for persistent history 

### ISSUE THREAD

**Issue by sefacan** [Xabaril/AspNetCore.Diagnostics.HealthChecks#338]
Hi,
We are using HealtChecksUI for five containers. Healtchecks history is not persistent with SqlLite. Maybe we can use volumes for persisting data or several storage provider can be added.

It can be like Hangfire features.

example: 
UseMemoryStorage()
UsePostgreSqlStorage()

**Comment by unaizorrilla** [comment]
Hi @sefacan 

You can change the EF provider to be used!

**Comment by sefacan** [comment]
@unaizorrilla 
I guess I couldn't tell you what I wanted.

The HealthChecks.UI project has the following code block.

```
services.AddDbContext<HealthChecksDb>(db =>
 {
   var connectionString = healthCheckSettings.HealthCheckDatabaseConnectionString;
    if (string.IsNullOrWhiteSpace(connectionString))
    {
        var contentRoot = configuration[HostDefaults.ContentRootKey];
        var path = Path.Combine(contentRoot, databaseName);
        connectionString = $"Data Source={path}";
    }
   else
    {
        connectionString = Environment.ExpandEnvironmentVariables(connectionString);
    }
    db.UseSqlite(connectionString);
});
```

And following code block has the internal class. I can't override or inherit from IHealthCheckReportCollector interfaces.

```
AddSingleton<IHostedService, HealthCheckCollectorHostedService>()
AddScoped<IHealthCheckFailureNotifier, WebHookFailureNotifier()
AddScoped<IHealthCheckReportCollector, HealthCheckReportCollector>()
```

**Comment by andresmoschini** [comment]
In my opinion, it would be great if the clients could inject his own `HealthChecksDb`.

I am having issues with my integration tests using `WebApplicationFactory` and I do not have any way to avoid the db file creation:

```
    System.AggregateException : One or more errors occurred. (The process cannot access the file 'E:\projects\doppler-forms\DopplerFormsTest\bin\Debug\netcoreapp3.1\healthchecksdb' because it is being used by another process.)
    ---- System.IO.IOException : The process cannot access the file 'E:\projects\doppler-forms\DopplerFormsTest\bin\Debug\netcoreapp3.1\healthchecksdb' because it is being used by another process.
```

**Comment by CarlosLanderas** [comment]
This is already in preview in UI version 3.1.1-preview1. 
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/455#issuecomment-613093369
