### ISSUE TITLE
UI Client Help Needed

### ISSUE THREAD

**Issue by nullptr1108** [Xabaril/AspNetCore.Diagnostics.HealthChecks#34]
I am trying to use the HealthChecks.UI.Client package to pull health checks from an API end point and there seems to be some disconnect between the client application and the end point that it is trying to communicate with.  Is there something that I have missed in the configuration for this? It appears that the UI application is not finding and registering the end points but I am not sure why that it. 

Result from healthchecks-api endpoint - 
`[{"id":1,"status":"Unhealthy","onStateFrom":"2018-12-14T18:33:10.6624959","lastExecuted":"2018-12-14T18:33:21.7626925","uri":"https://localhost:6001/health-ui","name":"Target API 1","discoveryService":null,"entries":[],"history":[]}]`

Appsettings.json for UI application - 
`"HealthChecks-UI": {
        "HealthChecks": [
            {
                "Name": "Target API 1",
                "Uri": "https://localhost:6001/health-ui"
            }
        ],
        "Webhooks": [
            {
                "Name": "",
                "Uri": "",
                "Payload": "",
                "RestoredPayload": ""
            }
        ],
        "EvaluationTimeOnSeconds": 10,
        "MinimumSecondsBetweenFailureNotifications": 60
    }`

Result from target end point - 
`{"status":"Healthy","totalDuration":"00:00:00.0106605","entries":{"heartBeat":{"data":{},"duration":"00:00:00.0017263","status":"Healthy"}}}`

Target API Startup.cs -
`public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            ...

            services.AddHealthChecks()
                .AddCheck<HeartBeat>("HeartBeat");

            services.AddHealthChecksUI();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
...

            app.UseHealthChecks("/health", new HealthCheckOptions()
            {
                Predicate = _ => true,
            });

            app.UseHealthChecks("/health-ui", new HealthCheckOptions()
            {
                Predicate = _ => true,
                ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
            });

            app.UseHealthChecksUI();
}`

**Comment by unaizorrilla** [comment]
Hi

When you navigate to /HealthChecks-UI  the spa show the HealthChecks results?

Can you create a minimal repro and I try to check and solve your issues.

I try to create also a sample with health checks and UI in the same project that you can check

**Comment by unaizorrilla** [comment]
Hi @nullptr1108 

I've created a sample with UI and HealthZ on the same project here https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/tree/master/samples/HealthChecks.UIAndApi can you checkout? this explain how solve your issues?

**Comment by nullptr1108** [comment]
Unai - Thank you for your quick reply to this issue. I will put together a small repro solution and then add it into this commentary.

**Comment by unaizorrilla** [comment]
Checkout the new sample

**Comment by nullptr1108** [comment]
@unaizorrilla  - I did check out the sample that you added which I think is a little different than the use case that I currently am trying to work through. I have put together a repro solution at https://github.com/nullptr1108/Repro-HeathChecksUI which follows the pattern that I am trying to implement across a larger project. Hopefully this will shed some light on what I am trying to accomplish

**Comment by unaizorrilla** [comment]
Let me some time to check this

**Comment by CarlosLanderas** [comment]
One question @nullptr1108. Why are you adding the UI in the svc.target project that is only meant to register HealthChecks when you have a separate UI monitor project that is registering the UI?

**Comment by nullptr1108** [comment]
@CarlosLanderas - Based on what I was seeing that project allowed for the response writer that was needed in the Svc.Target project to reply back in a way that the monitor can consume it. Does this reference need to be removed?

**Comment by CarlosLanderas** [comment]
You can remove the UI assembly and the AddHealthecksUI, UseHealthChecksUI from the SVC.target as only the health-ui path with the UIResponse Writer is needed for that service to be monitored by the other project you have 👍. You can read additional info on the README.md

**Comment by nullptr1108** [comment]
@CarlosLanderas - I removed the references that you indicated in your message and the behavior remains. It seems to me that the UI client in the monitor application is not able to see the target api that it is supposed to be monitoring. I dont see any errors that are being thrown through the execution in the containers.

**Comment by CarlosLanderas** [comment]
Are you using localhost in UI project appsettings? Because if you use localhost that's not gonna work. You have to assign the container name

**Comment by nullptr1108** [comment]
@CarlosLanderas - That took care of the issue that I was having, which is kind of an embarrassing oversight on my part. When I put the URI as http://svc.target:80 everything works as I would expect it to. When I try https://svc.target:443 it does not seem to work though. Is there a limitation or additional configuration for https?

**Comment by CarlosLanderas** [comment]
Yes, volumes have to be configured so an HTTPS certificate can be used. You can check more here. I close the issue as we found the problem. Thanks

https://mikewilliams.io/net-core-2-1-and-docker-how-to-get-docker-to-recognize-a-local-ssl-certificate-6e637e1e8800
