### ISSUE TITLE
Suggestion: Naming inconsistency for Aws and Azure packages

### ISSUE THREAD

**Issue by a-z-hub** [Xabaril/AspNetCore.Diagnostics.HealthChecks#342]
Aws and Azure service have different naming pattern:
![image](https://user-images.githubusercontent.com/4180472/69329558-6475ee00-0c62-11ea-8642-8e5bef27a121.png)

I think, better solution to use pattern HealthChecks.{cloud-provider}.{service}

**Comment by CarlosLanderas** [comment]
I completely Agree with you. I would also prefer Healthchecks.Azure.Whatever

@unaizorrilla what do you think

**Comment by unaizorrilla** [comment]
Yeap

**Comment by CarlosLanderas** [comment]
The problem is that similar named nuget packages would be duplicated and the consumers would find that confusing

**Comment by ahryshchanka** [comment]
I think it is possible to solve:
1] publish packages with valid names
and
2] publish new version of existing packages with [Obsolete](https://stackoverflow.com/questions/1759352/how-to-mark-a-method-as-obsolete-or-deprecated) attribute on `MethodName(this IHealthChecksBuilder builder, ...)` and full information about new packages and names
3] increase changed packages versions
4] remove inconsistent packages
5] publish again without inconsistent packages

**Comment by unaizorrilla** [comment]
Nuget does not allow tremove packages

**Comment by CarlosLanderas** [comment]
As @unaizorrilla  says, nuget do not support to completely remove packages as you would be breaking thousands of projects.

**Comment by ahryshchanka** [comment]
Yes, of course, we can't remove packages.

We can copy/paste already existing project and fix naming for it. As a result we will have 2 packages:
- first package with new valid name and some version
- second package with new version, old invalid name and Obsolete attribute where we will add message about first package and requirement to use new renamed package (reference to it, name or something else). Publish both of it.

As a result in one publish we will have new package and old with recommendation to use new correct.

After that you can remove old inconsistent maned project.

Profit!! Soft update for users.

**Comment by ahryshchanka** [comment]
In case some dev install old package Obsolete will inform them about new better version of package.

+ it is possible to mark package as [deprecated](https://stackoverflow.com/questions/50795559/how-to-deprecate-a-nuget-package) , sorry, I can't check how it works
