### ISSUE TITLE
Suggestion: Naming inconsistency for Identity Service

### ISSUE THREAD

**Issue by a-z-hub** [Xabaril/AspNetCore.Diagnostics.HealthChecks#343]
All packages have full name of checked services except Identity Service.
It have names:
- package name `AspNetCore.HealthChecks.OpenIdConnectServer`
- project name `HealthChecks.IdSvr`

**Comment by unaizorrilla** [comment]
True, a PR for change the project name to OpenIdConnectServer is appreciated! Really, this healtcheck use discovery endpoint ( .well-known/openid-configuration) and works for any OpenIdConnect server like Identity or Azure AD, Auth0 etc...

**Comment by jakubriha** [comment]
I've created a PR #2198 to close this issue. Looking forward for review!
