### ISSUE TITLE
[Docker image] Is there a way to configure de app path Base ?

### ISSUE THREAD

**Issue by alefcarlos** [Xabaril/AspNetCore.Diagnostics.HealthChecks#345]
When using sub-directory in URL it needs to set pathBase, is there a way to set it in the docker image?

It is trying to lookup resources in "/".

![image](https://user-images.githubusercontent.com/5452336/69390327-a2e4ca80-0cad-11ea-8633-55f86fa4744e.png)

**Comment by CarlosLanderas** [comment]
If you are using s subdirectory you can use the UseRelative options in the UI setup

**Comment by alefcarlos** [comment]
@CarlosLanderas  I need to set UseRelative as an Env variable ?

**Comment by CarlosLanderas** [comment]
I've just realized the docker image is currently exposing branding and path configs but I'm not sure you can configure the relative path settings. Let me check it and if is not supported I'll submit a PR to add it ASAP

**Comment by CarlosLanderas** [comment]
@alefcarlos , I am configuring the application under app1 subdirectory and it works:

![image](https://user-images.githubusercontent.com/16475649/69433963-ef2b1b80-0d3c-11ea-86dc-47ac9d1f5129.png)

**Comment by alefcarlos** [comment]
I'm using reverse proxy, it may help.

**Comment by unaizorrilla** [comment]
Hi @CarlosLanderas are you following this issue?

**Comment by CarlosLanderas** [comment]
Yes. When we merge the relative UI PR we continue with this 👍

**Comment by CarlosLanderas** [comment]
@alefcarlos, I've just created this PR 

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/367

It allows you to set an environment variable that will disable relative paths. This is a feature that has been available for a long time in the UI but not in the docker image. I'm going to test it using a reverse proxy and if it is working I'll merge it soon

**Comment by alefcarlos** [comment]
@CarlosLanderas I'm gonna test it !

**Comment by CarlosLanderas** [comment]
Remember you should specify the api, resources and webhook paths using the other env variables if default absolute paths don't match the target URLs.

**Comment by CarlosLanderas** [comment]
@alefcarlos have you tried the PR branch to check if it covers your scenario?

Thanks

**Comment by alefcarlos** [comment]
@CarlosLanderas I'm gonna see it in this weekend, ok ?

**Comment by alefcarlos** [comment]
I'm sorry for delay, end of the year was tough... I've tested here and works fine ♥️

**Comment by CarlosLanderas** [comment]
Thanks! I'll merge it ASAP!

Happy new year!
