### ISSUE TITLE
HealthChecks.Publisher.ApplicationInsights: TelemetryConfiguration.Active is deprecated

### ISSUE THREAD

**Issue by chrisketelaar** [Xabaril/AspNetCore.Diagnostics.HealthChecks#348]
This issue is not to be confused with #186 

According to Microsoft to use of `TelemetryConfiguration.Active` in HealthChecks.Publisher.ApplicationInsights, is deprecated for AspNetCore. Their advise is to use `IOptions<TelemetryConfiguration>` and get the InstrumentationKey from there. 

Link to code:
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/e5e0a26aa9829d29c569e43c65b9ca4bc39a9b9f/src/HealthChecks.Publisher.ApplicationInsights/ApplicationInsightsPublisher.cs#L116

Link to deprecating issue Microsoft:
https://github.com/microsoft/applicationinsights-dotnet/issues/1152

I can make a PR for this, but wanted to discuss it first.

**Comment by unaizorrilla** [comment]
Hi @chrisketelaar 

PR is welcome, thanks!!
