### ISSUE TITLE
Provide path for healthchecksdb SQL Lite  DB

### ISSUE THREAD

**Issue by Grey007** [Xabaril/AspNetCore.Diagnostics.HealthChecks#350]
Hi, 

Is it possible to provide a path for the SQL Lite DB to be saved to? 

We are running our .net core app in Kubernetes + Docker and we've prevented the app to write to the file system. 

Therefore we would like to mount the db to mounted drive

**Comment by karl-sjogren** [comment]
You can configure it in appsettings like this.

```
  "HealthChecksUI": {
    "HealthChecks": [
      {
        ...
      }
    ],
    "HealthCheckDatabaseConnectionString": "Data Source=D:\\home\\healthchecksdb.db"
  }
```

It is also available in the readme.

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks#configuration

**Comment by unaizorrilla** [comment]
I close this issue because is already documented as @karl-sjogren says!
