### ISSUE TITLE
Critical: AddHealthChecksUI calls BuildServiceProvider, causing Singletons to be instantiated multiple times

### ISSUE THREAD

**Issue by ffMathy** [Xabaril/AspNetCore.Diagnostics.HealthChecks#351]
AddHealthChecksUI calls BuildServiceProvider, causing Singletons to be instantiated multiple times. This also causes memory issues, and should be fixed.

**Comment by ffMathy** [comment]
Related StackOverflow question: https://stackoverflow.com/questions/48856483/net-core-singleton-creation-is-called-multiple-times

**Comment by unaizorrilla** [comment]
Hi @ffMathy 

Let me check this and I try to respond on this question ASAP!

**Comment by unaizorrilla** [comment]
Hi @ffMathy 

I aggre that call BuildServiceProvider can cause that singletons can be instantiated multiple times, but in our case we use this call to resolve IConfiguration inside AddHealthChecksUI. If you test it, you can verify that the instance resolved for IConfiguration is the same one on Startup and not duplication exist in this case.

I close the issue, reopen is necessary!

Thanks for contribute on this!

**Comment by ffMathy** [comment]
It needs to be reopened.

The problem is not the configuration instance. The problem is that developers assume that their Singleton services run only once.

By using your project, all my Singleton services all of a sudden run twice, leading to memory issues and locking issues.

Microsoft has very clearly defined that this is a bad idea.

If you need the configuration instance, you can access it without calling Build service provider easily. Just turn your AddSingleton call into a callback.

**Comment by unaizorrilla** [comment]
Hi @ffMathy 

Yes, i can access to configuration object without build service provider again, true, but this is a breaking change! 

Meanwhile if you have a problem with some singleton registration you can move AddX after AddHealtchChecksUI.

 ie, agree that we need to fix this, but we need make a breaking change, planned for next version!

**Comment by ffMathy** [comment]
Can you elaborate on how this is a breaking change? I'm fairly confident it can be done with no breaking changes.

**Comment by CarlosLanderas** [comment]
Fixed in version 3.1.1-preview1. No more BuildServiceProvider in ConfigureServices
