### ISSUE TITLE
Registration multiple topics on AzureServiceBusTopic healthcheck gives error.

### ISSUE THREAD

**Issue by RDJoling** [Xabaril/AspNetCore.Diagnostics.HealthChecks#356]
> 'Duplicate health checks were registered with the name(s): azuretopic '

usage: 
          
```
foreach (var healthTopic in healthCheckConfiguration.HealthCheckTopics)
 {                services.AddHealthChecks().AddAzureServiceBusTopic(serviceBusPublisherConfiguration.ServiceTopicBusUrl, healthTopic);
    }

```

**Comment by CarlosLanderas** [comment]
All HealthChecks have a default name parameter. Use different names when adding several of them.

AddAzureServiceBusTopic(param, param2, name: "thetopicname")
AddAzureServiceBusTopic(param, param2, name: "anothertopicname")
