### ISSUE TITLE
Date modified is missing from HealthChecks.SqlServer.dll

### ISSUE THREAD

**Issue by zokiz** [Xabaril/AspNetCore.Diagnostics.HealthChecks#357]
The HealthChecks.SqlServer.dll file which is part of AspNetCore.HealthChecks.SqlServer (v3.0.0) Nuget package is missing the 'Date modified'. This makes our CI not able to create Nuget packages since the `nuget pack` command fails with the message `The DateTimeOffset specified cannot be converted into a Zip file timestamp.`

This makes us remove this health check and not use it at all. Is there possibility for this Nuget package to be re-published with correct file?

<img width="272" alt="date_modified_missing" src="https://user-images.githubusercontent.com/3917666/70416584-b3dc5c80-1a5f-11ea-89e4-2faaf5106d5d.PNG">

**Comment by unaizorrilla** [comment]
Hi @zokiz 
Let me check this, but! Why you include this library in your package? Normally you reference this as nuget packager. Are you including our/this binaries in your nuget packages?

**Comment by zokiz** [comment]
Yes we do. We reference the Nuget package in our API project and then we publish the project and create our own Nuget package, which is properly versioned as per our API ruleas, and includes all project dependencies so it can be later deployed on different environments. This package is then uploaded to our private Nuget server by TeamCity our CI and from there OctopusDeploy takes it in order to use it for deployments on different environments.

**Comment by unaizorrilla** [comment]
Hi @zokiz 

Normally, when we publish we create a zip file and  upload into artifact directory and then publish to any environment from here, not from new NuGet package.
After checking this, in AppVeyor the output for dotnet pack contains valid modified date, you can see this on build artifacts

https://ci.appveyor.com/api/buildjobs/tgrgdr5dg22r2sk5/artifacts/artifacts%2FAspNetCore.HealthChecks.SqlServer.3.0.0.nupkg

I don't know why on push or restore this value is missing, if you have any idea or more information about this issue I'm glad to help on this.

**Comment by unaizorrilla** [comment]
Hi @zokiz 

I'm following the issue https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/357 with some Microsoft guys! I

**Comment by CarlosLanderas** [comment]
Still having problems with this issue?

**Comment by CarlosLanderas** [comment]
This has been reported as fixed with new package releases
