### ISSUE TITLE
Verify SQL schema

### ISSUE THREAD

**Issue by Odonno** [Xabaril/AspNetCore.Diagnostics.HealthChecks#358]
What if we could check the SQL database schema in a healthcheck? To ensure that some tables/columns do exist based on a model.

What do you think?

**Comment by unaizorrilla** [comment]
Hi @Odonno 

Umm for us, healtchecks evaluate the service availability not the configuration of the service. In our case, sql server check  the service is up and running but not schema migrations etcs etc.

If you need this feature probably for some specific scenario you can create custom healtcheck to do that!..

Thanks 

Unai
