### ISSUE TITLE
[Question] How Can I Check REST Api Service HealthCheck?

### ISSUE THREAD

**Issue by MAliM1988** [Xabaril/AspNetCore.Diagnostics.HealthChecks#36]
Hi Everyone

How can i use HealthCheck for REST Api Service Healthy ?

Thanks for your suggest.

**Comment by unaizorrilla** [comment]
Hi,

Checkout https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/README.md#tutorials-demos-and-walkthroughs-on-aspnet-core-healthchecks to get some tutorials about  HealthChecks
