### ISSUE TITLE
"Dynamic" configuration

### ISSUE THREAD

**Issue by fleed** [Xabaril/AspNetCore.Diagnostics.HealthChecks#361]
What's the suggested way to configure the healthchecks from a database?
I would like to have a list of systems in the database, and then add some checks for those systems.

Is there also a way to trigger a reload of the configuration (when someone adds or removes a system to/from the database)?

**Comment by CarlosLanderas** [comment]
Hello @fleed.

HealthChecks UI uses a sqlite temporal database, so the way to configure dynamic healthchecks from a database would be retrieving this registers from the BD and adding them programatically inside the AddHealthChecksUI setup using the setup method AddHealthCheckEndpoint:

```csharp
 .AddHealthChecksUI(setupSettings: setup =>
                {
                    setup.AddHealthCheckEndpoint("endpoint1", "/health-random");

```
Sample:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/samples/HealthChecks.UI.Branding/Startup.cs#L35
