### ISSUE TITLE
RedisCheck should switch to new StackExchange.Redis library

### ISSUE THREAD

**Issue by sadjadbp** [Xabaril/AspNetCore.Diagnostics.HealthChecks#37]
RedisCheck should switch to new StackExchange.Redis library as oppose to old 1.2.6 version; this creates reference confusion for VS.

**Comment by unaizorrilla** [comment]
Yeap, I try to solve it ASAP and update the package.

**Comment by unaizorrilla** [comment]
Hi sadjadbp, 

I check that Microsoft ASP.NET Core packages (Microsoft.Extensions.Caching for example) also use StackExchange.Redis.StrongName 1.2.6.
Why this package version generate "reference confusion for VS"?

**Comment by cilerler** [comment]
Not sure about the confusion/conflict part.  Not experiencing it however you should definitely want to start using new library that referenced here https://github.com/aspnet/Announcements/issues/322

> **Caching**
_We are releasing a new package "Microsoft.Extensions.Caching.StackExchangeRedis" which will depend on StackExchange.Redis 2.0. "Microsoft.Extensions.Caching.Redis" will continue to ship in ASP.NET Core 2.2 with the StackExchange.Redis 1.0 dependency and will be removed in 3.0._
>
> _To use the new package, remove your dependency on Microsoft.Extensions.Caching.Redis (if present), and add a dependency to "Microsoft.Extensions.Caching.StackExchangeRedis". Next, change your AddDistributedRedisCache invocation in ConfigureServices to AddStackExchangeRedisCache. No further changes should be necessary._

**Comment by unaizorrilla** [comment]
Hi @cilerler

Thanks a lot for this reference, it is true but SignalR Core 1.1.0  also use the StrongName reference

https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Redis/1.1.0

A try to update the package but, probably a problem with different version still exist in the future.

**Comment by unaizorrilla** [comment]
Can you checkout 2.2.2 version of Redis heealth check?

**Comment by sadjadbp** [comment]
@unaizorrilla thanks worked like a charm, I have reference to their latest 2.0.519 and everything work with this new release.
