### ISSUE TITLE
CS0012 The type 'ProducerConfig' is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by Berezhnyk** [Xabaril/AspNetCore.Diagnostics.HealthChecks#371]
The description of AspNetCore.HealthChecks.Kafka 2.2.2 contains the following requirements:
`Confluent.Kafka (>= 1.0.0) `

I use Confluent.Kafka v 1.3.0.
But I get an error:
`CS0012	The type 'ProducerConfig' is defined in an assembly that is not referenced. You must add a reference to assembly 'Confluent.Kafka, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'`

.Net Core 2.2

**Comment by CarlosLanderas** [comment]
Hello @Berezhnyk. The Healthcheck is using version 1.2.0. Let me update to 1.3.0 an publish a new version.

Thanks

**Comment by Berezhnyk** [comment]
@CarlosLanderas, but I faced with this issue also with Confluent.Kafka version 1.2.0.

**Comment by CarlosLanderas** [comment]
Could you paste your csproj dependencies and versions?

**Comment by Berezhnyk** [comment]
My csproj: 
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.Kafka" Version="2.2.2" />
    <PackageReference Include="Confluent.Kafka" Version="1.3.0" />
    <PackageReference Include="Confluent.Kafka.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.HealthChecks" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="2.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
  </ItemGroup>

</Project>
```

**Comment by CarlosLanderas** [comment]
@Berezhnyk , version 2.2 of the healthcheck is using version 1.0 as the error suggests:
.net core 2.2 branch:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/netcore-2.2/build/dependencies.props

**Comment by CarlosLanderas** [comment]
@Berezhnyk so weird. I have created an asp.net core 2.2 with this dependencies and I have no problem.

HealthChecks can only be used with AspNetCore. Why aren't you using Microsoft.NET.Sdk.Web?

Could you change it and reference Microsoft.AspNetCore.All?

```xml

```<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>

  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.Kafka" Version="2.2.2" />
    <PackageReference Include="Confluent.Kafka" Version="1.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    
  </ItemGroup>

</Project>
```

**Comment by Berezhnyk** [comment]
@CarlosLanderas Here is the code https://github.com/Berezhnyk/KafkaHealthCheck.
I've tried to build it on two different machines.

**Comment by CarlosLanderas** [comment]
@Berezhnyk , you are right, when using the setup function the producer config exposed is version 1.0.0 and it does not compile. Let me publish a new 2.2 version using Kafka 1.3.0 for your scenario

**Comment by CarlosLanderas** [comment]
AspNetCore.HealthChecks.Kafka 2.2.3 has been published with Confluente.Kafka version 1.3.0
