### ISSUE TITLE
[3.0.2] .AddApplicationInsightsPublisher without instrumentation key dies

### ISSUE THREAD

**Issue by joshlang** [Xabaril/AspNetCore.Diagnostics.HealthChecks#372]
A breaking change in 3.0.2 (does not occur in 3.0.1).

In our local environment, we do not have an instrumentation key defined anywhere.  We call .AddApplicationInsightsPublisher() as part of our setup.  Since upgrading to 3.0.2, this now causes a crash complaining that a key was not defined in the constructor or options.

**Comment by CarlosLanderas** [comment]
Version 3.0.1 and previous were using TeletryConfiguration.Active that is a static that has been deprecated.

Here is the PR with some instructions on how to use the new implementation:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/365

You need to register Applications Insights in the WebHostBuilder using UseApplicationInsights, or in the ServiceCollection using services.AddApplicationInsightsTelemetry, or registering IOptions<TelemetryConfiguration> or you can see in the following test:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/test/UnitTests/DependencyInjection/Publisher.ApplicationInsights/Publisher.ApplicationInsightsUnitTests.cs#L45

**Comment by joshlang** [comment]
In a basic hello world app, the default asp.net core empty web template, add:

```
services
    .AddApplicationInsightsTelemetry()
    .AddHealthChecks()
    .AddApplicationInsightsPublisher();
```

And you'll explode with:
```
This exception was originally thrown at this call stack:
   HealthChecks.Publisher.ApplicationInsights.ApplicationInsightsPublisher.ApplicationInsightsPublisher(Microsoft.Extensions.Options.IOptions<Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration>, string, bool, bool)
   Microsoft.Extensions.DependencyInjection.ApplicationInsightsHealthCheckBuilderExtensions.AddApplicationInsightsPublisher.AnonymousMethod__0(System.IServiceProvider)
...
```

**Comment by CarlosLanderas** [comment]
Please, follow the Application Insights configuration guide here:

https://docs.microsoft.com/es-es/azure/azure-monitor/app/asp-net-core

If you use the parameterless version of AddApplicationInsightsTelemetry you should provide the configuration using an IConfiguration Provider as appsettings:

```json
{
  "ApplicationInsights": {
    "InstrumentationKey": "yourkey"
  }
}
```

You can also use other overload and configure it directly:

```csharp
services.AddApplicationInsightsTelemetry(config => {
        config.InstrumentationKey = "yourkey";
});
```

**Comment by joshlang** [comment]
Yes, thank you.  I know how application insights works, and the various configuration options.  Our application insights is working just fine, as we intend.  It's just the publisher that blows up.

I will work around this problem myself, I suppose.  Thanks anyway.

**Comment by joshlang** [comment]
This would be an easy fix for you though:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/6e7be013565551b5f3c8f3e0bb9b19d059619d8a/src/HealthChecks.Publisher.ApplicationInsights/ApplicationInsightsPublisher.cs#L40

All you need to do is call TelemetryConfiguration.CreateDefault(), which is the newer way of getting a TelemetryConfiguration if none was provided (after static was deprecated)

**Comment by CarlosLanderas** [comment]
Hello @joshlang, you are right but, the thing is I do not like the idea of creating the necessary components for a healthcheck to work, but just request them to the service provider. Doing this drove us to face this Deprecated static method. And TelemetryClient.CreateDefault() could be the next

**Comment by CarlosLanderas** [comment]
@unaizorrilla  what do you think about this?

**Comment by joshlang** [comment]
I'm actually confused as to why you don't just inject `TelemetryClient`, but I admit I have no real knowledge of your codebase.

**Comment by joergjo** [comment]
Remember that App Insights doesn't require an IKey to be configured to work for local development, and that is actually a useful feature. IMHO, components depending on App Insights should follow that principle.
