### ISSUE TITLE
TaskCanceledException when stopping

### ISSUE THREAD

**Issue by hayer** [Xabaril/AspNetCore.Diagnostics.HealthChecks#376]
Getting a TaskCanceledException when stopping the webapp using Ctrl+C.

**Comment by CarlosLanderas** [comment]
Maybe I can't see it but what is exactly the benefit or not throwing/ logging an exception for a background service being that you are completely stopping the server?

**Comment by joshlang** [comment]
Stopping a service doesn't necessarily mean you want to immediately and ungracefully exit the application with an error code

**Comment by CarlosLanderas** [comment]
I agree, but in the case of the UI, that is retrieving checks to be rendered in the front-end spa and that data is cleaned on every startup...

I do not see any advantage from swallowing the exception when the server is stopping when you don't use any code to handle the task cancelled exception and where there is no need to handle data correctness or assure a critical process finished

@unaizorrilla what's your opinion?

**Comment by unaizorrilla** [comment]
PR is merged!

IMHO, the benefit on this is remove unnecessary noise from the logger and also allow write some code to gracefully shutdown when become necessary.

**Comment by hayer** [comment]
Sorry, been off GitHub for some days now. My problem with it was that when I was running in ISExpress and stopped the application while debugger was attached it threw the exeception - everytime. Was just annoying.

**Comment by unaizorrilla** [comment]
Already committed
