### ISSUE TITLE
AspNetCore.HealthChecks.Publisher.ApplicationInsights - 3.0.2 doesn't handle missing telemetry key

### ISSUE THREAD

**Issue by ianjirka** [Xabaril/AspNetCore.Diagnostics.HealthChecks#380]
In my startup code, I don't provide a telemetry key to AI if the environment is Development.  So far this has worked fine.

With AspNetCore.HealthChecks.Publisher.ApplicationInsights v 3.0.2, I get the below exception.  3.0.1 does not have this behavior.

Can you confirm if this is a bug or if I need to change how I do startup to not configure AI health checks in this case?

Thanks much.

-------

  Error Message:
   System.AggregateException : One or more errors occurred. (Value cannot be null. (Parameter 'No instrumentation key was provided in options or constructor'))
---- System.ArgumentNullException : Value cannot be null. (Parameter 'No instrumentation key was provided in options or constructor')
  Stack Trace:
     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at test.WebServerUnitTests.ConfigureWebSite() in C:\rep\uhe.infra.patterns\test\UnitTests\WebsiteUnitTests.cs:line 73
----- Inner Stack Trace -----
   at HealthChecks.Publisher.ApplicationInsights.ApplicationInsightsPublisher..ctor(IOptions`1 telemetryConfiguration, String instrumentationKey, Boolean saveDetailedReport, Boolean excludeHealthyReports)

**Comment by sungam3r** [comment]
Relates to #372 and #373

**Comment by CarlosLanderas** [comment]
@ianjirka, Microsoft now recommends relaying in Dependency injection to retrieve TelemetryConfiguration after TelemetryConfiguration.Active has been deprecated:

https://github.com/microsoft/ApplicationInsights-dotnet/issues/1152

. By using:

```csharp
services.AddApplicationInsightsTelemetry();
```
You can directly setup your configuration from appsettings or use the setup method to provide instrumentation key.

https://docs.microsoft.com/es-es/azure/azure-monitor/app/asp-net-core

**Comment by ianjirka** [comment]
@CarlosLanderas - I agree, and this is what I currently do.  I just do not set the telemetry key in the Development environment to avoid the number of things that need to be set up during development.

**Comment by joshlang** [comment]
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/373 will fix it if it's accepted

**Comment by CarlosLanderas** [comment]
@joshlang, I am going to submit a new PR that will no have the throw exception, but we are going to relay on DI and not going to use TelemetryClient.CreateDefault static, as Microsoft good practice is using Options<TelemetryConfiguration>

**Comment by joshlang** [comment]
Nope, it's okay.  I'm not particularly attached to my solution, and I'm happy to see yours get preference - the important thing is that it's fixed.  You're also more familiar with the preferences & styles of this repo!

Thanks!!
