### ISSUE TITLE
HealthChecks.UI.dll has a wrong version in package 3.0.8

### ISSUE THREAD

**Issue by fleed** [Xabaril/AspNetCore.Diagnostics.HealthChecks#384]
The assembly contained in the `HealthChecks.UI 3.0.8` Nuget package has a wrong version:

`HealthChecks.UI, Version=3.0.5.0, Culture=neutral, PublicKeyToken=null`

This ends up with a runtime exception if I publish and run the application:

```
Unhandled exception: System.IO.FileLoadException: Could not load file or assembly 'HealthChecks.UI, Version=3.0.8.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'HealthChecks.UI, Version=3.0.8.0, Culture=neutral, PublicKeyToken=null'
   at CliApp.Startup.ConfigureServices(IServiceCollection services)
```

The workaround that I found is to reference the package **3.0.5**, but that's not the ideal solution.

**Comment by unaizorrilla** [comment]
Hi @fleed 

I create a simple project to check this and all is working fine and version in packages are ok. Can you clean your project and check again, if the problem persist, can you send a repro of this?

![image](https://user-images.githubusercontent.com/1630008/71443139-910da180-2709-11ea-9b47-dd2c40ef4d17.png)

**Comment by CarlosLanderas** [comment]
@fleed, this is very weird, as package versions are in sync with dependencies.props and it is not a manual and error prone process. 

As Unai suggests, I would try to clean the solution.

Thanks

**Comment by fleed** [comment]
Hi @CarlosLanderas 
Thank you for replying.
I tried running a `dotnet clean`, but I will try again cleaning the nuget packages
