### ISSUE TITLE
Timeline not loading

### ISSUE THREAD

**Issue by FedericoJoseLucia** [Xabaril/AspNetCore.Diagnostics.HealthChecks#391]
Im working with one of your samples and I cant make the timeline to work. The ui loads fine, but the timeline appears empty. I've tried working this out with the "HealthCheckDatabaseConnectionString" but that doesn't appear to be the problem.

**Comment by CarlosLanderas** [comment]
Are you using the UI.Branding sample that has random healthchecks?
If you are using a sample where health checks never fail nothing will appear in the timeline as it only shows the healthchecks status changes

**Comment by FedericoJoseLucia** [comment]
No, I made sure to make it fail and succeed several times, but the timeline is empty.

**Comment by CarlosLanderas** [comment]
Strange. I've tested it and it's working. Could you upload a repro project to github?

**Comment by FedericoJoseLucia** [comment]
I cant right now, i'll try later. Is there any sqlite configuration needed?

**Comment by rajeshkandati** [comment]
Can you direct me on how to setup HealthCheckDatabaseConnectionString? I am using Azure SQL and HealthCheckExecutionHistories table is empty even though I tried to fail health checks several times. Also, the Timeline is empty.

**Comment by CarlosLanderas** [comment]
This is being investigated here:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/559
