### ISSUE TITLE
2.2.0 Latest release

### ISSUE THREAD

**Issue by abraxas79713** [Xabaril/AspNetCore.Diagnostics.HealthChecks#392]
I have noticed that the methods (AddKey, AddCertificate) within the AzureKeyVaultOptions class are not available in the NugetPackage release 2.2.0 is it possible to get a release for this?

Thanks

**Comment by CarlosLanderas** [comment]
Sure. We can cherry-pick those changes and emit a new 2.2 release. I'll do it ;)
