### ISSUE TITLE
Prometheus integration

### ISSUE THREAD

**Issue by SbiCA** [Xabaril/AspNetCore.Diagnostics.HealthChecks#4]
Hi I was just wonder about how you'll integrate Prometheus in the port. 

Do you have plans to port the PrometheusTracker? I was also kind of wondering if would be of interest to have a Prometheus"ResponseWriter" so that you could expose the metrics for the HealthCheck as straight Prometheus metrics.

**Comment by unaizorrilla** [comment]
Hi @SbiCA 

Yeap, is our idea to port the prometheus tracker but, a new ResponseWriter can be also a very good idea instad of using prometheus gateways..
PR are wellcome of course

thanks
Unai

**Comment by unaizorrilla** [comment]
Close because the feature is merged. 

Thanks again @SbiCA
