### ISSUE TITLE
Azure Table storage check cannot find table

### ISSUE THREAD

**Issue by adamoisescu** [Xabaril/AspNetCore.Diagnostics.HealthChecks#400]
We have an issue after upgrading AspNetCore.HealthChecks.AzureStorage
to Version="3.0.1". Our table storage health check returns this error:  "Table 'ourtablename' not exists."

Downgrading the package to AspNetCore.HealthChecks.AzureStorage
to Version="3.0.0" fixes the issue.

**Comment by unaizorrilla** [comment]
Hi @adamoisescu

I just tested the healthcheck and is working fine.

```
services.AddHealthChecks()
                .AddAzureTableStorage("DefaultEndpointsProtocol=https;AccountName=[account];AccountKey=[secret];EndpointSuffix=core.windows.net", "ourtablename");

```

The error "Table XX not exist" is default error when the table does not exist in the storage account, this error is from code:

```
 var table = blobClient.GetTableReference(_tableName);
                    if (!await table.ExistsAsync())
                    {
                        return new HealthCheckResult(context.Registration.FailureStatus, description: $"Table '{_tableName}' not exists");
                    }
```

Can you add more information on this issue, try to create a repro app or show us the code?

**Comment by adamoisescu** [comment]
Hello,

I found the issue. We didn't pay attention to the method's signature. Sorry for this.

In 3.0.1 the method signature is: 
`public static IHealthChecksBuilder AddAzureTableStorage(this IHealthChecksBuilder builder, string connectionString, string tableName = null, string name = null, HealthStatus? failureStatus = null, ...)`
whereas in 3.0.0 it was:
`public static IHealthChecksBuilder AddAzureTableStorage(this IHealthChecksBuilder builder, string connectionString, string name = null,  HealthStatus? failureStatus = null, ... )`

We had a custom name set for the HealthCheck and now we were sending that as tableName. The danger of automatic nuget packages update combined with optional params and code that's not breaking :D

Btw, prior to 3.0.1 how did the check actually check the table without a name?

**Comment by CarlosLanderas** [comment]
Thanks for the additional information @adamoisescu . Closing the issue :)
