### ISSUE TITLE
.net core 3 single file deployment with custom css and Windows service

### ISSUE THREAD

**Issue by mariopasquali** [Xabaril/AspNetCore.Diagnostics.HealthChecks#402]
Hello,

Great project!

I am having troubles when deploying using single file exe as Windows service with custom css.  Long story short, when ran as Windows service, the current directory is c:\windows\system32.  The issue with custom css is:

```csharp
public Options AddCustomStylesheet(string path)
{
    var stylesheetPath = Path.Combine(Environment.CurrentDirectory, path);
    ...
```
I can't specify a path like desired (such as in appdata, based on the entrypoint, etc) due to the `Path.Combine(Environment.CurrentDirectory, path)`.  This looks very limiting with limited gain.  If this behavior has to be retained for backward compatibility, I would recommend at the minimum checking `IsPathRooted` (which is better than `IsPathFullyQualified` in this specific case). 

Thank you

**Comment by CarlosLanderas** [comment]
@mariopasquali would this work for you?. For retrocompatibility, if you dont qualify the path, it would use the current directory, and if you do it would use the given path. I've been able to load css files from other hard disks:

```csharp
   public Options AddCustomStylesheet(string path)
        {
            string stylesheetPath = path;

            if(!Path.IsPathFullyQualified(stylesheetPath))
            {
                stylesheetPath = Path.Combine(Environment.CurrentDirectory, path);
            }

            if (!File.Exists(stylesheetPath))
            {
                throw new Exception($"Could not find style sheet at path {stylesheetPath}");
            }
            
            CustomStylesheets.Add(stylesheetPath);
            
            return this;
        }

**Comment by mariopasquali** [comment]
Hi @CarlosLanderas, thanks, yes this helps!

**Comment by CarlosLanderas** [comment]
Thanks @mariopasquali. Commited!. It will be published soon. Be tuned!
