### ISSUE TITLE
Update nuget for Azure Storage

### ISSUE THREAD

**Issue by ranouf** [Xabaril/AspNetCore.Diagnostics.HealthChecks#408]
The new version of Azure storage is available here:
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/README.md

Could you update your service:
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.AzureStorage/AzureBlobStorageHealthCheck.cs

(same for table storage and queue)

Thanks

**Comment by CarlosLanderas** [comment]
Hello @ranouf. We are going to bump all healthchecks versions and UI to 3.1 and upgrade all package dependencies soon. Thanks for reporting!
