### ISSUE TITLE
Possible to customize the description text cell?

### ISSUE THREAD

**Issue by CarljohanDanling** [Xabaril/AspNetCore.Diagnostics.HealthChecks#409]
I'm wondering if its possible to customize the layout and structure of how the text for the description row is shown in the HealthChecksUI webpage?

It would be nice to be able to make new lines if you want to display a collection of description text. In our project we collect data from microservices. If we would get, lets say 5 types of parameters that we would like to show in the description text row, like it is now everything comes on a single row. To make it easier to read, we have concatenate each string with some spaces or "-" characters between each string, but it would be easier to read if each string had its own row.

If someone knows how to implement this or any workaround, please share :)

**Comment by CarlosLanderas** [comment]
@CarljohanDanling this is not currently supported but we will have it in consideration for the next UI version. All the  UI resources are embedded in the assembly and we might need to introduce some kind of component configurer in C#.

We will have this in consideration. 
Thanks!
