### ISSUE TITLE
HealthCheck UI SQLite Error

### ISSUE THREAD

**Issue by IsaacWalker** [Xabaril/AspNetCore.Diagnostics.HealthChecks#411]
Howdy,

I'm trying to add a the UI to the health checks in an  Asp.Net Core 3.1 Project, and I'm running into this error:
![image](https://user-images.githubusercontent.com/36536997/74091535-72dce480-4ab0-11ea-8780-3040ca65915a.png)

Which, when viewed in the browser console:

![image](https://user-images.githubusercontent.com/36536997/74091546-90aa4980-4ab0-11ea-9624-7aea0aa7f27b.png)

...and following the 500 error gives:

![image](https://user-images.githubusercontent.com/36536997/74091562-c7805f80-4ab0-11ea-90e8-98e540757e81.png)

I'm certain that its not the Health Checks causing the issue as they work independently, at /health.

The health checks are configured as follows:
ConfigureServices:
```cs
            //adding health check services to container
            services.AddHealthChecks()
            .AddCheck<PrinterHealthCheck>(nameof(PrinterHealthCheck))
            .AddCheck<SchedulerHealthCheck>(nameof(SchedulerHealthCheck));

            services.AddHealthChecksUI("healthchecksdb", setupSettings: options => 
            {
                options.AddHealthCheckEndpoint("Health Check Endpoint", "http://localhost:62397/health");
            });
```
Configure:
```cs
            app.UseHealthChecks("/health", new HealthCheckOptions()
            {
                ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
            });

            app.UseHealthChecksUI(options =>
                 options.UIPath = "/health-ui"
            );
```
Any ideas what could be causing this error with the SQLite database?

**Comment by unaizorrilla** [comment]
Hi,

Can you share with us more info? A repro project?

Is like some exception with sqlite when evaluate the health checks! Can you try sample projects, UIandApi is like you are trying to do!

**Comment by IsaacWalker** [comment]
Okay I think I found the culprit, you should be able to reproduce it by adding the following reference:
``
 <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="3.1.1" />
``
This of course has a further dependency on Microsoft.EntityFrameworkCore.InMemory v3.1.1.
Now, changing it to the version used in HealthCheck.UI (3.0.0) fixes the problem, and is using that version of EF is fine for what I'm doing.

Moving forward now would be to ensure that the current version of HealthChecks.UI is compatible with the newest version of EFCore.

**Comment by CarlosLanderas** [comment]
@IsaacWalker your code shows custom healthchecks (Printerhealthcheck, schedulerHealthcheck)
As Unai suggested, we would need to see some code or repro project to help you.

As 30 days has passed we temporaly close the issue. Feel free to open it if you need more help
