### ISSUE TITLE
Prometheus-Net 3.x is not supported

### ISSUE THREAD

**Issue by jessie7216** [Xabaril/AspNetCore.Diagnostics.HealthChecks#419]
The AspNetcore.HealthChecks.Publisher.Prometheus package does not support the latest Prometheus-Net versions of 3.x. 

It causes an exception to be thrown in LivenessPrometheusMetrics.cs at 
Registry = DefaultCollectorRegistry.Instance; 
and makes the package unusable.

**Comment by unaizorrilla** [comment]
Hi @jessie7216 

I'm on contact with @RonnyAnc  to update the new package (pull model) to prometheus 3 version packages.

**Comment by Daniel15** [comment]
I'm working on this. Will send a PR shortly!

**Comment by CarlosLanderas** [comment]
Great @Daniel15 !

**Comment by Daniel15** [comment]
Fixed by #528

**Comment by RonnyAnc** [comment]
Sorry people, I just could not do this last weekend. If you need something I could help this week.

**Comment by RonnyAnc** [comment]
The prometheus-net version was older in my pr because I respected the same that was already in the repository for the Prometheus.Publisher module, I forgot to ask for that. I agree, for this new package, should be the last one. Sorry for the delay 🙏

**Comment by RonnyAnc** [comment]
Thank you @Daniel15 for fixing this! :)

**Comment by unaizorrilla** [comment]
Hi @RonnyAnc 

Can you review also the P ? , I try to do a review and merge this week, but because you are the initial contributor of this will be good more eyes on this!
