### ISSUE TITLE
AspNetCore.HealthChecks.IdSvr package does not exists on the NuGet.org feed

### ISSUE THREAD

**Issue by draganjovanovic1** [Xabaril/AspNetCore.Diagnostics.HealthChecks#42]
Package `AspNetCore.HealthChecks.IdSvr` is listed in the readme file but it does not exist on the [NuGet.org feed](https://www.nuget.org/packages?q=AspNetCore.HealthChecks.IdSvr)

**Comment by unaizorrilla** [comment]
Is OpenIdConnectServer, I try to fix readme
