### ISSUE TITLE
healthchecksdb in memory?

### ISSUE THREAD

**Issue by brianmat** [Xabaril/AspNetCore.Diagnostics.HealthChecks#420]
Is this possible?  If so, what would the connection string look like since I have not yet been able to get this to work.  Trying to sort out if this is a technical limitation or a syntax issue on my end with the connection.

**Comment by CarlosLanderas** [comment]
Hello @brianmat. The UI works with sqlite right now and there is not option to use it in in memory. However, we might introduce the feature in the future as there are several feature requests for this.

Thanks!
