### ISSUE TITLE
using health checks offline / without internet --> icons not visible/do not appear

### ISSUE THREAD

**Issue by zegroz** [Xabaril/AspNetCore.Diagnostics.HealthChecks#422]
Hi, 

I have following issue: 
On the page there are the icons for some actions like + for add_circle_outline or - for remove. 
But in case there is no internet connection instead of these icons the word for these icons appear, e.g. instead of the add icon + the word "add_circle_outline" appears insted, see also screenshot.

used project was directly from   Xabaril / AspNetCore.Diagnostics.HealthChecks github **HealthChecks.UIAndApiCustomization** sample.

To reproduce: Either disable internet connection or 
comment out of the line:
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">`

![health_check](https://user-images.githubusercontent.com/5676113/75111628-7f2e7900-563c-11ea-9dd6-5ddc787b0dfd.png)

Any idea?
Thanks in advance.

**Comment by CarlosLanderas** [comment]
This comes from UI Version 2.0 new look and feel. @evacrespo I'm gonna put this resources inside the assembly as everything else

**Comment by unaizorrilla** [comment]
Hi @CarlosLanderas , any update on this?

**Comment by CarlosLanderas** [comment]
@zegroz thanks for reporting the issue. I'll have in consideration this problem for the next version UI. The current UI version have embedded all resources (css, js, html) within the assembly and this requires to expand the code to support woff2 files and we might change the current UI for the next version.

Thank you very much for reporting and we add this to triage :)

**Comment by CarlosLanderas** [comment]
This will be fixed in the new UI version. Icons will be embedded in js the bundle.

**Comment by RenoHoangmotivesvn** [comment]
@CarlosLanderas Hi Sir, how can I change the icon in HealthCheck UI?

**Comment by sesausmd** [comment]
2024: still the same error here.
How can I fix it?
![image](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/133007328/8e66a361-cdec-40ab-946e-b1700fded019)

**Comment by abdullahilter** [comment]
![uirerror](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/5087654/3feeefd1-1aac-4013-9265-147043f165b6)

Same story.

framework;
net8.0

packages;
"AspNetCore.HealthChecks.UI" Version="8.0.0"
"AspNetCore.HealthChecks.UI.Client" Version="8.0.0"
"AspNetCore.HealthChecks.UI.InMemory.Storage" Version="8.0.0"

**Comment by gleneccles** [comment]
Same here. New person here who just installed from nuget. Seems we are missing resources. I am seeing add_circle_outline and check_circle instead of icons.

**Comment by burnchar** [comment]
Same issue here. Fresh install. Icons do not work. Instead, the page shows "remove_circle_outline" and "menu_open" etc.

**Comment by StandBackBurrito** [comment]
I am seeing the same issue with version 8.0.1

**Comment by edcsu** [comment]
For those still facing the issue [check](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/2130#issuecomment-1870639531)
