### ISSUE TITLE
[Question] Node Healthcheck behind load balancer

### ISSUE THREAD

**Issue by amccool** [Xabaril/AspNetCore.Diagnostics.HealthChecks#425]
I'm looking to not only track the overall health of a url, but also track the health of the nodes behind a load balancer.

normally I would use something like (executed from a machine inside my network):
`curl --resolve api.biz.cc:443:<the internal ip, rather than the vip> https://api.biz.cc/api/healthcheck`

Is this something that this package can handle?   I didnt see anywhere that I can explicitly override the DNS.   Note that I want to hit both the vips and the internal ips.

**Comment by unaizorrilla** [comment]
Hi @amccool 

I'm sorry, but I don't understand the scenario, can you explain a bit more?

**Comment by amccool** [comment]
Typically I will use a common DNS name which refers to the vip of the load balancer.   However I would also like to test the node's endpoints as well, by bypassing the load balancer.  To do that I need to override the DNS entry to point at the individual node endpoints.   This is something that is supported?

**Comment by amccool** [comment]
looks like alot more configuration would be needed to support this.   Closing and adding a feature request, as the question is answered.
