### ISSUE TITLE
[Application Insights] Ability to use ITelemetryInitializers in HealthChecks.Publisher.ApplicationInsights

### ISSUE THREAD

**Issue by SpaceOgre** [Xabaril/AspNetCore.Diagnostics.HealthChecks#426]
We have a ITelemetryInitializer that we hook up to AI using DI in startup.cs to add extra information to our telemetry. But HealthChecks.Publisher.ApplicationInsights does not add them to its TelemetryConfiguration.

I would like an option to either use the default TelemetryConfiguration instead of creating a new one (this would be enough for our use case) or pass in a list of ITelemetryInitializer during config that is added to the TelemetryConfiguration that is created.

I'm more than willing to do either of these things and create a PR.

**Comment by unaizorrilla** [comment]
Hi @SpaceOgre 

AI publisher use DI to get configured telemetry configuration, our AddApplicationInsightPublisher get the TelemetryConfiguration from the configured options.

You can see it on

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/2a66bc9588701f7a50d33eb2652727a562ce5f33/src/HealthChecks.Publisher.ApplicationInsights/DependencyInjection/ApplicationInsightsHealthCheckBuilderExtensions.cs#L28

And used on 

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/2a66bc9588701f7a50d33eb2652727a562ce5f33/src/HealthChecks.Publisher.ApplicationInsights/ApplicationInsightsPublisher.cs#L30

**Comment by SpaceOgre** [comment]
Hi @unaizorrilla, 

The configuration you get from DI is only used to get the InstrumentionKey here (what I can see from looking the code over at least) 

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/2a66bc9588701f7a50d33eb2652727a562ce5f33/src/HealthChecks.Publisher.ApplicationInsights/ApplicationInsightsPublisher.cs#L122

You then create a new TelemetryConfiguration using this key, and do not use the one from DI. As far as I know and results from testing this means that registered ITelemetryInitializers in DI are not applied to the telemetry sent by your publisher.

If you for instance change this:
`new TelemetryConfiguration(_telemetryConfiguration?.InstrumentationKey)`
to
`_telemetryConfiguration`
Then you get all the ITelemetryInitializers and other config done.

**Comment by unaizorrilla** [comment]
True, i'm sorry !

I accept a PR on this change if your are able to do that, if not I try to perform this change!

**Comment by SpaceOgre** [comment]
I hope I will get time for it tomorrow, if so how would you like it to work? A new bool that activates this usage of the DI configuration maybe?
I guess that there might be other people using this publisher that would not like all of their other config in the health check telemetry. So a way to opt in or opt out would be good.

I guess you could see the instrument key parameter as this already as it requires the creation of a new configuration anyway. And before you used the Active singleton so it would then work like it did before. 

But it is your repo so I would like to do it in a way that matches how you usally does these kind of changes.
