### ISSUE TITLE
Azure Storage Table with storage emulator does not work

### ISSUE THREAD

**Issue by tomkerkhove** [Xabaril/AspNetCore.Diagnostics.HealthChecks#428]
Azure Storage Table with storage emulator does not work as it creates invalid JSON responses:
> SyntaxError: JSON.parse: end of data after property value in object at line 15 column 44 of the JSON data

We are using this for local development, however, using a real storage account works fine.

**Comment by CarlosLanderas** [comment]
Thanks for reporting. I'll give.it a try

**Comment by CarlosLanderas** [comment]
@tomkerkhove, I am using Windows Azure Storage Emulator 5.10.0.0 and it's working for me.

```csharp
services.AddAzureBlobStorage("UseDevelopmentStorage=true", "superblobs");
```

![image](https://user-images.githubusercontent.com/16475649/76470058-f65f5d80-63ef-11ea-8847-8accfb55c5c7.png)


Could you give me more information. Emulator version, HealthChecks and endpoints configuration etc?.

Thanks

**Comment by tomkerkhove** [comment]
Clearly I was having a bad day, closing as it works fine - Sorry!
