### ISSUE TITLE
Shared MongoDB hosts fail health check due to permissions

### ISSUE THREAD

**Issue by claytondus** [Xabaril/AspNetCore.Diagnostics.HealthChecks#43]
In a shared hosting environment such as MLab, the MongoDB health check will fail if the user does not have permissions to ListDatabases().

```
mongodb: {
data: { },
description: "Command listDatabases failed: not authorized on admin to execute command { listDatabases: 1 }.",
duration: "00:00:00.1014917",
exception: "Command listDatabases failed: not authorized on admin to execute command { listDatabases: 1 }.",
status: "Unhealthy"
},
```
I could prepare a MongoDbSingleDatabaseHealthCheck that would call GetDatabase() and ListCollectionsAsync() to work around this issue.

**Comment by unaizorrilla** [comment]
Hi @claytondus 

I pushed a new version for MongoDb 2.2.1 (building at this moment) , in this version you can specified a database name when register the healthcheck. If database name is specified the health check list this database collection instead list all databases.


Please close this issue if is resolved!

**Comment by claytondus** [comment]
Works as expected, thanks.
