### ISSUE TITLE
Memory Usage Increasing Health Check UI

### ISSUE THREAD

**Issue by p0onage** [Xabaril/AspNetCore.Diagnostics.HealthChecks#436]
Hello,

I've noticed this running a health check UI on the following NuGet package versions 

    <PackageReference Include="AspNetCore.HealthChecks.EventStore" Version="2.2.2" />
    <PackageReference Include="AspNetCore.HealthChecks.UI" Version="2.2.32" />

and on 

    <PackageReference Include="AspNetCore.HealthChecks.EventStore" Version="3.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI" Version="3.0.9" />

As I watch in the memory diagnostics tool I notice the memory creeping up, is this expected?  

I notice that there is a healthcheckdb now, does this get written to constantly in memory causing this gradual increment?

**Comment by p0onage** [comment]
I've just found multiple calls in the code base to 	`services.AddHealthChecks()` could that cause a memory leak issue with registering it multiple times?

i.e

**Comment by CarlosLanderas** [comment]
Hello @p0onage .

AddHealthChecks() is a package from Microsoft and should be called only once. After AddHealthchecks you should register all your healthchecks all together as you can see in this sample:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/samples/HealthChecks.UI.Branding/Startup.cs#L29
