### ISSUE TITLE
Nuget conflict between MySql.Data and MySqlConnector in AspNetCore.HealthChecks.MySql

### ISSUE THREAD

**Issue by udlose** [Xabaril/AspNetCore.Diagnostics.HealthChecks#437]
I am using the AspNetCore.HealthChecks.MySql package v3.0.1 and getting a package conflict against my MySql nuget package v8.0.19:

> The type 'MySqlCommand' exists in both 'MySql.Data, Version=8.0.19.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d' and 'MySqlConnector, Version=0.56.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92'

**Comment by CarlosLanderas** [comment]
Hello @udlose , this is now an issue with healthchecks. Is an issue you are suffering because you are also using MySql.Data package. I recommend you follow this steps:

https://stackoverflow.com/questions/48683241/the-type-mysqlconnection-exists-in-both-mysql-data-issue
