### ISSUE TITLE
[UI] No endpoints when using a non-conformant healthcheck endpoint

### ISSUE THREAD

**Issue by amccool** [Xabaril/AspNetCore.Diagnostics.HealthChecks#438]
I have several websites with handrolled healthchecks.  their output looks like this:
`{"utcTime":"2020-03-05T23:02:17.5793442Z","machine":"DODAD","version":{"major":3,"minor":1,"build":0,"revision":32,"majorRevision":0,"minorRevision":32}}`

When I add these endpoint to the UI, I get `NullReferenceException` in my debug output, and the UI doesnt render any endpoints at all.

`settings.AddHealthCheckEndpoint("xxx", new Uri("https://olderwebsite/api/healthcheck").ToString());
`

HealthChecks.UI.Core.HostedService.HealthCheckCollectorHostedService: Error: HealthCheck collector HostedService threw an error: Object reference not set to an instance of an object.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at HealthChecks.UI.Core.Notifications.WebHookFailureNotifier.GetFailedMessageFromContent(UIHealthReport healthReport) in C:\Users\alexm\source\repos\AspNetCore.Diagnostics.HealthChecks\src\HealthChecks.UI\Core\Notifications\WebHookFailureNotifier.cs:line 124
   at HealthChecks.UI.Core.Notifications.WebHookFailureNotifier.NotifyDown(String name, UIHealthReport report) in C:\Users\alexm\source\repos\AspNetCore.Diagnostics.HealthChecks\src\HealthChecks.UI\Core\Notifications\WebHookFailureNotifier.cs:line 41
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.Collect(CancellationToken cancellationToken) in C:\Users\alexm\source\repos\AspNetCore.Diagnostics.HealthChecks\src\HealthChecks.UI\Core\HostedService\HealthCheckReportCollector.cs:line 65
   at HealthChecks.UI.Core.HostedService.HealthCheckCollectorHostedService.Collect(CancellationToken cancellationToken) in C:\Users\alexm\source\repos\AspNetCore.Diagnostics.HealthChecks\src\HealthChecks.UI\Core\HostedService\HealthCheckReportCollectorHostedService.cs:line 87
```

UIHealthReport.Entries is null in
```
        private string GetFailedMessageFromContent(UIHealthReport healthReport)
        {
            var failedChecks = healthReport.Entries.Values
                .Count(c => c.Status != UIHealthStatus.Healthy);

            return $"There are at least {failedChecks} HealthChecks failing.";
        }
```

**Comment by amccool** [comment]
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs#L91

looks like because my endpoints returns valid json,  the deserializer honors it, but doesn't fully create a valid object you were expecting (e.g. Entries is null and the TotalDuration is TimeSpan.Zero (the default))

**Comment by amccool** [comment]
does https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/246 address my issue?

**Comment by CarlosLanderas** [comment]
@amccool the UI only works with the UIClient package response writer. It can't work with custom hand rolled Healthchecks outputs as it does not know the format

**Comment by CarlosLanderas** [comment]
@amccool can you show some code to show the healthchecks configuration and the ui configuration?

**Comment by amccool** [comment]
`https://xxx/api/healthcheck`
returns
`{"utcTime":"2020-03-05T23:02:17.5793442Z","machine":"DODAD","version":"major":3,"minor":1,"build":0,"revision":32,"majorRevision":0,"minorRevision":32}}`

UI setup
```
 services.AddHealthChecksUI("healthcheckdb", settings=> {
                settings.AddHealthCheckEndpoint("xxx", new Uri("https://xxx/api/healthcheck").ToString());
```

**Comment by CarlosLanderas** [comment]
@amccool in that lines of code you are only wiring the services in the IServiceCollection. I need to see also the HealthChecks configuration (AddRedis, AddCustomHealthCheck, etc) and the endpoints mapping MapHealthChecks, MapHealthchecksUI, etc

**Comment by amccool** [comment]
so that's the point.    I'm not using a `compliant` healthcheck endpoint.   I'm using a self rolled endpoint.  My endpoint returns json data that does NOT deserialize into `UIHealthReport`.

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs#L91

when my endpoint's json is returned
`                var healthReport = await response.As<UIHealthReport>();`
`healthReport` is a default object ..... with a `Status` of `Unhealthly`

**Comment by CarlosLanderas** [comment]
The UI does not support retrieving non compliant formats from health checks endpoints. I think is obvious.

**Comment by CarlosLanderas** [comment]
```csharp
                .AddHealthChecks()
                .AddSqlServerHealthCheck(cnnString)
                .AddCheck<CustomHealthCheck>("random1", tags: new[] { "custom" })
```
```csharp
config.MapHealthChecks("/health-random", new HealthCheckOptions
                   {
                       Predicate = r => !r.Tags.Contains("custom"),
                       ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
                   });
```

**Comment by amccool** [comment]
How can I add older WCF based services?  How can I add nodejs endpoints?

**Comment by CarlosLanderas** [comment]
This is an AspNetCore HealthChecks platform that extends Microsoft package  Microsoft.Extensions.Diagnostics.HealthChecks. The supported platforms are .net core 3.1, 3.0 and 2.2.

We started this project called [Beatpulse](https://github.com/Xabaril/BeatPulse) but then we aligned with Microsoft to extend their abstractions and libraries.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.diagnostics.healthchecks.healthcheckservice?view=dotnet-plat-ext-3.1

The goal of this project is being the main Asp.Net Core HealthChecks repository, avoiding users to reimplement the wheel for the same services all the time and offer an standard UI to display your HealthChecks. If you want to support other platforms or services with this UI you need to follow the json payload formats and the UI will be able to consume it.

**Comment by amccool** [comment]
ok - I think that answers it.   Only AspNetCore Healthcheck's content is supported for Healthchecks.UI.
