### ISSUE TITLE
Published app trying to create SqlLite on c:\

### ISSUE THREAD

**Issue by asfaya** [Xabaril/AspNetCore.Diagnostics.HealthChecks#44]
Hi guys,
I tried the health checks locally on my dev machine and everything worked great.
I'm deploying this to my staging server and the app is trying to create the Sql Lite DB on the root of c:
This is what I find on the app log:

---------------------------------------------------------
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.2.0-rtm-35687 initialized 'HealthChecksDb' using provider 'Microsoft.EntityFrameworkCore.Sqlite' with options: None
fail: Microsoft.EntityFrameworkCore.Database.Connection[20004]
      An error occurred using the connection to database 'main' on server 'C:\healthchecksdb'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
---------------------------------------------------------
Any idea on why it is trying to create it outside the app folder?
Is there any way I can change this?
Thanks!

**Comment by carlowahlstedt** [comment]
I'm seeing something similar. I'm running on a Windows Server on IIS. I gave the app pool user to the folder, without any luck.

<img width="750" alt="image" src="https://user-images.githubusercontent.com/2687687/50185675-77f83680-02e6-11e9-8fe1-c64042567906.png">

**Comment by unaizorrilla** [comment]
The database path is extracted from HostDefaults.ContentRootKey, this value depend on if the project is hosted in-process or not and the configured value for this setting.

You can modify or use the method UseContentRoot in your CreateWebHostBuilder to modify the application content root.

```
            services.AddDbContext<HealthChecksDb>(db =>
            {
                var contentRoot = configuration[HostDefaults.ContentRootKey];
                var path = Path.Combine(Path.GetDirectoryName(contentRoot), databaseName);
                db.UseSqlite($"Data Source={path}");
            });
```

I'm also on the way to push a new feature to configure the database path and also if this database is on memory or persisted

**Comment by unaizorrilla** [comment]
Hi @asfaya , @carlowahlstedt 

Well, the code for discovery the ContentRootKey create a invalid path because Path.GetDirectoryName remove latest segment. I fixed in the new 2.2.5 version ( building at this moment ).

Also I added a new configuration setting HealthCheckDatabaseConnectionString on HealthCheckUI settings, the sample HealthCheks.UIAndApi contains this new parameter setting if you need to check howto use it.

Please close the comment if this resolve your issues.

**Comment by carlowahlstedt** [comment]
To be clear `HealthCheckDatabaseConnectionString` still relies on a SQLite database?

**Comment by unaizorrilla** [comment]
Yeap

**Comment by carlowahlstedt** [comment]
Looks like updating the package and deploying worked! Thanks!

**Comment by carlowahlstedt** [comment]
Not sure if these are releated
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/2687687/50345788-3c37b980-04fe-11e9-95ff-8caf24f453be.png">


<img width="352" alt="image" src="https://user-images.githubusercontent.com/2687687/50345778-3510ab80-04fe-11e9-8d63-c5687939a70a.png">

**Comment by asfaya** [comment]
Just downloaded
I'll let you know
