### ISSUE TITLE
Add icon for each package

### ISSUE THREAD

**Issue by a-z-hub** [Xabaril/AspNetCore.Diagnostics.HealthChecks#448]
I have suggestion to add icon for each nuget package

I think It allow to group all nuget packages in nuget.org search result and it will be more clear to find all required libraries from one owner.

**Comment by CarlosLanderas** [comment]
Yeah, I think is a great idea.
cc @unaizorrilla

**Comment by ahryshchanka** [comment]
![icon-01](https://user-images.githubusercontent.com/4180472/76697867-6b12f000-66ad-11ea-81ad-72099effa62a.png)

![icon 1 svg](https://user-images.githubusercontent.com/4180472/76697885-91389000-66ad-11ea-8d67-37f63a766cc6.png) -- github don't allow upload *.svg files, please remove .png from file name and you will get vector image

**Comment by sungam3r** [comment]
@a-z-hub I cannot download file. See #956 . I'm OK to change icon to anything; ping @CarlosLanderas
