### ISSUE TITLE
[UI] Kubernetes discovery: When namesapces values are provided, the result still shows all services

### ISSUE THREAD

**Issue by elvishsu66** [Xabaril/AspNetCore.Diagnostics.HealthChecks#449]
Hi @CarlosLanderas and the team,

I am so happy when you guys released UI 3.0.10, however, I have found a little bug and I hope you guys could assist us to fix it at your earliest convenience.

Cheers,
Elvis

---

**What happened**:

When I specified namespaces in the appsettings.jon, the end result still gives me all services instead of the services within the namespaces.

The **IOption<> pattern** could not bind IEnumerable<string> from JSON object.
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/8eedb4e96cf9079f75d519123f36ede53da46349/src/HealthChecks.UI/Core/Discovery/K8S/KubernetesDiscoveryOptions.cs#L17

**What you expected to happen**:

The [kubernetesDiscoverySettings ](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/8eedb4e96cf9079f75d519123f36ede53da46349/src/HealthChecks.UI/ServiceCollectionExtensions.cs#L50)should have valid namespaces bound with the service provider so the value [k8sNamespaces ](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/8eedb4e96cf9079f75d519123f36ede53da46349/src/HealthChecks.UI/Core/Discovery/K8S/Extensions/IKubernetesExtensions.cs#L21) in the **KubernetesHttpClientExtensions** class would not be empty.

All in all, when the Namespaces value is provided in appsettings, the discovered services should be only from the provided namespaces.

**How to reproduce it (as minimally and precisely as possible)**:

Please refer to the following values in appsettings.json

**Source code sample**:
```json
{
  "HealthChecksUI": {
    "Webhooks": [],
    "KubernetesDiscoveryService": {
      "Enabled": true,
      "InCluster": true,
      "ClusterHost": "https://kubernetes.default:443",
      "HealthPath": "healthchecks",
      "Namespaces": [ "namespace1", "namespace2" ]
    },
    "EvaluationTimeOnSeconds": 30,
    "MinimumSecondsBetweenFailureNotifications": 300
  }
}
```

**Anything else we need to know?**:

I recommend changing this from 
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/8eedb4e96cf9079f75d519123f36ede53da46349/src/HealthChecks.UI/Core/Discovery/K8S/KubernetesDiscoveryOptions.cs#L17

To

```cs
public string[] Namespaces { get; set; } = {};
```

**Environment**:

- .NET Core version: 3.0.100 +
- Healthchecks version: 3.0.10
- Operative system: Windows or Linux

**Comment by CarlosLanderas** [comment]
Hello @elvishsu66. To be honest, I reviewed the whole PR but I did not try the configurable namespaces from appsettings.json. Let me take a look and fix it. Thanks for reporting

**Comment by elvishsu66** [comment]
Hi @CarlosLanderas,

Thank you very much for the quick fix. I really appreciate your help.

Cheers,
Elvis

**Comment by CarlosLanderas** [comment]
@elvishsu66 version 3.0.11 will be published in some minutes

**Comment by elvishsu66** [comment]
@CarlosLanderas, you rock, mate.
