### ISSUE TITLE
ElasticsearchHealthCheck: Add basic auth configuration

### ISSUE THREAD

**Issue by Guymestef** [Xabaril/AspNetCore.Diagnostics.HealthChecks#45]
Hello,

Elasticsearch behind X-Pack Shield is protected with a basic auth.
Here a sample to create an ElasticClient with basic auth:

```C#
var esUri = new Uri(Configuration.Uri);
var settings = new ConnectionSettings(esUri)
     .BasicAuthentication(Configuration.UserName, Configuration.Password);
var lowlevelClient = new ElasticClient(settings);
```

Can we add this to the current ElasticsearchHealthCheck?

**Comment by unaizorrilla** [comment]
Hi @Guymestef 

Try 2.2.1 when build finish and the package come uploaded.

The elastic registration enable set new options parameters

options=>options.UseServer("uri")
or
options=>options.UseServer("uri").UseBasicAuthentication("username","password")
or 
options=>options.UseServer("uri").UseCertificate(certificate)

For back compatibility the older registration method is also present.

Please, close this if issue is solved!

**Comment by Guymestef** [comment]
Solved 👍
