### ISSUE TITLE
Not able to make authentication work with Health Check UI

### ISSUE THREAD

**Issue by kisalay1988** [Xabaril/AspNetCore.Diagnostics.HealthChecks#453]
I have created a separate .Net Core Web API which has the endpoint for the Health Check UI. This service will add individual Health Check endpoints of the individual api and show the status of all Apis in some single page. I need to restrict this UI endpoints only for a particular set of users using Windows Authentication.

I have implemented many ways but the authentication doesn't seem to be working at all. My health check UI service doesn't have any controllers as its not needed.

Any help here?

**Comment by CarlosLanderas** [comment]
@kisalay1988 , you have not filled the required fields when creating the issue, so I do not have enough information to help you. I do not know if you are using version 2.2, 3.0, your setup, what have you tried in sample source code, etc. Please, add some more information
