### ISSUE TITLE
Healthchecks do not reload configuration secrets

### ISSUE THREAD

**Issue by alexander-telegin** [Xabaril/AspNetCore.Diagnostics.HealthChecks#454]
## Description
Healthchecks cache connection strings/clients to resources which makes it impossible to react to updates in configuration.
For example Azure Key Vault (one of the .NET Core configuration providers) supports [ReloadInterval](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1#configuration-options) now. If a particular Secret were recycled it would require restarting of all Applications/Services where Healthchecks depend on it.
## Possible fix
Specify connection string as a Func and access it in the Healthcheck, e.g.:
```c#
IConfiguration config = // create configuration
// ...
    .AddCosmosDb(provider => config["CosmosConnectionString"])
```
Clients, if not created per request, need to be recycled. I do not have a simple solution for that.

**Comment by CarlosLanderas** [comment]
Hello @alexander-telegin. Our HealthChecks are public and we just offer an standard way of registering them, but you can create your own IHealthChecksBuilder extension to register the healthcheck as you wish.

For example:

```csharp
 .AddHealthChecks()
 .Add(new HealthCheckRegistration("cosmosdb", sp=> new CosmosDbHealthCheck(configuration["CosmosKey"]), failureStatus: default, tags: default))
```

**Comment by alexander-telegin** [comment]
@CarlosLanderas , thank you for quick response.
Makes sense. However, if I created a PR with such registration would you reject it with the aforementioned reason?

**Comment by CarlosLanderas** [comment]
@alexander-telegin , the thing is if we add this for one healthcheck, we should have it for the others to have a common api design. And like it's not a requested feature it might be a better choice just to create an extension method in your project to accomplish this.

**Comment by sungam3r** [comment]
Closed as answered.
