### ISSUE TITLE
HealthCheck UI - Configurable Storage Providers (InMemory, SqlServer, Postgres, Sqlite)

### ISSUE THREAD

**Issue by CarlosLanderas** [Xabaril/AspNetCore.Diagnostics.HealthChecks#455]
**What would you like to be added**:

Health Check UI Storage Providers (SqlServer, Postgres, Sqlite)

We need to start working in configurable Health Checks Database providers.

**Why is this needed**:

Right now, we only support SQLite and this is very limiting. For example Azure App Service running under linux is not compatible

We are going to allow the user configuring it's own storage provider using Entity Framework Core.

The idea is  making the UI DbContext public, configuring the default storage as "In Memory", (if we have no compatibility issues) and allow the user to override this default provider when ConfigureDbContext is configured by the user

**Comment by CarlosLanderas** [comment]
Issues related to SQLite or requesting further storage providers:

#444 
#338 
#303 
#226 
#181 
#161 
#29

**Comment by CarlosLanderas** [comment]
How do you think we should implement this feature?. Do you think we should add migrations for different providers (SqlServer, Postgres, Sqlite) inside the HealthChecks.UI assembly and expose methods such as:

```csharp
 services.AddHealthChecksUI().
  AddUISqlServerStorage(connectionString)()
````

of just make our DbContext public and let the user create their own migrations for whatever provider?

**Comment by devbrsa** [comment]
@CarlosLanderas I would say the first approach, better intention, easier to mock and extendable.

**Comment by devbrsa** [comment]
@CarlosLanderas how can I help you with such a feature?

**Comment by amccool** [comment]
```
services
 .AddHealthChecksUI()
 .AddUISqlServerStorage(connectionString)
```

This style looks best.  I personally like the extension method style on the `AddHealthChecksUI()`.   However, using the connection string directly here will limit the mocking of the dbcontext/etc for testing (not sure it matters as much for the production side).

IMHO, I think you will want a combination of both.  e.g.  add the storage dependency, then add that dependency to the HealthCheck.UI dependency.

**Comment by CarlosLanderas** [comment]
The main difference of boths approaches is, with the first one, we would be the ones creating the migrations inside the UI assembly and wiring everything internally (MigrationsAssembly, Database migrate execution, etc) and the user would be limited to the available provider migrations.

The second options requires more work for the user, but everything can be customized out of the UI (With the risk of doing it wrong).

If we stick with the second option and allow the user to create the Migrations we would still need to trigger the initial seed that feeds the storage with the configured Healthcheck and webhook endpoints.

**Comment by Phillip9587** [comment]
What's the status of this change?

**Comment by CarlosLanderas** [comment]
Waiting for feedback and opinions

**Comment by Phillip9587** [comment]
I like the first option. The fluent style keeps your package simple. If you implement the standard data providers everyone will be happy i think.

The second option would make your package more complex to configure and it would not be so straightforward as it is right now.

**Comment by Skleni** [comment]
I also prefer the first option. Don't get me wrong, but I don't want to have to think about _your_ migrations as well (if that's possible).

**Comment by Odonno** [comment]
Same. I prefer the first option to only allow the minimum options required, black box mode.

The only thing is the name of the extension method, I would prefer something like this to make it clear about the intended function:

```cs
services
  .AddHealthChecksUI(setup => 
  {
    setup.AddSqlServerStorage(connectionString);
  });  
```

**Comment by sungam3r** [comment]
First option.

**Comment by udlose** [comment]
First option - keeping things "black box" is extremely important.

**Comment by CarlosLanderas** [comment]
> Same. I prefer the first option to only allow the minimum options required, black box mode.
> 
> The only thing is the name of the extension method, I would prefer something like this to make it clear about the intended function:
> 
> ```cs
> services
>   .AddHealthChecksUI(setup => 
>   {
>     setup.AddSqlServerStorage(connectionString);
>   });  
> ```

Yes, of course this is another valid options. Thanks for the propoisal.
We are going to migrate all packages to 3.1 and start working on this feature

**Comment by devbrsa** [comment]
@CarlosLanderas are you accepting PRs only for bugfixes or improvements as well? Do you have a guideline over how to perform PRs?

**Comment by CarlosLanderas** [comment]
Work has started. We have added a HealthChecksUIBuilder se we can properly chain all the dependencies.

Follow work in this branch:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/tree/storage-providers

**Comment by kevbite** [comment]
@CarlosLanderas looking at the commits so far it seems that it's still very much dependant on Entity Framework Core, is there any plan on abstracting this away so other database providers that don't have an EF provider can be implemented?

**Comment by CarlosLanderas** [comment]
@kevbite to be honest I don't think so (at least at the moment) as several parts in the UI use EF Core. (collector, middleware, seeding, etc). What DB provider are you thinking about?

**Comment by kevbite** [comment]
@kevbite I was thinking about building support for MongoDB, I know few products out there that only has MongoDB as  backing store.
The alternative is to build a EF Core provider but that seems a bit of a roundabout way to achieve it.

**Comment by Odonno** [comment]
Well, you can maybe propose different kind of storage models and create an abstraction layer inside the library so that whatever Storage Layer, it should implement the required methods. 

I believe that EF Core will be suitable for most scenarii but you can also offer a way to let developer create their own extension method which will return the right storage layer (class) for their use case.

As an example, see:

```cs
services
  .AddHealthChecksUI(setup => 
  {
    // Provided by a HealthChecks UI package
    // Will use an EF Core implementation (or whatever)
    setup.AddSqlServerStorage(connectionString);

    // Provided by anyone
    // Will use the according implementation to store data in a mongodb instance
    setup.AddMongoDbStorage(connectionString);
  });
```

**Comment by CarlosLanderas** [comment]
HealthChecks UI 3.1.1-preview1 has support for database providers.
Please, check the updated docs and give us your feedback!

The new published packages in version 3.1.1-preview will be:

- HealthChecks.UI.InMemory.Storage
- HealthChecks.UI.SqlServer.Storage
- HealthChecks.UI.SQLite.Storage
- HealthChecks.UI.PostgreSQL.Storage

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks#ui-storage-providers
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks#ui-database-migrations
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/doc/ui-docker.md

**Comment by cesarbmx** [comment]
Getting `Unable to find package AspNetCore.HealthChecks.UI.Core` while installing the nuget

**Comment by CarlosLanderas** [comment]
@cesarbmx, let me check it, as we do not want to publish that assembly as a nuget package. Thanks!

**Comment by CarlosLanderas** [comment]
@cesarbmx, this has been solved

**Comment by cesarbmx** [comment]
@CarlosLanderas - All working.
This is a great project. Delighted by this contribution. Thanks!

**Comment by CarlosLanderas** [comment]
@cesarbmx great! Thank you voy your feedback!

**Comment by udlose** [comment]
@CarlosLanderas  any support for MySql planned?

**Comment by CarlosLanderas** [comment]
@udlose, yes, at soon at is supported in 3.0. They support 2.2 right now if I am not wrong

**Comment by udlose** [comment]
> @udlose, yes, at soon at is supported in 3.0. They support 2.2 right now if I am not wrong

Can you please clarify what you are referring to?  I am currently using MySql 5.7.12 in my .NET Core 3.1.3 application. I don't understand who the _it_ and _they_ you are referring to

**Comment by CarlosLanderas** [comment]
@udlose , let me check it, as it seems to have support for netstandard!

**Comment by CarlosLanderas** [comment]
@udlose, migrations can not be created, they need to upgrade the provider as you can read here. I forgot I faced this problem when tried to create the provider the first time:
`
Method 'get_Info' in type 'MySql.Data.EntityFrameworkCore.Infraestructure.MySQLOptionsExtension' from assembly 'MySql.Data.EntityFrameworkCore, Version=8.0.19.0, Culture=neutral, `

PublicKeyToken=c5687fc88969c44d' does not have an implementation.

https://github.com/dotnet/efcore/issues/17788#issuecomment-530733555

**Comment by CarlosLanderas** [comment]
@udlose in the issue, the suggest using 

https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql

That is a fully featured provider. I am gonna give it a try

**Comment by CarlosLanderas** [comment]
@udlose, here is the published MySql storage provider package:

https://www.nuget.org/packages/AspNetCore.HealthChecks.UI.MySql.Storage

**Comment by udlose** [comment]
> @udlose, here is the published MySql storage provider package:
> 
> https://www.nuget.org/packages/AspNetCore.HealthChecks.UI.MySql.Storage

@CarlosLanderas  Thank you so much!  I greatly appreciate your promptness :)

I'm not using EntityFramework, I assume that was an implementation/support blocker on your side?  

I will pull the package and give it a try later this week or next (have another pressing item I need to complete first).  What all do I need to do on my side to get the provider and database setup?  We are running MySql in AWS.  TIA

**Comment by CarlosLanderas** [comment]
@udlose, it automatically runs migrations against the connection string database creating all the requires tables.

**Comment by udlose** [comment]
@CarlosLanderas for the connection string I provide to the `AddHealthChecksUI` method, should it be a separate database? I don't want to provide my current application database as I am afraid the migration may cause issues to it.

**Comment by OskarKlintrot** [comment]
@CarlosLanderas Is there any way to run the migrations manually? Or better yet, generate them as you normaly do in EF? Applying migrations on startup seems a bit dangerous if you are using more than one instance...

**Comment by protradeshare-admin** [comment]
For Postgres DB, is it possible to configure any other schema then public?

**Comment by udlose** [comment]
@CarlosLanderas can you please respond to my comment from April 20th?
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/455#issuecomment-616821087

**Comment by Odonno** [comment]
Same question as @protradeshare-admin, how do we change the schema for the storage options (other than dbo for SQL Server so)?

**Comment by jeffersantoss** [comment]
Same question as @protradeshare-admin and @Odonno, I have more then one context and I intend to use the same database to store the health checks data, how can I change the schema for the storage? Because I already have a table named __EFMigrationsHistory in the public schema.
