### ISSUE TITLE
SQLServer health check Keyword not supported: 'authentication'.

### ISSUE THREAD

**Issue by EloiNmbrs** [Xabaril/AspNetCore.Diagnostics.HealthChecks#458]
Hi,

we have being using your healthchecks for quiet some time and all is great. Unfortunately our infrastructure have now guidelines to change all the accesses to our databases to use Authentication='Active Directory Password' in the connection string. We changed the connection strings and now the SQLServer Healthcheck is always returning the following error

"exception": "Keyword not supported: 'authentication'.",

looks like it can't handle the Authentication keywork in the connection string.

Any ideas on how can we fix it?

Thank you

**Comment by unaizorrilla** [comment]
Hi @EloiNmbrs 

Do you have more info about this issue? We are using System.Data.SqlClient 4.7.0 and create  a new SqlConnection, nothing more..

**Comment by iSatishYadav** [comment]
Another keyword not supported "Column Encryption Setting=Enabled" used for accessing data with Always Encrypted. Seems like underlying System.Data.SqlClient doesn't support them. @unaizorrilla Switching to Microsoft.Data.SqlClient might help?

**Comment by unaizorrilla** [comment]
Yeap, probably, I try to work on this the weekend!!

**Comment by unaizorrilla** [comment]
Hi @EloiNmbrs  @iSatishYadav 

The issue is related with System.Data.SqlClient on DotNetCore, the solution is move to use Microsoft.Data.SqlClient as @iSatishYadav  say!

https://github.com/dotnet/SqlClient/issues/11

I try to change this dependency now before the migration to 3.1 that come next week!

**Comment by unaizorrilla** [comment]
Hi @EloiNmbrs  @iSatishYadav 

 A new release build is on appveyor, when finished a new package 3.0.1 for Sql Server healthcheck will be available on NuGet.

Please close the issue if the new package solve it!

**Comment by EloiNmbrs** [comment]
Hi, sorry for the late response. I will test and let you know. 
Thank you

**Comment by EloiNmbrs** [comment]
Issue is fixed with this new version. 
Thank you!
