### ISSUE TITLE
iot hub and event hub support?

### ISSUE THREAD

**Issue by baywet** [Xabaril/AspNetCore.Diagnostics.HealthChecks#46]
Hi!
Great project we started implementing it recently and we love it so far!
Question: is support for iot/event hub in the pipes?
Thanks!

**Comment by unaizorrilla** [comment]
Hi @baywet 

EventHub is supported on AspNetCore.HealthChecks.AzureServiceBus, IoTHub is not yet implemented. You can contribute on it :)

**Comment by baywet** [comment]
@unaizorrilla thanks for the fast reply!
I just gave it another try using AddAzureEventHub with the settings from the default endpoint in the iot hub and it works like a charm!
