### ISSUE TITLE
Upgrade HealthChecks to NetStandard 2.1 and UI to netcoreapp3.1

### ISSUE THREAD

**Issue by CarlosLanderas** [Xabaril/AspNetCore.Diagnostics.HealthChecks#467]
**What would you like to be added**:

Upgrade all healthchecks to netstandard 2.1 and UI and samples to netcoreapp3.1

**Why is this needed**:

Target to latest netstandard and netcoreapp versions.
The new healthchecks nuget versions will be 3.1.X

**Comment by vip32** [comment]
why was this netstandard2.1 upgrade needed? are any new features of the new 2.1 used?
the issue is that now you enforce all packages using yours to upgrade to 2.1, which where fine on 2.0 before. also netcoreapp3.1 works fine with netstandard2.0 packages
