### ISSUE TITLE
Kafka client should be long lived

### ISSUE THREAD

**Issue by mhowlett** [Xabaril/AspNetCore.Diagnostics.HealthChecks#470]
Please, fill the following sections to help us fix the issue

**What happened**:

The root cause of an incident in confluent cloud (a kafka hosting service) was traced back to a high rate of new connections due to this library. Constructing a Kafka client is very expensive, and you should generally only do this once per application instance if you can.

can you use a long lived singleton instance (perhaps via a wrapper injected via DI?) instead of creating a new producer here: https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.Kafka/KafkaHealthCheck.cs#L22 ?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Source code sample**:

**Anything else we need to know?**:

**Environment**:

- .NET Core version
- Healthchecks version
- Operative system:
- Others:

**Comment by unaizorrilla** [comment]
Hi @mhowlett 

I try to address this asap! do you have any Reference about reconnections (if needed) when connection is breaking up and wake up?

**Comment by unaizorrilla** [comment]
Hi @mhowlett 

A new release build is on appveyord, when finish a new package 3.0.2 with this fix will be available on NuGet.

**Comment by mhowlett** [comment]
thanks for the quick response! those changes LGTM.

btw: i was also going to comment that a better general purpose health check is definitely possible, however exactly what is best will take some thinking. at some point i'll do that thinking and provide some input... in the mean time, here's some commentary on why it's not obvious: https://github.com/confluentinc/confluent-kafka-dotnet/wiki/Client#can-i-use-the-net-client-to-check-if-my-kafka-cluster-is-down

**Comment by mhowlett** [comment]
> do you have any Reference about reconnections (if needed) when connection is breaking up and wake up?

the client is designed to automatically recover from any lost connections, lost brokers etc and this should be very reliable. If you were paranoid about bugs in the client, you could dispose the client and create a new instance in the event of a problem, though you should keep track of some state to rate limit this. I don't think that's necessary.
