### ISSUE TITLE
ArangoDB Health Check

### ISSUE THREAD

**Issue by mvarga6** [Xabaril/AspNetCore.Diagnostics.HealthChecks#479]
**What would you like to be added**:
A simple health check for an ArangoDb database server, implemented similarly to the other NoSql health checks.

**Why is this needed**:
Adds support for more integrations.

**Already Implemented and Tested**
I've actually already implemented this package following the conventions of the repo, including unit tests, etc. I left out a functional test tho, but that would be minimal lift to get added as well (depending if it's necessary or not).

Would a PR be welcomed for this change?

**Comment by ahryshchanka** [comment]
@mvarga6 sorry, but I did PR. I don't know will you track this issue or not. As a result, PR for ArangoDb can take a lot of time. In case you track issue -- please push your PR, I'll cancel my.
Repository authors more active when you have PR.

**Comment by mvarga6** [comment]
@ahryshchanka No worries!  I was just trying to follow the contribution guidelines of "don't push your PR".
