### ISSUE TITLE
how can one secure access to ui

### ISSUE THREAD

**Issue by dolphinsd** [Xabaril/AspNetCore.Diagnostics.HealthChecks#492]
Is there a way to secure access to healthcheck ui? 
For example, Hangfire offers an easy way to configure authorization handler.
See http://docs.hangfire.io/en/latest/configuration/using-dashboard.html#configuring-authorization

Does healthchecks have this feature?

**Comment by CarlosLanderas** [comment]
Asp.Net Core 3 has the new endpoints where you can have individual authentication and authorization with RequireAuthorization.

You have an authorization sample commented in the branding sample:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/samples/HealthChecks.UI.Branding/Startup.cs

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/samples/HealthChecks.UI.Branding/IServiceCollectionExtensions.cs

**Comment by unaizorrilla** [comment]
Close by no-reply!
