### ISSUE TITLE
ui javascript error

### ISSUE THREAD

**Issue by dolphinsd** [Xabaril/AspNetCore.Diagnostics.HealthChecks#493]
Latest live version 3.1.0 fails with javascript error:
See below, it fails in line with e = e.filter(e=>null != e);

TypeError: e.filter is not a function
    at t.LivenessPage.<anonymous> (healthchecks-bundle.js:formatted:1614)
    at Generator.next (<anonymous>)
    at r (healthchecks-bundle.js:formatted:1540)
(anonymous) @ healthchecks-bundle.js:formatted:120
r @ healthchecks-bundle.js:formatted:120
Promise.then (async)
s @ healthchecks-bundle.js:formatted:120
(anonymous) @ healthchecks-bundle.js:formatted:120
i @ healthchecks-bundle.js:formatted:120
load @ healthchecks-bundle.js:formatted:120
onPollingElapsed @ healthchecks-bundle.js:formatted:120
setInterval (async)
startPolling @ healthchecks-bundle.js:formatted:120
initPolling @ healthchecks-bundle.js:formatted:120
componentDidMount @ healthchecks-bundle.js:formatted:120
Vi @ vendors-dll.js:22
Ji @ vendors-dll.js:22
Ii @ vendors-dll.js:22
zi @ vendors-dll.js:22
os @ vendors-dll.js:22
Pn @ vendors-dll.js:22

 "healthchecks-ui-polling");
    t.LivenessPage = class extends r.Component {
        constructor(e) {
            super(e),
            this._healthChecksClient = new o.HealthChecksClient(this.props.endpoint),
            this.initPolling = this.initPolling.bind(this),
            this.onPollinIntervalChange = this.onPollinIntervalChange.bind(this),
            this.expandAll = this.expandAll.bind(this),
            this.collapseAll = this.collapseAll.bind(this);
            const t = localStorage.getItem(u) || 10;
            this.state = {
                error: "",
                livenessData: [],
                pollingIntervalSetting: t
            }
        }
        componentDidMount() {
            this.load(),
            this.initPolling()
        }
        load() {
            return i(this, void 0, void 0, function*() {
                try {
                    let e = (yield this._healthChecksClient.getData()).data;
                    e = e.filter(e=>null != e);
                    for (let t of e)
                        t.onStateFrom = `${t.status} ${s.default.utc(t.onStateFrom).fromNow()}`;
                    e && e.length > 0 && this.setState({
                        livenessData: e
                    })
                } catch (e) {
                    this.setState({
                        error: "Could not retrieve health checks data"
                    }),
                    console.error(e)
                }
            })

**Comment by CarlosLanderas** [comment]
Can you paste you configuration? It sounds like the api-path is missconfigured.

**Comment by unaizorrilla** [comment]
Close with no-reply
