### ISSUE TITLE
Could not retrieve health checks data but network tab shows successful retrieval

### ISSUE THREAD

**Issue by remy90** [Xabaril/AspNetCore.Diagnostics.HealthChecks#494]
Please, fill the following sections to help us fix the issue

**What happened**:
HealthCheckUI page displays: "Could not retrieve health checks data"

**What you expected to happen**:
Indication in healthchecksui of my apis and db in the UI. "/hc" does return the expected JSON, "/hc-ui#/healthchecks" also retrieves "/hc" JSON data successfully, as determined by monitoring the network tab.

**How to reproduce it (as minimally and precisely as possible)**:

I added the following to my Startup.cs:
```
ConfigureServices(...) { services.AddHealthChecksUI(); }
Configure(...) 
{ 
    app.UseHealthChecks("/hc", new HealthCheckOptions()
    {
        Predicate = _ => true,
        ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse,
    });
    app.UseHealthChecksUI(config =>
    {
        config.ApiPath = "/hc";
        config.UIPath = "/hc-ui";
    });
}
```
appSettings: 
```
"HealthChecks-UI": {
      "HealthChecks": [
        {
          "Name": "Ordering HTTP Check",
          "Uri": "https://localhost:44328/hc"
        }
      ]
    }
```

Following this tutorial: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/monitor-app-health

**Anything else we need to know?**:
![Screenshot 2020-04-21 12 16 51](https://user-images.githubusercontent.com/47695385/79860174-2116db80-83ca-11ea-958a-d29c7b7464c4.png)

**Environment**:

- .NET Core version: 3.1
- Healthchecks version: 3.1.0
- Operative system: Windows 10
- Others:

**Comment by CarlosLanderas** [comment]
Hello @remy90 , you are setting the same path for the healthchecks endpoint and the ui-api path.
Just remove this line, or set a different path

```csharp
  config.ApiPath = "/hc";
```

**Comment by remy90** [comment]
My first attempts were without ApiPath assignment. I don't think it's hitting /hc at all..
![Screenshot 2020-04-21 14 32 29](https://user-images.githubusercontent.com/47695385/79871881-f4b88a80-83dc-11ea-8186-99aa6269478b.png)

**Comment by CarlosLanderas** [comment]
@remy90 can you publish the whole sample so we can help you?

**Comment by remy90** [comment]
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddApplicationInsightsTelemetry();
    var migrationsAssembly = typeof(MyDbContextFactory).GetTypeInfo().Assembly.GetName().Name;
    var config = new Config();

    Configuration.GetSection("MyConfig").Bind(config);

    var connectionString = myConfig.ConnectionString;

    services.AddDbContext<MyDbContext>(ConfigureDbContext());

    services.AddAuthentication().AddAzureAd().AddCookie();
    services.AddAuthentication();
    services.AddRazorPages();
    services
        .AddHealthChecks()
        .AddCheck(
                "myDB-check",
                new SqlConnectionHealthCheck(connectionString),
                HealthStatus.Unhealthy,
                new[] { "mydb" })
        .AddSqlServer(connectionString);
    services.AddHealthChecksUI();
    services.AddControllers()
    services.ConfigureServices(Configuration);
}

public void Configure(IApplicationBuilder app)
{
    app.UseBrowserLink();
    app.UseDeveloperExceptionPage();
    IdentityModelEventSource.ShowPII = true;

    app.UseStaticFiles();

    app.UseRouting();

    app.UseCors();

    app.UseAuthentication();

    app.UseAuthorization();

    app.UseHealthChecks("/hc", new HealthCheckOptions()
    {
        Predicate = _ => true,
        ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse,
    });

    app.UseHealthChecksUI(config =>
    {
        config.UIPath = "/hc-ui";
    });
    app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllers();
        endpoints.MapControllerRoute(
                name: "default",
                pattern: "{controller=Home}/{action=Index}/{id?}");
        endpoints
                .MapRazorPages()
                .RequireAuthorization();
        endpoints.MapHealthChecks("/hc");
        endpoints.MapHealthChecksUI();
    });
}
```

**Comment by CarlosLanderas** [comment]
You are registering the healthchecks middleware twice, one with the old version and one with the new version.

You dont have to use:

```csharp
app.UseHealthChecksUI(config =>
    {
        config.UIPath = "/hc-ui";
    });
```

and 

```csharp
  endpoints.MapHealthChecksUI();
```

Please, read the docks and check the samples

**Comment by remy90** [comment]
Only made the upgrade to 3.1 in the past few days. My apologies, however that still doesn't seem to have done the trick. I've removed ```
app.UseHealthChecksUI(config =>
    {
        config.UIPath = "/hc-ui";
    });
```

and applied:
`endpoints.MapHealthChecksUI(options => options.UIPath = "/hc-ui");`

still receiving the same results as before

**Comment by CarlosLanderas** [comment]
I can help you if you share the project with a github repository, otherwise the project has a lot of custom code that I would need to check.

However, I found a problem in this line:

```csharp
  endpoints.MapHealthChecks("/hc");
```
You are not configuring the UIResponseWriter that is necessary to export healthchecks to a UI readable format, check it here:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/samples/HealthChecks.UI.Branding/Startup.cs#L80

I recommend you to read the samples as you have different flavours.

**Comment by remy90** [comment]
I clearly was using a mixture of flavours. The original article I referenced suggests it's using 3.1 based on the package references. For posterity, the following resolved my issue:

```
services.AddHealthChecksUI("healthchecksdb", setup =>
    setup.AddHealthCheckEndpoint("endpoint2", "health-process");
```
