### ISSUE TITLE
HealthChecks UI Next Version Feedback Help

### ISSUE THREAD

**Issue by unaizorrilla** [Xabaril/AspNetCore.Diagnostics.HealthChecks#50]
Hi all

We are planning to create a new milestone for HealthChecks UI with some improvements, like:

 - Better UI 
 - Enable Style customization
 - Enable Company Branding
 - More features in the UI
    - show some old states
    - create failure notifiers from the ui

We are delighted to receive your suggestions!

**Comment by CarlosLanderas** [comment]
Ping @evacrespob

**Comment by HalidCisse** [comment]
Health history graph, Uptime percentage on the UI
Example:
![image](https://user-images.githubusercontent.com/6313791/50379439-b91f7c00-0641-11e9-9b68-3e7b096194a9.png)

**Comment by evacrespob** [comment]
M

**Comment by espenrl** [comment]
Authenticated access by OAuth2 would be nice. The information can reveal a lot of interesting information for malicious users.

**Comment by CarlosLanderas** [comment]
@espenrl that's something we had on beatpulse but is not ready on Microsoft Healthchecks API. They told me they are waiting for asp.net core 3.0 that will have middleware authorization not coupled to MVC so we will have it soon

**Comment by rickvi1** [comment]
Maybe it's an idea to order the items in the UI on health state. Unhealthy services will then show up on the top and are better visible when you have a long list of monitored services.

**Comment by espenrl** [comment]
Taking up the issue with authenticated access again. I finally understand that we were discussing two different issues last time.

A) Data is collected from the health check endpoints and put into the database.
B) Health Check UI pulls the data from the database and show it to the user.

I was thinking of case B.  It would be nice if the Health Check UI would require me to login and redirect to an STS (OAuth2). And then use the token returned to access `/healthchecks-api`.



---
I've already taken care of A) myself by hooking into the HttpClient used by HealthCheckReportCollector. Thank you for using a named HttpClient :)

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/38dc6e1c409d2066adffd744a230f4827d2a2083/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs#L38

**Comment by JustBasics96** [comment]
@espenrl 
I think the login on the authentication is a smaller problem.

When using Azure, AWS or some other cloud service, with a bearer token protection, the HealthCheck-API can't access the NetCore HealthCheck. So a middleware, to provide an authentication header is still needed.

**Comment by espenrl** [comment]
@JustBasics96 

Here is how I add a bearer token to the requests done by HealthCheckReportCollector.

``` CSharp
services.AddTransient<HealthChecksHttpClientHandler>()
                .AddHttpClient("health-checks") // HealthChecks.UI.Keys.HEALTH_CHECK_HTTP_CLIENT_NAME
                .AddHttpMessageHandler<HealthChecksHttpClientHandler>();
```

https://gist.github.com/espenrl/bf214bbbd99c83af77278baf1219f1a3 (HealthChecksHttpClientHandler)

**Comment by CarlosLanderas** [comment]
One of the ideas I was talking the other day with @evacrespob is revamping the whole UI interface and redesign the styles to sass files using BEM naming, so consumers can load local a css stylesheet to the UI middleware to be able to rewrite all configurable styles (tables, logo image, colors, etc)...

We will start working on vnext UI next week

**Comment by Snoopysgit** [comment]
it would be great to have an addon to forward result of the healthchecks-ui to azure application insights. Right now this can be done on each individual healthcheck. This works fine, but it does not cover cases where the service is not reachable at all (the custom events during this time are just missing).

As the healthchecks-ui is also like a monitoring watchdog, it could send custom events to azure with additional information like:
- last successful execution time
- up since
- down since
- test duration
- ...
this would greatly increase the possibilities to create diagrams in azure.

**Comment by loweware** [comment]
Including the data/details of each health check as part of the row expansion. Having a single portal to view all health check data would be nice, instead of having to hit multiple urls to get detailed information.

**Comment by tellybrown** [comment]
Add/Edit Urls via the UI.  Config file would load the base URL's but more could be added via UI.  I have a production team that manages all this stuff and would be nice to just add/edit urls on the fly without having to push new config to production.  Production is behind a firewall so no direct communications.

**Comment by tellybrown** [comment]
Grouping of urls would be nice.  Even if it is just encoding the current name with the grouping name.

example:
 "HealthChecks": [{"Name": "DEV - my service", "Uri": "http://test.com"}]
or
 "Groups": ["Name": "DEV",  "HealthChecks": [{"Name": "my service", "Uri": "http://test.com"}]]

**Comment by SychevIgor** [comment]
Allow "/" for UIPath option 
 app.UseHealthChecksUI(config => {
                //config.UIPath = "/";
            });
Scenario: API, without any views. On a start page we wanna show health check result, but library implementation forcing us to setup spmething else.

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/351f7d2b626c4cb009bc260a429b08560b67cfa1/src/HealthChecks.UI/ApplicationBuilderExtensions.cs

` Action<string, string> ensureValidPath = (string path, string argument) =>
             {
                 if (string.IsNullOrEmpty(path) || !path.StartsWith("/"))
                 {
                     throw new ArgumentException("The value for customized path can't be null and need to start with / characater.");
                 }
             };

            ensureValidPath(options.ApiPath, nameof(Options.ApiPath));
            ensureValidPath(options.UIPath, nameof(Options.UIPath));`

**Comment by snavarropino** [comment]
Allow us to define in the UI different EvaluationTimeOnSeconds and MinimumSecondsBetweenFailureNotifications for each healthcheck uri 

Something like this:
```json
  "HealthChecks-UI": {
    "HealthChecks": [
      {
        "Name": "Api",
        "Uri": "https://healthchecksapi.azurewebsites.net/healthCheck",
        "EvaluationTimeOnSeconds": 5,
        "MinimumSecondsBetweenFailureNotifications": 60
      },
      {
        "Name": "AnotherApi",
        "Uri": "https://healthchecksanotherapi.azurewebsites.net/healthCheck",
        "EvaluationTimeOnSeconds": 10,
        "MinimumSecondsBetweenFailureNotifications": 120
      }
    ],
  }
```

**Comment by roblangston** [comment]
It would be nice to have an overall health status at the top of the page for situations where you might be monitoring multiple services from the same page.  This would reflect the lowest health status across all of the monitored services.  It would be especially helpful when some of the services with a problem might be displayed off the bottom of the page so there wouldn't be a visual cue unless scrolling down.

**Comment by ruant** [comment]
Authentication headers on the HTTP queries the UI makes.
