### ISSUE TITLE
Change the title of the web interface

### ISSUE THREAD

**Issue by JessySaint** [Xabaril/AspNetCore.Diagnostics.HealthChecks#501]
**A way to customize the title of the web interface, from "Health Checks UI" to a custom title**:

**This would be usefull for other languages, or even like if we want to plublish mutiple applications for different health checks**:

![2020-04-24 10_45_42-Health Checks UI](https://user-images.githubusercontent.com/64267169/80225341-ef478400-8618-11ea-8c6d-e4fb2d1d6bdd.png)

Thank you,

**Comment by CarlosLanderas** [comment]
Easy to implement. All right 👍

**Comment by CarljohanDanling** [comment]
> 
> 
> Easy to implement. All right 👍

Great! I've also wanted to customize it :)

**Comment by CarljohanDanling** [comment]
While on interface topic, I would like to be able to change the favicon. Is that easy to implement? @CarlosLanderas

**Comment by unaizorrilla** [comment]
Hi @CarlosLanderas is this implemented? Can i close the issue?

**Comment by gabrielmaldi** [comment]
> While on interface topic, I would like to be able to change the favicon. Is that easy to implement? @CarlosLanderas

You can just place a `favicon.ico` file at the root folder of your static files and browsers will pick it up.

**Comment by gabrielmaldi** [comment]
I submitted #731 to address this issue.

**Comment by vickpto** [comment]
@CarlosLanderas 
@MCKanpolat

Guys do you know when this change could be available?
I downloaded the last version of the library and is not available yet

**Comment by MCKanpolat** [comment]
Hi @vickpto,

Still waiting this PR.

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/731
