### ISSUE TITLE
IHttpContextAccessor in custom HealthCheck

### ISSUE THREAD

**Issue by cesarbmx** [Xabaril/AspNetCore.Diagnostics.HealthChecks#502]
I am trying to use IHttpContextAccessor in one custom HealthCheck but it does not get injected.
I am calling `services.AddHttpContextAccessor();` during startup.

Error:
`System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'HealthChecks.SslCertificateHealthCheck'.`

![image](https://user-images.githubusercontent.com/1844530/80249079-321c5280-863f-11ea-9ede-4ba4659e560a.png)

**Comment by CarlosLanderas** [comment]
Why using the accessor? The HealthCheck collection (both in Microsoft HealthChecks and the UI) is triggered from a hosted service. There is no request http context attached

**Comment by cesarbmx** [comment]
Thanks for the quick reply.
Since the library is primarily API based, I thought there would be an HttpContext. 

I need a different approach, then. Would it be possible to pass a configuration parameter  on Startup via `.AddCheck<SslCertificateHealthCheck>("SSL certificate");`? 
Otherwise, I will just inject `IConfiguration ` in my custom HealthCheck and grab the value.

Thanks!
