### ISSUE TITLE
Creating NuGet package generates warning NU5125: The 'licenseUrl' element will be deprecated.

### ISSUE THREAD

**Issue by manne** [Xabaril/AspNetCore.Diagnostics.HealthChecks#505]
The build contains a warning for each NuGet package being created.

```
Successfully created package 'C:\Users\ZZZ\Documents\GitHub\Xabaril_AspNetCore.Diagnostics.HealthChecks\artifacts\AspNetCore.HealthChecks.Gcp.CloudFirestore.3.1.1.nupkg'.
C:\Program Files\dotnet\sdk\3.1.201\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead. [C:\Users\ZZZ\Documents\GitHub\Xabaril_AspNetCore.Diagnostics.HealthChecks\src\HealthChecks.Gcp.CloudFirestore\HealthChecks.Gcp.CloudFirestore.csproj]
```

**What would you like to be added**:
It is actually a change.
Replace the line
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/4a08e828a784cb4c6e6e4da1b915fa4625ecc8de/build/dependencies.props#L10

with 
```XML
<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
```

Or the license file could be packaged and be added to the package information with

```XML
<PackageLicenseFile>LICENSE</PackageLicenseFile>
```

For more information, see [NuGet - Packing a license expression or a license file](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file)

**Why is this needed**:
To get rid of the warnings

If there is a decision and a change is wanted, I can provide a PR

**Comment by unaizorrilla** [comment]
Hi @manne 

A PR is welcome for this! THANKS!

**Comment by manne** [comment]
@unaizorrilla 
which option
A) `<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>` or
B) `<PackageLicenseFile>LICENSE</PackageLicenseFile>`

**Comment by unaizorrilla** [comment]
A
