### ISSUE TITLE
Clean health check project files

### ISSUE THREAD

**Issue by manne** [Xabaril/AspNetCore.Diagnostics.HealthChecks#506]
**What would you like to be added**/changed:
In a comment of my PR https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/504#pullrequestreview-400411374. I copied, pasted and adapted the lines https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/4a08e828a784cb4c6e6e4da1b915fa4625ecc8de/src/HealthChecks.IdSvr/HealthChecks.IdSvr.csproj#L2-L16.
As sungam3r annotated the following properties are overriding itself, therefore not needed and can be deleted.
- PackageLicenseUrl
- PackageProjectUrl
- RepositoryUrl
- Company
- Authors
- PublishRepositoryUrl
- AllowedOutputExtensionsInPackageBuildOutputFolder

A quick analysis shows that 43 `csproj` files contain `<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>`. Removing these properties will introduce some noise in a possible PR, merge conflicts in open PRs.

**Why is this needed**:
To make adding new project files to the repo and PR reviews more efficient

***How should we handle this situation?***
Some possible solution which came into my mind
- Leave it as it is
- Make several PRs 
- Make one PR

I am up to proposals, discussions, ... .

**Comment by sungam3r** [comment]
Option 3.

**Comment by manne** [comment]
@sungam3r I am workin on a PR

I stumbled across this:
What's the reason that in some project the `LangVersion` is declared to `Latest` and in some it is not? Should I centralize this property into `Directory.Build.props`?

**Comment by sungam3r** [comment]
> What's the reason that in some project the LangVersion is declared to Latest and in some it is not? 

I think it is just copy-paste stuff.

> Should I centralize this property into Directory.Build.props?

I think yes.

**Comment by unaizorrilla** [comment]
Yeap!
