### ISSUE TITLE
Error on AddSqliteStorage

### ISSUE THREAD

**Issue by Sokhz** [Xabaril/AspNetCore.Diagnostics.HealthChecks#510]
Hello,

**Versions :**
AspNetCore.HealthChecks.UI : 3.1.0
AspNetcore.HealthChecks.UI.SQLite.Storage : 3.1.1-preview3

My problem : 
I try to add SQLite storage supports to my HealthChecksUI.

Documentation says :
```csharp
services
    .AddHealthChecksUI()
    .AddSqliteStorage($"Data Source=sqlite.db");
```

Looking into the code in the repo, you have thoses extensions : 
```csharp
public static HealthChecksUIBuilder AddHealthChecksUI(this IServiceCollection services, Action<Settings> setupSettings = null)
```

```csharp
public static HealthChecksUIBuilder AddSqliteStorage(this HealthChecksUIBuilder builder, string connectionString, Action<DbContextOptionsBuilder> configureOptions = null)
```

When I F12 on `AddHealthChecksUI` in my solution, it shows:
```csharp
public static IServiceCollection AddHealthChecksUI(this IServiceCollection services, string databaseName = "healthchecksdb", Action<Settings> setupSettings = null);
```

The extension `AddSqliteStorage` is on type `HealthChecksUIBuilder`. But `AddHealthChecksUI` returns an `IServiceCollection` in my solution. So i cannot call `AddSqliteStorage` method.

**Comment by Sokhz** [comment]
I had to use preview too for the main package.

**Comment by CarlosLanderas** [comment]
Yeah, all related storage provider packages are on preview right now :)
