### ISSUE TITLE
Configuration is not updated when an endpoint URI changes

### ISSUE THREAD

**Issue by Skleni** [Xabaril/AspNetCore.Diagnostics.HealthChecks#513]
**What happened**:

When the URI of a health check endpoint is changed, this change is not reflected in the database and the calls are still made to the old URI.

**What you expected to happen**:

I would expect the health check UI to use the updated URI.

**How to reproduce it (as minimally and precisely as possible)**:

* Add a health check: `settings.AddHealthCheckEndpoint("Test", "http://localhost:5000/health");`
* Start the project, the health check is shown
* Stop
* Change the uri (for example, change the code to `settings.AddHealthCheckEndpoint("Test", "https://localhost:5001/health");`
* Start again
The calls still go out to `http://localhost:5000/health`, which is also still present in the Configurations table in the database.

The same problem occurs when the endpoints are configured using the app settings.

**Environment**:

- .NET Core version 3.1
- Healthchecks version: 3.1.1-preview4
- Operative system: Windows 10

**Comment by CarlosLanderas** [comment]
@Skleni take a look at this:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/454

**Comment by Skleni** [comment]
Thanks, but I'm not talking about changing it at runtime, but between application starts. That should work, shouldn't it?

**Comment by CarlosLanderas** [comment]
Thanks for the explanation @Skleni. Yes!. it is definitely something we can add with little effort. In current storage providers preview, only new healthchecks are added. We should check if name already exists and be able to update the URI.

**Comment by CarlosLanderas** [comment]
healthchecks-ui-3.1.1-preview5 is being published with this change included.

**Comment by Skleni** [comment]
Thanks, I'll give it a try ASAP. :)

**Comment by Skleni** [comment]
Works great! :)

**Comment by CarlosLanderas** [comment]
Thanks for reporting @Skleni !
