### ISSUE TITLE
404 Loading UI Resources

### ISSUE THREAD

**Issue by eddiederk** [Xabaril/AspNetCore.Diagnostics.HealthChecks#52]
My API application is configured to run below the root web app. e.g.: https://MyCoolApp.com/API
When I try and view the UI the page returns 404 for all of the resources because the page is trying to load the resources using the root web application. 
https://MyCoolApp.com/ui/resources/bootstrap-min.css
instead of https://MyCoolApp.com/api/ui/resources/bootstrap-min.css

I have tried to update the settings / configuration to no avail.
How do I configure the UI to reference the correct url?

Thanks

**Comment by unaizorrilla** [comment]
Could you use apipath and UI path on UseHealthChecksUI to add the api segment?

**Comment by CarlosLanderas** [comment]
@eddiederk un UseHealthChecksUI setup you have the UIResources path setting that will serve the UI resources on the configured path. You can configure /API/UI/resources

**Comment by unaizorrilla** [comment]
@CarlosLanderas , 

 On index.html, probably the uiResourcePath is not well formed when the site is under a not root segment. Can you checkout this?

 <link rel="stylesheet" href="#uiResourcePath#/bootstrap-min.css"/>

**Comment by CarlosLanderas** [comment]
Ok, bug reproduced @eddiederk . Lets us fix it.

**Comment by CarlosLanderas** [comment]
Here is the commit 
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/commit/2323ce5354dc646a3f9d458b042c7276e8e8f58d

@unaizorrilla  double check it please.

If modified the webhooks page mount point as well so it works with segments.

**Comment by unaizorrilla** [comment]
Hi  @CarlosLanderas  @eddiederk 

I pushed some minor changes, create a customization sample and update the ui version package.
When the [release build ](https://ci.appveyor.com/project/Xabaril/aspnetcore-diagnostics-healthchecks/builds/21267944) finished  a new package 2.2.8 fix this issue, please @eddiederk close if work for you!

**Comment by eddiederk** [comment]
Hey @CarlosLanderas and @unaizorrilla  Thanks for the quick response and updates.
I am getting 200 responses now however there is one last issue:
healthchecks-bundle.js doesn't contain the expected javascript but the json from the healthchecks-api xhr request.

UI is configured using the defaults. `app.UseHealthChecksUI()`

This only happens when not configured under the "not root segment"
![image](https://user-images.githubusercontent.com/12239329/50520371-2c2f5500-0a7d-11e9-8f70-ac66235637c4.png)

So it works in my development environment but not in production.

Thanks again for your assistance.

**Comment by unaizorrilla** [comment]
Hi @eddiederk 

I don't understand this 
"healthchecks-bundle.js doesn't contain the expected javascript but the json from the healthchecks-api xhr request."

Can you explain more the issue or the steps to reproduce this?

**Comment by eddiederk** [comment]
This is an odd one. If you browse to the following url you will see what i mean
https://schedule.sportdash.com/api/healthchecks-ui
the webpage downloads the following js file
https://schedule.sportdash.com/api/healthchecks-ui/healthchecks-bundle.js
The content of the file is not javascript but json.

**Comment by lurumad** [comment]
Hi @eddiederk 

I've tested in my IIS and works fine.

Please, can you stop the site, delete healthchecksdb and start again.

Regards!

**Comment by unaizorrilla** [comment]
Hi @eddiederk 

Yes, try to remove the healthchecksdb and restart the site, right now your sql server is reponding ok, If you modify the settings, please remove the healthchecksdb file.


![image](https://user-images.githubusercontent.com/1630008/50522272-59eebb00-0aca-11e9-8099-19e27cf8c71d.png)

**Comment by eddiederk** [comment]
What URL are you using?
when I browse to https://schedule.sportdash.com/api/healthchecks-ui I get a blank screen

**Comment by unaizorrilla** [comment]
I thinks you configured well the project right now, https://schedule.sportdash.com/api/healthchecks-ui, the ui is reac don't use IE, use Chrome or any other modern browser


![image](https://user-images.githubusercontent.com/1630008/50522540-c74f1b80-0acb-11e9-81c6-a1249659cf11.png)

**Comment by eddiederk** [comment]
Ohh yeesh CloudFlare cached the file. I purged the cache and the site is loading correctly now.
Thanks guys. Sorry for the extra trouble.
I will now close out the issue!

**Comment by unaizorrilla** [comment]
Thanks @eddiederk

**Comment by conort** [comment]
Hey guys,

Im having a similar issue, on latest available version 2.2.27 - has this been resolved? (version 2.2.8 does not seem to be available - unless its a pre-release candidate/nightly feed somewhere)

Within Startup I have:

app.UseHealthChecksUI(config =>
            {
                config.UIPath = "/watchdog/hc-ui";
                config.ResourcesPath = "/ui/resources";
            }); 

I get:
http://me-local.mydomain.com:381/watchdog/ui/resources/healthchecksui-min.css net::ERR_ABORTED 404 (Not Found)
http://me-local.mydomain.com:381/watchdog/ui/resources/vendors-dll.js net::ERR_ABORTED 404 (Not Found)
http://me-local.mydomain.com:381/watchdog/ui/resources/healthchecks-bundle.js net::ERR_ABORTED 404 (Not Found)
http://me-local.mydomain.com:381/watchdog/ui/resources/bootstrap-min.css net::ERR_ABORTED 404 (Not Found)
http://me-local.mydomain.com:381/watchdog/ui/resources/vendors-dll.js net::ERR_ABORTED 404 (Not Found)
http://me-local.mydomain.com:381/watchdog/ui/resources/healthchecks-bundle.js net::ERR_ABORTED 404 (Not Found)

Sources in Chrome seem to have watchdog/hc-ui  while is fine, then in watchdog/ui/resources route I get bootstrap-min.css & healthchecksui-min.css within root without any content

**If I have config.UIPath = "/watchdog/hc-ui"; & config.ResourcesPath = "/";**
I get:

http://me-local.mydomain.com:381/bootstrap-min.css net::ERR_ABORTED 404 (Not Found)
http://me-local.mydomain..com:381/healthchecksui-min.css net::ERR_ABORTED 404 (Not Found)
http://me-local.mydomain..com:381/vendors-dll.js net::ERR_ABORTED 404 (Not Found)
http://me-local.mydomain..com:381/healthchecks-bundle.js net::ERR_ABORTED 404 (Not Found)

Sources in Chrome seem to have watchdog/hc-ui  while is fine, then in route I get bootstrap-min.css & healthchecksui-min.css within root without any content

**If I have config.UIPath = "/watchdog/hc-ui"; & config.ResourcesPath = "/watchdog";**
I get:
Failed to load resource: the server responded with a status of 404 (Not Found)
healthchecksui-min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
healthchecks-bundle.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap-min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
vendors-dll.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
healthchecks-bundle.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap-min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
healthchecksui-min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)

Under Sources in Chrome have directory watchdog/hc-ui  & watchdog/watchdog/bootstrap-min.css and watchdog/watchdog/healthchecksum-min.css alone (empty content)

Suspect just having 

app.UseHealthChecksUI(config =>
            {
                config.UIPath = "/watchdog/hc-ui";
            }); 

or

app.UseHealthChecksUI(config =>
            {
                config.UIPath = "/watchdog/hc-ui";
                config.ResourcesPath = "/whatever;
            }); 

should work. 

Thanks

**Comment by unaizorrilla** [comment]
Hi, the samples works well for you?  Can you try without customize UIPath and ResorucesPath?

**Comment by conort** [comment]
Hi @unaizorrilla,

Yeah the samples work ok but they are not exactly catering for what I need.

For example I need the ui component to be of a specific path: (just using name watchdog here as an example)
http://me-local.mydomain.com:381/watchdog/healthchecks-ui

if leave defaults then
http://me-local.mydomain.com:381/healthchecks-ui
works perfectly well or if I use

app.UseHealthChecksUI(config =>
{
  config.UIPath = "/hc-ui";
});

http://me-local.mydomain.com:381/hc-ui
works perfectly well (able to resolve the resources)

Just in my particular instance I cant have /hc-ui running from root. Want it to run from a path watchdog/hc-ui - but then the resources are not found.

**Comment by unaizorrilla** [comment]
Can you try without customize config?

**Comment by conort** [comment]
Without customize config eg:

app.UseHealthChecksUI();

It works as expected, but I need to configure if to run from a specific path.
eg:

domain.com/somethingSpecific/healthchecks-ui
and not
domain.com/healthchecks-ui

So I have tried will all the above examples in my initial question but all are unable to resolve the resources.

**Comment by unaizorrilla** [comment]
Let me check but probably we have a bug here!

// cc @CarlosLanderas

**Comment by Veflow** [comment]
I'm having the same issue, I'm setting the UI path on UseHealthChecksUI on a sub path (/api/dashboard/ui) and leaving the other settings as default. 

I only started having this issue after upgrading to 2.2.32. It was working fine with version 2.2.29.

**Comment by CarlosLanderas** [comment]
Could you pleade paste your UI settings and your launchsettings, right now there are more configuration options.  Thanks

**Comment by Veflow** [comment]
In my configure services:
services.AddHealthChecksUI();

In my Configure:
app.UseHealthChecksUI(options => { options.UIPath = CustomRoutes.HealthUi; })

**Comment by CarlosLanderas** [comment]
And what is the value of CustomRouters HealthUI?  🤷 Are you running the app with IIS or Kestrel?

**Comment by Veflow** [comment]
public const string HealthUi = "/api/dashboard/health";

I'm running with Kestrel right now.

**Comment by CarlosLanderas** [comment]
You cannot configure the UI with three segment levels and not configure the other paths.

Try configuring all paths and disable UseRelativePaths for all of them

**Comment by Veflow** [comment]
Thanks for the detailed explanation! The following config seems to be working for me now: 

```
                .UseHealthChecksUI(options =>
                {
                    options.UIPath = CustomRoutes.HealthUi;
                    options.ApiPath = CustomRoutes.HealthUi + "/api";
                    options.ResourcesPath = CustomRoutes.HealthUi + "/resources";
                    options.WebhookPath = CustomRoutes.HealthUi + "/webhooks";

                    options.UseRelativeApiPath = false;
                    options.UseRelativeResourcesPath = false;
                    options.UseRelativeWebhookPath = false;
                })
```

**Comment by CarlosLanderas** [comment]
@Veflow that is the idea! Totally configurable, I'm glad it's working for you :)

**Comment by CarlosLanderas** [comment]
@Veflow if all the resources are in the same path level, then you can remove the UseRelativeResources lines 👍

**Comment by Veflow** [comment]
Thanks! 🥇
