### ISSUE TITLE
EvaluationTimeInSeconds will not set

### ISSUE THREAD

**Issue by OmerNassie** [Xabaril/AspNetCore.Diagnostics.HealthChecks#520]
**What happened**:
I followed the examples and the README file, I've set the `EvaluationTimeInSeconds` property to 300 seconds but it stays on 10 seconds. I tried from Configuration file (appsettings.json) or from the setup settings function but nothing works.

**What you expected to happen**:
I would expect that the EvaluationTimeInSeconds will be changed from 10 seconds to 300.

**How to reproduce it (as minimally and precisely as possible)**:
This is my configuration in appsettings.json

```
"HealthChecksUI": {
    "HealthChecks": [
      {
        "Name": "HTTP-Api-Basic",
        "Uri": "/health"
      }
    ],
    "EvaluationTimeInSeconds": 300,
    "MinimumSecondsBetweenFailureNotifications": 60
 }
```

My configure Services:
```csharp
      public void ConfigureService(IServiceCollection services)
       {
        services.AddHealthChecks()
                    .AddSqlServer(Configuration.GetConnectionString("SqlConnection"),
                                  healthQuery: "SELECT 1;",
                                  name: "SqlServer Connection Check",
                                  failureStatus: HealthStatus.Unhealthy,
                                  tags: new string[] { "db", "sql", "sqlserver" })
                    .AddDbContextCheck<DataAccess.Data.ApplicationDataContext>("DbContext Health Check", HealthStatus.Unhealthy, tags: new string[] { "db", "sql", "efcore", "sqlserver" });
            services.AddHealthChecksUI();
     }
```

My Configure:
```csharp
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapHealthChecksUI(opts =>
                {
                    opts.UIPath = "/health-ui";
                });
                endpoints.MapHealthChecks("/health", new HealthCheckOptions()
                {
                    Predicate = _ => true,
                    ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
                });
            });
     }
```

- .NET Core version .net core 3.1
- Healthchecks version 3.1.0
- Operative system: Windows 10
- Others:

**Comment by CarlosLanderas** [comment]
Hello @OmerNassie. I'm not able to reproduce this:

Using appsettings.json:

```json
"HealthChecksUI": {
    "HealthChecks": [
      {
        "Name": "Endpoint1",
        "Uri": "/memory-health"
      }
    ],
    "Webhooks": [],
    "EvaluationTimeinSeconds": 500,
    "MinimumSecondsBetweenFailureNotifications": 60
  }

works for me.

And using 
```csharp
  .AddHealthChecksUI(setupSettings: setup =>
                {
                    setup.SetEvaluationTimeInSeconds(300);
);
```

works as well.

Could you upload a non-working sample to github?

**Comment by OmerNassie** [comment]
Hi @CarlosLanderas thanks for the quick response!
Does the Health Checks UI is correlated with the evaluation time's value?
This is what not worked for me. Without opening the health checks UI the evaluation time works perfect.

**Comment by CarlosLanderas** [comment]
@OmerNassie these are two different thinkgs. The evaluation time in seconds is used by a background hosted service to poll healthchecks endpoints.

The UI refresh every, is the rate the spa queries the healthchecks UI Api. But the UI api does no trigger the collection (only queries the last results).
