### ISSUE TITLE
PrometheusResponseWriter.WritePrometheusResultText throw TypeLoadException

### ISSUE THREAD

**Issue by zh6335901** [Xabaril/AspNetCore.Diagnostics.HealthChecks#525]
I used `AspNetCore.HealthChecks.Prometheus.Metrics` package to generate health check metrics response, but it will throw exception when access the check url.

**What happened**:
It throw `TypeLoadException` when i access the check url: 
```
TypeLoadException: Could not load type 'Prometheus.Advanced.ICollectorRegistry' from assembly 'Prometheus.NetStandard, Version=3.0.0.0, Culture=neutral, PublicKeyToken=a243e9817ba9d559'.
HealthChecks.Prometheus.Metrics.PrometheusResponseWriter.WritePrometheusResultText(HttpContext context, HealthReport report)
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(ref TStateMachine stateMachine)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<TStateMachine>(ref TStateMachine stateMachine)
HealthChecks.Prometheus.Metrics.PrometheusResponseWriter.WritePrometheusResultText(HttpContext context, HealthReport report)
Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckMiddleware.InvokeAsync(HttpContext httpContext)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Prometheus.HttpMetrics.HttpRequestDurationMiddleware.Invoke(HttpContext context)
Prometheus.HttpMetrics.HttpRequestCountMiddleware.Invoke(HttpContext context)
Prometheus.HttpMetrics.HttpInProgressMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**What you expected to happen**:
It should be generate the prometheus format response.

**How to reproduce it (as minimally and precisely as possible)**:
Just use the `PrometheusResponseWriter.WritePrometheusResultText`

**Source code sample**:
```
    endpoints.MapHealthChecks("/hc", new HealthCheckOptions()
    {
        Predicate = _ => true,
        ResponseWriter = PrometheusResponseWriter.WritePrometheusResultText
    });
```

**Anything else we need to know?**:

**Environment**:

- .NET Core version 3.1.1
- Healthchecks version 3.1.1
- Operative system: win10
- Others:

**Comment by unaizorrilla** [comment]
Hi @zh6335901 

Related with your issue, this package depends on prometheus-Net version 2.1.3, you are using 3.0.0? version? 

Also, I try to fix an issue on the extension method namespace, this package allow to use 

` app.UseHealthChecksPrometheusExporter("/prometheus")`

Instead to set the response writer, but at this moment the namespace is not the convention that we use  (use the same namespace of the object that extend ).

Can you confirm that the issue is related with the 3.0.0 version? can you downgrade to 2.1.3?

@RonnyAnc Why this package use 2.1.3 instead 3.X version? Can you send a PR to update the package dependencies?

**Comment by zh6335901** [comment]
@unaizorrilla Yes, I am using prometheus-Net 3.5.0, And I tried downgrade 2.1.3, The writer is worked.

**Comment by unaizorrilla** [comment]
I just update the package to fix the issue with namespace on extension methods, you can use 

`UseHealthChecksPrometheusExporter("/prometheus")`

Instead write 

```
    .MapHealthChecks("/hc", new HealthCheckOptions()
    {
        Predicate = _ => true,
        ResponseWriter = PrometheusResponseWriter.WritePrometheusResultText
    });
```

And also I try to contact @RonnyAnc  to get more information about prometheus package versioning
