### ISSUE TITLE
URL defined with AddUrlGroup don't get checked

### ISSUE THREAD

**Issue by trhumphries** [Xabaril/AspNetCore.Diagnostics.HealthChecks#527]
**What happened**:
I added 
            services.AddHealthChecks()
                .AddMongoDb(Configuration?.GetValue<string>("MongoDB-Supplier--ConnectionString"), "Master", "mongo db")
                .AddUrlGroup(new Uri("http://product-api-healthcheck.supplier:80/healthcheck"), "Product API");

**What you expected to happen**:
I expected it to check the url added
**How to reproduce it (as minimally and precisely as possible)**:

**Source code sample**:

**Anything else we need to know?**:

**Environment**:
Kubernetes
- .NET Core version
3.1
- Healthchecks version
3.1.1
- Operative system:
- Others:

**Comment by CarlosLanderas** [comment]
@trhumphries how are you checking the HealthCheck? Are you using the UI? Kubernetes liveness or readiness probes?
Otherwise the Healthchecks are non meant to check target services unless they are invoked.

**Comment by trhumphries** [comment]
Using the UI and is displays the MongoDB check but not the URL Check

**Comment by CarlosLanderas** [comment]
Could you paste the whole configuration then please?. Thanks

**Comment by trhumphries** [comment]
I resolved it. By cluster context had been change so when I was restarting the pod it was on the wrong cluster. Thanks!
