### ISSUE TITLE
Non-display Health Checks

### ISSUE THREAD

**Issue by trhumphries** [Xabaril/AspNetCore.Diagnostics.HealthChecks#529]
In the Health Check UI Client I'd like to be able to suppress the display of specific health checks.
For instance I'd like to add a SignalR Health check however showing that on the Web client might confuse my end users. However If I could include it in the health check and forward it to Application Insight or Prometheus I could set up an alert to trigger when the specific health check is unhealthy.
This would allow me to monitor it proactively without having my end users call up and asking what SingalR is.

**Comment by CarlosLanderas** [comment]
Hello @trhumphries 
You can actually achieve that by using different endpoints, predicates and responsewriters:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/samples/HealthChecks.UI.StorageProviders/Startup.cs#L57

You can have and endpoint with a predicate that targets the non-display healthchecks so they can be queried and other endpoint with the UI ResponseWriter excluding the non display healthchecks.

**Comment by trhumphries** [comment]
Thanks. I'll try that
