### ISSUE TITLE
Healtchecks UI does not work with alpine docker image

### ISSUE THREAD

**Issue by NazmiAltun** [Xabaril/AspNetCore.Diagnostics.HealthChecks#53]
Currently , I am using   Healtchecks UI  in my application which is running inside a docker container. 
When i use  
`FROM microsoft/dotnet:2.2-aspnetcore-runtime-alpine`
 as base image ,  the container unexpectedly exits with code 139 with no log ( not that i could see ).
However when i have changed the base image to 
`FROM microsoft/dotnet:2.2-aspnetcore-runtime`
it works fine. 
Is there any way to make it work with alpine runtime image?

**Comment by unaizorrilla** [comment]
Hi @NazmiAltun 

Probably is an issue related with culture info on alpine images. I try to reproduce this try to solve.

P.S: You can use existing docker images from https://hub.docker.com/r/xabarilcoding/healthchecksui

**Comment by unaizorrilla** [comment]
Hi @NazmiAltun 

After some investigations, the issue is related with SQLite, on Linux-Alpine the database migration throw a "cannot open database file". I try to check permissions and other workarounds but not working for me.

**Comment by twsI** [comment]
Throws an exception for me with `microsoft/dotnet:2.2.1-aspnetcore-runtime` too

**Comment by unaizorrilla** [comment]
Hi @twsl

UI is asp.net core 2.2 not 2.1

**Comment by NazmiAltun** [comment]
Hi @unaizorrilla 
After spending hours with gdb, i've come to the same conclusion. Seems like a bug related to SQLite.  I am using `microsoft/dotnet:2.2-aspnetcore-runtime`  base image at the moment and it works fine.

**Comment by unaizorrilla** [comment]
Hi @NazmiAltun 
I send a question to EF Core Team, but is not solved yet.

**Comment by twsI** [comment]
> 
> 
> Hi @twsl
> 
> UI is asp.net core 2.2 not 2.1

Im am using the latest 2.2.1 [image](https://hub.docker.com/r/microsoft/dotnet/), see [dockerfile](https://github.com/dotnet/dotnet-docker/blob/master/2.2/aspnetcore-runtime/stretch-slim/amd64/Dockerfile)

**Comment by unaizorrilla** [comment]
Hi @twsI 

I work with latest 2.2 versions and all is working for me, HeallthChecks UI exist on dockerhub with this latest versions.

Can you check the [docker file ](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/build/docker-images/HealthChecks.UI.Image/Dockerfile
)and [powershell ](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/build-docker-image.ps1 )that we use to create this?

**Comment by PedroS11** [comment]
I tried today and 2.2-alpine still throws the error. Is there any workaround apart from using 2.2 image? Because alpine version is almost half the size.

**Comment by andresrsanchez** [comment]
> I tried today and 2.2-alpine still throws the error. Is there any workaround apart from using 2.2 image? Because alpine version is almost half the size.

Net Core 3

**Comment by unaizorrilla** [comment]
I need to check if this works well on netcore3, I try to do this on a few days!

**Comment by PedroS11** [comment]
So this project will only work on dotnet core 2.2 standard docker image? Only on dotnet core 3.0 it will work with the alpine version?
