### ISSUE TITLE
Dynamically adding health check endpoints

### ISSUE THREAD

**Issue by kisalay1988** [Xabaril/AspNetCore.Diagnostics.HealthChecks#535]
**What would you like to be added**: As per current implementation, all the health check endpoints should be added while registering the HealthCheckUI middleware. Consider a case :
1. There are multiple APIs with multiple versions and their own respective Health Check JSON endpoints.
2. Depending on the case I want to filter the Health Check UI to show the data for specific versions but that's not possble as all endpoints needs to be configured when registering the UI middleware
3. Possiblity to add some custom fields to the UI like for each endpoint say, I want to add :
    a. Complete endpoint URL
    b. Date when the API was last built
    c. The username who deployed the API, etc

**Why is this needed**:
Providing more flexibility to users in customizing the UI as per needs.

I am working on an API project where I actually have such requirement. I am trying to figure out my own way to achieve it.

**Comment by CarlosLanderas** [comment]
This capability is added in our docker image as the K8s operator is able to publish discovered services to the target UI.

**Comment by kisalay1988** [comment]
Let me explain the case which I am trying to implement.

1. Say I call an API : http://localhost/api/healthcheck?version=1.1
2. This API call would collect all the API details and the health check endpoints with version 1.1 and then redirect to the UI showing the status only of these endpoints.

**Comment by NateB2** [comment]
Currently we work around this by dynamically fetching the endpoints from an external data store during startup, adding them in the startup code, and rebooting the web app if the endpoints we want to monitor changes.  Hardly ideal - having a way to dynamically add health check endpoints in some fashion would be much better. In our circumstance, we are using Azure App Services and have no plans to migrate to K8s.

**Comment by CarlosLanderas** [comment]
@NateB2, HealthChecksDb DbContext is now public. You can retrieve it using Dependency Injection and use the underlying storage provider to add, remove or edit your remote endpoints.

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.UI.Core/Data/HealthChecksDb.cs

**Comment by kisalay19** [comment]
@CarlosLanderas .. Great ... Let me implement it in my solution then and check :)

**Comment by hartmark** [comment]
For future Googlers also finding this thread.

We wanted to dynamicly add and disable healthchecks, however there's is no active-flag so we need some logic to keep the healthchecks we want to keep.

We ended up building a simple controller that first does a delete and adds back the ones we want to keep.

```
    [HttpDelete]
    [Route("AllHealthChecks")]
    public void ClearAllHealthChecks()
    {
        healthChecksDb.Configurations.RemoveRange(healthChecksDb.Configurations);
        healthChecksDb.SaveChanges();
    }
    
    [HttpPost]
    [Route("HealthCheck")]
    public void AddHealthCheck(string name, string uri)
    {
        var healthCheckConfiguration = new HealthCheckConfiguration
        {
            Name = name,
            Uri = uri
        };
        healthChecksDb.Configurations.Add(healthCheckConfiguration);
        healthChecksDb.SaveChanges();
    }

```
