### ISSUE TITLE
Support for using DelegatingHandlers in UI

### ISSUE THREAD

**Issue by OskarKlintrot** [Xabaril/AspNetCore.Diagnostics.HealthChecks#536]
**What would you like to be added**:
I want to register my own `DelegatingHandler`s.

**Why is this needed**:
You can solve everything (I think) you want to do with a `DelegatingHandler` in a `HttpClientHandler` but they have different purposes. I my case I needed to add different auth header depending on which service where going to be called. That should be in a `DelegatingHandler` and not in a `HttpClientHandler` IMHO.

**Comment by CarlosLanderas** [comment]
Hello @OskarKlintrot 

Could you try something like this?

```csharp
    public class LandeClientHandler : HttpClientHandler
    {
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var uri = request.RequestUri.AbsoluteUri;
            if (uri.EndsWith("health"))
            {
                request.Headers.Add("SuperHeader", "Health!");    
            }
            else
            {
                request.Headers.Add("SuperHeader", "SomeOtherValue");
            }
            
            return base.SendAsync(request, cancellationToken);
        }
    }
```

And then:

```csharp
 services
  .AddHealthChecksUI(setup =>
    {
     setup.UseApiEndpointHttpMessageHandler(sp => new LandeClientHandler());
   });
```

**Comment by OskarKlintrot** [comment]
That's how I solved it but as I wrote, IMHO a `HttpClientHandler` is not the right place, that's what `DelegatingHandler`s are for.

**Comment by CarlosLanderas** [comment]
Taking a look to Microsoft Docs:

**DelegatingHandler** - A class used to plug a handler into a handler chain.

**HttpClientHandler** - A class that operates at the bottom of the handler chain that actually handles the HTTP transport operations.

The difference is subtle. Could you provide more information about why you think a DelegatingHandler is better in this case? 
You just need to set a header based on the url or do you have any other requirements?

**Comment by OskarKlintrot** [comment]
Sure, "better" is a stretch but as you pointed out the HttpClientHandler is the one "that actually handles the HTTP transport operations", which I have no intention to do. My intention is to "plug a handler into a handler chain" to mutate the request. I don't care how to handle the actual HTTP-call (which is the responsibility of the HttpClientHandler), I just want to mutate the request and be done with it. So it's less about what I can or can't do with the HttpClientHandler vs DelegatingHandler, it's more about the subtile difference _why_ you, according to the docs, would use one over the other. Does that make sense?

Here is a nice poster over WebApi 2 where it's a bit easier to spot the differences between the two, it's still quite accurate for aspnet core: https://www.asp.net/media/4071077/aspnet-web-api-poster.pdf

**Comment by CarlosLanderas** [comment]
We can add this to the setup:

```csharp
 .AddHealthChecksUI(setup =>
  {
     setup.UseApiEndpointHttpDelegatingHandler(sp => new MyDelegatingHandler(innerHandler));
});
```
and I'm taking a look to the current HttpClientBuilder extensions and:


```csharp
  client.AddHttpMessageHandler(sp => {
    var settings = sp.GetService<IOptions<Settings>>();
      settings.Value.ApiEndpointDelegatingHandler?.Invoke(builder.Services) ?? 
       SomeUIDefaultDelegatingHandler;
 })
```
**AddHttpMessageHandler** requires a mandatory DelegatingHandler returned.
Maybe we can add this using:

```csharp
 .ConfigureHttpMessageHandlerBuilder(builder =>
  {
      var settings = builder.Services.GetService<IOptions<Settings>>();
      var delegatingHandler =  settings.Value.ApiEndpointDelegatingHandler?.Invoke(builder.Services) ?? null;
      if (delegatingHandler != null)
      {
           builder.AdditionalHandlers.Add(delegatingHandler);
      }
)
```

What do you think?.

cc @unaizorrilla

**Comment by OskarKlintrot** [comment]
No problem, this is quite confusing :) 

I would prefer if you could use DI [as in the docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#outgoing-request-middleware) to register them. That is really convenient. Would `settings.Value.ApiEndpointDelegatingHandler` be just one? I think you would probably want to support multiple delegating handlers.

**Comment by CarlosLanderas** [comment]
Ok, I have it running. I'll submit the PR later. This would be the API:

```csharp
.AddTransient<MyDelegatingHandler>()
                .AddTransient<MyDelegatingHandler2>()
                .AddHealthChecksUI(setup =>
                {
                    setup.UseApiEndpointHttpMessageHandler(sp => new HttpClientHandler
                    {
                        Properties =
                        {
                            ["Prop1"] = DateTime.Now
                        }
                    });

                    setup.UseApiEndpointDelegatingHandler<MyDelegatingHandler>();
                    setup.UseApiEndpointDelegatingHandler<MyDelegatingHandler2>();
```

**Comment by OskarKlintrot** [comment]
That looks beautiful! Thank you!

**Comment by CarlosLanderas** [comment]
@OskarKlintrot, I am finishing some new features in the UI and this will be included in the next release. Thanks!
