### ISSUE TITLE
Add a Cosmos DB Storage Provider

### ISSUE THREAD

**Issue by NateB2** [Xabaril/AspNetCore.Diagnostics.HealthChecks#537]
**What would you like to be added**:
EF Core Cosmos DB Storage Provider for the HealthCheck UI.  
https://docs.microsoft.com/en-us/ef/core/providers/cosmos/?tabs=dotnet-core-cli

**Why is this needed**:
We can take advantage of Cosmos collection/database pooling and not need to spin up an Azure SQL instance if our other services already use Cosmos as a data source. We also get some other benefits of Cosmos, including easy high-availability support and potentially lower latency.

**Comment by CarlosLanderas** [comment]
@NateB2 I was testing the current codebase and I am seeing the CosmosDB provider is not compatible. 

'The LINQ expression 'DbSet<HealthCheckConfiguration>.Any()' could not be translated.

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.UI/Core/HostedService/UIInitializationHostedService.cs#L66

We need to investigate this a little bit more and check that we can introduce this provider without having to change the whole codebase:

I've seen similiar issues of people having trouble with common EF operations:

https://github.com/dotnet/efcore/issues/18673

**Comment by NateB2** [comment]
Yeah, that's disappointing.  Seems like they've fixed some of those issues for the upcoming 5.0 release, so perhaps trying again in a couple months might be the way to go...

**Comment by CarlosLanderas** [comment]
Sure, we will take a look again when a new version is released :).

**Comment by NateB2** [comment]
It looks like the issue has been resolved in .NET 5: https://github.com/dotnet/efcore/issues/18673

**Comment by CarlosLanderas** [comment]
We start migrating soon. If it works we el release cosmos provider nugget ;)

**Comment by nikunj231991** [comment]
is there any update on CosmosDB Storage Provider?
