### ISSUE TITLE
WindowsServiceHealthCheck - another pc

### ISSUE THREAD

**Issue by ignatandrei** [Xabaril/AspNetCore.Diagnostics.HealthChecks#541]
**What would you like to be added**:
WindowsServiceHealthCheck can see services on another PC also.
Please add  PC  Name to the constructor in the file
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.System/WindowsServiceHealthCheck.cs

See reference at 
https://docs.microsoft.com/en-us/dotnet/api/system.serviceprocess.servicecontroller.-ctor?view=dotnet-plat-ext-3.1#System_ServiceProcess_ServiceController__ctor_System_String_System_String_

**Why is this needed**:
To make health check monitor also other PC's servoces

**Comment by CarlosLanderas** [comment]
System package 3.1.2 is being published with this enhancement. Thanks @ignatandrei
