### ISSUE TITLE
Some services are not able to be constructed

### ISSUE THREAD

**Issue by cdagdeviren** [Xabaril/AspNetCore.Diagnostics.HealthChecks#557]
Hi,

I get the error after upgrading the package

InvalidOperationException: Error while validating the service descriptor 'ServiceType: HealthChecks.UI.Core.Notifications.IHealthCheckFailureNotifier Lifetime: Scoped ImplementationType: HealthChecks.UI.Core.Notifications.WebHookFailureNotifier': Unable to resolve service for type 'HealthChecks.UI.Core.Data.HealthChecksDb' while attempting to activate 'HealthChecks.UI.Core.Notifications.WebHookFailureNotifier'.

**Comment by CarlosLanderas** [comment]
Could you paste your csproj with configured UI versions? Thanks

**Comment by cdagdeviren** [comment]
I using packages, 

    <PackageReference Include="AspNetCore.HealthChecks.System" Version="3.1.2" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="3.1.1" />
    <PackageReference Include="AspNetCore.HealthChecks.Aws.S3" Version="3.1.1" />
    <PackageReference Include="AspNetCore.HealthChecks.AzureServiceBus" Version="3.2.1" />
    <PackageReference Include="AspNetCore.HealthChecks.AzureStorage" Version="3.2.0" />
    <PackageReference Include="AspNetCore.HealthChecks.Kafka" Version="3.1.2" />
    <PackageReference Include="AspNetCore.HealthChecks.RabbitMQ" Version="3.1.2" />
    <PackageReference Include="AspNetCore.HealthChecks.SignalR" Version="3.1.1" />
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="3.1.1" />
    <PackageReference Include="AspNetCore.HealthChecks.UI" Version="3.1.1" />
    <PackageReference Include="AspNetCore.HealthChecks.Uris" Version="3.1.2" />

.net core startup configureservices,
     var healthChecksBuilder = services.AddHealthChecks()
                .AddSqlServer(connectionString: AppSettings.ConnectionStrings.Mobilbt,
                    healthQuery: "SELECT 1;",
                    name: "Sql Server",
                    failureStatus: HealthStatus.Degraded)
                .AddUrlGroup(new Uri(AppSettings.ResourceServer.Endpoint),
                    name: "Resource (Web API) Server",
                    failureStatus: HealthStatus.Degraded)
                .AddSignalRHub(AppSettings.NotificationServer.Endpoint + "/HealthCheckHub",
                    name: "Notification (SignalR) Server",
                    failureStatus: HealthStatus.Degraded)
                .AddUrlGroup(new Uri(AppSettings.BackgroundServer.Endpoint),
                    name: "Background Services Server",
                    failureStatus: HealthStatus.Degraded);

            services.AddHealthChecksUI(setupSettings: setup =>
            {
                setup.AddHealthCheckEndpoint("Basic Health Check", $"{AppSettings.CurrentUrl}/healthcheck");                
            });

stratup.cs configure
 app.UseHealthChecks("/healthcheck", new HealthCheckOptions
            {
                Predicate = _ => true,
                ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse,
                ResultStatusCodes =
                {
                    [HealthStatus.Healthy] = StatusCodes.Status200OK,
                    [HealthStatus.Degraded] = StatusCodes.Status500InternalServerError,
                    [HealthStatus.Unhealthy] = StatusCodes.Status503ServiceUnavailable,
                },
            });

            app.UseHealthChecksUI(); // /healthchecks-ui#/healthchecks

**Comment by CarlosLanderas** [comment]
@cdagdeviren if you read the DOCS, since version 3.1.1 the HealthChecks UI works with an storage provider. You can see samples here:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/samples/HealthChecks.UI.StorageProviders/Startup.cs#L43

There error that you are receiving is because no storage provider has been configured.

**Comment by cdagdeviren** [comment]
@CarlosLanderas thanks for help,

**Comment by CarlosLanderas** [comment]
@cdagdeviren you are welcome :)
