### ISSUE TITLE
Add support in the CosmosDB health check to check database / collection is present

### ISSUE THREAD

**Issue by tiesmaster** [Xabaril/AspNetCore.Diagnostics.HealthChecks#558]
**What would you like to be added**:
It would be very handy if the `CosmosDbHealthCheck` could also check if a given database is present, or collection. I saw that the `RavenDBHealthCheck` has support for checking for databases, so maybe this can also be useful for the `CosmosDbHealthCheck`.

**Why is this needed**:
You _might_ consider the existence of the database / collection to be part of being healthy for a given service, and as such, you might want to have your healthcheck  check for that.

**Comment by tiesmaster** [comment]
Awesome! I'd like to contribute, but I don't know when (I'm quite busy atm). When I get around to it, then I'll announce something here.

**Comment by dmytrohridin** [comment]
Hello
Any progress on collections present? If not - I can take a look
Thank you

**Comment by CarlosLanderas** [comment]
Looks like this was already merged
@unaizorrilla ?

**Comment by dmytrohridin** [comment]
@CarlosLanderas Database existence merged, but what about collections?

**Comment by tiesmaster** [comment]
Indeed, support for the database is in, but collections are still pending. That was going to be a follow up PR, but I haven't got any time for that yet. That's on my TODO list, but that's going to take a bit of time. If anyone else wants to pick that, then it's all yours.

**Comment by CarlosLanderas** [comment]
Yeah, I meant databases. Sorry I was reading too fast :)

**Comment by dmytrohridin** [comment]
@unaizorrilla check for collections is added, review PR, please
Thank you :)

**Comment by dmytrohridin** [comment]
cc @CarlosLanderas

**Comment by tiesmaster** [comment]
Stale
