### ISSUE TITLE
Custom header for UI

### ISSUE THREAD

**Issue by ignatandrei** [Xabaril/AspNetCore.Diagnostics.HealthChecks#562]
**What would you like to be added**:
In the page https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/6058b0cd3908a84f7d8c7faa72495d0edca80215/src/HealthChecks.UI/client/components/LivenessPage.tsx

there is a   <h1>Health Checks status</h1>

This should be replaced by a custom text that comes from a call to the http backend .(and , if the http is not 200, replaced with default text 
The endpoint could be stored in the HealthChecks.UI.Configuration.Options class( we have already there AddCustomStylesheet) 

**Why is this needed**:
1 . In order to figure what health check is ( if we have more than 1 on different PC)
2. Let the user customize his header

**Comment by CarlosLanderas** [comment]
This is gonna be added like this in version 3.1.2:

```csharp
services.AddHealthChecksUI(setupSettings: setup =>
{
  setup.SetHeaderText("Cool Health Checks Status");
 });
