### ISSUE TITLE
Ability to customize HTTP status codes for Prometheus.Metrics

### ISSUE THREAD

**Issue by epaulsen** [Xabaril/AspNetCore.Diagnostics.HealthChecks#566]
**What would you like to be added**:
Similar to the healthchecks, I would like to have the ability to map health check results to http status codes for the prometheus metrics publisher.

**Why is this needed**:
We are currently using the Prometheus health check exporters, and have configured prometheus to scrape /healthmetrics endpoint for all instances at a given interval.  This works well as long as health checks are reporting healthy or degraded, we get the metrics for individual health checks. 

However, the default behavior whenever a health check reports Unhealthy is to add a http response code of 503 service unavailable.  For prometheus, this means that the entire scrape job is aborted, and metrics are not collected for that scrape.  This means that we lose fine-grained details about which health check is failing.

I have a fix ready to go if this feature request is ok.

**Comment by wladneto** [comment]
I need this implemetation... 👍

**Comment by CarlosLanderas** [comment]
A PR for this feature is welcome. Feel free to contribute ☺️

**Comment by wladneto** [comment]
I solved with another method...

like this:
app
                .UseHealthChecks("/metrics", new HealthCheckOptions
                {
                    ResultStatusCodes =
                {
                    [HealthStatus.Healthy] = StatusCodes.Status200OK,
                    [HealthStatus.Degraded] = StatusCodes.Status200OK,
                    [HealthStatus.Unhealthy] = StatusCodes.Status200OK
                },
                    Predicate = _ => true,
                    ResponseWriter = PrometheusResponseWriter.WritePrometheusResultText
                });
