### ISSUE TITLE
Kafka Health check not working for compacted topics

### ISSUE THREAD

**Issue by KostovMartin** [Xabaril/AspNetCore.Diagnostics.HealthChecks#57]
Kafka health check is not working in the case where kafka is configured by default to create compacted topics. The reason is that compacted topics require key, but the health-check is without such. In this case we get: `ErrorCode: InvalidMsg`.
It is fairly easy to add key for the check.

**Comment by unaizorrilla** [comment]
Can you create a PR with the changes to support this scenario or a simple gist with a sample?
