### ISSUE TITLE
Event Store 20.6.0 gRPC connection support

### ISSUE THREAD

**Issue by jasonycw** [Xabaril/AspNetCore.Diagnostics.HealthChecks#572]
**What would you like to be added**: Support for gRPC connection string

Instead of `ConnectTo=tcp://localhost:1113`, now connection string will be `https://localhost:2113`

**Why is this needed**:
1. TCP is disabled on v20.6.0 by default, and deprecation of Atom and TCP
2. Introduction of a liveness health check at `{server_address}/health/live`.

Ref: 
1. https://eventstore.com/blog/event-store-20.6.0-release/
2. https://github.com/EventStore/EventStore/blob/0de1881010310c8ec8e48cc3db48ce2a2ce86e93/CHANGELOG.md

Related issue: https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/232

**Comment by unaizorrilla** [comment]
Are you able to summit a PR on this?

**Comment by unaizorrilla** [comment]
Hi @jasonycw

Are you able to send a PR on this enhacement?

**Comment by jasonycw** [comment]
Hi @unaizorrilla 
Not at the moment, since we are also trying to better implement the new Event Store library ourselves.

They changed to use SSL and dropped the old [`EventStore.ClientAPI`](https://github.com/EventStore/ClientAPI.NetCore) package support, replaced with [`EventStore.Client`](https://github.com/EventStore/EventStore-Client-Dotnet)

**Comment by unaizorrilla** [comment]
Hi @jasonycw 

Ok, I try to do that, but I'm not experienced with EventStore :-) . In your opinion, what is better to do:

 - update the current package with new 20.X version and introduce breaking changes
 - Create a new package (EventStore.Grpc) with grpc support and mantain two packages


Thanks in advance

**Comment by jasonycw** [comment]
IMO, I think it would be easier to maintain a new package since EventStore did the same.

But it would be better if we can ask more people who are also using EventStore as one opinion may not reflect on everyone usage. :)

**Comment by pmikolajczak** [comment]
Is this one worked on? I could chip in, just don't want to duplicate the work 😄 
The new package the way to go, same as ES client did. I am a heavy ES user and we do this internally as well - have separate packages for tcp and grpc clients.
