### ISSUE TITLE
>Basic Health Check Support In UI

### ISSUE THREAD

**Issue by Noer024** [Xabaril/AspNetCore.Diagnostics.HealthChecks#573]
**What would you like to be added**:
Health Check UI: A method to indicate a health check given in appsettings.json will only give a basic response. 

The given URI will respond with a simple 200 status **without** a full Health Check UI model. The Health Check UI instance considers this a healthy response still.

**Why is this needed**:
I cannot find a method of adding a URI that responds with a simple status, without content, that does not result in a JSON deserialisation error.

**Comment by unaizorrilla** [comment]
Hi @Noer024 

**HealthCheck UI** show and works **only** with Health Checks configured using our response model, https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.UI.Client/UIResponseWriter.cs
