### ISSUE TITLE
Allow for single HelathChecks k8s resource to provide healthchecks from multiple namespaces

### ISSUE THREAD

**Issue by skwasiborski** [Xabaril/AspNetCore.Diagnostics.HealthChecks#575]
**What would you like to be added**:
Add configuration to HealthChecks resource used with HealthChcecks operator that would allow to serve healthchecks from multiple namespaces.

**Why is this needed**:
I would like to have single UI showing health information for all services in the cluster.

**Comment by CarlosLanderas** [comment]
Hello @skwasiborski 
As you say, k8s resource is not cluster wide but namespace wide. I was thinking in implementing this feature some weeks again asking myself if someone could need it and here you are :)

**Comment by brechtvhb** [comment]
Would also love the possibility to have one UI that serves health checks from multiple namespaces.

**Comment by CarlosLanderas** [comment]
Hello @brechtvhb. I have already coded this and I am already testing.

There is going to be a new CRD option scalled scope (Cluster and Namespaced)

If you use Cluster, the UI will listen to all services in all namespaces:


```yaml
spec:
  name: healthchecks-ui    
  scope: Cluster
  servicesLabel: HealthChecks
  serviceType: LoadBalancer
```
