### ISSUE TITLE
Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by OmerNassie** [Xabaril/AspNetCore.Diagnostics.HealthChecks#576]
Please, fill the following sections to help us fix the issue

**What happened**:
Health checks UI has unhealthy status although the /health endpoint returns healthy. It is changed yesterday to unhealthy and no matter what I can't return it to healthy. The state is only on the server.

Moreover, there's an Endpoint row added that I didn't mention with the error:
Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

I can't figure from where is it

**What you expected to happen**:
Status healthy when /health returns healthy.

**How to reproduce it (as minimally and precisely as possible)**:
I can't produce it locally, only at the server. It seems like a cache problem or something

**Anything else we need to know?**:

**Environment**:

- .NET Core version 3.1
- Healthchecks version 3.1.5
- HealthCheckus-UI version 3.1.1
- Operative system: Azure Windows Server
- Others:

**Comment by unaizorrilla** [comment]
This error is typical when configuration is wrong ( invalid uris for heath and ui )! Can you check if our samples are working well?

**Comment by GustavoFonsecaDeAlmeida** [comment]
I had this problem in some load tests. However the reason was my proxy while the servers were overloaded and were responding too many requests.

I think it's not a health check lib problem.

**Comment by OmerNassie** [comment]
Hi guys, unfortunately it is not invalid URIs issue since in other applications the implementation works perfect.
The thing is the configured endpoint (/health) returns healthy health check while /healthchecks-api returns this error message.

I tried renaming the health endpoint, delete website cache, nothing fixes the problem.
When added more healthchecks they wasn't reflected and the error still remained

**Comment by unaizorrilla** [comment]
Hi @OmerNassie 

Are you check our samples and how to configure UI?

**Comment by attiqeurrehman** [comment]
@OmerNassie I am having the same issue and individually calling /health for other services are working fine.

**Comment by dotnetshadow** [comment]
I'm having the same issue, I've checked my urls to make sure they are correct. For me the issue happened when I added **RequireAuthorization** 
`endpoints.MapHealthChecksUI().RequireAuthorization(Name.RequireRoleAdministrator);`
