### ISSUE TITLE
Health check UI is not updating status when name of check is too long.

### ISSUE THREAD

**Issue by AndrzejKroczynski** [Xabaril/AspNetCore.Diagnostics.HealthChecks#577]
**What happened**:
Health check UI is not updating status when name of check is too long.

**What you expected to happen**:
Health check UI updates status as usual

**How to reproduce it (as minimally and precisely as possible)**:
- Create check with **name** longer that 50 chars
- Trigger status change for this check

**Source code sample**:
![image](https://user-images.githubusercontent.com/28391487/87033742-16a8f880-c1e7-11ea-857a-119bc4fd34ce.png)

The reason for the issue is mismatch in **name** column length - in HealthCheckExecutionEntries it has 500 chars, in HealthCheckExecutionHistories only 50.

**Anything else we need to know?**:
Please update HealthCheckExecutionHistories.name column to hold 500 chars (it is useful to keep longer names so they are more descriptive for complex checks)

**Environment**:

- .NET Core version: 3.1
- Healthchecks version: 3.1.1
- Operative system: Widows 10
- Others:

**Comment by unaizorrilla** [comment]
Thanks for catch up this issue!! 

@CarlosLanderas  do you have time to fix this?

**Comment by CarlosLanderas** [comment]
Yes. I'll fix it

**Comment by unaizorrilla** [comment]
Hi @CarlosLanderas 

Can I close this?

**Comment by CarlosLanderas** [comment]
I'm on holiday. I haven't worked on it yet.
