### ISSUE TITLE
AzureKeyVault: naming of `keyIdentifier` is misleading

### ISSUE THREAD

**Issue by Kiechlus** [Xabaril/AspNetCore.Diagnostics.HealthChecks#579]
The parameter is called `keyIdentifier`, but what is actually meant is `keyName`. https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.AzureKeyVault/AzureKeyVaultOptions.cs#L100

Because the `GetKeyAsync` function is called like this: 
`GetKeyAsync(this IKeyVaultClient operations, string vaultBaseUrl, string keyName, CancellationToken cancellationToken = default);`

When adding a key identifier, which looks something like this `https://xxxxx-vault.vault.azure.net/keys/sxxxxek/2fa2xxxxxxxxx45add0c247af7a1` the result is aways `Bad Request`

Apart from that it would maybe be better to use the real key identifier `GetKeyAsync(this IKeyVaultClient operations, string keyIdentifier, CancellationToken cancellationToken = default);` because this also includes the `keyVersion`.

**Comment by CarlosLanderas** [comment]
Hello @Kiechlus . A PR is welcome :)

**Comment by Kiechlus** [comment]
![image](https://user-images.githubusercontent.com/9875731/87048278-d30cb980-c1fb-11ea-93f2-f885d640aa2f.png)

**Comment by Kiechlus** [comment]
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/580/files

**Comment by unaizorrilla** [comment]
Merged!
