### ISSUE TITLE
app.UseHealthChecksUI() crashes the Host  on Asp.Net Core 3.1

### ISSUE THREAD

**Issue by MithunChopda** [Xabaril/AspNetCore.Diagnostics.HealthChecks#582]
Please, fill the following sections to help us fix the issue

I have an empty ASP.NET Core 3.1 Web Application project with AspNetCore.HealthChecks.UI installed. While the app.UseHealthChecks() works fine, the app.UseHealthChecksUI() middleware crashes the Host on startup with the following error

+		[0]	{"Error while validating the service descriptor 'ServiceType: HealthChecks.UI.Core.Notifications.IHealthCheckFailureNotifier Lifetime: Scoped ImplementationType: HealthChecks.UI.Core.Notifications.WebHookFailureNotifier': Unable to resolve service for type 'HealthChecks.UI.Core.Data.HealthChecksDb' while attempting to activate 'HealthChecks.UI.Core.Notifications.WebHookFailureNotifier'."}	System.Exception {System.InvalidOperationException}

- .NET Core version 3.1
- Healthchecks version 3.1.1
- Operative system: WIndows 10

**Comment by CarlosLanderas** [comment]
You need to configure the storage provider. Please read the docs here:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks#ui-storage-providers
