### ISSUE TITLE
Object Reference Not Set

### ISSUE THREAD

**Issue by maldworth** [Xabaril/AspNetCore.Diagnostics.HealthChecks#584]
I'm getting that exception in the AbsoluteUriFromRelative method.

I think it has to do with this commit?
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/commit/4716252cdd0de199c7ac6d21103afec8eb05445e

I only get the error when I run local integration tests using the WebApplicationFactory for Testing
https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1

if I run normally (dotnet run), it works fine.

**Comment by CarlosLanderas** [comment]
Do you have the stack trace? As when using test server, probably Iserver or some other http context feature might not be registered or compatible with WebApplicationFactory

If you can provide the stack trace or some additional info I can take a look

Thanks

**Comment by maldworth** [comment]
It's happening here:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/83eb960e53178520ba727cb09c2f1156ad124745/src/HealthChecks.UI/Core/ServerAddressesService.cs#L24

It's because there is no [IServerAddressesFeature with the test host](https://github.com/aspnet/Hosting/issues/967).

**Comment by CarlosLanderas** [comment]
Take a look here for testing:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/test/FunctionalTests/HealthChecks.UI/ServerAddressesServiceTests.cs#L46

**Comment by maldworth** [comment]
ok thanks!
