### ISSUE TITLE
Use MailKit for SMTP healthcheck?

### ISSUE THREAD

**Issue by bkaid** [Xabaril/AspNetCore.Diagnostics.HealthChecks#59]
SmtpClient has been [deprecated](https://docs.microsoft.com/en-us/dotnet/api/System.Net.Mail.SmtpClient?view=netcore-2.2) with MailKit recommended as its replacement.

**Comment by CarlosLanderas** [comment]
Not sure if this is necessary as it is not evolving code. Let me check it. 
Thanks!
