### ISSUE TITLE
Update StackExchange Redis Version Please

### ISSUE THREAD

**Issue by josephderonde** [Xabaril/AspNetCore.Diagnostics.HealthChecks#595]
Hi,

Please could you update the version of StackExchange redis you use to 2.1.58.

currently i can see you are using "/AspNetCore.Diagnostics.HealthChecks/blob/master/build/dependencies.props" to set 
<StackExchangeRedis>2.0.601</StackExchangeRedis>

From version 2.1.0 StackExchange added support for redis sentinel, and from 2.1.50 they have enabled you to pass "0.0.0.0,serviceName={ServiceName}" to enable to Sentinel detection in the connection string.

It would be great if we could have support for healthchecks on redis sentinel.

Many Thanks
Joe.

**Comment by unaizorrilla** [comment]
I try to do asap!

**Comment by josephderonde** [comment]
brilliant thanks @unaizorrilla

**Comment by unaizorrilla** [comment]
Already pushed, a new release build is on app veyor, when finished a new package 3.1.2 will be on nuget with a dependency on latest 2.1.58 redis package!

Please close if the new package fix the issue

**Comment by josephderonde** [comment]
awesome - i will test the sentinel mode and update results here so you can update documentation etc at a later date.

**Comment by josephderonde** [comment]
@unaizorrilla i now have this working with redis sentinel in docker swarm

i am not sure if you want to update the docs or anything to point to the fact it works.

in swarm mode i had to point at my manger as the ip address and expose the ports for redis and redis sentinel. i could not find a better option for this i would have preferred if they had given us an option to pass in the sentinel container name and the redis container name so i could reference them individually, but it looks like it just says yes your a sentinel, ill just flip the port number rather than get the masters full address

configuration["RedisConnectionString"] = 0.0.0.0:26379,serviceName=mymaster

```
                .AddRedis(
                    configuration["RedisConnectionString"],
                    failureStatus: HealthStatus.Degraded,
                    name: "basket_redis-check",
                    tags: new string[] { "redis", "basket_redis" })
```

when you pass in serviceName=mymaster the connection Multiplexer detects that you want to connect in sentinel mode and switches the port to 26379 and detects the master node, then connects to the master node via 6379

updates to documentation should be as easy as add serviceName=mymaster etc to connect to sentinel.

Thanks again for updating this so quickly!!

Joe.
