### ISSUE TITLE
Possibility to run the health check only on demand

### ISSUE THREAD

**Issue by freedeveloperjagg** [Xabaril/AspNetCore.Diagnostics.HealthChecks#597]
**What would you like to be added**:
A button in the interface and a configuration setting that allow to stop and only scan for the health check on demand or when you need it.

**Why is this needed**:
The APIs that I develop are under high traffic and the continue lectures of the Health check routines produce a significative overhead in processing.

**Comment by CarlosLanderas** [comment]
Hello @freedeveloperjagg .
I am already working on this. The new UI interface will have a start and stop button and the interval confguration will be done when configuring the UI middleware in the backend
