### ISSUE TITLE
Can't Find Package for HealthChecks.UI

### ISSUE THREAD

**Issue by twurm** [Xabaril/AspNetCore.Diagnostics.HealthChecks#6]
I can't seem to find the HealthChecks.UI nuget package.  I checked the last [AppVeyor build](https://ci.appveyor.com/project/Xabaril/aspnetcore-diagnostics-healthchecks/builds/20223232) and it looks like the package is getting built, but not uploaded to MyGet.

**Comment by CarlosLanderas** [comment]
Thanks for reporting @twurm, it seems when we migrated the repository from [Beatpulse](https://github.com/Xabaril/beatpulse) we did not add the new UI libraries for nuget publish.

They are published now on myget feed
