### ISSUE TITLE
What is the difference between AddSqlServer and AddDbContextCheck?

### ISSUE THREAD

**Issue by ranouf** [Xabaril/AspNetCore.Diagnostics.HealthChecks#600]
Hi,

I noticed that there is extension to validate that the connexion to SQL Server works correctly:
- AddSqlServer 
- AddDbContextCheck

What is the difference? Do you recommend to use one more?

Thanks

**Comment by CarlosLanderas** [comment]
Hello @ranouf ! AddDbContextCheck is from Microsoft and it tests whether the DbContext can connect with the Database Connection string. Both Healthchecks have different options and you can use the one that suits better to you 👍🏻
