### ISSUE TITLE
Use consistent config setting name values

### ISSUE THREAD

**Issue by pbolduc** [Xabaril/AspNetCore.Diagnostics.HealthChecks#602]
Please, fill the following sections to help us fix the issue

**What happened**:

I was reviewing the source code to understand it more and noticed in consistency in the naming of configuration settings.  It seems [KubernetesDiscoverySettings](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/92b4e5a2bf9d266022221cb0309a54ba69827da0/src/HealthChecks.UI/Core/Discovery/K8S/KubernetesDiscoveryOptions.cs#L15) uses 

```
public int RefreshTimeOnSeconds { get; set; }
```

whereas the [Settings](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/92b4e5a2bf9d266022221cb0309a54ba69827da0/src/HealthChecks.UI/Configuration/Settings.cs#L14) class uses

```
int EvaluationTimeInSeconds { get; set; }
```

It would be better if the configuration settings were consistent using ```InSeconds``` which is clearer. The Settings class was changed from ```public int EvaluationTimeOnSeconds { get; set; }``` to  ```internal int EvaluationTimeInSeconds { get; set; }``` in version 2.2.27 in this commit: e19da86d4e96a9fa04131ecfee9308c49907fde7

**What you expected to happen**: Use consistent configuration naming style.

**How to reproduce it (as minimally and precisely as possible)**:  n/a

**Source code sample**: n/a

**Anything else we need to know?**:

**Environment**:

- .NET Core version 3.1
- Healthchecks version: 3.1.x
- Operative system: n/a
- Others: n/a

**Comment by sungam3r** [comment]
fixed in 892d29e
