### ISSUE TITLE
HealthCheck UI is empty

### ISSUE THREAD

**Issue by RagnarGothur** [Xabaril/AspNetCore.Diagnostics.HealthChecks#603]
Hello!
In my case the "/health-api" works as expected: returns json with healthcheck results. But there are no any healthcheck results on "/health-ui" because the "/health-ui-api" returns an empty array.
Configuration examples:
```
services
                .AddHealthChecks()
                .AddCheck("Self", () => HealthCheckResult.Healthy())
                .AddNpgSql(
                    name: "Database",
                    npgsqlConnectionString: Configuration.GetValue<string>("ConnectionString"),
                    healthQuery: "SELECT 1;",
                    failureStatus: HealthStatus.Degraded
                )
                .Services
                .AddHealthChecksUI()
                .AddInMemoryStorage(options =>
                {
                    options.EnableDetailedErrors();
                });


app
                .UseRouting()
                .UseEndpoints(config =>
                {
                    config.MapHealthChecks("/health-api", new HealthCheckOptions
                    {
                        Predicate = _ => true,
                        ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
                    });

                    config.MapHealthChecksUI(setup =>
                    {
                        setup.UIPath = "/health-ui";
                        setup.ApiPath = "/health-ui-api";
                    });

                    config.MapDefaultControllerRoute();
                });
```

All of the packages have 3.1.1 version.
How can I fix it?

**Comment by SteppenHorde** [comment]
Finally got it working by changing code like this:
`.AddHealthChecksUI(settings => settings.AddHealthCheckEndpoint("checks", "/health-api"))`.
But I still wonder why the code sample from [UIAndApiCustomization](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/samples/HealthChecks.UIAndApiCustomization/Startup.cs) didn't work for me... Can someone explain that incomprehensible behavior please?

**Comment by Odonno** [comment]
I have the same result you have. Seems like the code sample is broken at the moment.

But, to me, it feels more natural and logic to specify the endpoints yourself. If no endpoint provided, then no result (empty UI). So, the default behavior would be to do this:

```csharp
services.AddHealthChecksUI(settings =>
{
    settings.AddHealthCheckEndpoint("Self", "/healthz");
});
```

**Comment by CarlosLanderas** [comment]
@RagnarGothur , I see you are using AddHealthChecks without the setup configuration,that means that your settings must be specified in appsettings, secrets or environment variables, where you should specify the target healthcheck endpoints.

you can also specify the remote endpoints as @Odonno says:

```csharp
services.AddHealthChecksUI(settings =>
{
    settings.AddHealthCheckEndpoint("endpoint1", "/healthz");
});
```

Could you show your **appsettings** configuration?. They should have /health-api segment 

The  [UIAndApiCustomization](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/samples/HealthChecks.UIAndApiCustomization/sample) is working fine for me:

![image](https://user-images.githubusercontent.com/16475649/91961083-ff7c1800-ed0a-11ea-9b61-ac79cec9d7df.png)
