### ISSUE TITLE
Please upgrade to the new Key Vault and Storage client libraries

### ISSUE THREAD

**Issue by heaths** [Xabaril/AspNetCore.Diagnostics.HealthChecks#606]
We have released [new versions](https://aka.ms/azsdk/net) of the Azure SDK Client Libraries for Key Vault, Storage, and other Azure services. We see that you are still using the older packages. The new Azure SDK is faster, leaner, and more extensible. Please see our [introductory video](https://aka.ms/azsdk/intro) and our [value propositions](https://aka.ms/azsdk/valueprop) for more information. We hope that you upgrade to these new packages. We are happy to offer assistance in upgrading while we work on migration guides.

For Key Vault, we have split the client libraries into 3 separate packages that can be used together but, individually, are smaller dependencies:

* [Azure.Security.KeyVault.Certificates](https://www.nuget.org/packages/Azure.Security.KeyVault.Certificates/) ([README](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Certificates/README.md), [Samples](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Certificates/samples))
* [Azure.Security.KeyVault.Keys](https://www.nuget.org/packages/Azure.Security.KeyVault.Keys/) ([README](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Keys/README.md), [Samples](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Keys/samples))
* [Azure.Security.KetVault.Secrets](https://www.nuget.org/packages/Azure.Security.KeyVault.Secrets/) ([README](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Secrets/README.md), [Samples](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Secrets/samples))

Samples are also available in our [samples browser](https://aka.ms/azsdk/net/keyvault/samples).

We also have [new Storage client libraries](https://www.nuget.org/packages?q=Azure.Storage). You can authenticate with both using the [Azure.Identity](https://www.nuget.org/packages/Azure.Identity/) package, which includes [DefaultAzureCredential](https://devblogs.microsoft.com/azure-sdk/authentication-and-the-azure-sdk/) that simplifies code to work in both development and production environments.

**Comment by CarlosLanderas** [comment]
Hello @heaths , thanks for the info!. We are back from holidays and we are gonna start working on the issues. We will update the dependencies.

**Comment by unaizorrilla** [comment]
Hi @heaths 

I summit a PR with changes proposed on this issue on #618  Can you check if this is ok for you?

**Comment by unaizorrilla** [comment]
Closed with #618

Thanks @heaths for helping on this!
