### ISSUE TITLE
Make the Health-UI independent of internet access

### ISSUE THREAD

**Issue by camiteca** [Xabaril/AspNetCore.Diagnostics.HealthChecks#607]
**What would you like to be added**:

I'd like to be able to run the health-ui independent from internet access. 

**Why is this needed**:

We have closed environments that are not allowed by our organization's firewall to access external Urls. If we try to run it as is, we see some ugly fallbacks:

![image](https://user-images.githubusercontent.com/1260651/90240300-43c17a00-de29-11ea-82b2-32acc5664896.png)

Would you consider changing the font to be embedded? Or maybe provide a different approach for the icons to work? Thank you in advance.

**Comment by espenrl** [comment]
I'm experiencing the same issue in a production environment with no ability to access resources on internet.

**Comment by unaizorrilla** [comment]
I’m finish my vacation and try to check this, also @CarlosLanderas  can you checkout?

**Comment by CarlosLanderas** [comment]
I'll work on it. I'm gonna upgrade react version and redesign the front-end code  and I'll take the chance to do this.

**Comment by CarlosLanderas** [comment]
This is in progress. I am updating the UI to React Hooks and adding some new feats. The material icons will now be processed by webpack and embedded in the bundle so no internet access would be required.

**Comment by camiteca** [comment]
Since you're at it, if you could also check out also these alignment issues, it would greatly improve the visual appearence. If we deploy every tab the columns are all taking different widths.

![image](https://user-images.githubusercontent.com/1260651/92741356-d0a31900-f37e-11ea-9f73-e3e4aa8639bf.png)

Please let me know if you see fit to create a new issue to resolve this other problem.
