### ISSUE TITLE
Multi URI health check 

### ISSUE THREAD

**Issue by saeidehv** [Xabaril/AspNetCore.Diagnostics.HealthChecks#61]
I wanted to show health check result of different projects ( Micro Services) in one project.
I set up configuration like HealthChecks.UIAndApiCustomization sample and added my other project health url like this :

"HealthChecks-UI": {
    "HealthChecks": [
      {
        "Name": "Http and UI on single project with customizations",
        "Uri": "http://localhost:8001/custom/healthz"
      },
      {
        "Name": "Payments",
        "Uri": "https://localhost:44386/health"
      }

    ],
but the result from other project is not been showed in the HealthChecksUI. It just shows the first project health result.
Is it the correct way to do this? Do I miss something ? 

Thanks in advanced.
Saeideh

**Comment by CarlosLanderas** [comment]
Hello @saeidehv, could you show your configuration for the Payments endpoint?. Startup.cs and the launchSettings.json so we can see where the probem could be?.
Thanks

**Comment by saeidehv** [comment]
Hello,
Thanks for the great work.
In my endpoint I had a custom response writer for formatting the health check response. I changed it to  UIResponseWriter.WriteHealthCheckUIResponse ,now it is working.
But I am facing another issue , why the health page in healthchecks-ui is not being updated every 10 seconds? in appsettings I changed   EvaluationTimeOnSeconds to "EvaluationTimeOnSeconds": 60.
Thank you

**Comment by CarlosLanderas** [comment]
The EvaluationTimeOnSeconds is a configuration for the collector service background task. It specifies the interval the UI backend will call your health checks endpoints and store the results on sqlite database.

The update interval you can see in the frontend SPA represents how often the frontend will call to the backend UI API to gather the health checks results.

**Comment by unaizorrilla** [comment]
Can I close this issue?

**Comment by saeidehv** [comment]
Thanks for more explanation.
Yes, please.
