### ISSUE TITLE
Incompatible with MySqlConnector v. 1.x

### ISSUE THREAD

**Issue by m-jepson** [Xabaril/AspNetCore.Diagnostics.HealthChecks#612]
Namespaces changed in the MySqlConnector library, which breaks the healthcheck.

**Comment by unaizorrilla** [comment]
Hi @m-jepson 

Let me check this a soon as posible!

**Comment by unaizorrilla** [comment]
Hi @m-jepson 

Upgrade dependency version! A new release is on app veyor (https://ci.appveyor.com/project/Xabaril/aspnetcore-diagnostics-healthchecks/builds/35008570 ), When finish a new package with version 3.2.0 will be available on NuGet!

**Comment by unaizorrilla** [comment]
Hi again!

The release fail because we have issue with pomelo and mysqlconnector version but i'm working around this issue!

I try to push a new release build yet and wait for the new package 3.2.0

**Comment by unaizorrilla** [comment]
The new release build is https://ci.appveyor.com/project/Xabaril/aspnetcore-diagnostics-healthchecks/builds/35009538
