### ISSUE TITLE
Getting Exception System.AggregateException

### ISSUE THREAD

**Issue by mohitpaliwal82** [Xabaril/AspNetCore.Diagnostics.HealthChecks#613]
**What happened**:
Hi Team 
I am using .net core version 3.1 and using AspNetCore.HealthChecks.UI (3.1.1) and AspNetCore.HealthChecks.UI.Client (3.1.1)
and getting below exception

System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: HealthChecks.UI.Core.Notifications.IHealthCheckFailureNotifier Lifetime: Scoped ImplementationType: HealthChecks.UI.Core.Notifications.WebHookFailureNotifier': Unable to resolve service for type 'HealthChecks.UI.Core.Data.HealthChecksDb' while attempting to activate 'HealthChecks.UI.Core.Notifications.WebHookFailureNotifier'.) (Error while validating the service descriptor 'ServiceType: HealthChecks.UI.Core.HostedService.IHealthCheckReportCollector Lifetime: Scoped ImplementationType: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector': Unable to resolve service for type 'HealthChecks.UI.Core.Data.HealthChecksDb' while attempting to activate 'HealthChecks.UI.Core.HostedService.HealthCheckReportCollector'.)'

Same code If I ran on AspNetCore.HealthChecks.UI (3.0.10) without AspNetCore.HealthChecks.UI.Client it is working fine.

**What you expected to happen**:

Code/library should be work on higher version as well without breaking. 

**Source code sample**:

public void ConfigureServices(IServiceCollection services)
        {
            
            services.AddControllers();
            services.AddHealthChecks().AddCheck("Foo", () =>
                   HealthCheckResult.Healthy("Foo is OK!"), tags: new[] { "foo_tag" })
                .AddCheck<ExampleHealthCheck>("Sample1", null, new[] { "Sample" })
                .AddCheck("Sample2", new SqlConnectionHealthCheck("Data Source=PALIWAL\\SQLEXPRESS;Integrated Security=True"), HealthStatus.Unhealthy, new string[] { "orderingdb" }); ;

            services.AddHealthChecksUI();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {           

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapDefaultControllerRoute();
                endpoints.MapHealthChecks("/mohit", new HealthCheckOptions()
                {
                    Predicate = obj => true,
                    ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
                });
            });

            app.UseHealthChecksUI();
        }

"HealthChecksUI": {
    "HealthChecks": [
      {
        "Name": "HTTP-Api-Basic",
        "Uri": "/mohit"
      }
    ],
    //"Webhooks": [
    //  {
    //    "Name": "",
    //    "Uri": "",
    //    "Payload": "",
    //    "RestoredPayload": ""
    //  }
    //],
    "EvaluationTimeOnSeconds": 10,
    "MinimumSecondsBetweenFailureNotifications": 60,
    "MaximumExecutionHistoriesPerEndpoint": 15
  }

**Environment**:
Windows 10 Home (Visual studio 2019 community edition)
- .NET Core version
.NET CORE 3.1
- Healthchecks version
Microsoft.AspNetCore.Diagnostics.HealthChecks 2.2.0
- Operative system:
Windows 10 Home (Visual studio 2019 community edition)
- Others:

**Comment by CarlosLanderas** [comment]
Hello. Check the Storage Provider configuration section. Latest versions are compatible with different storage providers and you need to configure one of them.

Thanks :)

**Comment by LiviuSosu** [comment]
I'm follwoing strictly the documentation (without other services or providers) and I am getting the same exception. And I have exactly the same environment as mohitpaliwal82. 

I'm just exploring, trying to get better, so no pressure :-) Did I undesrtood corectly, are you working on it: https://www.gitmemory.com/CarlosLanderas

or is it solved?
