### ISSUE TITLE
ServerAddressService throws InvalidOperationException

### ISSUE THREAD

**Issue by aevitas** [Xabaril/AspNetCore.Diagnostics.HealthChecks#614]
After having successfully tested the health check endpoint and UI, I'm suddenly greeted with `InvalidOperationException`s and all sorts of incomprehensible log messages in production. 

Within my ASP.NET Core 3.1 application, I've registered the health checks like so:

```
        private void RegisterHealthChecks(IServiceCollection services)
        {
            services.AddHealthChecks()
                .AddSqlServer(Configuration["ConnectionStrings:Database"])
                .AddRabbitMQ(
                    $"amqp://{Configuration["QueueConnection:UserName"]}:{Configuration["QueueConnection:Password"]}@{Configuration["QueueConnection:QueueHostName"]}:{Configuration["QueueConnection:QueueHostPort"]}",
                    new SslOption());

            services.AddHealthChecksUI(cfg => cfg.AddHealthCheckEndpoint("health", "/healthz"))
                .AddInMemoryStorage();
        }
```

The `/healthz` endpoint is working fine, and I can observe my services being available, both in test and in production. However, whereas the UI works fine on test, it throws the following exception continuously in production:

> GetHealthReport threw an exception when trying to get report from /healthz configured with name health.
> 
> System.InvalidOperationException: Sequence contains no elements at System.Linq.ThrowHelper.ThrowNoElementsException() at System.Linq.Enumerable.First[TSource](IEnumerable`1 source) at HealthChecks.UI.Core.ServerAddressesService.AbsoluteUriFromRelative(String relativeUrl) at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetEndpointUri(HealthCheckConfiguration configuration) at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReport(HealthCheckConfiguration configuration)
>

This is usually accompanied by a message saying `Notification is sent on same window time.`, of which I can't tell the meaning.

I've had a look, and the exception itself appears to originate from the `ServerAddressService`, and occurs when `AbsoluteUriFromRelative` is called. Is there something I'm configuring wrong here, and if so, shouldn't that be caught before this eventually ends up throwing a nondescript `InvalidOperationException`?

**Comment by CarlosLanderas** [comment]
Hello @aevitas aevitas. Where are you deploying the application?. 

When the host starts it waits for kestrel or IIS to report the listening addresses by using IServerAddressFeature. 

Are you using docker? Are you specifying the listening URLs with env variables?

**Comment by aevitas** [comment]
Hey @CarlosLanderas 

Thanks for getting back to me so quickly! We're deploying the application to IIS, and I'm fairly certain (although not 100% sure) that the listening URLs aren't passed through environment variables. I assumed the UI would be able to resolve the health endpoint through simply adding it as a relative URL using `cfg.AddHealthCheckEndpoint`. Is that assumption incorrect and should we be passing the health endpoint as an environment variable instead?

**Comment by CarlosLanderas** [comment]
Here is the PR where this was introduced:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/339

As you can see a Microsoft Employee participated in the discussion and told us that kestrel reports the listening URLs immediately after started and IIS might take a while, but the UI server doesn't until reported. It could be happening that an ipv6 or non DNS format address is being reported from IIS. If you use http://localhost/health it will work definitely.

I need to take a look to the code and check whether the UI is logging the discovered endpoints at startup. Does the stack trace print the URL that is using for the HealthCheck request?

**Comment by CarlosLanderas** [comment]
#410 might be related
