### ISSUE TITLE
Expand by default

### ISSUE THREAD

**Issue by majco333** [Xabaril/AspNetCore.Diagnostics.HealthChecks#62]
Is it any way how to expand all rows by default after start?

Thanks

**Comment by CarlosLanderas** [comment]
Not at the moment @majco333. The thing is that health checks results might appear after the UI has been initialized. Also we have also the scenario where healths check endpoints are automatically discovered when using kubernetes so you can tag new deployments and they appear after some time.

Maybe we could monitor the health checks that have been already reported, and the new ones that arrive can be automatically expanded.

**Comment by majco333** [comment]
Thanks
