### ISSUE TITLE
Dropped the support to the Azure table storage

### ISSUE THREAD

**Issue by EdoardoTona** [Xabaril/AspNetCore.Diagnostics.HealthChecks#620]
**What happened**:
AspNetCore.HealthChecks.AzureStorage 3.3.0 dropped the support to Azure table storage (aa0c6ffe0137970d5b20fecdb66b912a96613c3c).

**What you expected to happen**:
Be able to healthcheck the Azure table storage.

**How to reproduce it (as minimally and precisely as possible)**:
Update from AspNetCore.HealthChecks.AzureStorage 3.2.0 (last working version) to 3.3.0

**Comment by unaizorrilla** [comment]
In new azure storage SDK‘a table client is not longer supported. The plan is use cosmos HealthCheck for this but SDK and healthcheck is on preview

**Comment by unaizorrilla** [comment]
Hi @heaths

What is the state of Azure.Data.Tables? is on preview on nuget? What is the new way to manage Storage Tables?

**Comment by christothes** [comment]
The first beta release of Azure.Data.Tables is due to release this month. Keep a lookout for a post on the [SDK blog](https://devblogs.microsoft.com/azure-sdk/) for details.

**Comment by unaizorrilla** [comment]
Ok!

**Comment by f2calv** [comment]
So Azure.Data.Tables package is [now available](https://www.nuget.org/packages/Azure.Data.Tables) (well available in beta at least...) the documentation link is broken but [samples link works](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/tables/Azure.Data.Tables/samples).

So we wait for a new cosmosdb/tables healthcheck library now right?

**Comment by unaizorrilla** [comment]
Yeap! I try to do that this week!!

**Comment by unaizorrilla** [comment]
Hi @EdoardoTona @f2calv @christothes 

The preview of CosmosDB healthcheck already contains a AddAzureTable healtcheck using new Azure.Data.Tables preview package!

The release is on app veyor, when finished a new preview package AspNetCore.HealthChecks.CosmosDb 3.2.1-preview will be on NuGet!

Just close this issue, please reopen if necesary!
