### ISSUE TITLE
AddElasticsearch(...) Could not load type 'Elasticsearch.Net.IInternalSerializerWithFormatter'

### ISSUE THREAD

**Issue by aleksandrdotnet** [Xabaril/AspNetCore.Diagnostics.HealthChecks#621]
I cannot check healthcheck with elasticsearch

**Source code sample**:
(...).AddElasticsearch(setup =>
                        {
                            setup.UseServer(SerilogElasticSearchConfiguration.Uri)
                                .UseBasicAuthentication(SerilogElasticSearchConfiguration.Login,
                                    SerilogElasticSearchConfiguration.Password)
                                .UseCertificateValidationCallback((o, certificate, arg3, arg4) => true)
                                .UseCertificateValidationCallback(CertificateValidations.AllowAll);
                        }, tags: new[] { "elasticsearch" });

**Exception**:
HealthCheckUI shows me:
Could not load type 'Elasticsearch.Net.IInternalSerializerWithFormatter' from assembly 'Elasticsearch.Net, Version=7.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d'.

**Trace stack**:
[18:27:44 DBG] Executing HealthCheck collector HostedService.
[18:27:44 ERR] Health check elasticsearch completed after 1.3747ms with status "Unhealthy" and 'null'
[18:27:44 ERR] The webhook notification has not executed successfully for  webhook. The error code is "NotFound".

- .NET Core 3.1
- Healthchecks version 3.1.1
- Operative system: Windows

**Comment by rebeccapowell** [comment]
Same issue. It seems like using Serilog ElasticSearch Sinks in combination with this package causes an issue, since this dependency has a specific version requirement.

**Comment by sungam3r** [comment]
Please try the latest stable/preview versions.
