### ISSUE TITLE
Auth support for health checks UI endpoint

### ISSUE THREAD

**Issue by skiyak** [Xabaril/AspNetCore.Diagnostics.HealthChecks#625]
We've adopted the health checks UI, but from the documentation I couldn't find any instructions on how to enable auth for this endpoint. Is this somehow supported, or is there any plan to enable auth optionally? Currently, this endpoint is public, which is far from ideal for our case.

**Comment by CarlosLanderas** [comment]
Hello @skiyak. What authentication provider would you need? We've been discussing to add support for Azure AD and Identity Server

**Comment by skiyak** [comment]
Hi Carlos, thanks for the quick response. We'd be happy with Azure AD.

**Comment by CarlosLanderas** [comment]
Working in this. Finally, we are adding support for OpenId Connect so we can use Azure, and other providers as well.

https://twitter.com/Carlos_Lande/status/1307126187609784322

**Comment by CarlosLanderas** [comment]
@skiyak, we decided to not introduce this inside the UI as there are simpler mechanisms to do this. Take a look to the new OIDC samples added to the samples folder:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/tree/master/samples/HealthChecks.UI.Oidc

Thanks!
