### ISSUE TITLE
Custom Description

### ISSUE THREAD

**Issue by josejavierpaez** [Xabaril/AspNetCore.Diagnostics.HealthChecks#626]
hi, I hope you will be fine and thanks for this amazing lib.

I would like to know how to write my custom description when I use the health checks provider by the lib. for example, am using the provider for SQL-SERVER and when the status is healthy the description is null.

like a picture

![image](https://user-images.githubusercontent.com/47426910/92509397-30ab8b00-f1d8-11ea-9e02-92d52466c2b7.png)

my wish is can write a custom description

**Comment by LeonT27** [comment]
Hi,

I was looking for this too, to show more information when the check is healthy but, the SQLSERVER lib (and I think all of them), don't have a way to put a custom message. 

You can take the .cs file (https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.SqlServer/SqlServerHealthCheck.cs) and add your custom message but, you're going to use and maintain that file.

I think a predicate can be added to the implementation for custom message when is healthy, in the case of SQLSERVER healthcheck something like this, 

**Param:** Func<SqlConnection, string> _customHealthyMessage
**Code (from SqlServerHealthCheck.cs):**
```
using (var connection = new SqlConnection(_connectionString))
{
    await connection.OpenAsync(cancellationToken);
    using (var command = connection.CreateCommand())
    {
        command.CommandText = _sql;
        await command.ExecuteScalarAsync(cancellationToken);
    }
    //Add _customHealthyMessage to Healthy result
    return HealthCheckResult.Healthy(_customHealthyMessage(connection));
}
```
**Implement predicate like:**

`predicate => $"State: {predicate.State}"`

And add an overload method or a default value to the predicate.

**Comment by CarlosLanderas** [comment]
Hello, we could implement something like this:

```csharp
        public SqlServerHealthCheck(string sqlserverconnectionstring, string sql, Action<SqlConnection> beforeOpenConnectionConfigurer = null, Func<SqlConnection, SqlCommand, string> userCustomDescriptionCallback = null)
        {
            _connectionString = sqlserverconnectionstring ?? throw new ArgumentNullException(nameof(sqlserverconnectionstring));
            _sql = sql ?? throw new ArgumentNullException(nameof(sql));
            _beforeOpenConnectionConfigurer = beforeOpenConnectionConfigurer;
            _userCustomDescriptionCallback = userCustomDescriptionCallback;
        }
        public async Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken = default)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                {
                    _beforeOpenConnectionConfigurer?.Invoke(connection);

                    await connection.OpenAsync(cancellationToken);
                    using (var command = connection.CreateCommand())
                    {
                        command.CommandText = _sql;
                        await command.ExecuteScalarAsync(cancellationToken);

                        return HealthCheckResult.Healthy(GetCustomDescription(connection, command));
                    }

                }
            }
            catch (Exception ex)
            {
                return new HealthCheckResult(context.Registration.FailureStatus, exception: ex);
            }
        }

        private string GetCustomDescription(SqlConnection connection, SqlCommand command)
            => _userCustomDescriptionCallback switch
            {
                null => string.Empty,
                _ => _userCustomDescriptionCallback(connection, command)
            };
```

However, I would like to have a common surface for all healthchecks and the problem I foresee is that is gonna be very difficult to know what params/information every user is gonna need. Maybe we don't need this for all HealthChecks and can only be implemented in those that this feature is more requrested.

**Comment by sungam3r** [comment]
Covered by `SqlServerHealthCheckOptions.HealthCheckResultBuilder` as well as for other db checks.
