### ISSUE TITLE
How can I display non-compliant healthcheck

### ISSUE THREAD

**Issue by dsfrederic** [Xabaril/AspNetCore.Diagnostics.HealthChecks#632]
I'm trying to create a watchdog for our azure environment.

This would combine a list of external healthchecks. The problem is that our healthchecks are not compliant with the standard at the moment. I would rather not have to change all healtchecks. Is there a solution for this?

**Comment by CarlosLanderas** [comment]
@dsfrederic, you can use a different Response Writer and map it to another health path.

For example, use default healthchecks in /healthz

```csharp
 config.MapHealthChecks("/healthz", new HealthCheckOptions
      {
        Predicate = _ => true,
        ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
      });
```

Use custom healthchecks and transformation with your custom response writer:

```csharp
 config.MapHealthChecks("/healthz2", new HealthCheckOptions
      {
        Predicate = _ => true,
        ResponseWriter = UIResponseWriter.YourCustomResponseWriter
      });
```

Add them as two different remove endpoints:

/healthz
/healthz2

**Comment by JackPoint** [comment]
Maybe you can change the output of your own checks to a compatible one? Or create a proxy like thing that does the checks on your existing checks and output them in the correct format.

**Comment by sungam3r** [comment]
Closed as stale.
