### ISSUE TITLE
UI cannot display polling interval 

### ISSUE THREAD

**Issue by senvardarsemih** [Xabaril/AspNetCore.Diagnostics.HealthChecks#636]
**What happened**:
After upgrading nuget packages (AspNetCore.HealthChecks.UI & AspNetCore.HealthChecks.UI.Client) to latest version 3.1.2,
polling interval info not displaying on right corner of the ui page.

**What you expected to happen**:
Displaying correct polling interval value

**How to reproduce it **:
Upgrade AspNetCore.HealthChecks.UI and AspNetCore.HealthChecks.UI.Client packages to 3.1.2 version.

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/5811617/93469954-e02fde00-f8f9-11ea-8db7-fe16b4535fa8.png)
![image](https://user-images.githubusercontent.com/5811617/93469996-ef169080-f8f9-11ea-99a9-ac1080eb005b.png)

**Environment**:

- .NET Core version : 3.1.8
- Healthchecks version : latest
- Operative system: Windows

**Comment by CarlosLanderas** [comment]
There is no more polling interval configuration in the front-end. It's done in the backend and you can find it in the README.docs

**Comment by code1line** [comment]
OK, understood. But you could show the value, right?

**Comment by WonkySoft** [comment]
2 years later and still not visible.

**Comment by hades200082** [comment]
FYI for any that find this issue looking for a fix, I solved this in my app...

I was using app.UseHealthChecks() and app.UseHealthChecksUI().

Your example uses app.MapHealthChecks() and app.MapHealthChecksUI().
