### ISSUE TITLE
AddTcpHealthCheck not available

### ISSUE THREAD

**Issue by thomasdc** [Xabaril/AspNetCore.Diagnostics.HealthChecks#64]
Is there a reason why there isn't a `AddTcpHealthCheck` extension method in `NetworkHealthCheckBuilderExtensions`? You have a `TcpHealthCheck` but it's not referenced.

**Comment by CarlosLanderas** [comment]
This could be due to the migration from the Beatpulse project. We'll add it thanks.

**Comment by CarlosLanderas** [comment]
Fixed here:
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/commit/13c13041452801c00c83b9ee81a63a2f050b37ae

The network package version 2.2.2 will be published in nuget when build ends.
