### ISSUE TITLE
Getting Access Denied on WindowsServiceHealthCheck (HealthCheck.Systems extensions)

### ISSUE THREAD

**Issue by jayleongwk** [Xabaril/AspNetCore.Diagnostics.HealthChecks#640]
**What happened**: When trying to use WindowsServiceHealthCheck with remote server(require Authentication), will getting Access Denied error on health check. It happens to work only on Local windows services.

For others functions in Systems package, it seem only works on Local, but not remote.

**What you expected to happen**: Use health check on remote window server to check on services status with authentication enable. If possible, add remote capabilities on healthcheck.systems extensions.

**How to reproduce it (as minimally and precisely as possible)**: just to add health check as sample like below..
.AddWindowsServiceHealthCheck("services name", s => s.Status == ServiceControllerStatus.Running, "remote server name" ,"Test",HealthStatus.Degraded, new[] { "test" }, TimeSpan.FromMilliseconds(5000));

**Source code sample**:

**Anything else we need to know?**: It is more like a improvement rather than an issues, but i have encounter this, which i report here.

**Environment**: 

- .NET Core version 3.1
- Healthchecks version 3.1.8
- Operative system: window server 2012
- Others:

**Comment by CarlosLanderas** [comment]
Hello @jayleongwk. This is not a HealthCheck issue, but an issue with the underlying ServiceController class.
That "Access Denied" error probably indicates that the identity under which process application is running does not have permission to work with that service.
