### ISSUE TITLE
Release 3.1.2 broke retrieval of ui-settings on relative api path

### ISSUE THREAD

**Issue by bogataj** [Xabaril/AspNetCore.Diagnostics.HealthChecks#642]
**What happened**: Release 3.1.2 broke retrieval of ui-settings on relative api path.

**What you expected to happen**: When reading ui-settings from api, it should respect and use the setting of api relative paths.

**Comment by bogataj** [comment]
#643

**Comment by CarlosLanderas** [comment]
Looks good. Thanks for catching this 👍

**Comment by CarlosLanderas** [comment]
I'm gonna publish version 3.1.3 with the fix

**Comment by bogataj** [comment]
> Version 3.1.3 will include this fix in some minutes

I've deployed and tested version 3.1.3 now in our kuberenetes cluster and can confirm it's working as excepted again 👍

**Comment by CarlosLanderas** [comment]
@bogataj are you using the K8s operator to deploy the UI and monitor de services? :). Just to know 👍🏻

**Comment by bogataj** [comment]
> @bogataj are you using the K8s operator to deploy the UI and monitor de services? :). Just to know 👍🏻

No, only plain yaml resource scripts, no CRDs, yet :)
