### ISSUE TITLE
HealthChecks.Prometheus.Metrics returning HTTP 503 if one healthcheck is unhealthy

### ISSUE THREAD

**Issue by forki** [Xabaril/AspNetCore.Diagnostics.HealthChecks#644]
I'm using HealthChecks.Prometheus.Metrics and trying to import it into Prometheus.
As soon as one health check is going into unhealthy the whole endpoint is returning HTTP 503

It looks like Prometheus is completely ignoring the data in that case. My yml looks like that:

    - job_name: myhealthjob
      static_configs:
      - targets: ['localhost:8087']
      metrics_path : '/prometheus-health-metrics'

Is there something I need to change in the yml or can I somehow make the healthcheck give a 200?

Thanks

**Comment by unaizorrilla** [comment]
I think this issue is just closed with #566  from @epaulsen !!

Can you check? probably the  release for new package 3.1.4 is on appveyor now but in a few minutes the package will be available on NuGet!
