### ISSUE TITLE
MongoDb Storage for .net core 2.2

### ISSUE THREAD

**Issue by xico002** [Xabaril/AspNetCore.Diagnostics.HealthChecks#645]
Hi!

First of all I'd like to know if  health checks has MongoDB storage support for .net core 2.2 or any other support since I can't find it anywhere.
If not I would suggest the implementation in .net core 2.2 of the providers implemented in .net core 3.1 version plus adding MongoDB support.

I would really appreciate an answer.

**Comment by sungam3r** [comment]
https://www.nuget.org/packages/AspNetCore.HealthChecks.MongoDb targets `net6` and `netstandard2.0` now. `netstandard2.0` is compatible with `netcoreapp2.2`.

**Comment by sungam3r** [comment]
Closed as answered.
