### ISSUE TITLE
HealthCheck collector HostedService threw an error: Value cannot be null. (Parameter 'source')

### ISSUE THREAD

**Issue by AlexanderArvanitis** [Xabaril/AspNetCore.Diagnostics.HealthChecks#651]
What happened:
Health checks UI is empty although the /health endpoint returns an response. When running on Kestrel I can tell from the logs that the the endpoint is called and returns correctly.

From the exception message I gather that execution.Entries in SaveExecutionHistoryEntries might be empty for some reason, but I haven't been able to test it.

Maybe I'm doing something wrong with how I setup it all up?
**This is my Startup.cs:**
```
public void ConfigureServices(IServiceCollection services)
        {
            services
                .AddHealthChecksUI(setup => 
                {
                    setup.AddHealthCheckEndpoint("test", "https://localhost:8080/health");
                })
                .AddInMemoryStorage();
        }
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGet("/", async context =>
                {
                    await context.Response.WriteAsync("Hello World!");
                });
                endpoints.MapHealthChecksUI();
            });
        }

```
**From the outputwindow/kestrell:**
```
info: HealthChecks.UI.Core.HostedService.UIInitializationHostedService[0]
      Initializing UI Database
info: HealthChecks.UI.Core.HostedService.UIInitializationHostedService[0]
      Saving healthchecks configuration to database
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: System.Net.Http.HttpClient.health-checks.LogicalHandler[100]
      Start processing HTTP request GET https://localhost:8080/health
info: System.Net.Http.HttpClient.health-checks.ClientHandler[100]
      Sending HTTP request GET https://localhost:8080/health
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\000-alar\source\repos\HealthMonitor\HealthMonitor
info: System.Net.Http.HttpClient.health-checks.ClientHandler[101]
      Received HTTP response after 2771.9594ms - ServiceUnavailable
info: System.Net.Http.HttpClient.health-checks.LogicalHandler[101]
      End processing HTTP request after 2785.141ms - ServiceUnavailable
fail: HealthChecks.UI.Core.HostedService.HealthCheckCollectorHostedService[0]
      HealthCheck collector HostedService threw an error: Value cannot be null. (Parameter 'source')
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Microsoft.Extensions.Diagnostics.HealthChecks.HealthReportExtensions.ToExecutionEntries(UIHealthReport report)
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.SaveExecutionHistory(HealthCheckConfiguration configuration, UIHealthReport healthReport)
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.Collect(CancellationToken cancellationToken)
   at HealthChecks.UI.Core.HostedService.HealthCheckCollectorHostedService.Collect(CancellationToken cancellationToken)
```

What you expected to happen:
I expect the UI to work.

How to reproduce it (as minimally and precisely as possible):
Since I'm the first to report this I think the problem could be on my end, but for me to reproduce it I've only got to setup a project to use the UI.

Anything else we need to know?:

Environment:
.NET Core version 3.1
Healthchecks version 3.1.5
HealthCheckus-UI version 3.1.1
Operative system: Windows 10 professional

**Comment by CarlosLanderas** [comment]
Are you using HealthChecks in the same endpoint of the UI?

I miss:

````csharp
endpoints.MapHealthChecks
```

before the MapHealthChecksUI.

You can take a look to all our samples:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/tree/master/samples

**Comment by Kamiljen** [comment]
Hi I'm not. I was hoping to use the package to monitor multiple other applications over distributed test environments. 
Lately I've been relying more and more on healthchecks, and I'd like to make my life a little easier.

From the example bellow in the documentation I was under the impression I could?

>  Sample 2: Configuration using setupSettings method:
>   services
>     .AddHealthChecksUI(setupSettings: setup =>
>     {
>        setup.AddHealthCheckEndpoint("endpoint1", "http://localhost:8001/healthz");
>        setup.AddHealthCheckEndpoint("endpoint2", "http://remoteendpoint:9000/healthz");
>        setup.AddWebhookNotification("webhook1", uri: "http://httpbin.org/status/200?code=ax3rt56s", payload: "{...}");
>     })
>     .AddSqlServer("connectionString");

**Comment by DavidCMulder** [comment]
Hi,
I noticed the same issue. When the healthcheck-ui is configured to consume health endpoints that return only 
{  "status": "Healthy"} , the exception occurs and all subsequent services are not displayed.

**Comment by CarlosLanderas** [comment]
The remote Health endpoints should use the UIResponseWriter, because the default Microsoft response is a text/plain

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/samples/HealthChecks.UI.StorageProviders/Startup.cs#L65

@Kamiljen are you using the UIResponseWriter in your remote endpoints?

**Comment by DavidCMulder** [comment]
Hi Carlos, the response in my context is with Content-Type: application/json. 
But maybe regardless of content-type and/or response, the overview should not break on an 'unsupported' health endpoint.

**Comment by Kamiljen** [comment]
Hi Carlos,
I wasn't in my test, but I know that some of the endpoints I want to monitor does. I'll try with one witch does and get back to you.
I agree with @DavidCMulder about the view not breaking for a 'unsupported' health endpoint though.

**Comment by JackPoint** [comment]
I've the same problem. I'd require authentication on my health endpoints. When the endpoint returns a 401 with no content, it says:

`Response is null or message can't be deserialized as HealthChecks.UI.Core.UIHealthReport.`

The output window says the same:

`System.InvalidOperationException: Response is null or message can't be deserialized as HealthChecks.UI.Core.UIHealthReport.`

But when the health endpoint returns content (the http body) like this:

`{"type":"https://httpstatuses.com/401","title":"Unauthorized","status":401,"traceId":"[....]"}`

The output window shows me this error:

```
HealthChecks.UI.Core.HostedService.HealthCheckCollectorHostedService: Error: HealthCheck collector HostedService threw an error: Value cannot be null. (Parameter 'source')

System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Microsoft.Extensions.Diagnostics.HealthChecks.HealthReportExtensions.ToExecutionEntries(UIHealthReport report)
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.SaveExecutionHistory(HealthCheckConfiguration configuration, UIHealthReport healthReport)
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.Collect(CancellationToken cancellationToken)
   at HealthChecks.UI.Core.HostedService.HealthCheckCollectorHostedService.Collect(CancellationToken cancellationToken)
```

It also skips checking the health endpoints added after this one.

**Comment by sungam3r** [comment]
Please try 7.x version and reopen if this issue still exists.
