### ISSUE TITLE
Is there a way to control the frequency of health checks?

### ISSUE THREAD

**Issue by conficient** [Xabaril/AspNetCore.Diagnostics.HealthChecks#652]
So I'm trialling the Health Check capability. I see the health checks appear to run pretty much constantly, with little delay between queries. Is it possible to control the frequency of the requests, or throttle the rate at which they are queried?

**Comment by CarlosLanderas** [comment]
Hello!, yes, you can set the interval using:

```csharp
 .AddHealthChecksUI(setupSettings: setup =>
  {
     setup.SetEvaluationTimeInSeconds(5); //Configures the UI to poll for healthchecks updates every 5 seconds
  });
```

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks#ui-polling-interval

**Comment by MohammedAbdelhafez** [comment]
is there a way to control the check frequency  independently in the AddCheck() or in custom health checks implementing IHealthCheck

**Comment by CarlosLanderas** [comment]
@MohammedAbdelhafez when you use AddCheck and MapHealthChecks, they are only collected when the endpoint is called, and that is what you can configure in the UI.

**Comment by junsaw** [comment]
Is it possible to modify the frequency for scenarios like this:

 services.AddHealthChecks()
                     .AddApplicationInsightsPublisher(Configuration["App:AppInsightsInstrumentationKey"])
                     .AddAzureBlobStorage(Configuration["Data:StorageAccountConnectionString"].ToString())
                     .AddAzureTable(Configuration["Data:StorageAccountConnectionString"].ToString());
