### ISSUE TITLE
Azure Table Storage healthcheck currently not available via nuget packages

### ISSUE THREAD

**Issue by sibbl** [Xabaril/AspNetCore.Diagnostics.HealthChecks#656]
I'm currently using the latest stable version `AspNetCore.HealthChecks.AzureStorage` in version `3.3.0` and `AspNetCore.HealthChecks.CosmosDb` in version `3.1.2`.

While `AddAzureTableStorage` was already removed from the `AzureStorage` package, the new `AddAzureTable` extension method is not available yet in the stable version of the `CosmosDb` package.

I'd appreciate if this could be made accessible again using stable versions and upcoming changes would be coordinated a bit better.

Thanks in advance!

**Comment by unaizorrilla** [comment]
Hi @sibbl
Answered on #620 New Apis from Azure Storage remove the table client. For now is included on CosmosDbClient as mentioned on #620

**Comment by sibbl** [comment]
> Hi @sibbl
> Answered on #620 New Apis from Azure Storage remove the table client. For now is included on CosmosDbClient as mentioned on #620

I understood and appreciate this change. However, the removal was already released to Nuget and the addition wasn't released yet.

As of now, using the latest versions there's no way to health check an Azure Table Store.

**Comment by unaizorrilla** [comment]
Hi @sibbl 

The healthcheck is on https://www.nuget.org/packages/AspNetCore.HealthChecks.CosmosDb/3.2.1-preview package

**Comment by sibbl** [comment]
> Hi @sibbl 
> 
> The healthcheck is on https://www.nuget.org/packages/AspNetCore.HealthChecks.CosmosDb/3.2.1-preview package

...which is not a stable version as I mentioned in my initial comment. 😉

I initially thought it might be a mistake that this was removed while not having a new version ready for production use yet. But I see there's no interest in such feedback and that's alright...

Thanks and enjoy your day!

**Comment by unaizorrilla** [comment]
Hi @sibbl 

I'm sorry if some of my words sounds like no interest!

I appreciate the feedback, the package is on pre-release because the Microsoft library to work with tables is also on pre-release I can't do anything meanwhile microsoft lib still on preview!

**Comment by andyblack19** [comment]
If you're going to remove this useful extension without any stable alternative, then at least update your readme which says it's available. 
Also, shouldn't you have bumped the major version here, if making this breaking change and removing functionality?

**Comment by unaizorrilla** [comment]
Hi @andyblack19 

Sorry!!  I agree and appreciate this feedback!
