### ISSUE TITLE
Healthchecks for Hangfire

### ISSUE THREAD

**Issue by pajzo** [Xabaril/AspNetCore.Diagnostics.HealthChecks#66]
I'm working on a Hangfire HealtCheck package.

Is there anything that i should be aware of before creating a PR? I'm new to open source contributions :)

See my work here:
https://github.com/pajzo/AspNetCore.Diagnostics.HealthChecks/tree/add-hangfire

**Comment by unaizorrilla** [comment]
Hi @pajzo 

Looks good, please send a PR and I try to start a conversation if any is not good, ok?

**Comment by pajzo** [comment]
@unaizorrilla deal - i just send the PR :)

#67

**Comment by unaizorrilla** [comment]
Merged, at this moment the healthcheck is very limited to number of failed executions, can you improve the functionality with more scenarios??

Thanks!
