### ISSUE TITLE
AddAzureKeyVault: 'IHealthChecksBuilder' does not contain a definition for 'AddAzureKeyVault'

### ISSUE THREAD

**Issue by iTiamo** [Xabaril/AspNetCore.Diagnostics.HealthChecks#660]
**What happened**: I used the AddAzureKeyVault method to add an Azure Key Vault health check. I then get the following error:

```
Error CS1929 'IHealthChecksBuilder' does not contain a definition for 'AddAzureKeyVault' and the best extension method overload 'AzureKeyVaultConfigurationExtensions.AddAzureKeyVault(IConfigurationBuilder, Uri, TokenCredential)' requires a receiver of type 'IConfigurationBuilder'
```

**What you expected to happen**: The Azure Key Vault health check to be registered.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install AspNetCore.HealthChecks.AzureKeyVault (3.2.0)
2. Add Health checks in ConfigureServices
3. Add Azure Key Vault health check

**Source code sample**:

```
services.AddHealthChecks()
    .AddAzureKeyVault(new Uri(Configuration["KeyVault:Endpoint"]), CredentialsProvider.GetAzureCredential())
    .AddDbContextCheck<RepositoryContext>();
```

**Anything else we need to know?**:

**Environment**:

- .NET Core version 3.1
- Healthchecks version 3.2.0

**Comment by anthonielance** [comment]
The _setup_ action is a required parameter. I was able to get this to work by passing in _null_ or an empty action `setup => {}` for that parameter.

**Comment by iTiamo** [comment]
Thanks @anthonielance, must not have had my coffee that day.

**Comment by sanjaydebnath** [comment]
@iTiamo @anthonielance But if we pass empty setup, the health check I believe will not even validate the connection to KV, until we have something like 'AddSecret()' inside the setup. Then is there any point of adding this?

Also we should add some .Getxxx() functions too as in many cases there wont be permission to add anything in KV but to get.
