### ISSUE TITLE
Upgrading HealthChecks.CosmosDb from 3.1.1 to 3.1.2 causes the health checks to fail with a resource not found response

### ISSUE THREAD

**Issue by yannify** [Xabaril/AspNetCore.Diagnostics.HealthChecks#663]
Upgrading HealthChecks.CosmosDb from 3.1.1 to 3.1.2 causes the health checks to fail with a resource not found response.

Output when using version 3.1.1:

```
{"status":"Healthy","totalDuration":"00:00:01.0445038","entries":{"self":{"data":{},"duration":"00:00:00.0012345","status":"Healthy","tags":[]},"CosmosDb-Check":{"data":{},"duration":"00:00:01.0338736","status":"Healthy","tags":["a","b"]}}}
```

Output when using 3.1.2

```
{"status":"Unhealthy","totalDuration":"00:00:02.9601614","entries":{"self":{"data":{},"duration":"00:00:00.0010857","status":"Healthy","tags":[]},"cosmosdb":{"data":{},"description":"Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: e965714d-6155-4f5e-a839-a5803cbf8cb0; Reason: ({\n  \u0022Errors\u0022: [\n    \u0022Resource Not Found. Learn more: https://aka.ms/cosmosdb-tsg-not-found\u0022\n  ]\n});","duration":"00:00:02.9344232","exception":"Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: e965714d-6155-4f5e-a839-a5803cbf8cb0; Reason: ({\n  \u0022Errors\u0022: [\n    \u0022Resource Not Found. Learn more: https://aka.ms/cosmosdb-tsg-not-found\u0022\n  ]\n});","status":"Unhealthy","tags":["a","b"]}}}
```

**Environment**:

- .NET Core version : 3.1
- Healthchecks version 3.1.1

**Comment by unaizorrilla** [comment]
Hi @yannify 

Just tested with new Azure CosmosDb and is working well on my side.

´´´csharp
.AddCosmosDb("AccountEndpoint=https://[account].documents.azure.com:443/;AccountKey=[key]", "[DatabaseName]");
´´´

Please, can you check any other related issue or add more information?

**Comment by yannify** [comment]
Hi @unaizorrilla,  

Thanks for the quick response!  Your example helped me solve my problem, I was missing the optional parameter of "[DatabaseName]"

So it appears that the upgrade from 3.1.1 to 3.1.2 is potentially a breaking change for some.

I found this recent PR where [DatabaseName] was introduced.

[Add support to specify the database to check for existence](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/commit/a7cf68cfcdb18f650ffa24db0c19644d2b244bb3#diff-ae05d5aaa64cac2d7bf73c86584b4978fcf2ccde189732dd6f0b8705edb7f4f7)

**Comment by unaizorrilla** [comment]
You can also add database name on the connection string without use the new parameter
