### ISSUE TITLE
Azure Service Bus Queue and Azure Queue Storage registrations use the same name

### ISSUE THREAD

**Issue by adrianiftode** [Xabaril/AspNetCore.Diagnostics.HealthChecks#665]
Please, fill the following sections to help us fix the issue

**What happened**:

These two health checks use the same name for the corresponding registrations

**What you expected to happen**:

To use different names

**How to reproduce it (as minimally and precisely as possible)**:

[AddAzureQueueStorage](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/96465d0424b8877378a7a3d74c1477e02bb7deed/src/HealthChecks.AzureStorage/DependencyInjection/AzureStorageHealthCheckBuilderExtensions.cs#L81)

[AddAzureServiceBusQueue](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/1acc622d698c80adb5272a92ee226176d7ee49a7/src/HealthChecks.AzureServiceBus/DependencyInjection/AzureServiceBusHealthCheckBuilderExtensions.cs#L58)

**Comment by CarlosLanderas** [comment]
@adrianiftode this looks like a bug!. Thanks for catching this

**Comment by sungam3r** [comment]
Names are `azure_queue_storage` and `azurequeue` after #2038
