### ISSUE TITLE
Does AspNetCore.HealthChecks.UI.MySql.Storage supports MariaDB

### ISSUE THREAD

**Issue by Gopichandar** [Xabaril/AspNetCore.Diagnostics.HealthChecks#668]
Can is use AspNetCore.HealthChecks.UI.MySql.Storage for MariaDB or any other workaround for this to use use HealthCheckUI with MariaDB backend

**Comment by CarlosLanderas** [comment]
Hello @Gopichandar . Let me take a look into it and maybe we can release a new Maria DB provider package

**Comment by CarlosLanderas** [comment]
According to Pomelo package this are the supported versions:

Currently supported versions are:

MySQL 8.0
MySQL 5.7
MariaDB 10.5
MariaDB 10.4
MariaDB 10.3

If you are using that versions you might only configure the connection string and it should work.

Give it a try and let us know if it does not work.

Thanks!
