### ISSUE TITLE
HealthChecksUI is not logging execution records to DB when no instance of the application is open

### ISSUE THREAD

**Issue by netcorenewbee** [Xabaril/AspNetCore.Diagnostics.HealthChecks#674]
Please, fill the following sections to help us fix the issue

**What happened**: My application is hosted in IIS, I see executions being recorded into the db only when the application is open in the browser. I'm using SQLServerStorage. Is this by design?

**What you expected to happen**: I expect the application to continuously monitor my healthcheck endpoints even when the application is not open in any browser and records the entries to the DB. When using In-Memory option the application is checking behind the scenes continuously but when using SQLServer Storage option I don't see the corresponding records.

**How to reproduce it (as minimally and precisely as possible)**: Use SQLServer Storage, Host your app in IIS and close all your browsers after starting the app pool. No executions are recorded. As soon as your application is launched in a browser it will start recording the executions entries in dbo.Executions table. Close the application browser, it will stop recording entries after 5 minutes of closing the browser.

**Source code sample**:

**Anything else we need to know?**:

**Environment**:

- .NET Core version - 3.1
- Healthchecks version -3.1.2
- Operative system - Win10
- Others:

**Comment by deathchurch** [comment]
I am also seeing this issue with the exact same setup.

**Comment by netcorenewbee** [comment]
One reason why I think this could be happening is because I have both my localhost and the IIS instance pointing to the same DB server. If I leave my IIS instance alone, it is saving execution records just fine.

**Comment by deathchurch** [comment]
I have now tried Health Checks UI on its own server running just that site, and it is setup to use a remote SQL server and the same thing is happening. After ~20minutes the executions will stop firing unless you are constantly having the Health Checks Status page running in a browser somewhere.

Started a new database and OnStateFrom was 09:31 and then LastExecuted was 09:51, it will only start executing again when I hit the Health Checks Status page.

**Comment by CarlosLanderas** [comment]
Hello everyone!. Do you have the following configurations in your IIS (not express):


For your hosted service to start automatically, you need to set the Start Mode of the application pool to Always Running.

For your hosted service to keep running indefinitely, you need to set the Idle Time-out of the application pool to 0

Source:
https://stackoverflow.com/questions/53753802/do-recurring-hosted-services-require-keep-alive

**Comment by sungam3r** [comment]
Closed as answered.
