### ISSUE TITLE
Allow HttpHandlers on AddUrlGroup and AddUri extension methods

### ISSUE THREAD

**Issue by Jaxelr** [Xabaril/AspNetCore.Diagnostics.HealthChecks#675]
**What would you like to be added**:
I would like the ability to customize the HttpClientHandlers in a similar fashion to the ConfigureWebhooksEndpointHttpclient and ConfigureApiEndpointHttpclient customization handler.

**Why is this needed**:
I currently have some websites that i would like to monitor behind an IIS 10 with windows authentication enabled. I would like to pass network credentials as part of the request to those URLs.

**Comment by CarlosLanderas** [comment]
@Jaxelr PR created!
