### ISSUE TITLE
Health checks for IDbConnection

### ISSUE THREAD

**Issue by tiakun** [Xabaril/AspNetCore.Diagnostics.HealthChecks#676]
**What would you like to be added**: Health checks package for generic `IDbConnection`

**Why is this needed**: While current health checks packages covers all popular databases, the packages themselves depends on the data access package which might conflict or duplicate with the package used in the application project. For example, there are `System.Data.SqlClient` and `Microsoft.Data.SqlClient` but if the application use `System.Data.SqlClient` then the `Microsoft.Data.SqlClient` is the dependency that duplicates in functionalities. The health check package that supports `IDbConnection` will solve this problem for those who doesn't want to include extra dependencies.

I would like to discuss if this is a good alternative solution to vendor-specific packages and I would like to contribute if everyone thinks it is a good thing.

**Comment by sungam3r** [comment]
I would not do that. Technically, there is no difficulty to do this, but the question is in the convenience of use. It's not enough to write health check class as such, that is, inherit from `IHealthCheck`. You still need to provide a way to connect/setup it to the application. It is when connecting a check, the settings that are specific for each check are specified. In this case, these settings are unique for each database provider. There are many databases. Not only relational. There are object/graph databases, cloud (Azure), etc.

Regarding dependencies and possible conflicts (System.Data.SqlClient vs Microsoft.Data.SqlClient). This is a well-known common problem and it concerns any application.

I close this one but feel free to post other comments.
