### ISSUE TITLE
Invalid host services while using `AddHealthChecksUI()` with Azure Functions

### ISSUE THREAD

**Issue by amih90** [Xabaril/AspNetCore.Diagnostics.HealthChecks#677]
Please, fill the following sections to help us fix the issue

**What happened**:
Failed to use HealthChecksUI together with Azure functions dependency injection, not sure if it is a bug or should be an enhancement. I haven't seen any docs about it

exception: 
```
A host error has occurred during startup operation '49eceb31-3c63-4a83-808e-10f82c46594c'.
func: Invalid host services. Microsoft.Azure.WebJobs.Script.WebHost: The following service registrations did not match the expected services:
[Invalid] ServiceType: Microsoft.Extensions.Hosting.IHostedService, Lifetime: Singleton, ImplementationType: HealthChecks.UI.Core.HostedService.UIInitializationHostedService, HealthChecks.UI, Version=3.1.3.0, Culture=neutral, PublicKeyToken=null
[Invalid] ServiceType: Microsoft.Extensions.Hosting.IHostedService, Lifetime: Singleton, ImplementationType: HealthChecks.UI.Core.HostedService.HealthCheckCollectorHostedService, HealthChecks.UI, Version=3.1.3.0, Culture=neutral, PublicKeyToken=null
[Invalid] ServiceType: Microsoft.Extensions.Hosting.IHostedService, Lifetime: Singleton, ImplementationType: HealthChecks.UI.Core.Discovery.K8S.KubernetesDiscoveryHostedService, HealthChecks.UI, Version=3.1.3.0, Culture=neutral, PublicKeyToken=null.
Value cannot be null. (Parameter 'provider')
```

**What you expected to happen**:
I've expected that a UI endpoint will be exposed as azure function.

**How to reproduce it (as minimally and precisely as possible)**:

**Source code sample**:
```
public class Startup : FunctionsStartup
{
    public override void Configure(IFunctionsHostBuilder builder)
    {
         builder.Services.AddHealthChecks()
           .AddSqlServer(<connection-string>)
           .AddApplicationInsightsPublisher();
          builder.Services.AddHealthChecksUI();
```

**Anything else we need to know?**:

**Environment**:

- .NET Core version netcoreapp3.1
- Healthchecks version AspNetCore.HealthChecks.UI 3.1.3

**Comment by CarlosLanderas** [comment]
@amih90 , the UI is compatible with Asp.Net Core and can be run in Kestrel or IIS servers. 
I don't think this can be run within an Azure Function due to it's internals, hosted services etc.

We have a docker image that you can use in Azure Containers Instances, Kubernetes, WebApp for containers, etc.
