### ISSUE TITLE
HealthChecks should never throw and always return a HealthCheckResult

### ISSUE THREAD

**Issue by vertonghenb** [Xabaril/AspNetCore.Diagnostics.HealthChecks#68]
Currently some `HealthChecks` can `throw,` but they should always return a `HealthCheckResult`.

For example in the `AzureBlobStorage`
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/7ee7a278279bbc776e309affc3304826905eb4f0/src/HealthChecks.AzureStorage/AzureBlobStorageHealthCheck.cs#L16

Throws:
```
FormatException: Settings must be of the form "name=value".
Microsoft.WindowsAzure.Storage.CloudStorageAccount+<>c.<Parse>b__97_0(string err) in CloudStorageAccount.cs, line 529
```

The `CloudStorageAccount.Parse(connectionString)` throws if the `connectionstring` is invalid. A solution for this would be to take in the connectionstring in the `constructor` as we do now, but parse the string in the `CheckHealthAsync` function. Which will `catch` the exception and return a `HealthCheckResult`

**Comment by vertonghenb** [comment]
Other HealthChecks that have this behavior:
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/7ee7a278279bbc776e309affc3304826905eb4f0/src/HealthChecks.AzureStorage/AzureQueueStorageHealthCheck.cs#L16

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/7ee7a278279bbc776e309affc3304826905eb4f0/src/HealthChecks.AzureStorage/AzureTableStorageHealthCheck.cs#L16

**Comment by unaizorrilla** [comment]
Hi @vertonghenb 

I try to check this issue today, thanks for fill this

**Comment by vertonghenb** [comment]
Dont worry i'll open a PR today.

**Comment by vertonghenb** [comment]
As an addition we could log a ValidationError from here: https://github.com/Azure/azure-storage-net/blob/master/Lib/Common/NameValidator.cs

**Comment by unaizorrilla** [comment]
merged!
