### ISSUE TITLE
More liberal DNS Check - check only for existence of at least 1 IP address

### ISSUE THREAD

**Issue by bakgerman** [Xabaril/AspNetCore.Diagnostics.HealthChecks#684]
**What would you like to be added**:
So today DNS Check compares the dns name and IP number in the arguments.   I wanted a DNS check that only checks if there is at least 1 IP Address found, in other words I wanted only to check the the DNS name is in fact registered.

**Why is this needed**:
I don't need to verify that the IP Address is a certain value, just that the dns name has at least 1 IP Address.
Perhaps make the IP Addresses in the DNS health checks arguments nullable, and if null only check that there is at least 1 IP address for that dns name.

**Comment by CarlosLanderas** [comment]
We have the DnsResolveHealthCheck, we can add DnsResolveHostsCountHealthCheck to the network package.

**Comment by bakgerman** [comment]
That would be nice.  You could maybe specify an int that says at least how many IPs should be found.

**Comment by CarlosLanderas** [comment]
@bakgerman take a lot to the PR (you can configure minHosts and maxHosts)

**Comment by bakgerman** [comment]
Cool, I will examine the PR by end of today.

**Comment by bakgerman** [comment]
I have updated to the preview version of the NuGet and will try it tomorrow
