### ISSUE TITLE
Application Insights - Availability

### ISSUE THREAD

**Issue by JackPoint** [Xabaril/AspNetCore.Diagnostics.HealthChecks#688]
**What would you like to be added**:
I added the package to report the health checks to Application Insights. It seems I can only find the results via Metrics -> Namespace: azure.applicationinsights -> Metric: AspNetCoreHealthCheckStatus. This also only reports the total, not the individual checks.

I expected to see the availability in the Application Insights Availability section. That gives me a nice overview about the availability. I also tested this package https://www.nuget.org/packages/Orneholm.ApplicationInsights.HealthChecks/ that seems to send data to the Application Insights Availability section.

Is this on purpose that the data is not available in the Availability section? I set the saveDetailedReports to true in the configuration. If I misconfigured this and the data should be there let me know.

**Why is this needed**:
The Availability option in Application Insights seems to be build for this. You can combine it with other checks and build alerting on it (alerting is also possible in current situation)

**Comment by CarlosLanderas** [comment]
Hello @JackPoint. This sounds interesting. Let me take a look into it

**Comment by JackPoint** [comment]
Hi @CarlosLanderas did you find time to look into this?

**Comment by sungam3r** [comment]
Please open PR to change `HealthChecks.Publisher.ApplicationInsights` package from this repo if this issue is still actionable.
