### ISSUE TITLE
Missing changelog with breaking API notices

### ISSUE THREAD

**Issue by hlovdal** [Xabaril/AspNetCore.Diagnostics.HealthChecks#693]
**What happened**:
Updating AspNetCore.HealthChecks.Rabbitmq from 3.0.3 to 3.1.4 caused build failure due to breaking API changes.

**What you expected to happen**:
When APIs are changed in a breaking way, that should be explicitly documented.

**Source code sample**:

```csharp
services.AddHealthChecks().AddRabbitMQ(rabbitMQConnectionString: ConvertRabbitMQUrl(options)); // 3.0.3
```

```csharp
services.AddHealthChecks().AddRabbitMQ(rabbitConnectionString: ConvertRabbitMQUrl(options)); // 3.1.4
```

**Solution**.

Please add a proper changelog document to this projects to at least document API breakages, although summarizing general changes is also good.

BTW the corresponding

```csharp
        /// <param name="rabbitMQConnectionString">The RabbitMQ connection string to be used.</param>
```
line in RabbitMQHealthCheckBuilderExtensions.cs was not updated when the parameter was renamed and should be fixed as well.

**Comment by sungam3r** [comment]
Generally speaking, this is not a backward incompatible _binary_ change to API. Your case is source code backward incompatibility. This is not so bad because you own the code and can just recompile it. However, I understand that even if the parameter name changes, programs may behave incorrectly if they use late binding and method lookup.

**Comment by sungam3r** [comment]
For now all changes in public APIs for each packable project are tracked by API approval files. For example, see https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/test/HealthChecks.Npgsql.Tests/HealthChecks.NpgSql.approved.txt
