### ISSUE TITLE
OpenID Connect server looks only at HTTP response code

### ISSUE THREAD

**Issue by sgielen** [Xabaril/AspNetCore.Diagnostics.HealthChecks#701]
**What happened**:

I performed a test health check to Identity Server and, to check its behaviour, I had an incorrect URL on purpose: "/ssox/" instead of "/sso/", where "/sso/" is reverse proxied to Identity Server. On "/" and below, all non-SSO requests return a single-page web application with 200 OK, so this occurred for "/ssox/" as well. There is no possibility for me to change this as the application depends on it.

To my surprise, the health check succeeded. This is because the health check only looks at HTTP status code, not whether the response makes any sense otherwise. However, from the HTTP response it is clearly visible that it is not Identity Server responding:

- content-type is not application/json but text/html
- body does not contain json
- even if body was interpretable as json, it does not contain issuer, jwks_uri, authorization_endpoint and all other typical keys in the response

**What you expected to happen**:

I expected the health check to fail since the Identity Server URL is not properly answered by an Identity Server.

**How to reproduce it (as minimally and precisely as possible)**:

```
                healthCheckBuilder.AddIdentityServer(identityServerUri);
```

Use an identityServerUri that responds 200 for all paths under it, but serves e.g. HTML instead of JSON. The path ".well-known/openid-configuration" will be requested and the response will erroneously be accepted by the Identity Server health checker.

**Environment**:

- .NET Core version: 3.1
- Healthchecks version: 3.1.1 (but also as of [current master](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/ca3b043/src/HealthChecks.IdSvr/IdSvrHealthCheck.cs))

**Comment by sungam3r** [comment]
PR is welcome.
