### ISSUE TITLE
5.0.0 versions of packages do not support .NET Standard?

### ISSUE THREAD

**Issue by FireEater64** [Xabaril/AspNetCore.Diagnostics.HealthChecks#705]
I see that `5.0.0` versions of these packages [have just been published](https://www.nuget.org/packages/AspNetCore.HealthChecks.Rabbitmq/5.0.0) - which is awesome 🙂 However, it appears that (most of) these newly published versions _only_ target `net5.0`, and have dropped support for `netstandard`. Is this intentional?

![image](https://user-images.githubusercontent.com/1670176/103279279-53e78980-49c5-11eb-89fd-133a9772c4e8.png)

Possibly related to #650

**Comment by CarlosLanderas** [comment]
@FireEater64, I am working in some improvements for version 5.0.0, so we are going to deploy a new release soon. I've been testing Uris healthcheck with multi target (netstandard20 and net5.0) and I thing we are going to add netstandard to all healthchecks packages if possible. The Operator and the UI will be .NET 5.0 though. @unaizorrilla  and I were discussing about this the other day and I thing supporting netstandard is necessary.
