### ISSUE TITLE
How to get health check for each and every endpoint in the API

### ISSUE THREAD

**Issue by SriAzureDev** [Xabaril/AspNetCore.Diagnostics.HealthChecks#706]
I would like to how to get healthcheck for each and every endpoint in an API. When i use the samples of UI and API, i can able to see its just healthy, but if any of my end point fails, i could not able to track.

It would be great if you can provide a sample.

The code which i used is
ConfigureServices:
 services.AddHealthChecks()
                .AddSqlServer(Configuration.GetConnectionString("SQLConnectionString"),
                  healthQuery: "SELECT 1;",
                  name: "Sql Server",
                  failureStatus: HealthStatus.Degraded)
                .Services
                .AddControllers();
            services.AddHealthChecksUI();
Configure:
 app.UseHealthChecks("/health", new HealthCheckOptions()
            {
                Predicate = _ => true,
                ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
            });

            app.UseMvc(cfg =>
            {
                cfg.MapRoute("Default",
                "{controller}/{action}/{id?}",
                new { controller = "App", Action = "Index" });
            })
            .UseHealthChecksUI();

**Comment by CarlosLanderas** [comment]
Hello @SriAzureDev . Could you explain me what you are trying to do?. Are you trying to test your controllers or something like that?

**Comment by projectje** [comment]
I do not think you would want to this with a healthcheck but with a unit test, regression test or something alike, otherwise your system will explode and it seems illogical to test the same endpoint numerous time just in case a unit test failed to verify the workings.

Then again... you could parse the generated Swagger API , parse the XML and generate the code for the HealthCheck Classes. E.g. here is some example PowerShell code to parse it and generate files:

` $swagger = Get-Content -Path $SwaggerFile -Encoding UTF8 -Raw | ConvertFrom-Json
    $swagger.paths |Get-ObjectMember | ForEach-Object {
        $obj = [pscustomobject]@{
            path    = $_.Key
            methods = $_.Value | Get-ObjectMember | ForEach-Object Key
        }
        $obj.methods | ForEach-Object {
            [string]$httpmethod = $_
            $filenameelements = $obj.path.Substring(5).split("/") -join "_"
            $filename = $filenameelements + "_" + $httpmethod
            $contentelements = $obj.path.Substring(5).split("/") -join "/"
            $content = '(Get-ChildItem -Path "$PSScriptRoot\..\Modules" -Recurse -Filter "*.psm1" -Verbose).FullName | ForEach-Object { Import-Module $_ -Force}' + "`n"
            $content += "$" + "path = '/api/" + $contentelements +"'" + "`n"
            $content += "`n"; $content | Out-File "$($OutPutDir)$($filename).ps1"
}}
`

**Comment by sungam3r** [comment]
Closed as stale.
