### ISSUE TITLE
Add Minio health checks

### ISSUE THREAD

**Issue by AdamHodgson** [Xabaril/AspNetCore.Diagnostics.HealthChecks#709]
**What would you like to be added**:
Health checks for [minio](https://min.io/) databases.

**Why is this needed**:
Expands the range of supported services.

**Comment by Vfialkin** [comment]
Minio is compatible with S3,so you should be able to use S3 healthchecks
https://github.com/xabaril/AspNetCore.Diagnostics.HealthChecks
