### ISSUE TITLE
HealthCheck - AppSettings

### ISSUE THREAD

**Issue by vertonghenb** [Xabaril/AspNetCore.Diagnostics.HealthChecks#71]
What often comes up is that AppSettings are not specified correctly, however I don't believe in the idea that the application should not StartUp if the AppSettings are invalid. I'd rather let the application start up and afterwards check the Settings using a Health Check.

### API Proprosal:

```cs
services.AddAppSettingsHealthCheck<AppSettings,AppSettingsValidator>()
```

### AppSettings
```cs
    public class AppSettings
    {
        public string MySetting1 { get; set; }
        public int MySetting2 { get; set; }
    }
```

### AppSettings Validator (FluentValidation)
```cs
public class AppSettingsValidator : AbstractValidator<AppSettings>
    {
        public AppSettingsValidator()
        {
            RuleFor(x => x.MySetting1).IsValidSQLConnectionString();
            RuleFor(x => x.MySetting2).NotEmpty();
        }
    }
```

### HealthCheck
- No Generics yet, but you'll get the point
- Using `FluentValidation` to check for the settings;
```cs
public class AppSettingsHealthCheck : IHealthCheck
    {
        private readonly AppSettings _settings;
        private readonly IValidator<AppSettings> _validator;

        public AppSettingsHealthCheck(IOptions<AppSettings>, IValidator<AppSettings> validator)
        {
            _settings = settings.Value;
            _validator = validator;
        }
        public async Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken = default(CancellationToken))
        {
            var result = await _validator.ValidateAsync(_settings);
            if (result.IsValid)
                return HealthCheckResult.Healthy("AppSettings are valid.");

            return HealthCheckResult.Unhealthy("AppSettings are invalid", new ValidationException("AppSettings Validation Failed", result.Errors));
        }
    }
```

### Result (as an example)
- MySetting1 is not a valid ConnectionString
- MySetting2 is cannot be empty

**Comment by unaizorrilla** [comment]
Umm let me check with more people!

**Comment by vertonghenb** [comment]
@unaizorrilla sure , give me a heads-up when you have a design reader

**Comment by CarlosLanderas** [comment]
@vertonghenb, thanks for your contribution. I do think that appsettings checking should be a task that has to be done on startup. Is difficult for me to see it like a Health check. It might have sense it you configure your settings with hot reload tough

**Comment by unaizorrilla** [comment]
I can close this?

**Comment by vertonghenb** [comment]
@CarlosLanderas 
The basic idea is that you:
- Always let the App Startup without any isses (wrong appsettings etc)
- But once the app is started, you can check for the AppSettings(if they're ok or not)

**Comment by carlowahlstedt** [comment]
I agree with @vertonghenb here. There might be situations where your app settings are invalid but it might only impact a small section of the site. Keeping the entire site from coming up, would mean that users couldn't even run in "degraded mode" until this one configuration was corrected.

This would also allow other libraries that require specific AppSettings to be configured to use this so that only their feature doesn't working but there can still be a notification that something isn't working.

**Comment by vertonghenb** [comment]
@carlowahlstedt i implementeren something like this not so long ago I’ll pr it when I get back from vacation
