### ISSUE TITLE
AspNetCore.HealthChecks.SqlServer version 5.0.0 and 5.0.1 are not working with SQL Kerberos authentication

### ISSUE THREAD

**Issue by yoniv87** [Xabaril/AspNetCore.Diagnostics.HealthChecks#710]
Please, fill the following sections to help us fix the issue.

**What happened**:

My SQL server is authenticated behind Kerberos.
I have upgraded the "AspNetCore.HealthChecks.SqlServer" NuGet package to version 5.0.0 or 5.0.1, and when I run the health check, I am getting an error "Cannot authenticate using Kerberos. Ensure Kerberos has been initialized ..."

**What you expected to happen**:

It should use the Kerberos ticket that configured on the machine (as it does in version 3.2.0)

**How to reproduce it (as minimally and precisely as possible)**:
1. Have an AD and a SQL server configured to work with Kerberos
1. On a Linux machine with KRB5 installed, create a Kerberos ticket ("kinit {username}")
2. Call the application health endpoint

**Source code sample**:
```
 services.AddHealthChecks()
                .AddSqlServer(connectionString: "Data Source=db1.contoso.com,1433;Trusted_Connection=True");
```

**Anything else we need to know?**:
It works perfectly in previous versions (like 3.2.0)

**Environment**:
Any Linux distribution with Kerberos

- .NET Core version: 5.0
- Healthchecks version: 5.0.0
- Operative system: Linux

**Comment by unaizorrilla** [comment]
Thanks @gr-liam  for contribute this, a new release is on appveyor, when finished a new package 5.0.2 will be available on nuget!

**Comment by yoniv87** [comment]
Thanks, @gr-liam and @unaizorrilla.
