### ISSUE TITLE
Provide Dapr health check

### ISSUE THREAD

**Issue by tomkerkhove** [Xabaril/AspNetCore.Diagnostics.HealthChecks#712]
**What would you like to be added**:
Provide Dapr health check to determine if it can talk to the sidecar.

**Why is this needed**:
To ensure that the integration is setup correctly and that the sidecar is reachable & up.

**Comment by dmytrohridin** [comment]
I can take it, when the new version with https://github.com/dapr/dotnet-sdk/pull/662 will be released

**Comment by tomkerkhove** [comment]
Thanks @dmytrohridin !
