### ISSUE TITLE
Add Azure Digital Twin HealthCheck

### ISSUE THREAD

**Issue by CarlosLanderas** [Xabaril/AspNetCore.Diagnostics.HealthChecks#715]
**What would you like to be added**:

An Azure Digital Twin healthcheck that can check models and twin instances

**Comment by rafaarcangel** [comment]
You can see a PR on https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/766

**Comment by carlosrecuero** [comment]
PR merged and generate package AzureDigitalTwin 6.0.0
