### ISSUE TITLE
AspNetCore.HealthChecks.SqlServer from v3.2.0 to >= v5.0.0 DB Connection Issues

### ISSUE THREAD

**Issue by LeeStevens318** [Xabaril/AspNetCore.Diagnostics.HealthChecks#721]
**What happened**:
Upgrading **AspNetCore.HealthChecks.SqlServer** from v3.2.0 to >= v5.0.0 causing the application to stop working. It has issues connecting to the database, when it was perfectly fine on v3.2.0 upgraded and downgraded multiple times to check it is the package upgrade causing the issue.

It effects the whole application i think it's due to one of the required upgrades by upgrading to new version. The First exception thrown is:

Microsoft.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 25 - Connection string is not valid)

Again, downgrading works fine the connection string:

Server=server_name\\SQLSERVER,1433;Initial Catalog=db_name;User ID=username;Password=password;MultipleActiveResultSets=true

**What you expected to happen**:
Upgrade with no issues.

**How to reproduce it (as minimally and precisely as possible)**:
This project is rather large and has many other packages so not possible to show, give source code.

**Anything else we need to know?**:
Requires these licenses, so could be a dependency causing the issue?

![image](https://user-images.githubusercontent.com/28816427/107161977-568dc380-69f4-11eb-9dd3-af798e59ffd4.png)

**Environment**:

- .NET Core version: 5.0.102
- Healthchecks version: 5.0.1
- Operative system: Windows 10 Pro, 10.0.19042
- Others:

**Comment by LeeStevens318** [comment]
@erik-johansson-stratsys can you elaborate what you mean `copy the AddSqlServer`, i still have this issue.

**Comment by fernandezja** [comment]
> > @erik-johansson-stratsys can you elaborate what you mean `copy the AddSqlServer`, i still have this issue.
> 
> Remove the package reference and copy these two files into your project, and simply use them instead:
> 
> https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.SqlServer/SqlServerHealthCheck.cs
> 
> https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.SqlServer/DependencyInjection/SqlServerHealthCheckBuilderExtensions.cs
> 
> Hopefully that should work for you too.
> 
> I'm really confused about why this issue happens, my only guess is that it's related to the version of Microsoft.Data.SqlClient.

This troubleshoot work for me... 

1.  Remove package reference > AspNetCore.HealthChecks.SqlServer (5.0.2)
2. Copy these two files (SqlServerHealthCheck.cs and SqlServerHealthCheckBuilderExtensions.cs)
3. And add reference nuget [Microsoft.Data.SqlClient](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). I use version 2.1.2
  `  <PackageReference Include="Microsoft.Data.SqlClient" Version="2.1.2" />`

**Comment by unaizorrilla** [comment]
Hi all!

I'm so sorry for delay on the responses here! :-( , there is not the best times for me ..

I just updated the package to use the latest Microsoft.Data.SqlClient version 2.1.2 and create some repro for this, but I can't see the issue on my side, please note my comments on https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/760

A new build is on appveyor, when finsihed a package with version 5.0.3 will be available for AspNetCore.HealthChecks.SqlServer!

Unai

**Comment by LeeStevens318** [comment]
@unaizorrilla no problem, at least you got to it. I have upgraded and everything is now ok!
