### ISSUE TITLE
Update CRD apiVersion to apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by Kampfmoehre** [Xabaril/AspNetCore.Diagnostics.HealthChecks#723]
**What would you like to be added**:
Update the apiVersion of the Kubernetes health check operator from `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1`.

**Why is this needed**:
Custom resource definitions with the apiVersion `apiextensions.k8s.io/v1beta1` are depcretaed and will be removed in Kubernetes 1.22+. See the [release Notes of Kubernetes 1.16](https://v1-16.docs.kubernetes.io/docs/setup/release/notes/).

I would make a PR with the required changes if it is wanted. The change is relatively small and can be seen in this commit https://github.com/droidsolutions/AspNetCore.Diagnostics.HealthChecks/commit/9e9738024e0282cfa3576b6f27de8241d66fbc0f

**Comment by rafa-arcangel** [comment]
@carlosrecuero can we do something about this?.. If you want, you can assign it to me.
