### ISSUE TITLE
Serialization and deserialization of 'System.Type' instances are not supported

### ISSUE THREAD

**Issue by npandrei** [Xabaril/AspNetCore.Diagnostics.HealthChecks#724]
Please, fill the following sections to help us fix the issue

**What happened**:
Using a 3rd party HealthCheck (MassTransit) that returns an Exception object cannot be serialized. Receiving this error 

`System.NotSupportedException: Serialization and deserialization of 'System.Type' instances are not supported and should be avoided since they can lead to security issues. Path: $.Entries.Data.Exception.TargetSite.DeclaringType.`

**What you expected to happen**:
The serialization to work / Have a way to handle this

**How to reproduce it (as minimally and precisely as possible)**:
I can try to create an example, but I think it is pretty straight forward what the issue is.

**Environment**:

- .NET Core version: 5.0
- Healthchecks version 5.0.1

**Comment by unaizorrilla** [comment]
Hi @npandrei 

On which library is the issue?

**Comment by npandrei** [comment]
> Hi @npandrei
> 
> On which library is the issue?

Hi @unaizorrilla 

I am using `MassTransit` with `RabbitMq`.

**Comment by NatMarchand** [comment]
Hi there!
Should be fixed with an upcoming release of MassTransit, see mentionned issue above.

**Comment by npandrei** [comment]
> Hi there!
> Should be fixed with an upcoming release of MassTransit, see mentioned issue above.

hi, cool thanks ! will check when it is released
