### ISSUE TITLE
Cannot compile with Kubernetes HealthCheck

### ISSUE THREAD

**Issue by LandryDubus** [Xabaril/AspNetCore.Diagnostics.HealthChecks#726]
**What happened**:
When trying to configure a Kubernetes health check using the AspNetCore.HealthChecks.Kubernetes package, I got the following errors while the KubernetesClient package was correctly referenced in the project (version 4.0.12):

> The type 'KubernetesClientConfiguration' is defined in an assembly that is not referenced. You must add a reference to assembly 'KubernetesClient, Version=3.0.0.0, Culture=neutral, PublicKeyToken=a0f90e8c9af122de'.
> 
> The type 'V1Deployment' is defined in an assembly that is not referenced. You must add a reference to assembly 'KubernetesClient, Version=3.0.0.0, Culture=neutral, PublicKeyToken=a0f90e8c9af122de'.

I am not able to compile the project with this Kubernetes health check.
Other health checks (Redis, Azure Keyvault) work seemlessly.

**What you expected to happen**:
I expected the code to be able to compile.

**Source code sample**:
```csharp
services.AddHealthChecks()
             .AddKubernetes(options => options
                    .WithConfiguration(KubernetesClientConfiguration.BuildDefaultConfig())
                    .CheckDeployment("deployment-name", d => !string.IsNullOrEmpty(d.Name()), "namespace"));
```

**Environment**:
- .NET Core version: 5
- Healthchecks version: 5.0.1 (AspNetCore.HealthChecks.Kubernetes) - 5.0.3 (Microsoft.Extensions.Diagnostics.HealthChecks)
- KubernetesClient version: 4.0.12
- Operative system: Windows 10 20H2

**Comment by VarukVlad** [comment]
Hello! I'd like to vote up this request. Have the same issue. Any solution?

**Comment by sungam3r** [comment]
Current version of package references v4:
```
  <PackageReference Include="KubernetesClient" Version="4.0.26" />
```

**Comment by sungam3r** [comment]
Current version of KubernetesClient is 11.0.44
