### ISSUE TITLE
TcpHealthCheck option to specify the AddressFamily (IPV4 or IPV6) of the IP protocol

### ISSUE THREAD

**Issue by mj-nico23** [Xabaril/AspNetCore.Diagnostics.HealthChecks#730]
Hi,
First, thank you for this excelente work. In my team we've been using healthchecks for a while without issues.

**What would you like to be added**:
An option to [TcpHealthCheck](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.Network/TcpHealthCheck.cs) to specify the [AddressFamily](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.addressfamily?view=net-5.0) (IPV4 or IPV6) to use in the [TcpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient.-ctor?view=net-5.0#System_Net_Sockets_TcpClient__ctor_System_Net_Sockets_AddressFamily_).

**Why is this needed**:
In our case while we were migrating a service to a new resource one dependency started to came back unhealthy.
This was a service dependency inside the same vnet and we use a TcpHealthCheck to check the connection, we noticed the service was reachable by the new resource. In fact the integration was working fine, the only thing failing was the healthcheck.
The error was _"An attempt was made to access a socket in a way forbidden by its access permissions. [::ffff:10.XX.XX.XX]:443"_. 

I created a custom healthcheck to use the TcpClient with the option AddressFamily.InterNetwork (IPV4) and this start working as  expected.
The only difference in my custom [TcpHealthCheck](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.Network/TcpHealthCheck.cs) implementation is the optional TcpClient AddressFamily parameter.
```csharp
public async Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken = default)
{
    try
    {
        foreach (var (host, port) in _options.ConfiguredHosts)
        {
            using (var tcpClient = new TcpClient(AddressFamily.InterNetwork)) // Use IPV4 AddressFamily
            {
                await tcpClient.ConnectAsync(host, port).WithCancellationTokenAsync(cancellationToken);

                if (!tcpClient.Connected)
                {
                    return new HealthCheckResult(context.Registration.FailureStatus, description: $"Connection to host {host}:{port} failed");
                }
            }
        }
        return HealthCheckResult.Healthy();
    }
    catch (Exception ex)
    {
        return new HealthCheckResult(context.Registration.FailureStatus, exception: ex);
    }
}
```

Maybe can be a good idea to expose this AddressFamily option through the [TcpHealthCheckOptions](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/d5b6d17b79eb5aa61449682953ae3f7b5c07825b/src/HealthChecks.Network/TcpHealthCheckOptions.cs)

If this sound good to you I can send a PR with this changes.

**Comment by unaizorrilla** [comment]
Hi @mj-nico23 

This will be fixed on db7f318, a new release build is on appveyord, when finished a nuget package 5.0.2 for this healthcheck will be on NuGet. Sorry for delay on answer this and not allow to send a PR on time :-(
