### ISSUE TITLE
Set HealthReportEntry.Description using Exception message when status is unhealthy

### ISSUE THREAD

**Issue by Hellaren** [Xabaril/AspNetCore.Diagnostics.HealthChecks#734]
Hi there! Thanks for the awesome lib.

I've noticed that health checks for the major DBs won't set any description to the HealthReportEntry in case if exception happened during DB open operation ([mysql](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/d5b6d17b79eb5aa61449682953ae3f7b5c07825b/src/HealthChecks.MySql/MySqlHealthCheck.cs#L35), [Oracle](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/d5b6d17b79eb5aa61449682953ae3f7b5c07825b/src/HealthChecks.Oracle/OracleHealthCheck.cs#L36), [Npg](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/d5b6d17b79eb5aa61449682953ae3f7b5c07825b/src/HealthChecks.NpgSql/NpgSqlHealthCheck.cs#L42)).

This leads to a problem that DefaultHealthCheckService logs an error that looks like:
> [Error] [5] [Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService+Log.HealthCheckEnd] 
 Health check DB completed after 1234.567ms with status Unhealthy and '(null)'

The "(null)" part represents the description property that is empty.

Is there any design decision that was made to avoid setting an exception message as a description for the check result, or it's ok to fix that? 

Note:
I've tried to look for a similar issue, but found only #145 and seems like it was created for UI part.

**Comment by sungam3r** [comment]
I think this issue is covered by setting custom `UIResponseWriter`, see #1581.
