### ISSUE TITLE
Error when publishing self-contained app

### ISSUE THREAD

**Issue by gabrielmaldi** [Xabaril/AspNetCore.Diagnostics.HealthChecks#735]
Please, fill the following sections to help us fix the issue

**What happened**:

Running `dotnet publish --self-contained --runtime osx-x64` on an app which references `AspNetCore.HealthChecks.Network 5.0.1` fails:

```
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
MyProject.csproj : error NU1605: Detected package downgrade: System.Threading.ThreadPool from 4.3.0 to 4.0.10. Reference the package directly from the project to select a different version.
MyProject.csproj : error NU1605:  MyProject -> AspNetCore.HealthChecks.Network 5.0.1 -> SSH.NET 2016.1.0 -> System.Net.Sockets 4.1.0 -> runtime.unix.System.Net.Sockets 4.3.0 -> System.Threading.ThreadPool (>= 4.3.0)
MyProject.csproj : error NU1605:  MyProject -> AspNetCore.HealthChecks.Network 5.0.1 -> SSH.NET 2016.1.0 -> System.Threading.ThreadPool (>= 4.0.10)
```

**What you expected to happen**:

A succesful build.

**How to reproduce it (as minimally and precisely as possible)**:

Just create a .NET 5 project and reference `AspNetCore.HealthChecks.Network 5.0.1`. Then run `dotnet publish --self-contained --runtime osx-x64` (or whatever your runtime is).

**Source code sample**:

**Anything else we need to know?**:

Although this can be circumvented with `<NoWarn>NU1605</NoWarn>` or `<WarningsAsErrors></WarningsAsErrors>` it is not desirable at all since it might fail at runtime.

**Environment**:

- .NET Core version: `5.0.103`
- Healthchecks version `5.0.1`
- Operative system: `macOS Catalina 10.15.7`
- Others:

**Comment by sungam3r** [comment]
Just for infogmation - you can disable `NU1605` warning or/and set `TreatWarningAsErrors` to `false`.
