### ISSUE TITLE
environment variable 'HealthChecksUI__HealthChecks' does not override appsettings.json

### ISSUE THREAD

**Issue by ruwentos** [Xabaril/AspNetCore.Diagnostics.HealthChecks#742]
When we deploy our health check website inside a container, we can see that an environment variable is set like:

HealthChecksUI__HealthChecks=[{"Name":"house value micro-service","Uri":"http://housevalue-ms/NORD/MicroService-houseValue/hc"},{"Name":"Client micro-service","Uri":"http://Client-ms/NORD/MicroService-Client/hc"}]

It does not overwrite the value `"HealthChecksUI": {
    "HealthChecks": []}` in the appsettings.json.

According to your manual this would be expected behavior ([link](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#environment-variables)).

- .NET Core version 3.1
- Healthchecks version 3.1.3
- Operative system: Ubuntu 20.04

**Comment by sungam3r** [comment]
@ruwentos Please reopen with minimum runnable repro if issue is still actual.
