### ISSUE TITLE
Caching Calls to Health Checks

### ISSUE THREAD

**Issue by pghdeveloper** [Xabaril/AspNetCore.Diagnostics.HealthChecks#745]
Not really an enhancement request, but I'm having trouble figuring out how to cache the health checks so that certain health checks don't get run all the time.  Since they get run implicitly as opposed explicitly, I can use the MemoryCache library.

**Comment by alex-sameli** [comment]
An option would be to make CheckHealthAsync virtual and then create a CachedXYHealthCheck. Using a decorator is a bit terse because the default DI does not support decorating (You'd roll your own, or use Scruptor).

**Comment by sungam3r** [comment]
Another option is to write custom `HealthCheckService` taking majority of implementation from `DefaultHealthCheckService`.
