### ISSUE TITLE
CosmosDb Healthchecks in 5.x causes exception when reading from Cosmos Db SQL API

### ISSUE THREAD

**Issue by Ronnehag** [Xabaril/AspNetCore.Diagnostics.HealthChecks#748]
Please, fill the following sections to help us fix the issue

**What happened**:
Updating HealthChecks to 5.x to enable AzureTable extension causes CosmosDb serialization to throw error
"Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Azure.Cosmos.Serialization.HybridRow.Result>"
Using CosmosDb SQL api with Microsoft.Azure.Cosmos 3.17.1.
Downgrading HealthChecks to 3.x makes it work again, but doesn't add the functionality to add healthchecks for azure table storage.

**What you expected to happen**:
Enable health checks for Azure Table Storage and keeping CosmosDb working.

**How to reproduce it (as minimally and precisely as possible)**:
Use CosmosDb SQL with Microsoft.Azure.Cosmos 3.17.1. 
Add AspNetCore.HealthChecks.CosmosDb 5.0.1.
Add AddAzureTable() Healthcheck to IServiceCollection.
Read/writing data to CosmosDb with SQL API.

**Source code sample**:

**Anything else we need to know?**:
{"Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Azure.Cosmos.Serialization.HybridRow.Result> Microsoft.Azure.Cosmos.Serialization.HybridRow.RecordIO.RecordIOStream.ReadRecordIOAsync(System.IO.Stream, System.Func`2<System.ReadOnlyMemory`1<Byte>,Microsoft.Azure.Cosmos.Serialization.HybridRow.Result>, System.Func`2<System.ReadOnlyMemory`1<Byte>,Microsoft.Azure.Cosmos.Serialization.HybridRow.Result>, Microsoft.Azure.Cosmos.Serialization.HybridRow.MemorySpanResizer`1<Byte>)'."}

**Environment**: Local with Cosmos emulator

- .NET Core version: 5.0
- Healthchecks version
AspNetCore.HealthChecks.AzureStorage Version="5.0.1"
AspNetCore.HealthChecks.CosmosDbVersion Version="5.0.1"
AspNetCore.HealthChecks.UI.Client Version="5.0.1"
- Operative system: Windows 10
- Others:

**Comment by sungam3r** [comment]
Please try with the latest versions of packages and reopen if issue still exists.
