### ISSUE TITLE
Health Checks for Azure Search

### ISSUE THREAD

**Issue by ctvanzandt42** [Xabaril/AspNetCore.Diagnostics.HealthChecks#756]
**What would you like to be added**:

I'd like to add a health check for Azure Search.

**Why is this needed**:

As companies move towards share-nothing architecture, Azure Search is becoming more and more popular. Its API is pretty easy to interact with and the ability to index CosmosDB and Azure SQL Server makes it a great candidate for a search solution. It's also used as the primary persistence model for some applications, and thus, it'd be good to establish health with it.

**Comment by ctvanzandt42** [comment]
@unaizorrilla Does this mean you're planning to implement? Am I free to work on building this out myself?

**Comment by homemadesoftware** [comment]
I would like to help with this. I am using Azure Search and Asp.Net Health checks in a project and I have already added an implementation for my own use. I am happy to bring this to a standard to fit with the rest of the project and send a pull request. 
How do I start please?

**Comment by cieciurm** [comment]
Hello,

Azure Search support has been added in #1843 :)
