### ISSUE TITLE
Release new version for AspNetCore.HealthChecks.DynamoDb and AspNetCore.HealthChecks.Aws.S3 to avoid build errors/warnings

### ISSUE THREAD

**Issue by edumserrano** [Xabaril/AspNetCore.Diagnostics.HealthChecks#758]
**What would you like to be added**:

Release an updated version of the AWS S3 and AWS DynamobDB health check packages.

AWS has released version 3.7.x of these packages which depend now on `AWSDK.Core 3.7.x` package but the current dependency on AWSDK.Core package on the AWS health check packages is for `AWSSDK.Core (>= 3.5.1.32 && < 3.6.0)`.

I would like to update the version used here:
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/50594f0643515e83f9bf6ce864f9594bf980b865/build/dependencies.props#L71
and
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/50594f0643515e83f9bf6ce864f9594bf980b865/build/dependencies.props#L78

So that the dependency on AWSSDK.Core get's update as well to version 3.7.

**Why is this needed**:

When using a project targetting .NET 5  `<TargetFramework>net5.0</TargetFramework>`, I want to use a package from AWSSDK that is on version 3.7.x on my project, for instance `AWSSDK.Extensions.NETCore.Setup 3.7.0.1`, and I want to also use the `AspNetCore.HealthChecks.DynamoDb` package. Currently this fails with the following warning:
```
Error	NU1107	Version conflict detected for AWSSDK.Core. Install/reference AWSSDK.Core 3.7.0 directly to project ClassLibrary1 to resolve this issue. 
 ClassLibrary1 -> AWSSDK.Extensions.NETCore.Setup 3.7.0.1 -> AWSSDK.Core (>= 3.7.0) 
 ClassLibrary1 -> AspNetCore.HealthChecks.DynamoDb 5.0.1 -> AWSSDK.DynamoDBv2 3.5.1.10 -> AWSSDK.Core (>= 3.5.1.32 && < 3.6.0).
```

If I do what is suggested and add `AWSSDK.Core 3.7.0` instead of an error I now get the following warning:
```
warning NU1608: Detected package version outside of dependency constraint: AWSSDK.DynamoDBv2 3.5.1.10 requires AWSSDK.Core (>= 3.5.1.32 && < 3.6.0) but version AWSSDK.Core 3.7.0 was resolved.
```

**Comment by unaizorrilla** [comment]
Hi @edumserrano 

A new release build is on appveyor, when finished a new packages 5.0.2 for DynamoDb and S3 will be availables on NuGet!
