### ISSUE TITLE
CosmosDb health check is not supporting auth keys

### ISSUE THREAD

**Issue by mateuszdomaszczynski** [Xabaril/AspNetCore.Diagnostics.HealthChecks#762]
While adding health check for CosmosDb there should be option for providing auth key, next to connectionstring using constructor:
new CosmosClient(string connectionString, string authKeyOrResourceToken)

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.CosmosDb/CosmosDbHealthCheck.cs#L41

**Comment by unaizorrilla** [comment]
Hi @mateuszdomaszczynski 

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.CosmosDb/CosmosDbHealthCheck.cs#L41 use the override for connection string not (account endopint, resource key).

You can create the connection string with both parameters use it on AddCosmosDb

Regards
Unai

**Comment by carlosrecuero** [comment]
This issue is stale after 9 months without an answer.
