### ISSUE TITLE
Securing the UI by adding sign in to Microsoft Azure AD

### ISSUE THREAD

**Issue by SoucianceEqdamRashti** [Xabaril/AspNetCore.Diagnostics.HealthChecks#765]
Hello,

I am wondering how I would go about securing the UI by ensuring users sign in to Azure AD first.

I have seen this link:
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/492

I have also seen that you can add MicrosoftIdentityWebUI but that is only an option to controllers or Razor pages. How would I embedded that in the Health Check UI?

Essentially what I want is that users not signed ut are sent to azure ad for sign in and redirected back and upon log off go to some log off page.

I have created the app in the azure with all the settings but not sure how to configure this in the startup and enable it on the health check ui. 

Thanks.

**Comment by CarlosLanderas** [comment]
Take a look at this sample:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/samples/HealthChecks.UI.Oidc/Startup.cs

**Comment by SoucianceEqdamRashti** [comment]
I did try that but upon running I got this error:
`System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.
 ---> System.IO.IOException: IDX20807: Unable to retrieve document from: 'System.String'. HttpResponseMessage: 'System.Net.Http.HttpResponseMessage', HttpResponseMessage.Content: 'System.String'.
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

Here is my startup:
```
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.OpenApi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace HealthCheckUI
{
    public class Startup
    {
        private const string HealthChecksUIPolicy = nameof(HealthChecksUIPolicy);
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {

            services.AddControllers();
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "HealthCheckUI", Version = "v1" });
            });
            services.AddHealthChecksUI(setupSettings: setup =>
            {
                setup.ConfigureApiEndpointHttpclient((sp, client) =>
                {
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", "cm91bmR0aGVjb2RlOnJvdW5kdGhlY29kZQ==");
                });
            })
            .AddInMemoryStorage().Services
                .AddAuthorization(cfg =>
                {
                    cfg.AddPolicy(name: HealthChecksUIPolicy, cfgPolicy =>
                    {
                        cfgPolicy.AddRequirements().RequireAuthenticatedUser();
                        cfgPolicy.AddAuthenticationSchemes(OpenIdConnectDefaults.AuthenticationScheme);
                    });
                })
                .AddAuthentication(options =>
                {
                    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
                })
                .AddCookie(options =>
                {
                    options.SlidingExpiration = true;

                })
                .AddOpenIdConnect(options =>
                {
                    options.Authority = "https://login.microsoftonline.com/tenantid/oauth2/v2.0/authorize";
                    options.ClientId = "id";
                    options.ClientSecret = "secret";
                    options.ResponseType = "code";
                    options.SaveTokens = true;
                });
    }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseSwagger();
                app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "HealthCheckUI v1"));
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapHealthChecksUI().RequireAuthorization(HealthChecksUIPolicy);
            });
        }
    }
}
```

**Comment by SoucianceEqdamRashti** [comment]
Seems to be the authority url.

When changing it to **`https://login.microsoftonline.com/{tenantId}`** then I and redirected to the AAD login. Does that mean that you are adding additional parts to the final url?
