### ISSUE TITLE
HealthChecksPushService can't connect to an ExternalName service

### ISSUE THREAD

**Issue by rafaarcangel** [Xabaril/AspNetCore.Diagnostics.HealthChecks#772]
When I try to connect HealthCheck operator using an ExternalName service, the system throws an exception, because it can't connect.

When trying to create address, throws an: Object null exception.
Reviewing the code, the problem was that the current CreateAdderss method from KubernetesAddressFactory tries to get the address from the service.Spect.ClusterIP, but, in the case of external name services, this value must be null.

```
    class KubernetesAddressFactory
    {
        public static string CreateAddress(V1Service service, HealthCheckResource resource)
        {
            var defaultPort = int.Parse(resource.Spec.PortNumber ?? Constants.DefaultPort);
            var port = GetServicePort(service)?.Port ?? defaultPort;
            var address = service.Spec.ClusterIP;
```

**Comment by rafaarcangel** [comment]
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/773

**Comment by carlosrecuero** [comment]
Already integrated in another PR. Thank you for your collaboration @rafaarcangel .
