### ISSUE TITLE
Invalid nuget name in Prometheus Exporter section

### ISSUE THREAD

**Issue by skalinets** [Xabaril/AspNetCore.Diagnostics.HealthChecks#775]
**What happened**:
In the documentation (section [HealthChecks Prometheus Exporter](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks#healthchecks-prometheus-exporter)) the nuget package is invalid (`AspNetcore.HealthChecks.Publisher.Prometheus`)

**What you expected to happen**:
The nuget package should read `AspNetCore.HealthChecks.Prometheus.Metrics`

**Comment by lurumad** [comment]
Thanks @skalinets
