### ISSUE TITLE
InvalidOperationException: EventHubProducerClient can't be created using the specified connection

### ISSUE THREAD

**Issue by sharmilamuthukrishnan** [Xabaril/AspNetCore.Diagnostics.HealthChecks#778]
I have installed AspNetCore.HealthChecks.AzureServiceBus packager version 5.1.0. And I have added health check for Azure Event hub. I wanted to make sure connection should be made over AMQP, so I have used Func for the connection string,
 ```
services.AddHealthChecks().AddAzureEventHub(options=> new EventHubConnection(eventHubConnectionString,eventHubName,new EventHubConnectionOptions
            {
                TransportType = EventHubsTransportType.AmqpWebSockets
            }), name: "EventHub", tags: new[] { "healthLive" }).ForwardToPrometheus();
```
But getting error as InvalidOperationException: EventHubProducerClient can't be created using the specified connection.
But if I use connection string like below :
 ```
services.AddHealthChecks().AddAzureEventHub(eventHubConnectionString,eventHubName, name: "EventHub", tags: new[] { "healthLive" }).ForwardToPrometheus();
```
its working fine and getting Healthy status as response.

**Comment by lurumad** [comment]
Hi @unaizorrilla 

Can you review the PR?

Regards!

**Comment by sharmilamuthukrishnan** [comment]
thanks.
Its working now.
