### ISSUE TITLE
HealthChecks UI Docker Image description error

### ISSUE THREAD

**Issue by thxu2** [Xabaril/AspNetCore.Diagnostics.HealthChecks#78]
change this

docker pull xabarilcoding/healthchecksui 
docker run --name ui -p 5000:80 -d healthchecksui:latest

on 

docker pull xabarilcoding/healthchecksui 
docker run --name ui -p 5000:80 -d xabarilcoding/healthchecksui:latest

**Comment by unaizorrilla** [comment]
Thanks @thxu2 , on Readme.md??

**Comment by thxu2** [comment]
ui-docker.md

**Comment by unaizorrilla** [comment]
done!

**Comment by thxu2** [comment]
and in the line with params to)

**Comment by CarlosLanderas** [comment]
Changed. Thanks @thxu2
