### ISSUE TITLE
AzureKeyVault health check always returns "healthy"

### ISSUE THREAD

**Issue by cshaw33** [Xabaril/AspNetCore.Diagnostics.HealthChecks#785]
Please, fill the following sections to help us fix the issue

**What happened**:
I am setting up an AzureKeyVault health check and wanted to ensure that the health check would return Unhealthy if the connection to the KeyVault failed.  I attempted to test this by using an invalid URL when setting up the health check.  Even when an invalid url is used (fomatted as a valid url, but not pointing towards an Azure Key Vault instance), the health check returns "Healthy".

The same behavior also occurs when the KeyVault setup is commented out of Program.cs CreateHostBuilder setup code and there is no valid AzureKeyVault connection, so the health check is not falling back on the KeyVault connection added to the host builder.

It's possible that my health check setup is incorrect, but even so I would expect Unhealthy to be returned for a health check that is misconfigured.

**What you expected to happen**:
If the incorrect URL is passed in when setting up the Health Check, the check should return "Unhealthy"

**How to reproduce it (as minimally and precisely as possible)**:
Set up an AzureKeyVault health check using a url that does not point to a valid Azure Key Vault.  Ping health check endpoint, status returned is 200 OK

**Source code sample**:
Health Check setup in Startup.cs ConfigureServices method:
```c#
            services.AddHealthChecks()
                .AddDiskStorageHealthCheck(s => s.AddDrive("C:\\", healthCheckThresholdOptions.DiskStorageMinimumFreeMegabytes)) // At least 1 GB free
                .AddProcessAllocatedMemoryHealthCheck(healthCheckThresholdOptions.ProcessAllocatedMemoryMaximumMegabytesAllocated); // 1 GB max allocated memory

            var keyVaultEndpoint = configuration[ConfigurationKeys.KeyVault];
            if (!string.IsNullOrWhiteSpace(keyVaultEndpoint))
            {
                services.AddHealthChecks()
                    .AddAzureKeyVault(
                        new Uri("https://www.thisisnotarealurl.com"),
                        new DefaultAzureCredential(),
                        setup =>
                        {
                            setup
                            .UseKeyVaultUrl("https://www.thisisnotarealurl2.com")
                            .UseAzureManagedServiceIdentity();
                        });
            }

            return services;
```

Serialized health report:
```json
{
	"Entries": {
		"diskstorage": {
			"Data": {},
			"Description": null,
			"Duration": "00:00:00.0005483",
			"Exception": null,
			"Status": 2,
			"Tags": []
		},
		"process_allocated_memory": {
			"Data": {},
			"Description": "Allocated megabytes in memory: 30 mb",
			"Duration": "00:00:00.0011718",
			"Exception": null,
			"Status": 2,
			"Tags": []
		},
		"azurekeyvault": {
			"Data": {},
			"Description": null,
			"Duration": "00:00:00.0001661",
			"Exception": null,
			"Status": 2,
			"Tags": []
		}
	},
	"Status": 2,
	"TotalDuration": "00:00:00.0013350"
}
```

**Anything else we need to know?**:

**Environment**:

- .NET Core version netcoreapp3.1
- Healthchecks version 3.1 (tested with AspNetCore.HealthChecks.AzureKeyVault package versions 3.1.1 and 3.2.0)
- Operative system: Windows 10 Pro version 1809
- Others:

**Comment by sungam3r** [comment]
@cshaw33 Things have changes over years, there are no `UseKeyVaultUrl` and `UseAzureManagedServiceIdentity` methods anymore, but I reproduced aforementioned behavior. Indeed, HC returns OK if you do not call `AddSecret`, `AddKey,` or `AddCertificate` on the provided `AzureKeyVaultOptions`.
