### ISSUE TITLE
Always getting "Sequence contains no elements" in Health Check UI just on testing stage

### ISSUE THREAD

**Issue by emjion** [Xabaril/AspNetCore.Diagnostics.HealthChecks#786]
**Actual:**
In test environment I'm always faced with this topic
![image](https://user-images.githubusercontent.com/5416988/120994625-f41bb880-c784-11eb-8b8f-bfb21ab46858.png)
Remote debugging leads to no result. Implemented health check looks good on local machine.

**Expected:**
Get the corresponding health-check as I do something like that HealthCheckResult.Healthy(...) on my local machine and no exceptional message like "sequence contains no element" on testing stage

**Startup.cs** 
![image](https://user-images.githubusercontent.com/5416988/120993266-a8b4da80-c783-11eb-9f69-4af79b1db971.png)

ConfigureServices
![image](https://user-images.githubusercontent.com/5416988/120993598-fa5d6500-c783-11eb-9281-f9ac5b8ad6fe.png)

Real Health-Check
![image](https://user-images.githubusercontent.com/5416988/120993896-44dee180-c784-11eb-9be2-9010f9e74dc5.png)

**Environment**:

- .NET Core version: 3.1
- Healthchecks version: 3.1.1
- Operative system: Windows 10

**Comment by sungam3r** [comment]
Please try the latest v7 versions of packages and reopen if issue is still actual.
