### ISSUE TITLE
RabbitMQ: OneHostOnly or MemoryLeak

### ISSUE THREAD

**Issue by maksym-kovalov** [Xabaril/AspNetCore.Diagnostics.HealthChecks#796]
Hello!
I have set of RabbitMQ hosts and need to check all hosts.

**What happened**:
1) If I use .AddRabbitMQ (with Singleton inside) - I get the last registered healthcheck status only - for any HealthCheck.
(this issue about it https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/764)
2) If I use HealthCheckRegistration instead and passed on a ConnectionFactory for each host - I get correct statuses but memory leak.
(this issue about it https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/563)

**What you expected to happen**:
Correct HealthCheck statuses for all hosts and correct work with memory.

**How to reproduce it (as minimally and precisely as possible)**:
First case - register 2 HealthChecks (one for working host, another - for none-working) - by AddRabbitMQ.

Second Case - register 2 HealthCheck (working hosts or not - does not matter)
checksBuilder.Add(new HealthCheckRegistration(
		name: $"{RabbitMQHealthCheck}[{connection.Host}]", 
		factory: (Func<IServiceProvider, IHealthCheck>)(sp => 
			(IHealthCheck)new RabbitMQHealthCheck(new ConnectionFactory()
			{
				Uri = new Uri(connection.ConnectionString),
				AutomaticRecoveryEnabled = true
			})),
		failureStatus: failureStatus,
		timeout: timeOut,
		tags: Settings.Tags
	)
);

**Environment**:
- AspNetCore.HealthChecks.Rabbitmq 5.0.1
- .NET Core version 3.1
- Operative system: Win10

Give me please an advice how to register HealthChecks correctly - for set of RabbitMQ hosts.

**Comment by unaizorrilla** [comment]
Hi @ maksym-kovalov 

You can use a different aproach for this case.. 

The first one is registered your singleton for your N host

With something like that 

```csharp
   services.AddSingleton<IConnectionFactory>(sp =>
            {
                return new ConnectionFactory()
                {
                    Uri = new Uri("amqp://hostA:5672"),
                    HostName = "hostA"
                };
            });

            services.AddSingleton<IConnectionFactory>(sp =>
            {
                return new ConnectionFactory()
                {
                    Uri = new Uri("amqp://hostB:5672"),
                    HostName = "hostB",
                };
            });

```

and instead of using our AddRabbitMQ use Add directly 


```csharp
  services
                .AddApplicationInsightsTelemetry()
                .AddHealthChecks()
                .Add(new HealthCheckRegistration(
                    "HostA",
                    sp => new RabbitMQHealthCheck(sp.GetServices<IConnectionFactory>().Where(c=>c.Uri.Equals("amqp://hostA:5672")).Single()),
                    HealthStatus.Unhealthy,
                    Enumerable.Empty<string>()))
                .Add(new HealthCheckRegistration(
                    "HostB",
                    sp => new RabbitMQHealthCheck(sp.GetServices<IConnectionFactory>().Where(c => c.Uri.Equals("amqp://hostB:5672")).Single()),
                    HealthStatus.Unhealthy,
                    Enumerable.Empty<string>()));
```

Obviously, use configuration instead of magic connection strings, and a more smart aproach instead where.first, but this is only to ilustrate the way to do that!

Unai
