### ISSUE TITLE
Allow the specification of tolerations on the healthchecks-ui pod

### ISSUE THREAD

**Issue by Meertman** [Xabaril/AspNetCore.Diagnostics.HealthChecks#798]
**What would you like to be added**: I would like to be able to specify via the custom resource definitions which (optional) tolerations need to be set on the pod created by the operator for hosting the UI. 

**Why is this needed**: In an enterprise context, the resources created on kubernetes are often limited for running on certain nodes. One of the options to enable this limitation is through the use of tolerations. When it is not possible to set tolerations on the pods created for hosting the UI, the pod won't be assigned to any node and is thus unable to start.

**Comment by carlosrecuero** [comment]
Published on version 6.0.4 of Ui.K8sOperator package
