### ISSUE TITLE
.NET Standard support

### ISSUE THREAD

**Issue by rpopovych** [Xabaril/AspNetCore.Diagnostics.HealthChecks#802]
Hello!

I am interested in leveraging some of the healthcheck packages in my library code that targets netstandard. I was wondering why .NET runtime was targeted instead of .NET Standard and if there is a potential future where there is a switch or multi targeted build supporting both.

**Comment by sungam3r** [comment]
@rpopovych The latest preview packages (not all) were changed to switch back to netstandard2.0 ; please try the latest preview.
