### ISSUE TITLE
UI returns error but Api returns all Healthy

### ISSUE THREAD

**Issue by bartvanduinkerken** [Xabaril/AspNetCore.Diagnostics.HealthChecks#803]
Please, fill the following sections to help us fix the issue

I am using the tool version 3.1.2 with net core 3. 
When I retrieve the api /healthz all is returned as Healthy. 

But when I go to the UI I get the following error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

When I look on the server I see the following error: GetHealthReport threw an exception when trying to get report from /healthz configured with name Dependencies.

When I run the tool Locally everything works. 

I expect to UI to show all is Healthy. 

I am using: 
```
app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapHealthChecks("/healthz", new HealthCheckOptions
                {
                    Predicate = _ => true,
                    ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
                });
                endpoints.MapHealthChecksUI(setup =>
                {
                    setup.AddCustomStylesheet("resources/css/healthcheck.css");
                });
            });
```

```
services.AddHealthChecksUI(opt =>
            {
                opt.SetEvaluationTimeInSeconds(15); 
                opt.MaximumHistoryEntriesPerEndpoint(60);
                opt.SetApiMaxActiveRequests(1); 
                opt.AddHealthCheckEndpoint("Dependencies", "/healthz"); 
            }).AddInMemoryStorage();

            services.AddHealthChecks()
```

- .NET Core version 3.1
- Healthchecks version: 3.1.2
- Operative system: Windows

**Comment by projectje** [comment]
try on the line opt.AddHealthCheckEndpoint("Dependencies", "/healthz"); 

To add the root uri to it e.g. setup.AddHealthCheckEndpoint("memory", rootUri + "memory");
Where the rootUri is e.g. configuration["ApiUrl"] + "/health_";
