### ISSUE TITLE
The remote certificate is invalid [I know its duplicated]

### ISSUE THREAD

**Issue by xico002** [Xabaril/AspNetCore.Diagnostics.HealthChecks#804]
It gave me this error:
The SSL connection could not be established, see inner exception.
       ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot

I have healthchecks that connect to https endpoints. I tried this but did not work:

services.AddHttpClient("uri-group").ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler()
{
    ClientCertificateOptions = ClientCertificateOption.Manual,
    ServerCertificateCustomValidationCallback = (httpRequestMessage, cert, cetChain, policyErrors) =>
    {
        return true;
    }
});

Can you help me with this?

Regards
xico002

**Comment by xico002** [comment]
@unaizorrilla  can you help me with this please?

**Comment by Nisden** [comment]
Trying using https://github.com/dotnet/corefx/pull/19908

**Comment by xico002** [comment]
I tried this:
services.AddHttpClient("uri-group").ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler()
            {
                ClientCertificateOptions = ClientCertificateOption.Manual,
                ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
            });
Continues to give me this error:
The SSL connection could not be established, see inner exception.
---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot

Any other idea? Please

**Comment by Nisden** [comment]
Sorry no, its been working for me in other contexts.
