### ISSUE TITLE
AspNetCore.HealthChecks.Cosmosdb- Can this Package Support Managed Identity?

### ISSUE THREAD

**Issue by chitharansivasamy** [Xabaril/AspNetCore.Diagnostics.HealthChecks#818]
Please, fill the following sections to help us fix the issue

Please help to advise whether managed identity can support "AspNetCore.HealthChecks.Cosmosdb" nuget package. 

**What happened**:

-**- "AspNetCore.HealthChecks.Cosmosdb" - unable to perform with managed identity for higher environments ( QA, staging and prod)**

**What you expected to happen**:

 -- "AspNetCore.HealthChecks.Cosmosdb"  this package should accept managed identity for validating Cosmos DB.

**How to reproduce it (as minimally and precisely as possible)**:

--Use managed identity to verify the health checks with cosmos DB. 

**Source code sample**:

      CosmosClient cosmosClient = environment == "local" ?
	            new CosmosClient(cosmosConnectionString, options)
            : new CosmosClient(cosmosConnectionString, new ManagedIdentityCredential(), options);

	            var healthChecksBuilder = services.AddHealthChecks();
	
	            healthChecksBuilder.AddCosmosDb(
	              connectionString: configuration.GetValue<string>("CosmosDbSettings:ConnectionString"),
	              database: configuration.GetValue<string>("CosmosDbSettings:DatabaseName"),
	              name: "Myapp_CosmosDB",
	              failureStatus: HealthStatus.Unhealthy,
              tags: new string[] { "db", "cosmosdb", "myapp" });

**Anything else we need to know?**:

   -- Straight forward connection string with ( AccountEndpoint and AccountKey) seems to work but without Accountkey using Managed Identity is not working.

**Environment**: QA, Staging, and PROD

- .NET Core version  -- core 3.1
- Healthchecks version  -- 5.0, 3.1.2
- Operative system: - windows
- Others:

**Comment by DanielHead** [comment]
I would love this as well

**Comment by skyfrk** [comment]
FYI: [Some overloads](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/851ed1536f057825eea892f0371a5d49601fcaae/src/HealthChecks.CosmosDb/CosmosDbHealthCheck.cs#L36) have been added in the mean time that made using managed identity possible.

**Comment by sungam3r** [comment]
@chitharansivasamy Please try the latest preview.
