### ISSUE TITLE
Getting NullReferenceException when using Slack webhooks.

### ISSUE THREAD

**Issue by am26292** [Xabaril/AspNetCore.Diagnostics.HealthChecks#834]
Please, fill the following sections to help us fix the issue

**What happened**:
Getting error, very frequently, Application not crashing though.

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=HealthChecks.UI
  StackTrace:
   at HealthChecks.UI.Core.Notifications.WebHookFailureNotifier.GetFailedMessageFromContent(UIHealthReport healthReport)
   at HealthChecks.UI.Core.Notifications.WebHookFailureNotifier.<Notify>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

  This exception was originally thrown at this call stack:
    HealthChecks.UI.Core.Notifications.WebHookFailureNotifier.GetFailedMessageFromContent(HealthChecks.UI.Core.UIHealthReport)
    HealthChecks.UI.Core.Notifications.WebHookFailureNotifier.Notify(string, HealthChecks.UI.Core.UIHealthReport, bool)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Source code sample**:

appsettings.json
"HealthChecksUI": {
    "Webhooks": [
      {
        "Name": "Slack",
        "Uri": "https://hooks.slack.com/services/XXXX/XXXX",
        "Payload": "{\"text\":\"The HealthCheck [[LIVENESS]] is failing with the error message [[FAILURE]]. <XXX|Click here> to get more details.\",\"channel\":\"#bsd-salesx-alerts-preprod\",\"link_names\": 1,\"username\":\"monkey-bot\",\"icon_emoji\":\":monkey_face:\"}",
        "RestoredPayload": "{\"text\":\"The HealthCheck [[LIVENESS]] is recovered. All is up and running\",\"channel\":\"#bsd-salesx-alerts-preprod\",\"link_names\": 1,\"username\":\"monkey-bot\",\"icon_emoji\":\":monkey_face\" }"
      }
    ],
    "EvaluationTimeInSeconds": 20,
    "MaximumHistoryEntriesPerEndpoint": 50,
    "MinimumSecondsBetweenFailureNotifications": 60,
    "HealthChecks": [
      {
        "Name": "Development - XXX",
        "Uri": "xxxx/health"
      }
]
  }

public void ConfigureServices(IServiceCollection services)
        {
            ....
            services.AddHealthChecksUI().AddSqlServerStorage(connectionString);
.....
        }

public void Configure(IApplicationBuilder app)
        {
            ...

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();

                endpoints.MapHealthChecksUI(options =>
                {
                    options.AddCustomStylesheet("dotnet.css");
                });
            });
        }

**Anything else we need to know?**:

**Environment**:
Development

- .NET Core version .Net 5
- Healthchecks version : 
    AspNetCore.HealthChecks.UI" Version="5.0.1" 
    AspNetCore.HealthChecks.UI.SqlServer.Storage" Version="5.0.1"
- Operative system: Windows 10
- Others:

**Comment by sungam3r** [comment]
@am26292 I think that https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/commit/109967b57a361984ba8e7a37bdf25f8b9f471074 should fix this.
