### ISSUE TITLE
Cosmos check times out with 408

### ISSUE THREAD

**Issue by AHarman** [Xabaril/AspNetCore.Diagnostics.HealthChecks#838]
Please, fill the following sections to help us fix the issue

**What happened**:

When using the CosmosDB health check, the healthcheck fails with the following being logged:

Health check cosmosDb completed after 99812.5988ms with status Unhealthy and description '(null)'
      Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: RequestTimeout (408);

**What you expected to happen**:

The healthcheck to succeed

**How to reproduce it (as minimally and precisely as possible)**:

Run the healthcheck repeatedly over an extended period. We encountered this after pointing to the healthcheck via a readiness check in Kubernetes.

**Anything else we need to know?**:

This may be because of this issue here:

https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1610#issuecomment-886720013

> do not use ReadContainerAsync as a health check. The read container is a metadata operation. The metadata operations is Cosmos DB are limited and will eventually get throttled. 

**Environment**:

- .NET Core version: 5.0
- Healthchecks version: 5.0.4
- Operative system: Linux

**Comment by sungam3r** [comment]
Now `CosmosDbHealthCheck` uses `CosmosDbHealthCheckOptions` with optional `DatabaseId` and `ContainerIds` and `ReadContainerAsync` method is called only if you specify `ContainerIds`.
