### ISSUE TITLE
Cannot register multiple AzureServiceBus health checks

### ISSUE THREAD

**Issue by paullly** [Xabaril/AspNetCore.Diagnostics.HealthChecks#840]
Hello,

**What happened**:
I want to inject multiple health checks using the AspNetCore.HealthChecks.AzureServiceBus library.

When I try to register multiple health checks (with the name field set to different names) I get the following error "System.ArgumentException: An item with the same key has already been added."

**What you expected to happen**:
Since the name property is set, there should be multiple health checks registered.

**How to reproduce it (as minimally and precisely as possible)**:

define something like:
`                .AddAzureServiceBusTopic(config.HostName, config.SenderTopicName, 
                    new ClientSecretCredential(config.TenantId, config.ClientId, config.ClientSecret), 
                    name: $"sender_topic_{config.SenderTopicName}", HealthStatus.Degraded, new []{Probes.Ready}, 
                    new TimeSpan(0,0,0,30))`

`                .AddAzureServiceBusSubscription(config.HostName,config.ReceiverTopicName, config.ReceiverSubscriptionName, 
                    new ClientSecretCredential(config.TenantId, config.ClientId, config.ClientSecret), 
                    name: $"receiver_sub_{config.ReceiverTopicName}", HealthStatus.Degraded, new []{Probes.Ready}, 
                    new TimeSpan(0,0,0,30));
`

**Anything else we need to know?**:

**Environment**:

- .NET Core version: 5.0.301
- Healthchecks version: 5.1.1
- Operative system: macOS Big Sur 11.6
- Others:

Thanks :)!

**Comment by CarlosLanderas** [comment]
You need to specify different names in the "name" parameter. Each health check should have a unique name

**Comment by paullly** [comment]
Hello,
sorry for the late response. As you can see in the above code, that's what I did:
name: $"sender_topic_{config.SenderTopicName}"
vs. $"receiver_sub_{config.ReceiverTopicName}"

but still, get the issue

Kind Regards

**Comment by carlosrecuero** [comment]
Hi @paullly, I have tried to reproduce your issue with an equivalent code but it worked properly. It seems to be a different issue than duplicated names (in that case, the error should be; Duplicate health checks were registered with the name(s): ...".

Could you please provide us more detail about the exception you get and/or a full example?

**Comment by carlosrecuero** [comment]
This issue is stale after 3 months without an answer.
