### ISSUE TITLE
Connection string factory in AddMongoDb

### ISSUE THREAD

**Issue by ivan-codes-foss** [Xabaril/AspNetCore.Diagnostics.HealthChecks#844]
**What would you like to be added**:

An extension method for adding a health check for MongoDB which accepts a delegate to create connections strings similar to how this is done in one of the SqlServerHealthCheckBuilderExtensions.AddSqlServer extension methods. 

**Why is this needed**:

I want to be able to configure connection string by resolving it from a service which is configured with the ServiceProvider.

**Comment by sungam3r** [comment]
PR is welcome.

**Comment by sungam3r** [comment]
Duplicate of #770, fixed in #1948 .
