### ISSUE TITLE
 Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by Podsyha** [Xabaril/AspNetCore.Diagnostics.HealthChecks#848]
Hi.
Sorry for my bad english.
I get this error: **Unexpected character encountered while parsing value: <. Path '', line 0, position 0.**
Moreover, if I go directly to the link: http://localhost:61443/health, then the JSON is displayed correctly.
`{
"status": "Healthy",
"totalDuration": "00:00:00.0229911",
"entries": {
"CheckService": {
"data": {},
"description": "Ok",
"duration": "00:00:00.0051258",
"status": "Healthy",
"tags": []
}
}
}`

Config:
```
public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddHealthChecksUI(setupSettings: setup =>
            {
                setup.AddHealthCheckEndpoint("ServiceVSPlan", "http://localhost:61443/health").SetEvaluationTimeInSeconds(1);
            })
                .AddInMemoryStorage();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapHealthChecksUI();
            });
        }
    }
```

```
app.UseEndpoints(endpoints =>
			{
				endpoints.MapControllers();

				endpoints.MapHealthChecks("/health", new HealthCheckOptions() 
				{
					Predicate = _ => true,
					ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
				});
			});
```

**Comment by sungam3r** [comment]
Probably it is xml response from intermediate node (balancer or so).

**Comment by nnamacha** [comment]
Got the same issue

**Comment by nnamacha** [comment]
I have finally discovered that if you have configured the API like this: "iisSettings": { "windowsAuthentication": true, "anonymousAuthentication: false, "iisExpress": { "applicationUrl": "localhost:23850", "sslPort: 0 } } It gives you the error , Is there any way that it works with windows authentication option enabled?

**Comment by Podsyha** [comment]
> I have finally discovered that if you have configured the API like this: "iisSettings": { "windowsAuthentication": true, "anonymousAuthentication: false, "iisExpress": { "applicationUrl": "localhost:23850", "sslPort: 0 } } It gives you the error , Is there any way that it works with windows authentication option enabled?

I also have windowsAuthentication enabled and anonymousAuthentication disabled. I cannot change these parameters in my project. Apparently this is the problem.

**Comment by amccool** [comment]
IIS is handing you back an XML/HTTP payload (the error payload) rather than the json one that healthchecks want

**Comment by sungam3r** [comment]
I believe this issue can be closed.
