### ISSUE TITLE
KubernetesChecksExecutor owns Kubernetes which is diposable, so it should be disposable?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Xabaril/AspNetCore.Diagnostics.HealthChecks#855]
**What would you like to be added**:
KubernetesChecksExecutor to implement IDisposable and Dispose Kubernetes .

**Why is this needed**:
To avoid leaks

**Comment by sungam3r** [comment]
Yes and not only that place needs attention to implement disposal process correctly.

**Comment by sungam3r** [comment]
@dzmitry-lahoda Effectively created KubernetesChecksExecutor / Kubernetes  objects live till application end so there is no memory leak. Hovewer I changed the code to handle this issue.

**Comment by sungam3r** [comment]
The point is some objects are long-lived when adding new health checks so reference ownership is not obvious.

**Comment by sungam3r** [comment]
For some health checks we just store such objects in static dictionaries forever, so...
