### ISSUE TITLE
Add an health endpoint after startup

### ISSUE THREAD

**Issue by bartatlascopco** [Xabaril/AspNetCore.Diagnostics.HealthChecks#858]
I have a case were I like to add an health endpoint after the hosted health UI is loaded.

I already tried to add it to the HealthChecks.UI.Configuration.Settings at runtime.

But the new endpoints are not rendered in the UI

**Comment by BartNetJS** [comment]
I've implemented this by adding the configuration record directy into the Configuration Database.
