### ISSUE TITLE
Unable to use latest version on .NET Core 2.2

### ISSUE THREAD

**Issue by OptimumDev** [Xabaril/AspNetCore.Diagnostics.HealthChecks#859]
Hello! I was using this library (version 2.2.1) for rabbitmq healthchecks in my .net core 2.2 project. Recently I found out that it was creating new connection for every check and decided to update library version in order to fix this. But even though it's written that .net core 2.2 is supported, inner dependencies can't be installed. So it looks like it's impossible to use this library on .net core 2.2

**What happened**:
Unable to instal library on .net core 2.2

**What you expected to happen**:
Library instals on supported version of .net core (written in readme)

**How to reproduce it (as minimally and precisely as possible)**:
Instal library version 5.0.2 from nuget

**Source code sample**:

**Anything else we need to know?**:
Log from installing:
```
Restoring packages for .NETCoreApp,Version=v2.2...
Resolving conflicts for .NETCoreApp,Version=v2.2...
Version conflict detected for Microsoft.Extensions.Configuration.Abstractions. Install/reference Microsoft.Extensions.Configuration.Abstractions 5.0.0 directly to project это Nuget.ID в Rider to resolve this issue. 
 это Nuget.ID в Rider -> AspNetCore.HealthChecks.Rabbitmq 5.0.2 -> Microsoft.Extensions.Diagnostics.HealthChecks 5.0.1 -> Microsoft.Extensions.Hosting.Abstractions 5.0.0 -> Microsoft.Extensions.Configuration.Abstractions (>= 5.0.0) 
 это Nuget.ID в Rider -> Microsoft.AspNetCore.App 2.2.0 -> Microsoft.Extensions.Configuration.Abstractions (>= 2.2.0 && < 2.3.0).
```
**Environment**:

- .NET Core version: 2.2
- Healthchecks version: 5.0.2
- Operative system: Windows 10

**Comment by sungam3r** [comment]
You are right and this is a common and well-known problem. MS metapackages have upper limits on their dependencies, which actually leads to the impossibility of using current versions of dependencies although these dependencies still target `netstandard2.0`. I think that time for netcore 2.2 is [irretrievably gone](https://devblogs.microsoft.com/dotnet/net-core-2-2-will-reach-end-of-life-on-december-23-2019/) and the simplest thing to be done is to fix readme. Now work is on the transition to NET6.

**Comment by OptimumDev** [comment]
Yeah, .net core 2.2 is dead, I know it. My project is cute old and I don't want to do a lot of work on it. Just saw readme and thought that it was good possibility to fix problem just by updating lib version. I would understand if you just change info in readme.
But out of interest: why would you need `Microsoft.Extensions.Diagnostics.HealthChecks 5.0.1` in rabbitmq health checks? I looked into the code of older versions (that were using version 2.2.0 or similar) and didn't find any changes in using Microsoft health checks

**Comment by sungam3r** [comment]
No need at all, actually 😄 . Just a side effect from projects/versions unification. A lot of projects from this repo **can be** multitargeted.

**Comment by OptimumDev** [comment]
Got it 👌 
Thank you for fast reactions!

**Comment by sungam3r** [comment]
You can copy-paste all code you need. Should be not a big deal for old project.

**Comment by OptimumDev** [comment]
Yeah, will probably do that, thanks for suggestion!
Should I close the issue or it's usually done by contributors?

**Comment by sungam3r** [comment]
You can if you are OK with answers.

**Comment by OptimumDev** [comment]
Sure, thanks for help 🙂
