### ISSUE TITLE
Null ref exception on UIHealthReport.Entries

### ISSUE THREAD

**Issue by BartNetJS** [Xabaril/AspNetCore.Diagnostics.HealthChecks#862]
**What happened**: 
An api is protected with oauth and sitting behind azure APIM.
The response from APIM on an unauthorized call is a JSON response like this:
{
    "statusCode": 401,
    "message": "Access denied due to missing subscription key. Make sure to include subscription key when making requests to an API."
}

The extensions method HttpResponseMessageExtensions.As will deserialize is to a UIHealthReport with a null entries property.
And this causes a null ref exception in the extension method HealthReportExtensions.ToExecutionEntries

**What you expected to happen**:
An UIHealthReport with valid entries that gives more insights on the issue

**Source code sample**:

I suggest the following:
To avoid null ref exception:
![image](https://user-images.githubusercontent.com/4865355/143004388-f2bdbbce-5f37-44bf-b6c0-c086953fe8a3.png)

and to make the result on errors more verbose:
![image](https://user-images.githubusercontent.com/4865355/143004608-b67b8198-bcd8-42ba-a168-1cb02d66e829.png)

What do you think?

This need to be changed:
![image](https://user-images.githubusercontent.com/4865355/143005246-555fd377-0d08-42c9-b5cc-db5421b6c787.png)
But need to convert it back to TContent and I could not find a good way to do so.
Also the where TContent : UIHealthReport was needed to accomplish it in my debugging session, of course not how it should be.
Input appreciated :-)

**Comment by carlosrecuero** [comment]
Hi @BartNetJS , could you please verify if version 6.0.3 of UI (https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/911), solves your issue?

**Comment by sungam3r** [comment]
Closed as resolved due to lack of feedback.
