### ISSUE TITLE
RabbitMQ channel is not closed correctly

### ISSUE THREAD

**Issue by StevenLiekens** [Xabaril/AspNetCore.Diagnostics.HealthChecks#863]
> Disposing channel and connection objects is not enough, they must be explicitly closed with the API methods from the example above.

Ref https://www.rabbitmq.com/dotnet-api-guide.html#disconnecting

You forgot to do this in the RabbitMQ Health check. ;)

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/262e11696cce0e909b4dfb9c2968787e84733296/src/HealthChecks.RabbitMQ/RabbitMQHealthCheck.cs#L39-L43

**Comment by rwkarg** [comment]
In the RabbitMQ client, the `Model` Dispose calls Abort which call Close on the model. The linked documentation does not agree with the current implementation.

**Comment by rwkarg** [comment]
In fact, the Dispose -> Abort -> Close path will not throw an exception, but changing to directly Close the connection will potentially throw an exception (see method comment):
https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/feceedccd6b81d4b461795390432dc3330fdf596/projects/RabbitMQ.Client/client/api/IModelExtensions.cs#L220-L234

**Comment by sungam3r** [comment]
Model is closed under `try`.

**Comment by StevenLiekens** [comment]
Where?

**Comment by unaizorrilla** [comment]
> Where?

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/262e11696cce0e909b4dfb9c2968787e84733296/src/HealthChecks.RabbitMQ/RabbitMQHealthCheck.cs#L39

**Comment by rwkarg** [comment]
This would still be a behavior changed if updated. Right now a successful model creation but error on closing the model will be a Successful check, but the proposed change would instead have that scenario go to the catch block for a Failed check.

Given that the sited documentation appears inaccurate (the RabbitMQ client code already calls Close when it's disposed), is there any reason to make a change?

**Comment by StevenLiekens** [comment]
Agree, the implementation does not match the implementation.

As implemented now

- Dispose() calls Abort()
  - https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/01c07c87f19019b30f368db3575d066858387077/projects/RabbitMQ.Client/client/impl/ModelBase.cs#L505-L519
- Abort() calls Close(abort = true)
  - https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/01c07c87f19019b30f368db3575d066858387077/projects/RabbitMQ.Client/client/impl/ModelBase.cs#L1017-L1025
- Close(abort = true) swallows exceptions
  - https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/01c07c87f19019b30f368db3575d066858387077/projects/RabbitMQ.Client/client/impl/ModelBase.cs#L175-L218
 
As documentation propses
- Close() without args calls Close(abort = false)
  - https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/01c07c87f19019b30f368db3575d066858387077/projects/RabbitMQ.Client/client/impl/ModelBase.cs#L1209-L1217
- Close(abort = false) throws exceptions
  - https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/01c07c87f19019b30f368db3575d066858387077/projects/RabbitMQ.Client/client/impl/ModelBase.cs#L175-L218

So upon reviewing the code I don't think my proposed changes should be made. Making the health check implement IDisposable for owned connections still seems like a good idea though.

**Comment by sungam3r** [comment]
I updated both PRs. Good ?
