### ISSUE TITLE
Health Check UI not working

### ISSUE THREAD

**Issue by justinteaw** [Xabaril/AspNetCore.Diagnostics.HealthChecks#87]
when I go to hc-ui I see "Could not retrieve health checks data"

This is what i have in my startup page:
public void ConfigureServices(IServiceCollection services)
        {
            services
                .AddHealthChecksUI()
                .AddHealthChecks()
                .AddSqlServer(connectionString: Configuration["Data:ConnectionStrings:Monitoring"]);

        }

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            
            app.UseHealthChecks("/hc", new HealthCheckOptions()
            {
                Predicate = _ => true,
                ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
            })
            .UseHealthChecksUI(setup => 
            {
                setup.ApiPath = "/hc";
                setup.UIPath = "/hc-ui";
            });

 
        }

**Comment by CarlosLanderas** [comment]
Are you configuring the appsettings like the UI sample project? You have to tell the UI the endpoints to monitorize. In this case the same host that registers the hcs

**Comment by justinteaw** [comment]
it's similar.  What i have currently is:

Snippet

"HealthChecks-UI": {
    "HealthChecks": [
      {
        "Name": "HTTP Basic",
        "Uri": "http://localhost:5001/hc"
      }
    ],
    "Webhooks": [],
    "EvaluationTimeOnSeconds": 10,
    "MinimumSecondsBetweenFailureNotifications": 60
  }

**Comment by unaizorrilla** [comment]
Hi @justinteaw 

You have invalid configuration, please review the samples in order to set this correctly, in your code you have the same path for ui and healthcheks results.

 ```
app.UseHealthChecks("/hc", new HealthCheckOptions()
        {
            Predicate = _ => true,
            ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
        })
        .UseHealthChecksUI(setup => 
        {
            setup.ApiPath = "/hc";
            setup.UIPath = "/hc-ui";
        });
```

You can set, for example UseHealthChecks("/healthz"...)

and USeHealthChecks() without setup. After this in configuration set http://localhost:[port]/healthz

You have a sample for this scenario on 
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/tree/master/samples/HealthChecks.UIAndApiCustomization

**Comment by justinteaw** [comment]
Great, that was it! thanks!

**Comment by ranouf** [comment]
Hi,

I followed your instructions and copy in startup:
```
app.UseHealthChecks("/hc", new HealthCheckOptions()
       {
           Predicate = _ => true,
           ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
       })
       .UseHealthChecksUI(setup => 
       {
           setup.ApiPath = "/hc";
           setup.UIPath = "/hc-ui";
       });
```

But I continue to get:

> Could not retrieve health checks data

Here is my app.settings:
	```
"HealthChecksUI": {
		"HealthChecks": [
			{
				"Name": "Http and UI on single project with customizations-1",
				"Uri": "https://localhost:44360/hc-ui"
			}
		],
		"Webhooks": [],
		"EvaluationTimeinSeconds": 10,
		"MinimumSecondsBetweenFailureNotifications": 60
		//"HealthCheckDatabaseConnectionString": "Data Source=%APPDATA%\\healthchecksdb" //-> Optional, default on WebContentRoot
	},
```

**Comment by CarlosLanderas** [comment]
Hello @ranouf, you are exposing healthcheck results and api in the same /hc path.

Change the API path or use the default

Also in the appsettings, the target path is the one you register with UseHealthChecks (in this case /hc)

I recommend you to check and run the samples.

**Comment by ranouf** [comment]
The things is the sample are with .net core 3.0 and I m using 2.2. I tried to go back in the history, but I didn t succeed to find to good way to configure it :)

Thanks @CarlosLanderas  for answering, i will take a look on it today.
