### ISSUE TITLE
Add support for NATS 

### ISSUE THREAD

**Issue by illegitimis** [Xabaril/AspNetCore.Diagnostics.HealthChecks#873]
**NATS** - [The Cloud Native Messaging System](https://github.com/nats-io) is gaining a traction as a 
[Connective Technology for Adaptive Edge & Distributed Systems](https://github.com/nats-io).

It would be nice to add support for a _Nats_ health check.
New package `AspNetCore.HealthChecks.Nats`.
Proposed implementation would use the [official C# Client](https://github.com/nats-io/nats.net) for NATS.

I can prepare a PR if you want.

**Comment by carlosrecuero** [comment]
Hi @illegitimis. Yes, a PR would be welcome. Thank you

**Comment by illegitimis** [comment]
Determining projects to restore...
  Restored D:\GIT\AspNetCore.Diagnostics.HealthChecks\test\HealthChecks.Nats.Tests\HealthChecks.Nats.Tests.csproj (in 284 ms).
D:\GIT\AspNetCore.Diagnostics.HealthChecks\src\HealthChecks.Nats\HealthChecks.Nats.csproj : warning NU1604: Project dependency NATS.Client does not contain an inclusive lower bound. Include a lower bound in the dependency version 
to ensure consistent restore results. [D:\GIT\AspNetCore.Diagnostics.HealthChecks\AspNetCore.Diagnostics.HealthChecks.Nats.sln]
D:\GIT\AspNetCore.Diagnostics.HealthChecks\src\HealthChecks.Nats\HealthChecks.Nats.csproj : warning NU1701: Package 'NATS.Client 0.2.1.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramewor
k,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your projec
t. [D:\GIT\AspNetCore.Diagnostics.HealthChecks\AspNetCore.Diagnostics.HealthChecks.Nats.sln]
  Restored D:\GIT\AspNetCore.Diagnostics.HealthChecks\src\HealthChecks.Nats\HealthChecks.Nats.csproj (in 768 ms).
build: Tag is 
build: Package version suffix is ci-local
build: Build version suffix is ci-local-7056f69

**Comment by sungam3r** [comment]
Implemented in #891
