### ISSUE TITLE
POST Calls Using Health Checks 

### ISSUE THREAD

**Issue by SujeshSasidharan** [Xabaril/AspNetCore.Diagnostics.HealthChecks#874]
Is it possible to make POST Calls using ASP.NET Core Health Checks

If already we have a way we include POST Calls please let me know if not adding a feature will be useful to check POST Calls.

we can check if a POST Call is healthy or not if we can integrate with APS.NET CORE Health Checks

**Comment by sungam3r** [comment]
@SujeshSasidharan Please reopen if it's still actual.
