### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by tsmith-sdm** [Xabaril/AspNetCore.Diagnostics.HealthChecks#878]
- Start HealthChecks.UI.Sample with HealthChecksUI.HealthChecks endpoint in faulted state.
- Wait for 1st health check.
- After 1st health check restore HealthChecksUI.HealthChecks endpoint to healthy state.

healthReport.Entries is still null

![image](https://user-images.githubusercontent.com/11469115/146649276-521610e1-9a9d-431f-895e-d26c5be53d15.png)

**Comment by carlosrecuero** [comment]
Hi @tsmith-sdm , could you please verify if version 6.0.3 of UI (https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/911), solves your issue?

**Comment by sungam3r** [comment]
Closed as resolved due to lack of feedback.
