### ISSUE TITLE
Add auth to the RavenDB health check

### ISSUE THREAD

**Issue by garrmark** [Xabaril/AspNetCore.Diagnostics.HealthChecks#88]
Secured connections to ravendb 4.x use an x509 certificate.  I'd like to add this functionality to the RavenDB check:
```
// load certificate
X509Certificate2 clientCertificate = new X509Certificate2();

using (IDocumentStore store = new DocumentStore()
{
    Certificate = clientCertificate,
    Database = "Northwind",
    Urls = new[] {"https://my_secured_raven"}
}.Initialize())
{
    // do your work here
}
```
I can prepare a pull request

**Comment by unaizorrilla** [comment]
Cool!

**Comment by garrmark** [comment]
My first attempt has failed the Appveyor checks, unfortunately I have trouble running docker compose on my development machine due to conflicts with virtualbox.

Can you help me by:
1. Determining if my docker component (garrmark/ravendb-secure) is getting started properly and listening on port 8080
2. Debugging the exception that is most likely thrown in the check at AspNetCore.Diagnostics.HealthChecks\src\HealthChecks.RavenDB\RavenDBHealthCheck.cs
`
                    store.Initialize();
                    var databases = await store.Maintenance.Server.SendAsync(new GetDatabaseNamesOperation(start: 0, pageSize: 100));
`
and telling me what the message is.

Any advise to get me moving in the right direction would be welcome, thanks.
