### ISSUE TITLE
An app queue connection string with only write message permissions, returns 'Unhealthy' in the health check

### ISSUE THREAD

**Issue by Zjokke** [Xabaril/AspNetCore.Diagnostics.HealthChecks#880]
Please, fill the following sections to help us fix the issue

**What happened**:
When using a queue connection string with limited permissions (ss=q, sp=a), the health check returns 'Unhealthy'.

**What you expected to happen**:
The health check only needs to verify if the queue is accessible.

**How to reproduce it (as minimally and precisely as possible)**:
Connect to an Azure Storage Queue with a SAS limited to Queue Objects and Add permissions.

**Source code sample**:
            services.AddHealthChecks()
                    .AddAzureQueueStorage(_yourConnectionStringWithLimitedPermissions_),
                                          queueName: _yourQueueName_,
                                          name: _yourHealthCheckName_,
                                          tags: new string[] { "all", "azurequeue" })

**Anything else we need to know?**:
When providing a connection string with too many permissions for the application role, the health check works.

**Environment**:
- .NET Core version: 3.1
- Healthchecks version: 3.3.1
- Operative system: Azure App Service
- Others: N/A

**Comment by sungam3r** [comment]
`AzureQueueStorageHealthCheck` calls  `queueClient.ExistsAsync`, no write operations. Could you inspect `HealthCheckResult.Exception` property to provide some clues?

**Comment by Zjokke** [comment]
It is the earlier line
var serviceProperties = await queueServiceClient.GetPropertiesAsync(cancellationToken); 
that requires higher permissions.
See the authorization section in https://docs.microsoft.com/en-us/rest/api/storageservices/get-queue-service-properties

**Comment by Zjokke** [comment]
https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas shows that with only 'Add' permissions, also the properties of the QueueClient cannot be read. Checking the existence of the queue name should be enough for the health check.

**Comment by sungam3r** [comment]
Looks like a plan. Would you like to make PR?

**Comment by sungam3r** [comment]
?I think this one was covered by #1409.
