### ISSUE TITLE
Tag is misaligned.

### ISSUE THREAD

**Issue by Aloento** [Xabaril/AspNetCore.Diagnostics.HealthChecks#887]
![image](https://user-images.githubusercontent.com/11802769/147678759-afbaabea-777f-47a5-8468-393ca4c07c44.png)

To fix it:

![image](https://user-images.githubusercontent.com/11802769/147678858-d32cff1f-e5fa-4a4d-866c-000e7ca1600c.png)

**Comment by carlosrecuero** [comment]
Hi @Aloento , I'm running the sample of the Healthchecks UI but I can't reproduce it.

![image](https://user-images.githubusercontent.com/1546791/149015451-f370dcf6-a27e-46a2-8a1f-097dfcd123f6.png)

Could you please provide us more information related with the misalignment?

Thank you in advance.

**Comment by Aloento** [comment]
@carlosrecuero see here
https://musiland.azurewebsites.net/HealthCheck#/healthchecks

**Comment by Aloento** [comment]
@carlosrecuero see here
https://musiland.azurewebsites.net/HealthCheck#/healthchecks

```css
:root {
  --primaryColor: #68217a;
  --secondaryColor: #f4f4f4;
  --bgMenuActive: #8e47a0;
  --bgButton: #68217a;
  --bgAside: var(--primaryColor);
}
```

**Comment by carlosrecuero** [comment]
Same results with your web. Could you please provide more info like browser, device, etc...?

![image](https://user-images.githubusercontent.com/1546791/149126790-429debad-6991-42f9-9dc8-24d8f54c0c90.png)

![image](https://user-images.githubusercontent.com/1546791/149126851-500254c0-eda8-4e89-aeab-ced542fe82c4.png)

**Comment by Aloento** [comment]
@carlosrecuero Strange...
![image](https://user-images.githubusercontent.com/11802769/149144335-4bea7fee-a09e-473f-80de-a500a055aac7.png)
Microsoft Edge 97.0.1072.55
Windows 11

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36 Edg/97.0.1072.55
