### ISSUE TITLE
It's not compatible with .net core 6

### ISSUE THREAD

**Issue by mamaly12** [Xabaril/AspNetCore.Diagnostics.HealthChecks#888]
When use this part of code in .net core 6:

 services.AddHealthChecksUI().AddInMemoryStorage();

This error is displayed:

System.MissingMethodException: 'Method not found: 'Void Microsoft.EntityFrameworkCore.MutablePropertyExtensions.SetValueComparer(Microsoft.EntityFrameworkCore.Metadata.IMutableProperty, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer)'.'

**Comment by carlosrecuero** [comment]
Hi @mamaly12 ,

I have tried to reproduce using the HealthChecks.Sample and HealthChecks.UI.Sample, targeting to the current preview packages:

```
  <ItemGroup>
	  <PackageReference Include="AspNetCore.HealthChecks.UI" Version="6.0.1-rc2.4" />
	  <PackageReference Include="AspNetCore.HealthChecks.UI.InMemory.Storage" Version="6.0.1-rc2.4" />
  </ItemGroup>
```
With this configuration, the sample runs properly.

![image](https://user-images.githubusercontent.com/1546791/147742606-4776feec-d0bb-4746-9306-523a23968130.png)

Could you please try to reproduce it using those samples and verify if you can reproduce it, please?

**Comment by mamaly12** [comment]
Hi, Thank you @carlosrecuero for your help. It works perfectly for me now:

![Screenshot 2021-12-30 142353](https://user-images.githubusercontent.com/7683251/147745613-58941274-5898-4873-8774-9c53839a5863.png)

Just one question, why has it not been released yet, and is it in pre-release condition?

**Comment by carlosrecuero** [comment]
Rest of the version 6.0 packages were release yesterday. We are still
working on UI and will be release in the following days.
