### ISSUE TITLE
Detailed HelthCheck event information on Application Insights publisher

### ISSUE THREAD

**Issue by lfraile** [Xabaril/AspNetCore.Diagnostics.HealthChecks#89]
Currently the Application Insights publisher just writes an event with the general info for the HealthReport, but it would be interesting (optionally) to be able to configure it to save one event for each HealthCheck, with the particular info for the HealthCheck, so you can filter on particular events and create alerts.

If you find it interesting I have done some work on it I can PR.

**Comment by unaizorrilla** [comment]
Yeap, sounds good!

**Comment by unaizorrilla** [comment]
Closed with PR #91 , thanks @lfraile  for contribute this!
