### ISSUE TITLE
.NET 6 HealthChecks-UI header is not displaying correctly

### ISSUE THREAD

**Issue by mindwerxkmg** [Xabaril/AspNetCore.Diagnostics.HealthChecks#892]
Please, fill the following sections to help us fix the issue

**What happened**: 'Health Check Status' label is missing from the header and the polling interval value only shows 'secs.' 

**What you expected to happen**: The 'Health Check Status' label and polling interval value should be displayed.

**How to reproduce it (as minimally and precisely as possible)**: See code below

**Source code sample**: 

services.AddHealthChecks()
                .AddCheck("OnQIFCApi.QueryStack API Service Health Check",
                          new ApiServiceHealthCheck(),
                          HealthStatus.Unhealthy,
                          new[] { "api service" })
                .AddCheck("OnQIFCApi.QueryStack SQL Server Health Check",
                          new SqlServerConnectionHealthCheck(Configuration.GetConnectionString("OnQIFCApiConnection")),
                          HealthStatus.Unhealthy,
                          new[] { "database" });

        services.AddHealthChecksUI(settings =>
                                   {
                                       settings.SetEvaluationTimeInSeconds(60);       //time in seconds between check
                                       settings.MaximumHistoryEntriesPerEndpoint(60); //maximum history of checks
                                       settings.SetApiMaxActiveRequests(1);           //api requests concurrency
                                       settings.SetMinimumSecondsBetweenFailureNotifications(60);
                                       settings.AddHealthCheckEndpoint("query stack api",
                                                                       "/api/health"); //map health check api
                                   })
                .AddInMemoryStorage();
...
app.UseEndpoints(endpoints =>
                         {
                             endpoints.MapControllers();

                             endpoints.MapHealthChecks("/api/health",
                                                       new HealthCheckOptions
                                                       {
                                                           Predicate      = _ => true,
                                                           ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
                                                       });

                             endpoints.MapHealthChecksUI();
                         });

        <PackageReference Include="AspNetCore.HealthChecks.UI" Version="6.0.2" />
        <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="6.0.2" />
        <PackageReference Include="AspNetCore.HealthChecks.UI.Core" Version="6.0.2" />
        <PackageReference Include="AspNetCore.HealthChecks.UI.InMemory.Storage" Version="6.0.2" />
       
**Anything else we need to know?**:  I have two services configured exactly the same way i.e. same code and installed packages.  One service does not display the header correctly and the other one does i.e. the title label and actual interval number are displayed.

**Environment**: 

- .NET Core version .Net 6
- Healthchecks version 6.02
- Operative system: Windows
- Others:
![healthchechsUI-Refs](https://user-images.githubusercontent.com/47189774/149517827-e8eb5060-4550-4c1d-b008-806ab865fa6c.png)
![healthchecksUI-secs](https://user-images.githubusercontent.com/47189774/149517863-6ec419b6-9e83-4cbf-801d-655f8cc38116.png)
![healthchecksUI-nosecs](https://user-images.githubusercontent.com/47189774/149517864-ff67a021-fa66-4013-a290-5edd84a66563.png)

**Comment by mindwerxkmg** [comment]
Rebuilt project = problem gone.

**Comment by code1line** [comment]
Same problem here, but no solution yet.

**Comment by code1line** [comment]
Solution: You have to use /healthchecks-ui. With a change (eg. /monitoring) it stops working.
