### ISSUE TITLE
Purpose of reference to UI.Core from UI.Client

### ISSUE THREAD

**Issue by danielwertheim** [Xabaril/AspNetCore.Diagnostics.HealthChecks#895]
**What would you like to be removed**:
Remove transient dependency on EntityFramework from UI.Client

**Why is this needed**:
The Client project seem to exist to provide monitored resources a way to provide a response that is compatible with the UI. If so, then why is there a reference against UI.Core which in turn has a reference on EntityFramework which is something the consumer of `UIResponseWriter` most likely don't want, right? Or it migth be that I'm encountering code that uses `UIResponseWriter` when it shouldn't.

**Comment by Maxwellwr** [comment]
In my opinion, HealthChecks.UI.Core.Data should be moved to a separate assembly, which will remove the reference to the EntityFrameworkCore

**Comment by sungam3r** [comment]
#763

**Comment by sungam3r** [comment]
Done.
