### ISSUE TITLE
Automatically delete head branches 

### ISSUE THREAD

**Issue by sungam3r** [Xabaril/AspNetCore.Diagnostics.HealthChecks#917]
I propose to enable this setting:
![изображение](https://user-images.githubusercontent.com/21261007/155303432-272b48f6-f3f9-46c4-aa8d-dcbf533d2290.png)

I have no access to repo settings to do this myself. Ping @unaizorrilla @carlosrecuero

**Comment by carlosrecuero** [comment]
Agreed and done.

![image](https://user-images.githubusercontent.com/1546791/156875873-26a830dd-1de3-40da-8855-aa486d9a6339.png)

**Comment by sungam3r2022** [comment]
Thanks.
