### ISSUE TITLE
Azure Storage Health Check Conflicts with Newer NuGet Packages

### ISSUE THREAD

**Issue by acgritt** [Xabaril/AspNetCore.Diagnostics.HealthChecks#93]
I believe the issue is due to the fact that in 9.4 the Azure Storage NuGet packages were broken from one package into a separate one each for Blob, File, and Queue with a Common one that is shared among them.  When attempting to use the Azure Blob Storage Health Check I was unable to get my code to compile due to the duplicate definition of the CloudStorageAccount and other objects being defined in the same namespace in two different assemblies.

**Comment by unaizorrilla** [comment]
Let me check!

**Comment by unaizorrilla** [comment]
Hi @acgritt 

Latest version of WindowsAzure.Storage is 9.3.3, I create a project with 9.3.3 reference and add AspNetCore.HealthChecks.AzureStorage and all is working ok.

![imagen](https://user-images.githubusercontent.com/1630008/52780734-30262f00-304b-11e9-9071-c9efb1211738.png)

**Comment by acgritt** [comment]
@unaizorrilla it turns out I am using the newer NuGets which are `Microsoft.Azure.Storage.*` and is version 9.4.2 right now. According to the [Azure Storage GitHub](https://github.com/Azure/azure-storage-net) it seems they made the namespaces the same to make it easier to migrate. However, by using the one with `WindowsAzure.Storage`, that is where the conflicts come in on my project.

**Comment by unaizorrilla** [comment]
Any reason to use Microsoft.Azure.Storage instead of WindowsAzure.Storage? Is this package the recommended wat at this moment?

**Comment by acgritt** [comment]
It seems that Microsoft.Azure.Storage is the one to use going forward.  According to the [Change Log](https://github.com/Azure/azure-storage-net/blob/master/Common/changelog.txt) as part of 9.4.0 they moved back to using the namespace from Microsoft.WindowsAzure.Storage to ease the transition between the two, but that is expected to be a temporary change.  Also the Project Site link for the WindowsAzure.Storage on NuGet sends you to the same repo as Microsoft.Azure.Storage.

**Comment by unaizorrilla** [comment]
I try to work on this topic on weekend. Stay tunned

**Comment by ejwill** [comment]
@unaizorrilla I believe you just need to set an alias on the package to fix the issue with conflicting namespaces

**Comment by acgritt** [comment]
@unaizorrilla I know it has been a long while, but has anything been done to support this?

**Comment by unaizorrilla** [comment]
Done on #618
