### ISSUE TITLE
Cache results to avoid overloading service

### ISSUE THREAD

**Issue by davidjamartin** [Xabaril/AspNetCore.Diagnostics.HealthChecks#931]
**What would you like to be added**:
I would like to be able to cache the results for a few seconds so that subsequent calls get the cached results rather than doing the test again.

**Why is this needed**:
There are two use cases for this.
- To avoid denial of service by overloading healthcheck endpoint
- If there is a circular reference A->B->C->A

**Comment by sungam3r** [comment]
What exactly are you talking about? What healthcheck? Or what other API?

**Comment by davidjamartin** [comment]
@sungam3r Thanks for responding.

This could be any healthcheck, but for the sake of an explanation, lets consider the _AddUrlGroup_ healthcheck.

**Circular Reference**
An example of the circular reference could be:
_ServiceA -> ServiceB -> ServiceA_
ServiceA this has a dependency on ServiceB so ServiceA implements AddUrlGroup checking health endpoint of ServiceB.
ServiceB has a dependency on ServiceA so also has an AddUrlGroup test back to ServiceA. This creates a circular dependency, by caching the result, the circular dependency will be cut because the Service will return a cached result on the second call. Without caching it will continue until one service times out.

**Denial of Service**
An example of denial of service could be ServiceA depends on 10 endpoints, so implements AddUrlGroup checks for each endpoint, this means every call to http://ServiceA/healthz will make 10 calls to the dependant services (1 per service). If http://ServiceA/healthz is called by 100 clients, this will subsequently result in 1000 calls downstream. Multiply this up and the service is doing nothing but AddUrlGroup checks or is autoscaled to support healthcheck calls. By caching the result temporarily the 10 downstream calls will not be made.

**Reference**
It's related to this question in the deprecated repo: [Healthcheck services should cache the results](https://github.com/dotnet-architecture/HealthChecks/issues/12)

**Comment by sungam3r** [comment]
I don't think that it is an issue for healthchecks itself. Such issues should be handled by some another application/library layer. HealthCheck responsibility is ... checking.

**Comment by sungam3r** [comment]
I think no action is needed here. At least for now. Feel free to reopen if you have further considerations and suggestions about possible design.
