### ISSUE TITLE
Add CI/CD for HealthChecks.EventStore

### ISSUE THREAD

**Issue by sungam3r** [Xabaril/AspNetCore.Diagnostics.HealthChecks#938]
I do not see it.

**Comment by carlosrecuero** [comment]
CI/CD generated on branch feature/eventstore-cicd, but FunctionalTests failing.

**Comment by sungam3r2022** [comment]
I don't use EventStore. Regarding `HttpStatusCode.ServiceUnavailable {value: 503}` in logs. I saw it before for all cases where something went wrong. Tests should log some minimal info about failed check to be debuggable. I propose to use extended response writer `services.Configure<HealthCheckOptions>(opt => opt.ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse)` and output the whole response into error log: 
`response.StatusCode.Should().Be(HttpStatusCode.OK, await response.Content.ReadAsStringAsync());`
