### ISSUE TITLE
Fix or remove build.ps1

### ISSUE THREAD

**Issue by sungam3r** [Xabaril/AspNetCore.Diagnostics.HealthChecks#941]
This script still contains `APPVEYOR_BUILD_NUMBER`.

**Comment by sungam3r** [comment]
@carlosrecuero Are `dotnet-install.ps1` and `install-sdk.ps1` still needed?

**Comment by carlosrecuero** [comment]
Hi, 

Sincerely I don't use them at all, but maybe there is some scenario of usage I don't know.

@unaizorrilla , what do you think?

**Comment by sungam3r** [comment]
Well... I think it's safe to remove these files now. No feedback from @unaizorrilla so far.
