### ISSUE TITLE
Question: how best to specify HealthChecksDb path in locked down environment

### ISSUE THREAD

**Issue by mikevanoo** [Xabaril/AspNetCore.Diagnostics.HealthChecks#95]
The default path for the HealthChecksDb works fine in development but when the app is published to a server environment where the account does not have write permissions to the folder (e.g. under C:\inetpub for IIS) then we get access denied errors.

Of course, manually changing the path upon deployment would work but is cumbersome. Is there another way? 

One solution would be to support expanding environment variables in the "HealthCheckDatabaseConnectionString" property so I can then just specify it like this:

`"HealthCheckDatabaseConnectionString": "Data Source=%APPDATA%\\healthchecksdb"`

Thoughts?

**Comment by unaizorrilla** [comment]
Umm good catch. I try to implemente this feature, of course PR are welcome if you want do this,

**Comment by unaizorrilla** [comment]
Closed with #96 by @mikevanoo
