### ISSUE TITLE
healthchecks-ui does not display all the healthchecks if the list is too long or the screen resolution too low

### ISSUE THREAD

**Issue by Snoopysgit** [Xabaril/AspNetCore.Diagnostics.HealthChecks#98]
![image](https://user-images.githubusercontent.com/4614552/52852961-5bc41a80-311a-11e9-9180-d239d698f1d7.png)

From the 25 registered services, only 21 are displayed with a screen resolution of 1920x1080

**Comment by unaizorrilla** [comment]
Hi @Snoopysgit 

@CarlosLanderas  can you check this?

**Comment by CarlosLanderas** [comment]
I made some changes to the UI so right now you scan use scroll to view a large number of services, and added some extra bottom margin. I also changed the css minifying process so it does not overwrite the source file. 

![liveness](https://media.giphy.com/media/4Z5o8cOCkcs67vIlvj/giphy.gif)

**Comment by CarlosLanderas** [comment]
HealthChecks.UI version 2.2.15 is being built and will be available soon in NuGet. I close the issue but feel to reopen if you find some issue @Snoopysgit
