### ISSUE TITLE
Add support for ElasticSearch Elastic Cloud

### ISSUE THREAD

**Issue by TylerSiegrist** [Xabaril/AspNetCore.Diagnostics.HealthChecks#989]
**What would you like to be added**: Currently only basic and credential authentication is supported. Elastic now has managed instances via Elastic Cloud, which can use an API key.

**Why is this needed**: Support for monitoring using an API key instead of credentials.

Elastic Cloud configuration using the NEST client is done like so:
`new ElasticClient(
                new ConnectionSettings(
                    new CloudConnectionPool(
                        configuration.GetValue<string>("ElasticSearch:CloudId"),
                        new ApiKeyAuthenticationCredentials(configuration.GetValue<string>("ElasticSearch:ApiKey"))
                    ),
                    sourceSerializer: JsonNetSerializer.Default
                )
            )`

**Comment by sungam3r** [comment]
PR is wellcome.

**Comment by sungam3r** [comment]
I think that it was fixed by #1577.
